### ISSUE TITLE
Scrolling back up puts wrong images into RecyclerView items

### ISSUE THREAD

**Issue by Orbyt** [bumptech/glide#1001]
When scrolling down my RecyclerView, Glide loads the images as normal. I noticed that if I scroll down and then scroll back up, some of the items in the list will now have the wrong images inside them, instead of the images that were there when first loaded.

I'm guessing this might be an issue with the view being recycled, but wanted to see if any similar behavior has been experienced by others. Any specific ideas on what might be the issue?

**EDIT:** The items that are having the issues still have all the other data in the right place (titles, dates, etc) so perhaps it isnt an issue with the views being recycled.

This is the code thats loading the images in onBindViewHolder() into the items that are causing problems:

```
Glide.with(mContext).load(mediaEntities[0].getMediaURL()).into(((TwitterViewHolder) holder).twitterImageView);
```

Note that I have a seperate item type (and therefore seperate ViewHolder) that is also using Glide to load images, but those items do not become messed up like the ones previously mentioned.

**Comment by Orbyt** [comment]
Well I suppose I found a fix. In summary, what I was doing was loading a list of tweets, some of which contained images. In my onBindVH(), I was checking to make sure the viewtype was a twitter item, and then checking if the twitter item had any images. If so, I set the visibility of an ImageView in the twitter item to visible, and then load the image into it.

What I ended up doing was making my getItemViewType() return another viewtype, eg: if it was a twitter item i could return VIEWTYPE_TWITTER or VIEWTYPE_TWITTER_IMAGE. I used the same viewholder, but in my onBindVH() I added a case for VIEWTYPE_TWITTER_IMAGE and then made the imageview visible and loaded the image. This seems to have alleviated the issue, though im not 100% sure why. 

Will leave open for a day or two for any responses, then will close.

**Comment by haninkyu** [comment]
i have a same issue, but i can't fix it.
would u help me .. ?? OTL

**Comment by TWiStErRob** [comment]
> I was checking to make sure the viewtype was a twitter item, and then checking if the twitter item had any images. If so, [...]

That sounds like a lot of `if`s. The problem is that when an item is recycled it still "shows" the image so if it's used again the image will be still visible, until you start a new load into it or Glide.clear it. You have to assume that the item is in inconsistent state and hence do a full reset on the view state that you expect to be true: set all texts, visibilities, backgrounds, colours, etc. in all possible branching paths inside bind. The values in the XML doesn't matter if you just one place where you modify these, they could be in that modified state so you have to reset to XML state in code. This is the general logic:
```java
if (vh == TWITTER_IMAGE) {
    vh.setTitle(model)
    if (model.hasImage()) {
        vh.image.show()
        Glide.....into(vh.image)
    } else {
        Glide.clear(vh.image)
        vh.image.hide()
    }
}
```
Notice the symmetry and state (visibility) restoration.

Also note that when you're using multiple item types it's worth clearing the state in onViewRecycled so the next bind starts with clean(ish) slate.

This is important in the following use case:
Imagine your model is [image, image, text, text, text...]. When you scroll this list the first two images may be kept in memory when the rest of the list is texts. It's not a biggie here, bit if you extrapolate to much more (5+) view types things can get out of hand.

With your first solution (i.e. shared view type) you will have to clear the image view if you implement the fix I proposed and it'll be fine. However with your solution (i.e. image and tsxt view type) you'll really need that Glide.clear in onViewRecycled because otherwise no-one will clear those images while the list is visible, unless there are new images shown in the list. This should clear up "not 100% sure why".

Feel free to ask if the above is confusing ;)

**Comment by Orbyt** [comment]
@TWiStErRob Your detailed responses are always appreciated, and this pretty much explains it:

> The problem is that when an item is recycled it still "shows" the image so if it's used again the image will be still visible, until you start a new load into it or Glide.clear it.

With the solution I posted, only items with the viewtype VIEWTYPE_TWITTER_IMAGE are having their imageviews visibility toggled, so when the view is recycled an image will just be reloaded. 

> Also note that when you're using multiple item types it's worth clearing the state in onViewRecycled so the next bind starts with clean(ish) slate.

Currently im not clearing them and it seems to be working fine, but will look into this.

Thanks!

**Comment by TWiStErRob** [comment]
> having their imageviews visibility toggled

Just make sure you `Glide.clear` the `ImageView` at the same time you hide it to prevent holding memory. (see "use case" above, and next paragraph)

> it seems to be working fine

Yes, it should work, but there may be off-screen never-to-be-seen-again images holding large chunks of memory. `onViewRecycled -> Glide.clear(vh.image)` solves this.

---

Feel free to ask here if you have more questions related to this later.
