### ISSUE TITLE
I had high hopes from Glide... it turns out, it's no better than picasso

### ISSUE THREAD

**Issue by daviddayag** [bumptech/glide#1008]
in fact it has more bugs than picasso.
it offers gif animations but with the amount of freesing / endless warning messages (Called reconfigure on a bitmap that is in use! This may cause graphical corruption!)  /  not loading images at all, it's just not worth it.
I tried 5 different versions.
using android 23.
using several devices (including nexus 5).
it's just not meant to run in a recycler view, it's just not stable enough like picasso.

**Comment by daviddayag** [comment]
and worst of all, it takes as much memory as picasso

**Comment by TWiStErRob** [comment]
Sad to see you go, here're a few things you might want to consider:

Please report those bugs you're talking about or comment on existing ones. If we don't know about it it's hard to fix them... this is your first interaction with Glide issues as far as I can see :(

> Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

See https://github.com/bumptech/glide/issues/743#issuecomment-157752057 and https://github.com/bumptech/glide/issues/743#issuecomment-156514757.

> it takes as much memory as picasso

that's new... based on [this article](http://inthecheesefactory.com/blog/get-to-know-glide-recommended-by-google/en) it should be better in most cases, or equal if you hard-code sizes... it highly depends on how you configure them. Do you have code/numbers to back this up?

> animated gifs

You don't have to display animated gifs in a list, even giphy.com on a computer doesn't play all items at once... `.diskCacheStrategy(SOURCE).asBitmap()` to the rescue, and when the user taps on it you can  reload the same url into the same view without the `.asBitmap()` to start playing the animation.

**Comment by daviddayag** [comment]
Thanks for the quick reply!
the thing is that up until now i used a simple library to transform animated gifs to animatedDrawable and cached them in memory for fast display and it worked pretty well.
Uses some memory in the process and the code isn't very pretty but it works.
I thought Glide will give a better solution, provided that it utilizes a better caching mechanism.
but all these issues above got me reverting back.
I think i'll wait until Glide is more mature, or until someone develop a better way to display images / gifs in a feed. (like google plus for example - performance there is amazing)

**Comment by TWiStErRob** [comment]
Yes, I agree you can't beat pre-decoded frames cached in memory, the Drawable just needs to draw them, however not all devices have that capability, for example did that solution work on a Galaxy S2 2.3.7 or even older/lowend phones? Glide decodes frames on the fly, only the GIF binary contents are cached in memory (so that it's seekable) and 2 frames at any time: 1 is displayed, and 1 is being loaded. By the way, nothing is stopping you from using Glide and integrate your AnimatedDrawable solution, it provides a framework for advanced configurability and that "isn't very pretty" will probably disappear (all the caching, threading, etc. should disappear), we solved a similar issue before: #805
