### ISSUE TITLE
how to create expired cache image?

### ISSUE THREAD

**Issue by thestarclubz** [bumptech/glide#1012]
expired cache image on disk and in memory how to ?

**Comment by thestarclubz** [comment]
expired cache image on disk and in memory how to ?

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation
Related methods: `.signature()`, `.diskCacheStrategy()`, `.skipMemoryCache()`

**Comment by thestarclubz** [comment]
sorry but i not understand method .signatrue()
do you have for a example?

**Comment by TWiStErRob** [comment]
It's a better way of saying:
```
http://url1?signature=signature1
http://url1?signature=signature2
```
These result in two different urls, so when the signature changes Glide is forced to reload, because the cache key is different. It's a better way, because if your model is not an URL (File, resource ID, custom object, etc.), then it's not possible to simply append random stuff to it, so signature provides a neat way to make the cache keys different when invalidating is needed.
