### ISSUE TITLE
Get best cached version

### ISSUE THREAD

**Issue by rcketscientist** [bumptech/glide#1015]
I read about a dozen "get cache" requests usually resulting in a "not needed, unless you have a new use case" verdict.  I believe I have a niche but useful use-case for quickly grabbing the best possible cache version.  

I have a gallery app that works with very large images with a custom implementation for the viewer.  When the viewer loads there's about a second of processing with a blank screen and it'd be great if I could request best cache and only cache from Glide so something can be displayed immediately, even if that is a pixelated thumb it's a huge step up from a blank screen (plus it would flow from a activity animation).

Caching the full image to ensure matching size and a reliable cache request is not possible as the images are too large to cache full images, but as I mentioned quality is not important, this is merely to ease the transition between gallery and viewer.

I'd be willing to make the changes myself if there's feedback that this would be a feasible/desirable addition.

On a sidenote, I was previously using the old BitmapFun caching, tried Picasso (but it's tied way too intimately to HTTP), then gave Glide a shot.  This is a truly fantastic library.  Easily plugged in a custom decoder, and a line of code later it was blowing away the speed of my prior cache.  Thank you for this excellent service and well done!

**Comment by TWiStErRob** [comment]
> this is merely to ease the transition between gallery and viewer.

This suggests that you already have a memory-cached thumbnail so you just need to match up the size with that when setting up the activity transition, or just add a thumbnail of that size to your viewer.

> the images are too large to cache full images

This sounds like a contradiction here. The images are too large to be cached, but they're not too large to be retrieved over the network over and over again? Glide's `SOURCE` cache saves the original image, no recompression is done, so if your image is 2MB on the server it'll cost 2MB traffic and 2MB on the device, but this means that later when you need it you can load **any** sized version of that image, even offline.

---

Let me know if you need more clarification or help to implement these in your app.

**Comment by rcketscientist** [comment]
>This sounds like a contradiction here. The images are too large to be cached, but they're not too large to be retrieved over the network over and over again?

The images don't come from a network at all (or don't have to).  They are high res raw images on attached storage running through a custom decoder (as opposed to the typical network portion).  I wasn't very clear about that sorry.

> This suggests that you already have a memory-cached thumbnail so you just need to match up the size with that when setting up the activity transition, or just add a thumbnail of that size to your viewer.

Yes I should have  a memory-cached thumb.  The part I'm confused about is what would be necessary to recreate that call.  I tried a couple things but didn't get a cached version.  I think the critical piece is the size, but can I just pass the size of the original ImageView?  For example, I'm using centerCrop in a square view, which I hope maintains the aspect ratio of the image and crops the longest dimension.  Is this correct?  I tried to follow the centerCrop logic but got lost.  A square thumb might be just as jarring as a blank screen.

What is the life-cycle of the memory cache btw?  If you are not using the cache throughout all aspects of the app, how would the memory threshold be reclaimed (or is garbage collection sufficient)?

**Comment by eicm** [comment]
I suggest you grab the thumbnail from the raw image metadata (almost all the new version of raw formats has it), and cache those thumbnails...

**Comment by rcketscientist** [comment]
Nowhere near "almost all" store a thumb.  And that is the initial grab in the gallery and the initial display in the viewer if available, however it is not without cost.  Hence the desire to use the cache to manage the transition with an instant ballpark thumb to display.

**Comment by eicm** [comment]
Correct me if I'm wrong but the DSLR cameras use that thumbnail and also the preview image (a jpg image w same resolution as the original raw image) to show images on their LCDs screen.

**Comment by rcketscientist** [comment]
On some.  In all cases it is a proprietary format and many manufacturers store no thumb at all.  For the big three there are thumbnails.  But there are as many that don't store one.  Even so, the thumbnail pull is not without cost and as I mentioned has a small delay (not to mention the large delay if a full decode is required).  If there's a copy sitting in memory it would be silly not to leverage it.

**Comment by eicm** [comment]
Out of curiosity: You use a specific custom decoder for each raw format?

**Comment by rcketscientist** [comment]
There is a decoder (algorithm) for each format no way around that, but I think you're more referring to whether I'm using a suite/library and I am.  I originally maintained a custom version of dcraw, but I'm now using libraw which is really fantastic wrapper around dcraw that makes life much easier.

**Comment by eicm** [comment]
Thanks, back to your original question each cached images are being saved based on a unique signature which consists of different values, like Url (parth), sizes, transformation... To hit the cache you need to have all the parameters that used for caching signature to be exactly the same. In your case I think it would be the size that you used for creating and caching the thumbnails are not matching...

**Comment by TWiStErRob** [comment]
> running through a custom decoder

Yeah, I was suspecting this, since you abandoned Picasso... that's [how I got here](http://stackoverflow.com/q/25148291/253468) too.

> I hope maintains the aspect ratio of the image and crops the longest dimension

Roughly, it scales the image uniformly (it doesn't keep the aspect, because the result will have the target's dimensions which may have a different aspect, but it keeps the pixels uniform/square) until one of the dimensions touches the left/right or top/bottom edge from the outside, it could be called `centerOutside` as well. Check [these images](http://etcodehome.blogspot.hu/2011/05/android-imageview-scaletype-samples.html). It doesn't necessarily crop the longest dimension, for example:
![image](https://cloud.githubusercontent.com/assets/2906988/13540091/ba68eb32-e254-11e5-8fe9-366d17acbfa6.png)


> what would be necessary to recreate that call.

Usually people trip up on size and transformations, you can see what's not matching [via logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow). Glide automatically determines both (size by waiting for layout and transformation for `android:scaleType` if not explicitly set on the load), and that's why it can problematic. I think the easiest and most generic way to get the sizing info would be (abbreviated because there's a lot of boilerplate due to inner classes):
```java
.listener(onResourceReady -> { target.getSize(viewHolder); return false; })
class YourViewHolder implements SizeReadyCallback {
    onSizeReady(w,h) -> { this.width = w; this height = h; }
}
```
so later when the users taps the item you can read the sizing info from the ViewHolder and pass it on. `getSize` is async by default, but since the load just finished it should be called back synchronously/immediately. All this would be much simpler if you use a `@dimen` resource in XML to size your views, because you can just use that (`getResources().getDimensionPixelSize()`). In the full viewer add `.override()` with the passed sizes.

> What is the life-cycle of the memory cache btw?

As soon as the image is loaded it's in the active resources, any load loading with the same params can hit that. When a new load is started to the same imageView or the load is cleared for some other reason the resource is put into the memory cache. Later if a load matches it will be checked in the pool. If the device is low on memory or the memory cache is full, the resources are LRU-evicted. All Glide loads use memory cache unless `.skipMemoryCache(true)`.

**Comment by rcketscientist** [comment]
Over dinner I had basically come to the decision that when I have a moment I'll work with targets and given that aspect ratio is not maintained I think this is the right route.  I appreciate the code pointer.  

Using a `@dimen` for size won't ever work unless you're satisfied with arbitrary and possibly crummy looking spacing.  I much prefer starting with `dimen` and fine-tuning the size to the screen dimensions.  However, I do still know the image size at the point of that calculation.

How often does that on-the-fly view dimension calculation occur?  If you know you have a static size for all images would it perhaps be better to work with targets anyway?  As I would prefer to maintain aspect ratio it might be in my interest to place the image in the view myself.  Can auto-orientation be turned off?  I could foresee that being a problem if I manually do this.

I've been searching for answers to these question, so if I missed something feel free to RTFM me.

**Comment by TWiStErRob** [comment]
We're on the same page on not hard-coding values, but some users here use them, so I thought I would throw that in...

> given that aspect ratio is not maintained

By the time the target gets the image it'll be already transformed (centerCropped) so the image size and the resource size should be exactly the same, and not equal to source image dimensions. Center-crop by definition cannot preserve the aspect ratio of the image dimensions, but it'll not distort the image.

> How often does that on-the-fly view dimension calculation occur?

Every single imageView separately, but possibly only once per imageView and not every load. If you know that you have a uniform grid layout (including linearlayout) you can get away with reading it only once: for example on the first bind.

What do you mean by auto-orientation? You said you were using a custom raw decoder so Glide is not involved in loading the image. But if it's JPEG EXIF orientation, that's tricky: #665.

**Comment by rcketscientist** [comment]
`You said you were using a custom raw decoder so Glide is not involved in loading the image.`

The thumbnails in many images are in fact jpg.  I never even checked if they store exif as well, but apparently they do, so it does work.  In fact it left me bewildered for a bit when I first got Glide working since I was already orienting the images, they were "over-oriented".

However, that won't be the case for types that require full decode, so it would be best if I were to turn it off in general.  I see in the linked issue that you can't turn it off, unless I can check if the orientation occurred I would consider this a showstopper, unfortunately.

**Comment by TWiStErRob** [comment]
You should be able to wrap a fetcher-returned stream in an ExifOrientationStream with a fixed rotation (=not rotated). You could create a custom model (`class NoRotateUrl { String url; }`) and write a fetcher that wraps another fetcher and wraps the stream as well, and use `BaseGlideUrlLoader` to return that fetcher. This is for normal JPEG loads, if you have a byte[] or similar representation of thumbnail and you want to prevent rotating that it's much easier to wrap it in ExifOrientationStream because you're likely creating a ByteArrayInputStream.

**Comment by rcketscientist** [comment]
All images are sent as a `ByteArrayStream` through `getResourceFetcher` in my custom `StreamModelLoader`.  You're saying that if I simply wrap that stream with `ExifOrientationStream` it will imply no rotation?

**Comment by TWiStErRob** [comment]
Yes, that should be the case, because you're loading JPEG which has an EXIF orientation that you want to turn off, so if that stream works as we expect, it should override that orientation to whatever you pass in the constructor. So there's still a rotation happening inside Glide, but you force it so that it doesn't actually rotate (0° rotation).

**Comment by TWiStErRob** [comment]
You can even know what the orientation is originally: `new ImageHeaderParser(is).getOrientation()`. `MediaStoreThumbFetcher` does something similar.

**Comment by rcketscientist** [comment]
`ExifOrientationStream ` worked.  

I had to force close the app, but the second try worked.  It appears:

`				new Thread(new Runnable()
				{
					@Override
					public void run()
					{
						Glide.get(GalleryActivity.this).clearDiskCache();
					}
				}).start();
				Glide.get(GalleryActivity.this).clearMemory();`

did not work as intended to clear the cache.

I'll follow up when I get a chance to tinker with pulling the cached version in the viewer.

**Comment by TWiStErRob** [comment]
You can always add `.diskCacheStrategy(NONE).skipMemoryCache(false)` while testing, it helps with developing a decoder a lot, because you don't have to continuously clear the caches.

Tip: `Thread` has a `run` method that you can override. But it should've worked, I do [the same](https://github.com/TWiStErRob/glide-support/blob/c2aaf759e80e67b5859d511413086b2ff5fc45db/src/main/java/com/bumptech/glide/supportapp/utils/ClearCachesTask.java) on [button press](https://github.com/TWiStErRob/glide-support/blob/c2aaf759e80e67b5859d511413086b2ff5fc45db/src/main/java/com/bumptech/glide/supportapp/TestActivity.java#L89).

**Comment by rcketscientist** [comment]
I did override the run method, no?  The thread does work, I've checked the filesystem when I initially implemented Glide.  For some reason my memory cache did not clear with that code.  Force closing the app did work, however.  My clear cache method also clears my image database and re-searches, so it _should not_ be something lingering in the app, but you never know.

**Comment by TWiStErRob** [comment]
Yes you did override, but on a Runnable object, never mind, just a few less characters.
The active resources are not in memory cache so those cannot be freed with `clearMemory`. The active resources are the ones that are visible in views (or more formally: has been delivered to targets via `onResourceReady` but hasn't been `onLoadCleared` yet).

**Comment by rcketscientist** [comment]
Oh I see, always saw it with a runnable, taught myself Java, so go figure.  That makes sense on the memory front.
