### ISSUE TITLE
play gif animation just one time

### ISSUE THREAD

**Issue by iielse** [bumptech/glide#1017]
i want to play gif animation just one time and stay on the last frame. How should I do

**Comment by TWiStErRob** [comment]
As far as I know there's a way to tell repetition count inside the GIF format, so if you have control over the files, export it with repeat=0 instead of infinite.
Otherwise Glide doesn't give you listeners for GIF events so you may have to look around for a specialised GIF library or you can try to make something work based on #446 (It looks like it's only in 4.0 snapshot, see wiki).

**Comment by iielse** [comment]
"you have control over the files, export it with repeat=0 instead of infinite.”
sorry, I don't know this before.
