### ISSUE TITLE
Set pre-sized color placeholder

### ISSUE THREAD

**Issue by samtstern** [bumptech/glide#1024]
I am using Glide to download images from a URL.  I am also using the `centerCrop()` option.

Before I load the image, I know the following information:
```json
  {
    "width": "<full width>",
    "height": "<full height>",
    "color": "<placeholder color>"
  }
```

I would like to show a placeholder of `color` in the exact final size the image will be displayed after `centerCrop`.  Is there any way to do this?  The problem is my layout looks like this:

```xml
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_below="@+id/button_upload"
    android:orientation="horizontal"
    android:weightSum="2">

    <ImageView
        android:id="@+id/image_view_1"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:background="@color/gray"
        android:scaleType="centerCrop"
        tools:src="@mipmap/ic_launcher" />

    <ImageView
        android:id="@+id/image_view_2"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:background="@color/gray"
        android:scaleType="centerCrop"
        tools:src="@mipmap/ic_launcher" />

</LinearLayout>
```

It seems like when the load starts the ImageView has 0 height.  Then once the image comes through I very briefly see the placeholder during the crossfade.  But I'd like to see the placeholder sooner (as soon as I call Glide) and in the right size.

**Comment by TWiStErRob** [comment]
You can try to make the ImageView as big as you want with layoutparams.width/height, but that may be problematic because you don't necessarily know how much is the width at the time of binding. Probably better with PercentFrameLayout, because you know 50% width and the aspect ratio. Or you can try creating a new class like below and let the ImageView calculate the aspect with wrap_content.
```java
class SizedColorDrawable(color, width, height) extends ColorDrawable(color) {
    getIntrinsicWidth -> width
    getIntrinsicHeight -> height
}
```

**Comment by TWiStErRob** [comment]
Alternatively all your problems would go away if you set a fixed height for this layout, because then the ImageViews could match height and centerCrop would take care of the rest.

**Comment by samtstern** [comment]
Ok I am doing something already with LayoutParams, I was hoping there was a "preferred" way to do this.

**Comment by TWiStErRob** [comment]
Not a Glide specific one, since this is a more broad Android problem IMO: you want to display something that doesn't have a size (color) in a view that wraps the content (that doesn't have a size) so you end up with nothing. Later you replace that content with something that has a size. Depending on the layout, I always try to make sure everything has sizes without contents; but try not to hard code sizes. I think in this case it's ok to fix the height of the view to some reasonable value using a `@dimen`. I would imagine you don't want the view changing size based on what image you load, and that's why you use centerCrop, so take an average size and fix it there. It would look weird anyway to have different list item height (and 0 height list items are very dangerous as well), or even if a toolbar-like view changes height. This is just my opinion, doesn't have to do anything with Glide.

**Comment by samtstern** [comment]
For people from the future:

It turns out a really great solution (or part of the solution) is to make a custom ImageView class that enforces an aspect ratio, since I know the aspect ratio in advance:

```
/**
 * ImageView that matches the aspect ratio from an {@link ImageInfo} object.
 */
public class RatioImageView extends ImageView {

    private static final String TAG = "RatioImageView";

    private static final int FIXED_WIDTH = 0;
    private static final int FIXED_HEIGHT = 1;

    private static final int DEFAULT_FIXED_DIMENSION = FIXED_WIDTH;
    private static final float DEFAULT_ASPECT_RATIO = 1.0f;

    private ImageInfo mImageInfo;
    private int mFixedDimension;

    public RatioImageView(Context context) {
        super(context);
    }

    public RatioImageView(Context context, AttributeSet attrs) {
        super(context, attrs);

        // Get attributes
        TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.RatioImageView);
        mFixedDimension = a.getInt(R.styleable.RatioImageView_fixed_dimension,
                DEFAULT_FIXED_DIMENSION);
        a.recycle();
    }

    public void setImageInfo(ImageInfo imageInfo) {
        this.mImageInfo = imageInfo;
        requestLayout();
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

        // Get aspect ratio from ImageInfo
        float aspectRatio = DEFAULT_ASPECT_RATIO;
        if (mImageInfo != null) {
            aspectRatio = ((float) mImageInfo.width / mImageInfo.height); // w : h
        }

        // Set dimensions according to aspect ratio
        if (mFixedDimension == FIXED_WIDTH) {
            int width = getMeasuredWidth();
            int height = (int) (width / aspectRatio);

            setMeasuredDimension(width, height);
        } else if (mFixedDimension == FIXED_HEIGHT) {
            int height = getMeasuredHeight();
            int width = (int) (height * aspectRatio);

            setMeasuredDimension(width, height);
        } else {
            Log.w(TAG, "Invalid fixed_dimension attribute, must be 'width' or 'height'.");
        }
    }
}
```

**Comment by TWiStErRob** [comment]
TIp: You can achieve the same with http://developer.android.com/tools/support-library/features.html#percent for any view.
