### ISSUE TITLE
How to dynamically change paths in external storage?

### ISSUE THREAD

**Issue by IskuhiSargsyan** [bumptech/glide#1033]
I want to download images in different directories, I mean in external storage with different paths,
and the paths should be created dynamically, if the only way to mention path is using  setDiskCache() in extended GlideModule,but GlideModule I need to mention in AndroidManifest.xml,while I need to choose path  dynamically.

**Comment by jjhesk** [comment]
+1

**Comment by IskuhiSargsyan** [comment]
Dear @TWiStErRob do you have any idea?

**Comment by TWiStErRob** [comment]
Deja vu with #792, I was trying to figure out a good way, but none came.

Glide has one cache, which can be determined dynamically (DiskCache.Factory), what's in the cache is determined by how DiskCache is implemented.

**Comment by IskuhiSargsyan** [comment]
@TWiStErRob  @Teovald 
You mean I need to create custom
ModelLoaders & DataFetchers classes. As I understand these classes could be used to load data from corresponding  directories, but  how to mention  for resource storing process different  directory paths.

**Comment by Teovald** [comment]
If your need is similar's to MFlisar's one, I think that his idea of using a salted signature is pretty good.  

Otherwise, you can use DiskCacheStrategy.NONE in order to save nothing in Glide's cache and handle saving yourself with a custom ModelFetcher.  
This is extra hacky though, and I don't understand why you would want to do that.

**Comment by Teovald** [comment]
if you need a sample of custom model loader and fetcher applied to synchronization, here is a minimal one : https://github.com/Teovald/Glide-Pinning-Image-Sample

This is a different use case though : here I just want to be able to 'pin' some content in order to make it always accessible.

**Comment by IskuhiSargsyan** [comment]
@Teovald 
I need to load different galleries ,each of that should be downloaded on external storage in  different subdirectories.
using MFlisar's version as I understand images are stored in the same directory ,where they are differ by their salted signature .
In Glide-Pinning-Image-Sample you create custom model loader and fetcher, while not apply DiskCacheStrategy.NONE ,
at this moment it's a bit hard to realise how I could customize this sample for my use any hints could be helpful :)
Why is it hacky though because it could cause outofmemoryexceptions? 
I need to have one shared memory cache with default size and concerning disc cache - store on external storage which includes different directories.

**Comment by Teovald** [comment]
>Why is it hacky though because it could cause outofmemoryexceptions? 
By itself, it is not going to cause OOM exceptions.  

It is hacky because you completely remove Glide's LRU disk cache and instead implement it yourself in a different step of the image loading process.  

let's schematise a load flow in order to help you understand the DiskCacheStrategy trick : 
a normal load goes that way :  

-look up in Memory Cache
-if not present, look up in Disk Cache
-if not present, ask ModelLoader & Fetcher to fetch the resource

by relying on DiskCacheStrategy.NONE for all your loads, you always skip step 2 and rely instead on the Fetcher in order to implement caching.  



I would like to better understand your use case.

>I need to load different galleries

you mean that you need to download one or several sets of pictures and then display them from disk, is that right ?
If that's the case, this is exactly what the pinning sample is doing. The download is up to you and the  ASynchronizableDataFetcher will allow you to hook it up with glide.

**Comment by IskuhiSargsyan** [comment]
No I need the same cache mechanism
My case is to display recyclerview, and when user  selects one it displays viewPager like gallery,
it could consist for example 30 images, and in the background I start service, which check if not  exists downloads/stores image  in external cache in specified directory path, while  if the  user swipes for ex. 
2 pages it should check in cache if it exists then display, if not exists download /store/display.
When user press back button and returns to the previous page, and selects another recyclerView item , the process starts again, only the images should be stored in another directory corresponding to the name of selected item.

So, I need the cache mechanism for background process -  only disk cache and for displaying both cache mechanishm(memory and disk cache), and Glide allows to have control all over it, only I need to dynamically create /change directory path  depends on selected recyclerView item.

**Comment by IskuhiSargsyan** [comment]
@Teovald @TWiStErRob
As I have described the case , as I need to store in different directories, 
do you think for  solving the task the solution is in creating custom ModelLoader & Fetcher ?

**Comment by IskuhiSargsyan** [comment]
@Teovald 
@TWiStErRob
It is unclear for me, I need only to dynamically change directories , why I need to create custom ModelLoader & Fetcher , as  I am setting path in  InternalStorageDirectory,  and need the same cache  mechanism as Glide provides.

**Comment by TWiStErRob** [comment]
Glide supports a single cache directory that is set up at application startup. If you want to do anything other than this you need to find ways to implement those. By using a custom model and fetcher you can simply skip Glide's internal caching and achieve whatever you want, but since it's a custom implementation you're mostly on your own there. @Teovald figured out a way to skip the cache and pull resources from a single directory before actually going to the network. If you apply this pattern multiple times you have your "different cache directories".

Based on this "need the same cache mechanism as Glide provides" and "need to dynamically change directory path [based on list] item" is not supported by Glide out of the box and you'll have to implement it. All the information you need should be available in the above comments. The only thing I would recommend looking at is the [Glide Flow diagram](https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit) which may help or confuse you on first look, but it's definitely a good resource once you understand it :)

I understand that you "need" to put the files in different directories, what I don't understand is **why** you want to do that. Can you please explain more about it?

**Comment by IskuhiSargsyan** [comment]
Each gallery could contain more than 1000 small images, and I add the implementation of unlimited external disk cache, when user opens each gallery it shows the progress for current downloaded gallery . try to read from cache if it exists. as the count of downloaded images could be too much , the reading, deleting process could be too long if it searches in folder where other resources of other galleries are exists. So  separating in different directories could decrease the reading process and deleting the selected gallery.

**Comment by TWiStErRob** [comment]
Ok, so that confirms that it's out scope for Glide. You can try the special fetcher, but it would be much easier to implement like this:
 * download the gallery (folder) yourself
 * delete the gallery (folder) yourself
 * load images from the downloaded gallery (folders) through Glide (with `load(File)` and let Glide handle the caching

Don't use Glide's cache as your main storage, constrain it to a reasonable size (like the default) and let the thumbnails populate it. This way when a gallery is opened, the user might see cached images, even if the gallery was deleted, which is not a bad thing. Show the list with an adapter and let it bind the non-existent file names, if it's in Glide cache it will be shown. Once the full download is complete you can notifyDataSetChanged() to reload any thumbnails that were missing from the cache. All the above is assuming that the individual images in the gallery don't change and you have enough metadata available about the gallery to deduce the file names.

**Comment by Teovald** [comment]
I agree with @TWiStErRob .  

Additionally, if you want to use Fetcher, this sounds like a good application case for the sample I linked earlier : https://github.com/Teovald/Glide-Pinning-Image-Sample

-You implement your own image downloading logic with the callbacks in order to get the overall progress, multiple folders and so on.
-The Fetcher reads from where you downloaded these files.  
-The Fetcher can optionally fetch the file when it is not yet there, so it would smooth some things up (like favoring the thumbnail currently viewed by the user if he/she scrolls). 

That way, you have your source files in these folders, and Glide handles mem & disk LRU of resources dimensioned to the views where you need to display them.  

Or if you want something more basic, load(File) is also a good option.

**Comment by TWiStErRob** [comment]
@Teovald based on "it shows the progress for current downloaded gallery" it sounds like the galleries are packaged as ZIP or something similar, so I think the "optionally fetch the file when it is not yet there" is out of the picture. If that was true, she could just simply use a normal Glide request to a HTTP endpoint (or a custom model in the most complicated case).

@IskuhiSargsyan take a look at that sample and try playing around with it to see what that options is capable of. (My last comment is not relying on that sample, it's a different approach.)

**Comment by IskuhiSargsyan** [comment]
Thanks a lot, for replying
Your suggestion is really good, only I could have such scenario and it could not fit.
I am displaying images via viewPager and it could consist 200 pages,
in the background  if I download images myself (not using Glide mechanism), for example it could in the process of downloading the 10th image, during that period the user could navigate to 50th page and the 50th image is not downloaded, user should not wait unit 50 images are downloaded and then use Glide.load(File).
the background download should continue its work ,and at the same time another instance of "download mechanism " (Glide) should download from the server /display/store/ .
Is it clear, what I mean?

**Comment by Teovald** [comment]
It is clear.

In this case, I think that the custom model Loader/Fetcher route might be
interesting.

Let's say that you call the model class you want to load `Image`

With a custom model Loader/Fetcher, you can call :
`Glide.with(ctx).load(image).into(view);`   where image is an Image object.


Again, look at the wiki & samples if you need to see how to make this work,
but this allows you to implement ModelLoader<Image> and ModelFetcher<Image>
that will be called by Glide during the load.
The ModelFetcher can take charge of downloading the image if it is not
done.

Since the `load(image)` call is made in the onBind callback of your
viewholder, you are guaranteed that it is called when the user tries to see
the image, so it is time to download the image even if it is out of order.
You will just need to also send it to your download module afterwards so it
is not downloaded twice.





2016-03-20 17:52 GMT+01:00 IskuhiSargsyan <notifications@github.com>:

**Comment by TWiStErRob** [comment]
Hehe, what @Teovald said, and I wrote this at the same time:

Based on your previous comments it sounded like you had a single download for a gallery. If you can address individual pages to be downloaded through HTTP, then you should write a custom model like this:
```java
class Page {
    String gallery;
    int pageNumber;
    File localFile;
    String remoteUrl;
}
```
then in a custom fetcher you can check if the local file exists and return that, if it doesn't then return a remote network stream. This is essentially what @Teovald's example is doing, you must know the structure beforehand if the user can jump to page 50. The only drawback is that if the user jumps then the 50th page may be double downloaded: once because the user displayed it and once because the background queue processed it, but since it is the same image Glide's cache will be up-to-date. This can be worked around though.

**Comment by IskuhiSargsyan** [comment]
Thanks so much for replying.
I am getting realise how I need to do.
I create custom DiskLruCacheWrapper, where l add getDiskCache(String subDirectory), for implementing different  subdirectories
and I have questions:)
in loadData() of  ASynchronizableDataFetcher you check if it doesn’t exist in disk cache fetch from server (using HttpUrlFetcher loadData())
but I don’t understand if we are skipping memory cache what we are doing in  ASynchronizableImageLoader  class in  getResourceFetcher()
Question 2) as I understand default  classes of fetcher/loaders  in  glide library are HttpUrlGlideUrlLoader/HttpUrlFetcher classes ,but in which classes I could find before fetching from server , the part where the check of image is in memory/disk cache.

**Comment by TWiStErRob** [comment]
1)
Not skipping memory cache, memory cache is checked, but if it's not found there Glide goes and tries to fetch. With that solution you're likely skipping disk cache in order to always query your custom fetcher.

2)
The entry points are:
 * memory cache and active resources in `Engine.load`
 * disk cache and fetching in `EngineRunnable.run/decode`

**Comment by IskuhiSargsyan** [comment]
in Glide.java we have method clearDiskCache() ,which calls clearDiskCache() of Engine.java -> DiskLruCacheWrapper clearDiskCache()
I want to add another one clearDiskCache(String param) in Glide.java
consequetly I need to add methods in Engine.java -> DiskLruCacheWrapper.java

Is  there any way to have these custom methods without making changes in Glide library?
I mean to create custom Glide /Engine/ classes where I could add my  methods and then apply these classes to Glide library/

**Comment by TWiStErRob** [comment]
You can't change classes in JARs easily. You could make a fork of Glide and make whatever changes, or somehow delete the .class files from the jar (dex doesn't like duplicates) and create your own copy of those, but you would be still modifying Glide code.

You're stuck with the interface DiskCache gives, but at the same time you can have a class that implements the interface required by Glide **and** has the methods you need. Just save an instance of the cache that you create and call your custom methods on that.

@Teovald's solution allows you to write whatever caching logic you want because you're in full control of whether to find files on the disk (let it be a disk LRU cache or pinned storage, up to you) or access the network, Glide is only concerned about getting an InputStream back.

Tip: you don't need to @-mention in every comment, every participant (on the right sidebar) gets notifications because we've commented.

**Comment by TWiStErRob** [comment]
@IskuhiSargsyan I assume you made it work, or went with a different solution.
