### ISSUE TITLE
If I do not apply any transformation to image and set disk Cache Strategy to RESULT what will be the behaviour 

### ISSUE THREAD

**Issue by thatsankur** [bumptech/glide#1074]
Hi All,

I am new to Glide and wanted to understand what will be the behaviour of library 

If I do not apply any transformation to image and set disk Cache Strategy to RESULT 

While I was testing I was making image request from from url in list view which list all items and and same image request in next page it was taking quite long time using below code 

```java
Glide.with(context)
                .load(url)
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .placeholder(defaultBackground)
                .into(imageView);
```

As you can see I am not applying any transformation to this image so will it be able to cache original image ?

While when I set disk Cache Strategy to ALL it was very very fast I'n loading image on same list view as well as on next page 

So my question is it mandatory to apply transformation to source image to use RESULT Policy or it will cache source image (from my observation I can see that it was very slow and I assume that it was not caching anything correct me if I am wrong meanwhile I will check the source)

**Comment by TWiStErRob** [comment]
Wow, this reminds me of myself when I was figuring this out :)

There are two types of disk caches: SOURCE and RESULT (ALL is applying both, the default is RESULT). SOURCE saves the incoming network bytes as they are, and RESULT saves the transformed Bitmap (which is tailored to a specific target(~view) size).

Any chance you're loading GIFs? Because those don't play well with RESULT cache, only SOURCE.

The size and transformation must match in order to hit the RESULT cache, and you're using a transformation, it's implicit (see `.into(ImageView)`) from the ImageView.scaleType in XML. If it's the same for both views, then it's fine.

Hope this helps, please ask if you need more.

**Comment by thatsankur** [comment]
Thanks for prompt reply :)
That's my question is actually **I am not applying any transformation on the Image downloaded **so I was wondering that it's not actually caching anything as the image download it taking time and I can see ill  effects in same image request in subsequent requests with caching strategy as RESULT

but it is working fine with ALL so  I was wondering weather is it the way it is supposed to work

**Comment by TWiStErRob** [comment]
Can you please describe the actual versus your expected behavior a little more. It's not totally clear what is not working for you. Don't spare sentences, describe in detail :)

Including SOURCE cache (using ALL) prevents multiple downloads of the same image. It's worth doing that if the thumbnail is read from the same image as the full screen image. Compare this to the case when the thumbnail has a different Uri, where it's not worth saving the SOURCE image, because it'll always be the same size (in the list) and the RESULT cache is read much faster (no downsampling and transformation needed).
