### ISSUE TITLE
SimpleTarget re-use issues

### ISSUE THREAD

**Issue by xufan** [bumptech/glide#1080]
**Glide Version**:3.7.0
**Device/Android Version**:5.1
I'm using Glide to get Bitmap from network and use SimpleTarget to async draw the Bitmaps on my CustomView.And I use this view in RecyclerView.

code in my CustomView:
```java
private void loadBitmap(int i) {
        Glide.with(getContext()).load(mImageUrls.get(i)).asBitmap().dontAnimate().dontTransform().into(glideTarget);
}

private SimpleTarget<Bitmap> glideTarget = new SimpleTarget<Bitmap>() {
        @Override
        public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
            mBitmaps.add(resource);
            invalidate();
    };

 @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();      
        Glide.clear(glideTarget);  
    }

 @Override
    protected void onDraw(Canvas canvas) {
          //...do draw Bitmaps like gridview but in single view
    }
```
The issue is if I declare ```glideTraget``` as fields and I scroll the RecyclerView ,some Image will missmatch.BUT if I create ```glideTraget``` each time for ```into```,everything is fine. 

full code is free to touch:
https://github.com/xufan/MultipleImageView

**Comment by TWiStErRob** [comment]
A `Target` represents a single resource loaded from a source into something and it's full lifecycle. Responsible for telling Glide the size of the target display and handling events like "started" or "failed" to display a placeholder/error Drawable.

**Since you have multiple sources and multiple grid locations, you need multiple targets.**

Few tips:
* in onResourceReady: `mBitmaps.set(i, resource)` because you may get async out of order
* in `setUrls` loop through the existing targets and `Glide.clear` each before clearing the target list
* to make your target more compliant I suggest to override `onLoadCleared -> mBitmaps.set(i, null)`
* use `.override(w,h)` to Glide load to not waste memory
* no need to clear targets in ondetached, you can call `setUrls(emptylist)` to prevent code duplication.

**Comment by xufan** [comment]
Thx for the tips and multiple targets seem work fine.

**Comment by xufan** [comment]
Major Error Happen..When I scroll fast and a long time on RecycleView.
```java
java.lang.StackOverflowError: stack size 8MB
at com.bumptech.glide.request.GenericRequest.init(GenericRequest.java:198)
at com.bumptech.glide.request.GenericRequest.obtain(GenericRequest.java:121)
at com.bumptech.glide.GenericRequestBuilder.obtainRequest(GenericRequestBuilder.java:838)
at com.bumptech.glide.GenericRequestBuilder.buildRequestRecursive(GenericRequestBuilder.java:832)
at com.bumptech.glide.GenericRequestBuilder.buildRequest(GenericRequestBuilder.java:790)
at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:658)
at android.ui.custom.MomentPicView.loadBitmap(MomentPicView.java:259)
```

line 259 in Method ```loadBitmap ```
```java
Glide.with(getContext()).load(mImageUrls.get(i)).asBitmap().diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(simpleTarget);
```

Is multiple targets cause this error?

**Comment by TWiStErRob** [comment]
Can you post the rest of the stack overflow? There needs to be a repeating pattern that holds a cue.

**Comment by xufan** [comment]
Sorry,I forgot to keep the rest of the stack overflow.Now I can't reappear that ..

**Comment by TWiStErRob** [comment]
Then there's isn't much we can do, the key point of the stack overflow is finding the loop, in this case who calls `loadBitmap` and why? Do you by any chance start a new load in any of the Target lifecycle callbacks?

**Comment by xufan** [comment]
Yes,I had start a new load on ```onResourceReady``` ,so the load can one by one

**Comment by TWiStErRob** [comment]
You shouldn't start a new load in those methods, because sometimes they're called sync (when hitting memory cache). So it's possible that it wasn't an infinite method call loop, just a really deep call stack.
You can start all loads at the same time into different targets, Glide will make sure not too many are requested through the network at the same time.

**Comment by TWiStErRob** [comment]
In onlayout call `for (int i = 0; i < mImageUrls.size(); ++i) loadBitmap(i);` and remove the all the `isLoading` and `bSize` logic, you can call `refresh(i)` in target.

**Comment by xufan** [comment]
I have change my code and ```StackOverflowError``` fixed.
But I find something strange maybe cause by re-use ```SimpleTarget ```.
Sometimes I scroll fast and stop at the bottom ,the bottom view draw bitmaps from previous request.
like https://github.com/bumptech/glide/issues/450, can I use ```ImageViewTarget``` or make something like ```ImageViewTarget``` implementation on ```SimpleTarget ```.

**Comment by xufan** [comment]
I think it can be close for now.
