### ISSUE TITLE
Android AccountManager access in OkHttp3 Authenticator 

### ISSUE THREAD

**Issue by rshah** [bumptech/glide#1105]
**Glide Version**:
3.7.0

**Integration libraries**:
okhttp3-integration-1.4.0

**Issue details / Repro steps / Use case background**: 
I'm looking for example using Glide with okhttp3 authenticator which in turn will ask for auth token from Android AccountManager. 
I'm trying to download image form the server which need OAuth2 token.
Since glide is called from main thread. I always hit by this exception thrown from AccountManager.
```Java
java.lang.IllegalStateException: calling this from your main thread can lead to deadlock
 	at android.accounts.AccountManager.ensureNotOnMainThread(AccountManager.java:1412)
 	at android.accounts.AccountManager.access$200(AccountManager.java:144)
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
My codes something like below.
I'm calling registerGlide() from Application onCreate() method.
```kotlin
private fun registerGlide() {
        val httpClientBuilder = OkHttpClient.Builder()

        httpClientBuilder.authenticator {
            route, response ->
            val originalRequest = response.request()
            val newRequest = originalRequest.newBuilder()

            if (originalRequest.header("Authorization") != null) { 
                val accountManagerFuture = accountManager.getAuthToken(account, AUTH_TOKEN_TYPE, null, null, null, null)
                val authTokenBundle = accountManagerFuture.result ?: throw AuthException("authTokenBundle is null")
                val authToken = authTokenBundle.get(AccountManager.KEY_AUTHTOKEN)!!.toString()
                newRequest.header("Authorization", "Bearer $authToken")
            }

            newRequest.build()
        }

        Glide.get(this)
            .register(GlideUrl::class.java, InputStream::class.java,
                    OkHttpUrlLoader.Factory(httpClientBuilder.build()))
    }
```
And from recycler adapter, i will call glide like:
```Java
Glide.with(context).load(iconUrl).into(targetView);
```

**Comment by TWiStErRob** [comment]
The stack trace is incomplete, not clear which method is being called on the wrong thread. Anyway, I think you should do two things to make sure you're correctly integrated into Glide:
 1. [Use a `GlideModule`](https://github.com/bumptech/glide/wiki/Configuration) (lazy config makes the app startup much faster by moving loading Glide classes from App.onCreate to somewhere where the main activity UI is already likely built, so the user sees less "white" at startup)
 2. Use a custom model (this will prevent slapping the token into **every** outgoing network call, some of your images may not need auth, because they're public) with Glide headers (this decouples your authentication from OkHttp so you're free to change to any networking library in the future)
I recommend Alternative 2 from https://github.com/bumptech/glide/issues/921#issuecomment-174185985, just ignore everything starting with "other" since you only need one custom model. `AuthLoader` will be definitely called in the background.

**Comment by rshah** [comment]
Something was wrong with account data in my app, after reinstalling the problem gone.
Sorry for the noise, but your input are really valuable. Thank you very much.
