### ISSUE TITLE
Glide Crashes when there is no internet connectivity

### ISSUE THREAD

**Issue by Sutirth** [bumptech/glide#1130]
Glide version: compile 'com.github.bumptech.glide:glide:3.7.0'

Scenario I am don't have internet access and glide crashes with exception as follows:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
    at com.bumptech.glide.load.model.LazyHeaders$StringHeaderFactory.hashCode(LazyHeaders.java:260)
```

Glide module load code:
```java
Glide.with(getApplicationContext()).load(glideUrl)
                    .signature(new StringSignature(teamInfo.getProfileImageUpdatedAt()))
                    .placeholder(R.drawable.badge_placeholder)
                    .dontAnimate()
.into(leaderboardFriendsViewHolder.teamUserPic);
```

**Comment by TWiStErRob** [comment]
Glide internally creates two instances of `StringHeaderFactory`:
 * `DEFAULT_ENCODING` which is a string constant
 * `DEFAULT_USER_AGENT` which is protected by `TextUtils.isEmpty`
So whatever is throwing that exception must be created by you.

I see that you use `glideUrl`, what headers/builders did you pass in?

**Comment by Sutirth** [comment]
@TWiStErRob  I am passing  
GlideUrl glideUrl = new GlideUrl(URL, new LazyHeaders.Builder()
                    .addHeader("access_token", ACCESS_TOKEN)
                    .build());
as glideUrl just an access token which I get using shared preference

**Comment by TWiStErRob** [comment]
Hmm, can it be null?
If you think not, then the static analysis failed us and I suggest you put a breakpoint in the `StringHeaderFactory` constrcutor with a condition `value == null`, and when the breakpoint is hit you can check the debug frames to see where it was called from, and possibly print the same info by executing `new Exception().printStackTrace()` in immediate or on breakpoint. Breaking in any other method is too late because it doesn't show where the value is coming from.

**Comment by TWiStErRob** [comment]
I assume you figured it out, feel free to reopen if you want more help regarding this.
