### ISSUE TITLE
Can it make view to bitmap?

### ISSUE THREAD

**Issue by gushoubang** [bumptech/glide#1131]
Can it make view to bitmap?

**Comment by TWiStErRob** [comment]
You have to write a custom model loader and data fetcher that passes the view along and a custom decoder that renders the view on a Bitmap.

I'm not sure it's worth it though, because you likely can't cache view conversions, so there isn't much benefit to using Glide. If you want to make it efficient by reusing Bitmaps you may use `Glide.get(context).getBitmapPool()` to "allocate" Bitmaps.

**Comment by gushoubang** [comment]
OK thanks
