### ISSUE TITLE
Image's resolution degrades when it's loaded from internet and saved in local disk

### ISSUE THREAD

**Issue by liushaofang** [bumptech/glide#1132]
Image's resolution has turned out to be 1080 * 607 when I am loading it into ImageView, the original resolution of which is 1920 * 1080. The following is my code.
`Glide.with(context).load(strUrl.asBitmap()
                    .listener(new CustomtListener(strLocal, callback))
                    .placeholder(R.drawable.pic_def).centerCrop().into(iv);`
CustomtListener get the load result and save downloaded image at local disk.
Could anyone tell me the reason and how to fix this problem?

**Comment by liushaofang** [comment]
1920/1080=1080/607~=1.78, so I do think Glide compressed the image in size, how can I avoid this size compression?Help ! ! !

**Comment by TWiStErRob** [comment]
1920x1080 is a landscape orientation and your phone is portrait 1080x1920. So Glide downscales the image to fit the width of the phone (to save memory, the user wouldn't see the difference anyway). Since you're hacking the Bitmap out of the view/listener you get this downsized version.

Take a look at the `downloadOnly()` API that gives you the original file (and caches it for later use), but if you just want to download the whole file, the use a networking library like OkHttp or Volley.
