### ISSUE TITLE
Glide not running scaleAnimation After retriving it from the Local Cache

### ISSUE THREAD

**Issue by PrathameshKesarkar** [bumptech/glide#1140]
I am trying to animate a ScaleIn Transition on An ImageView which is working perfectly fine when I try to open an Image for first Time but When I try to open The same Image for second TIme it doesn't animate for some reason after digging up the issue little bit I came to know that Glide skips the animation if it found Image in its local Cache

Is there any way I can run Animation even If it is present on Cache 

Here's the code
    `Glide.with(this)
                    .load(new File(imagePath))
                    .animate(R.anim.scale_in)
                    .into(mSendImageView);`

**Glide Version**:  **3.6.1**

**Comment by TWiStErRob** [comment]
Sorry, somehow I missed this.
The easiest workaround is `.skipMemoryCache(true)` which forces Glide to load each time from disk cache. It's not optimal, but it works and pretty simple.

A more complicated approach requires Glide [3.8.0](https://github.com/bumptech/glide/wiki/Snapshots), because of the method added in #1096; or v4
```java
.animate(new ViewAnimationFactory<GlideDrawable>(context, R.anim.scale_in) {
	@Override public GlideAnimation<GlideDrawable> build(boolean isFromMemoryCache, boolean isFirstResource) {
		return super.build(false, isFirstResource);
	}
})
```
Notice that it calls `super.build(false` to ignore if it's from memory cache. This will lead to Glide believing that all loads missed the memory cache and hence will animate.

If you can't upgrade to `3.8.0-SNAPSHOT`, you can do a similar inlining as seen in the listener of https://github.com/bumptech/glide/issues/527#issuecomment-148840717.
