### ISSUE TITLE
Image degradation after second start of app

### ISSUE THREAD

**Issue by martinsalaj** [bumptech/glide#1141]
3.7.0

**Integration libraries**:

**Device/Android Version**:
fails on Genymotion Galaxy S5 4.4.4
fails on real Nexus 7 6.0.1

**Issue details / Repro steps / Use case background**: 
After first start (after installing) of the app, the background pictures looks great. If I then go to home screen, remove the app from the stack and run the app again the picture quality is degraded. Any further attempt to restart the app keeps the degraded quality.
I checked in Android Device Monitor if in the cache a new picture (lower quality) is created but there is only one picture with the original size.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
In onCreate of mainActivity

ImageView background = (ImageView) findViewById(R.id.iv_background);
        Glide.with(this)
                .load(R.drawable.background)
                .centerCrop()
                .into(background);
```

**Layout XML**:
```xml
<RelativeLayout xmlns:android="...
<ImageView
        android:id="@+id/iv_background"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

First run screenshot:
![good](https://cloud.githubusercontent.com/assets/18599661/14717246/da2cc6fc-07f0-11e6-92b0-68fee2290204.jpg)

Second run screenshot:
![bad](https://cloud.githubusercontent.com/assets/18599661/14717251/dd705716-07f0-11e6-99e4-694cd7f9e805.jpg)

original image in the app:
![background](https://cloud.githubusercontent.com/assets/18599661/14717253/e067316a-07f0-11e6-8a7b-34dbdbd24614.png)

I'm taking a Udemy course and the project where this happens can be found on github (In my code there is more actual version of glide than in this branch)
https://github.com/slidenerd/BucketDrops/tree/video_29_implement_recyclerview_adapter/app/src/main/res

**Comment by martinsalaj** [comment]
Just found out that same behaviour can be reproduced at first start by rotating from portrait to landscape and back.

**Comment by TWiStErRob** [comment]
The problem is the gradient vs. `Bitmap.Config` or [Android's JPEG encoder](http://stackoverflow.com/q/36487971/253468).

You can work around by using one of these:

1. Enable high quality loading (the default is RGB_565):

	```java
	Glide.with(this)
        .load(R.drawable.background)
        .asBitmap()
        .format(DecodeFormat.PREFER_ARGB_8888)
        .centerCrop()
        .into(background);
	```
	this will likely make it better, but maybe not perfect.

2. Cache as PNG

	```java
	Glide.with(this)
        .load(R.drawable.background)
        .asBitmap()
        .format(DecodeFormat.PREFER_ARGB_8888)
        .encoder(new BitmapEncoder(CompressFormat.PNG, 100))
        .centerCrop()
        .into(background);
	``` 
3. Disable caching, since you already have the file on "fast" disk (inside the APK):

	```java
		Glide.with(this)
	        .load(R.drawable.background)
	        .diskCacheStrategy(NONE)
	        .centerCrop()
	        .into(background);
	```

I suggest using the last one, that's the least hacky and most resource-friendly.

**Comment by martinsalaj** [comment]
Works perfect. Thanks for the fast and informative reply.

**Comment by TWiStErRob** [comment]
Which one did you try and went with in the end?

**Comment by martinsalaj** [comment]
The last one, looks best.

**Comment by slidenerd** [comment]
Thanks for the big one @TWiStErRob  you really saved a lot of trouble for many people including me. I examined the data folder in the device monitor and wasnt sure why a bad quality image was loading, looks like I ll have to update the app and release a new patch with this in place :+1:

**Comment by TWiStErRob** [comment]
@slidenerd local files don't really need caching, maybe big files' little thumbnails (camera thumbs), but definitely not full size loads. BUT it's important not to turn off caching altogether because then you lose Glide's strength. You should try the other solutions too to see what is **really** causing the banding. As a teacher I think it's important to emphasize that every situation needs careful consideration. Take a look at https://github.com/bumptech/glide/issues/1085#issuecomment-200809180 for a good rule of thumb summary on caching.
