### ISSUE TITLE
Glide can't load image

### ISSUE THREAD

**Issue by ihsanbal** [bumptech/glide#1147]
When we draw the view with a canvas so Glide can't load image into the view.

**Comment by TWiStErRob** [comment]
Glide is async, can you please explain more what your problem is?

**Comment by ihsanbal** [comment]
I am using library for sectioned header view for recyclerview : https://github.com/timehop/sticky-headers-recyclerview this library drawin header views with canvas so when i will use drawing image view for upload profile image glide can't load into the view.

**Comment by TWiStErRob** [comment]
Because the image is not ready when it's drawn. You need to turn off animations with `.dontAnimate()` and notice this in their docs:

> The StickyHeaders aren't aware of your adapter so if you must notify them when your data set changes.
>
>     headersDecor.invalidateHeaders();

I think you need to call that method whenever the header is changed, that is when Glide finished loading the image. Try the following in order and stop when one of them work:
* add `.listener()` and call invalidateHeaders from `onResourceReady` and `return false`
* wrap invalidateHeader in a `view.post(new Runnable(){})`
* remove listener and create the target manually: `new GlideDrawableImageViewTarget` and override `onResourceReady`, call super and then call invalidateHeaders.
* wrap this invalidateHeaders in a post too.

It's OK, if that invalidate results in re-calling the Glide line because the image will be immediately server from memory cache so canvas drawing will see it. However you may need to check `isFromMemoryCache` argument to prevent infinite loops.
