### ISSUE TITLE
Feature Request: Progress Listener Callback in Listener

### ISSUE THREAD

**Issue by stripathi669** [bumptech/glide#1155]
I know this has been discussed several times, in several issues, in several ways with several different conclusion. (I have read #232 and related issues)

However, as awesome as this library is, I can't stress how important 'image download progress listener' feature is from users' or developers points of view (irrespective of whether one uses OkHttp or volley). It would be wonderful if we could have it as simple as just another callback in Litener (right where onResourceReady is).

Therefore it is my humble request to please consider this as a feature in one of the upcoming release. I do understand that this might be a not as easy as it looks.

Glide v3.6.0 with Volley integration

**Comment by TWiStErRob** [comment]
I agree it would be a nice addition, but I don't think it will happen for 3.x, maybe v4, PR is always welcome. Notice that #232 is still open, even though there's a workaround. Please subscribe to that issue in the right column, I'll close this as a duplicate. But let's continue our discussion:

Can you please elaborate here how the end users gain benefit from this? As a developer I understand that it's a useful debugging tool, but as a user I don't see any application where I would want to see how much of the image is downloaded as long as there is a placeholder (spinning or not) indicating that it's coming. The only place I could think of a progress be useful is when you pin some content, but that means that you're using Glide cache to store pinned content, which has no guarantees the file keep existing. If not using Glide's cache to store content then you have your own way to download where you can track your own progress. This is what we mean when we said "Glide is not a networking library".

I think this would require deep architectural changes and would force all integration libraries to implement this (OkHttp and Volley have facilities), or Glide to duplicate what those libs do (the default one doesn't have progress, only with a wrapping FilterInputStream or similar would it be possible). The hardest part is knowing how large the whole file is, because that's not a required part of the HTTP communication, everything is a stream in HTTP and Java without any indication of final size. Also fetchers don't necessarily have to return HTTP streams, it could be any stream like from ContentProvider, which may or may not do actual downloading.

**Comment by TWiStErRob** [comment]
@stripathi669 check out #1160's code. It's much closer to what you want than my huge gist in #232.

**Comment by stripathi669** [comment]
Thank you very much for listening to my plea.

Let us consider of an app similar to imgur, or giphy or instagram. As you know, a GIF can be of 2Mb or 50Mb. A user doesn't know this apriori before he taps to open the GIF. Now smaller images/GIF will be loaded quickly, but larger ones will take time. However, the attention span of a user is not that large, i.e. person will move away if the content is not loaded within 5 secs, not stare at the screen. The progress helps as the user may stay on screen( user can see how much is remaining).

Secondly, sometimes the internet is not working, even though the phone shows 4G signal. No increase in progress tells a user that it is internet's fault, not the app's.

Thirdly, a very vast majority of internet user base is in India and China, where slow speed internet is still common. This leads to points 1 & 2. Believe me, Glide is immensely popular there too.

On the feasibility part, I completely understand the complexity. It is challenging.
There is something that can be done: Only expose the downloaded (or decoded) size. It will be upon developers  to calculate the progress, as developers must be storing the total size of image apriori glide request(any good app does that).

As an example - I think Instagram does what we're talking about. I will try to post a screenshot if you haven't had a chance to see.

**Comment by TWiStErRob** [comment]
> No increase in progress tells a user that it is internet's fault, not the app's.

This is a good point, I hate reading reviews (on others' apps) that it's bad, but I know it's not the apps fault.

> Believe me, Glide is immensely popular there too.

I know I've seen the user names duing support on this forum. Yours looks Indian too.

> GIF can be of 2Mb or 50Mb [...] where slow speed internet is still common

In this case I would question the user, why is (s)he looking at huge files/images/videos with a bad connection?

> must be storing the total size of image apriori glide request

You mean like the API that returns the JSON contains url/width/height/size, right?

> I think Instagram does what we're talking about.

I'm not using this service.

> I completely understand the complexity.

I know you want this to be supported out of the box, but have you looked at the two workarounds?
What would you think about creating an integration library that supports this based on my gist for example?
