### ISSUE TITLE
calculateBestThreadCount does disk IO so had bad performance

### ISSUE THREAD

**Issue by danml** [bumptech/glide#1170]
GlideExecutor.calculateBestThreadCount seems to be doing disk IO and will trigger strict mode violations in some cases when used on the UI thread.

https://github.com/bumptech/glide/blob/4d2e710411c940d6824b52b654939ef21733ec37/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java#L169

```ruby
...
StrictMode:    at java.io.UnixFileSystem.list(UnixFileSystem.java:300)
StrictMode:    at java.io.File.list(File.java:1057)
StrictMode:    at java.io.File.listFiles(File.java:1175)
StrictMode:    at com.bumptech.glide.load.engine.executor.GlideExecutor.calculateBestThreadCount(GlideExecutor.java:247)
StrictMode:    at com.bumptech.glide.load.engine.executor.GlideExecutor.newSourceExecutor(GlideExecutor.java:102)
StrictMode:    at com.bumptech.glide.GlideBuilder.createGlide(GlideBuilder.java:267)
StrictMode:    at com.bumptech.glide.Glide.get(Glide.java:155)
StrictMode:    at com.bumptech.glide.manager.RequestManagerRetriever.getApplicationManager(RequestManagerRetriever.java:88)
StrictMode:    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:112)
StrictMode:    at com.bumptech.glide.Glide.with(Glide.java:431)
...
```

**Comment by TWiStErRob** [comment]
As far as I know those files in `/devices` are not real files, they come from the kernel and drivers and are virtually created/queried (barely remember creating our own at an embedded course at uni and it was just a few [C kernel calls/callbacks](http://stackoverflow.com/q/13132013/253468)). Obviously the point of these is to create the illusion of files so anything can handle them, including Java.

Based on this information, and that this happens only once (at the first `Glide.with/get` call) and the fact that we need the best possible CPU count to be performant later<sup>&#x2020;</sup>, I think this is a false positive and we could do this change so you don't get the penalty (@sjudd?):
```java
public static int calculateBestThreadCount() {
	ThreadPolicy originalPolicy = StrictMode.allowThreadDiskReads();
	try {
		...
	} catch (Throwable t) {
		...
	} finally {
		StrictMode.setThreadPolicy(originalPolicy);
	}
	...
}
```
*&#x2020; Imagine you have an 8-core nuclear power-plant phone, but because it's really effectively handling power, 7 of those are asleep when you set up Glide. The consequence of that would be that Glide becomes a serial image loader for the whole run of the app.*

---

As a local workaround if you want Glide to skip calling `calculateBestThreadCount` you can do your own setup like this:

```java
public class GlideThreadSetupModule implements GlideModule {
	@Override public void applyOptions(Context context, GlideBuilder builder) {
		builder.setResizeExecutor(GlideExecutor.newSourceExecutor(calculateCPUCountWithoutIO(),
				GlideExecutor.DEFAULT_SOURCE_EXECUTOR_NAME, UncaughtThrowableStrategy.DEFAULT));
	}
}
```

**Comment by sjudd** [comment]
Yes it's my understanding that this a false positive, we could do the try/finally approach and see if that works.

**Comment by sjudd** [comment]
Fixed here: https://github.com/bumptech/glide/commit/6d91e362060d4ea3301681989dc0f56b04037f36
