### ISSUE TITLE
Disable Lifecycle Integration

### ISSUE THREAD

**Issue by nverbeek** [bumptech/glide#1174]
Version 3.7.0

I have what is hopefully a simple question. Apologies if this has been asked before, I searched and didn't find anything relevant.  The version I am using has lifecycle integration, specifically reloading failed requests in onStart (I think it is onStart anyway), which occurs when the screen comes back on after being off.  In my case, I'm not sure this functionality is useful and I would rather turn this off.  Is there a way for me to disable this functionality?

**Comment by TWiStErRob** [comment]
You can try (an)using the application context: http://stackoverflow.com/a/32887693/253468

An alternative to broadening the context is to `Glide.clear()` any filed requests immediately so that when the context (re)starts those requests are not attached to the context. (Context here can be a fragment, I'm not referring to the class).

Would you mind explaining why is it not useful in your case? What is your case about?

**Comment by nverbeek** [comment]
It looks like the Glide.clear() was just the thing I needed.  A very simple and easy solution, thank you!

For further detail, our application is an enterprise application that generally runs on a secluded local network. High throughput customers often have network latency issues, and since images take up quite a lot of throughput we want to limit the requests as much as possible.  With the solution you gave, we can easily make this functionality configurable.

Thanks again!
