### ISSUE TITLE
"You cannot start a load for a destroyed activity" without starting load in background thread

### ISSUE THREAD

**Issue by yubaokang** [bumptech/glide#1181]
I use glide like this:
```java
 if (imageView != null) {
            Glide.with(imageView.getContext())
                    .load(url)
                    .placeholder(placeHolder)
                    .crossFade()
                    .into(imageView);
        }
```

get error like "You cannot start a load for a destroyed activity";
 I am sure ,it's not run in child thread.

**Comment by TWiStErRob** [comment]
If you were trying to start on load on a background/worker (=child?) thread you would get a different exception. T he problem here is that you start the load after the activity has been destroyed. There's no point in doing that because the user won't ever see the image. You'll need to guard the Glide load (and possibly anything around that code) with a check if it's too late do display the data. The best way I think is to cancel the async task in onDestroy, so once onPostExecute is called you can check isCancelled and not do anything.

**Comment by yubaokang** [comment]
if I user getApplicationContext to load Image, it's ok.but i think it's not a good way.
I use Retrofit2 android okhttp3 to load json data,and callback onMainThread,
when I Intent to Activity,and fast finish it, several time it happend;

-----------like this------------------
RetrofitUtils.getService().getUserInfo(SPUtils.getInstance(context).getUserId()).enqueue(new RCallback2<GJRes<UserInfoData>>() {
            @Override
            public void onSuccess(GJRes<UserInfoData> response) {
                UserInfoData userInfoData = response.getData();
                String mobile = userInfoData.getMobile();
                view.setPhoneNum(VerifyUtils.mobileReplace4Stars(mobile));
                UserInfoData.PlatformUserInfo pur = userInfoData.getPlatformUserInfo();
                if (pur != null) {
                    String nickname = pur.getNickName();
                    view.setNickname(nickname);
                    UserInfoData.PlatformUserInfo.Avatar avatar = pur.getAvatar();
                    if (avatar != null) {
                        String imgPath = avatar.getPath();
                        view.setHeadImg(imgPath);
                    }
                }
            }

            @Override
            public void onFailed(GJError gjError) {
            }
        });

-----------activity ----------
 @Override
    public void setHeadImg(String headUrl) {
        ImageUtils.showImageCircleHead(this, headUrl, iv_head);
        EventBus.getDefault().post(new UserInfoUpdateHead(headUrl));
    }
 @Override
    protected void onDestroy() {
        super.onDestroy();
        EventBus.getDefault().unregister(this);
        Glide.clear(iv_head);
        Glide.get(this).clearMemory();
//        Glide.with(this).pauseRequests();
    }
----------------alse it's not ok  -------------------

**Comment by yubaokang** [comment]
Can Glide cancel this Activity's or this Fragment's all Image request?

Glide.clear(iv_head);
Glide.get(this).clearMemory();
Glide.with(this).pauseRequests();
like this is not work.
thank you!

**Comment by TWiStErRob** [comment]
I think you can cancel the `getUserInfo` request, there's no point in continuing with any logic if there are no views to display the data, and never will be. Also when you do an EventBus unregister, does it prevent `UserInfoUpdateHead` from being executed?

Trying to clear all those things will never help you, because that's not the issue. Those are automatically done for you by Glide. You need to cancel your own logic (as I stated above) to prevent it from **starting** any new loads. Completed loads won't throw exceptions.

**Comment by yubaokang** [comment]
I have cancel the retrofit request,but it also doesn't work.
I see source code contain 
-----------------------------------------------------------
 @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
    private static void assertNotDestroyed(Activity activity) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && activity.isDestroyed()) {
            throw new IllegalArgumentException("You cannot start a load for a destroyed activity");
        }
    }
-----------------------------------------------------------
where it  means if the VERSION>17 and the activity has destroyed,it will throw exception?
and if add a judge like this:-->!context.isDestroyed()
-----------------------------------------------------------
 if (imageView != null && imageView.getContext() != null && !context.isDestroyed()) {
            Glide.with(context)
                    .load(url)
                    .placeholder(R.mipmap.ic_head_normal)
                    .crossFade()
                    .bitmapTransform(new CropCircleTransformation(imageView.getContext()))
                    .into(imageView);
        }
-----------------------------------------------------------

**Comment by TWiStErRob** [comment]
You have to cancel both getUserInfo and UserInfoUpdateHead.

The API 17 check is there because isDestroyed is added on that level.

Notice that if you manage to cancel these queued/posted code blocks, you shouldn't need any of those conditions.
