### ISSUE TITLE
How to change DEFAULT_CONNECTION_FACTORY inside HttpUrlFetcher?

### ISSUE THREAD

**Issue by liheyuan** [bumptech/glide#1187]
**Glide Version**: 3.7.0

Hello guys, 

We used a self-signed HTTPS cert on debug env, so may need to do litte thing on UrlConnection inside HttpUrlConnectionFactory under HttpUrlFetcher, is there anyway to configure/replace default DEFAULT_CONNECTION_FACTORY? 

OR I have to rewrite a new module and stub by install module?

Thank you.

**Comment by TWiStErRob** [comment]
Yep, I think you need to copy HttpUrlFetcher, HttpUrlGlideUrlLoader and create your own GlideModule to register the HttpUrlGlideUrlLoader.Factory, see https://github.com/bumptech/glide/wiki/Configuration.

You can get away with less duplication if you copy HttpUrlGlideUrlLoader into the same package and using the "visible for testing" constructor of HttpUrlFetcher.

---

An alternative to all this is to use [OkHttp](https://github.com/bumptech/glide/wiki/Integration-Libraries#okhttp-3) and configure your OkHttpClient appropriately.

**Comment by liheyuan** [comment]
@TWiStErRob Thank you very much.

BTW, Is it a good idea if Glide support some support for configure DEFAULT_CONNECTION_FACTORY ? or some kind of decoration class stub for UrlConnection ?

**Comment by TWiStErRob** [comment]
I think that whole `HttpUrlConnectionFactory` is there because `URL` is a final class and can't be mocked.

In general if you want to customize the loading logic it's usually easier to just drop in OkHttp and do a client configuration, it has a good API and many configuration opportunities.

The `HttpUrlFetcher` may be made more extensible by creating smaller overridable methods, but you would still need a custom loader/factory/module to change the behavior.

If you have something in mind that would make Glide better, feel free to make the change and create a PR, even if it's just to show us the concept. You could refine the pull later (tests and stuff) if we think it would be a good addition.
