### ISSUE TITLE
Loading image thumbnail then the full size will play the animation twice

### ISSUE THREAD

**Issue by 80998062** [bumptech/glide#1188]
I want to animate the image view when loaded.

But now the issue is it seems play the animation twice when it is downloaded first time.

> when load image from cache ,the animation work fine

I think this is due to the `.thumbnail()` method.

Cause when load a thumbnail first ,Glide will performs the cross-fade animation too ,

so for example .

Besides , I add `.dontAnimate()` still not work.

So I wander whether I should refactor on my custom animation 

or I must remove the `.thumbnail()`method to load only once.

---

Here is my custom Target : 

```java
package com.sinyuk.jianyimaterial.glide;

import android.animation.AnimatorListenerAdapter;
import android.animation.ObjectAnimator;
import android.animation.ValueAnimator;
import android.graphics.Bitmap;
import android.graphics.drawable.BitmapDrawable;
import android.support.v4.view.animation.FastOutSlowInInterpolator;
import android.widget.ImageView;

import com.bumptech.glide.request.target.ImageViewTarget;


public class SinyukTarget extends ImageViewTarget<Bitmap> {
    private final ImageView mImageView;

    private long mDuration = 2000;

    public SinyukTarget(ImageView view) {
        super(view);
        this.mImageView = view;
    }

    public SinyukTarget(ImageView view, long animateTime) {
        super(view);
        this.mImageView = view;
        this.mDuration = animateTime;
    }

    @Override
    protected void setResource(Bitmap resource) {
        mImageView.setImageBitmap(resource);
        AlphaSatColorMatrixEvaluator evaluator = new AlphaSatColorMatrixEvaluator();
        final AnimateColorMatrixColorFilter filter = new AnimateColorMatrixColorFilter(evaluator.getColorMatrix());

        final BitmapDrawable drawable = (BitmapDrawable) mImageView.getDrawable();

        drawable.setColorFilter(filter.getColorFilter());

        ObjectAnimator animator = ObjectAnimator.ofObject(filter, "colorMatrix", evaluator,
                evaluator.getColorMatrix());
        animator.addUpdateListener(animation -> drawable.setColorFilter(filter.getColorFilter()));
        animator.setInterpolator(new FastOutSlowInInterpolator());
        animator.setDuration(mDuration);
        animator.addListener(new AnimatorListenerAdapter() {});
        animator.start();
    }
}
```

Here is where I use Glide

```java
	shotRequest = Glide.with(mContext).fromString()
                .asBitmap()
                .error(mContext.getResources().getDrawable(R.drawable.image_placeholder_grey300))
                .placeholder(mContext.getResources().getDrawable(R.drawable.image_placeholder_grey300))
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .priority(Priority.IMMEDIATE)
                .thumbnail(0.2f);

	shotRequest.load(JianyiApi.shotUrl(itemData.getPic()))
	.into(new SinyukTarget(holder.shotIv, 552));
```
---

Any help will be appreciated . And sorry for my poor English ， 

hope I have described the problem clearly

**Comment by TWiStErRob** [comment]
The target doesn't distinguish between thumbnail and final image. You should have a flag in your target to indicate that an animation has already started and not start another one.

You may want to override `onResourceReady` instead of `setResource` to prevent the default logic from happening (see `ImageViewTarget` source code), though `.dontAnimate()` should prevent the cross-fade.

---

You can also use the `.listener()` to do the animation, where you can have almost the same code as in `setResource`, but you have `isFirstResource` available to you.

---

Another alternative is to use the numerous `.animate()` methods to do custom animations, in this case you can separate this logic nicely from your target, actually likely you don't need a target.

---

Tip, you don't need to store `mImageView` in your target, `super.view` is available and typed as `ImageView`.
