### ISSUE TITLE
You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by LinkOut** [bumptech/glide#1191]
**Glide Version**: Using the last version of Glide 

**Device/Android Version**:  Check this image -> http://postimg.org/image/8kz4zirpt/

**Issue details**:  The issue occurs when i open an Activity that is loading an image and i close it before image is being loaded. 

     Glide.with(mContext).load(Utility.getCorrectImage(mBusiness.getId_image())).placeholder(R.drawable.no_image).centerCrop().into(imgHeader);

This actually loades the image in the ImageView, mContext is the ACTIVITY Context. 

How to avoid this situation?

Thanks

**Comment by TWiStErRob** [comment]
Need a little more context, where is that line? Which lifecycle even? Is it as a result of an async background operation?

**Comment by LinkOut** [comment]
Ok sorry, this line is inside a Class, that got a method returning a View. This method is called onCreate, is not a background operation.

**Comment by TWiStErRob** [comment]
Hmm, so you're essentially starting the Glide load in `Activity.onCreate`. Are you using `AppCompatActivity`?

**Comment by LinkOut** [comment]
Sorry, is not onCreate is onEvent 
Yes i'm using AppCompatActivity, let me explain you better the scenario.

Starting from a list of elements (async taks) using EventBus i pass to an Activity the FULL object, this object contains an image. onEvent of EventBus im calling that method, passing the object and it returns me a View (that i use as a header of a list that is loading), that method is calling Glide using that activity context.

**Comment by TWiStErRob** [comment]
So you are using an async operation. This is what happens:
 1. onCreate
 2. onBackPressed -> finish()
 3. onDestroy
 4. onEvent -> Glide.load()

`onDestroy` should cancel the event bus messages, because **there's no point in creating a view or binding data to any views after that point, the user won't ever see it**. Glide cannot start the load because it's trying to add a lifecycle tracking fragment, which is not possible for a destroyed activity. (You can find similar issues here if you find for the exception message.)

**Comment by LinkOut** [comment]
I try something like this:
    static boolean isActive = false;
@Override
      public void onStart() {
         super.onStart();
         isActive = true;
      } 

      @Override
      public void onStop() {
         super.onStop();
         isActive = false;
      }

Why Glide make app crash and dont just ignore this...

**Comment by TWiStErRob** [comment]
Good question :) I think it's better like this. I would consider doing huge amounts of unnecessary work a bug. This just brings it to the surface so it's possible to fix it. Note that if we remove that check the app would still crash, just probably later.

If you really want to consume battery and keep working while the user is waiting to exit the activity, you can use this workaround: https://github.com/bumptech/glide/issues/803#issuecomment-163528497

**Comment by LinkOut** [comment]
The question is that same code with different library does not make app crash, since this app is in prod one crash due to a lib is not the best situation

**Comment by TWiStErRob** [comment]
I don't think it's nowhere officially stated that Glide can be used as a drop-in replacement for any other image loader, `Lib.load.into` can do extremely different things depending on which library and what arguments you pass in, only the method names are similar. Different libraries have different philosophies, that's why there are so many. It's possible that some different libraries don't track the lifecycle of the activity/fragment to clean up unused resources for you. There must be a reason why you swapped library as well...
