### ISSUE TITLE
How to use Glide to upload image to server?

### ISSUE THREAD

**Issue by piedpiperlol** [bumptech/glide#1192]
**Glide Version**: 3.7

I have an image stored in internal storage and I want to compress and upload it to server. How to do this using glide? Thank you for providing this library. it's amazing :)

**Comment by TWiStErRob** [comment]
Glide can only read files, see https://github.com/bumptech/glide#glide

That said you can prepare your image for upload with `.asBitmap().toBytes().into()`, see https://github.com/bumptech/glide/issues/481#issuecomment-107643716 for a full example. You'll need to upload the byte[] instead of `IOTools.writeFile`, and do it on a background thread!

**Comment by piedpiperlol** [comment]
How do you save the byte to a particular path?

**Comment by TWiStErRob** [comment]
https://www.google.com/search?q=write%20byte%20array%20to%20file%20java
If you want to upload search for "upload http java".

**Comment by piedpiperlol** [comment]
Is there a way to specify the size of the compressed image? Let's say the initial size is 1MB and I want it to be compressed to about 100kb.

**Comment by TWiStErRob** [comment]
That's only possible if you're using low level libjpeg to compress. If size is important you can do a binary search and compress the image with different qualities to find a good enough approximation.

I think it's much easier though to opt for a max size, because if the image cannot be bigger than that, then the byte size is capped as well. Play around with a few quality/max size variations with a few sample images to find good values.

**Comment by piedpiperlol** [comment]
By opt for a max size you mean setting the quality to 100? 
So the code will be something like : 
`        .toBytes(CompressFormat.JPEG, 100)
`
Is that right?

**Comment by TWiStErRob** [comment]
No, that would result in the best quality, and the byte size would be the biggest possible. I meant these two lines:
```java
        .atMost()
        .override(2048, 2048)
```
which will result in downsizing bigger images to have each side less than 2048. Here's a sample I have, I took 1882 images (with varying image dimensions) with my phone's camera and used the exact code in https://github.com/bumptech/glide/issues/481#issuecomment-107643716 to store it in my DB:
max: 775k, min: 11k, average: 159k, a quick histogram plot made with https://www.easycalculation.com/graphs/create-histogram.php:
![image](https://cloud.githubusercontent.com/assets/2906988/15150245/aacd4bda-16cc-11e6-8cdd-3b29952fe658.png)
You can see that most images are 72-200k. So I guess if you want to average around 100k you either need to use 70-75 as quality, or decrease the override size to ~1500.

**Comment by piedpiperlol** [comment]
Thank you for the explanation. May God bless your soul!
