### ISSUE TITLE
a problem about load a image from url

### ISSUE THREAD

**Issue by a6289413** [bumptech/glide#1196]
```xml
     <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
      >

        <ImageView
            android:id="@+id/iv1"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:scaleType="centerInside" />

        <ImageView
            android:id="@+id/iv2"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginLeft="5dp"
            android:scaleType="centerInside"
            android:layout_weight="1"
         />

        <ImageView
            android:id="@+id/iv3"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:scaleType="centerInside"
            android:layout_marginLeft="5dp"
            android:layout_weight="1"
        />
    </LinearLayout>
```
```java
Glide.with(mFragment).load(url1).centerCrop().placeholder(null).crossFade().into(iv1);
Glide.with(mFragment).load(url2).centerCrop().placeholder(null).crossFade().into(v2);
Glide.with(mFragment).load(url3).centerCrop().placeholder(null).crossFade().into(v3);
```

I load three images from our server, the size of each image is 720x1080, sometimes, the loaded images show 240x240,   but sometimes  the loaded iamges show 240x1080

**Comment by TWiStErRob** [comment]
How/where do you get those sizes?

Glide determines the target size, which in this case is `(screen width - margins) / 3` for width and 1080 for height. It uses 1080 because you used wrap_content, and in this case it's not possible to know how tall the image is until loaded, so Glide uses screen size as fallback. I think because you're using `centerCrop()` this may result in scaling the image weirdly.

Another When you reload these images (e.g. power button twice / depending on your lifecycle), these views already have sizes so the wrap->screen size fallback doesn't happen, resulting in different target size and that probably causes different render.

If you know the aspect of these images (which you seem to do: `720/1080`) I suggest using `PercentRelativeLayout` to make the height fixed by aspect ratio and not wrap content.

**Comment by a6289413** [comment]
thanks

**Comment by a6289413** [comment]
Sorry, today, I found out that the cause of the problem. Glide and no relationship. When my application to run in the background, if there is not enough memory, my application was killed. When I once again into the application, the picture will appear and the server as the height of. Do you have this in any good solution?

**Comment by TWiStErRob** [comment]
Same as before, make your layout without using `wrap_content`, for example `PercentRelativeLayout`. I never had this problem even without resorting to `PercentRelativeLayout`.
Make sure you start the Glide loads with the same UI state every time.
