### ISSUE TITLE
Loading Large Images

### ISSUE THREAD

**Issue by locomain** [bumptech/glide#1197]
I am not really sure if this has anything to do with Glide but i could not find my solution/anwser else where.

I am making a gallery application that should simply show the images that are available on the sdcard.
The images are being dislayed in a recyclerview and when a image is clicked this opens the image in a imageviewer.

in the imageviewer, when i try to load a larger image it takes the image 4/5 seconds to appear.
When trying out other gallery apps i noticed that they can load the image instantly, with some of them i know they actually use Glide.

my imageview layout:
```xml
    <ImageView
        android:id="@+id/image"
        android:layout_centerInParent="true"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

my glide code:
```java
      Glide.with(this)
                    .load(mImage.getPath())
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .priority( Priority.IMMEDIATE )
                    .dontanimate().into(imageview);
```

i tried using thumbnail() this did not make a lot of difference.

**Comment by TWiStErRob** [comment]
Most of those apps results to neat little tricks to speed up loading. The simplest one is preloading, the same time you bind you start a low priority load for a thumbnail that'll be shown when the user clicks, anticipating a user action may waste resources, but also give better UX if used well. If the image is preloaded then it's possible to sync-display with thumbnail and then let glide take the time to actually load the HQ image.

I know that QuickPic probably uses some kind of region-decoder for example, because when I give it (view intent) an content provider Uri that changed between previous showing and current one I can see little squares showing stale image fragments when zooming/rotating.

IMMEDIATE and thumbnail don't play well, because Glide automatically uses one-class-higher priority for thumbnails, if you use IMMEDIATE as the baseline it essentially disables the priority system and defeats the purpose of thumbnails because they are queued together with full loads which may be much slower and even block other thumbs from loading.

I think if you want really effective loading either preload/reuse the grid thumbnail when showing the full image, or use a library that is specialized in loading single big images; I'm sure if this works the next step will be zooming for which Glide is not the right solution.

The easiest solution is to just fire an intent for the user to pick their selected gallery app, which may not be an option if you're trying to compete with those apps, but this is just a file picker in a bigger app then it may be a viable solution.

**Comment by locomain** [comment]
Firing a intent is not really a option for what i am trying tot achieve.
I will try and educate my self some more on this topic.
Thank you for your detailed awnser and time it has been of great help.

**Comment by sjudd** [comment]
Photos caches a series of different image sizes and replaces each smaller image with a larger image when the larger image is ready. This can make images appear to load more quickly. 

The caveat is that it only applies once the thumbnails are generated and in cache. It takes just about the same amount of time to create a 50x50 thumb as it does to decode a full resolution Bitmap. If you clear cache on Photos or most apps that use Glide, you should see that images take a bit longer to load the first time and then are faster each subsequent time they're loaded.

One exception to this is MediaStore's thumbnail APIs. If you request an image with a size less than 512x384, Glide will try to use MediaStore's thumbnail. If that thumbnail already exists, the load may complete much faster, even after clearing data. MediaStore's thumbnails are generated lazily, so unless someone has requested the thumbnail previously, they may not exist, so there's no guarantee that using that size will be faster always.

**Comment by sharp-edge** [comment]
@sjudd Can you tell me how to distinguish a thumbnail from Full size image in `onResourceReady` ?

I need to save the original large size image in my local storage don't want to save the thumbnails:

      Glide.with(mContext).load(singleItem.getUrl()).asBitmap().thumbnail(0.2f).diskCacheStrategy(DiskCacheStrategy.ALL).listener(new RequestListener<String, Bitmap>() {

            @Override
            public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                return false;
            }

            @Override
            public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                Log.e("SARMAD_GLIDE", "onResourceReadyCalled");
                Log.e("SARMAD_GLIDE", "Is Loaded from Cache = "+isFromMemoryCache);
                Log.e("SARMAD_GLIDE", "Is First Time loaded = "+isFirstResource)
                // how to tell if the Bitmap resource is Thumbnail or actually the large size image
                return false;
            }
        }).into(holder.itemImage);

**Comment by TWiStErRob** [comment]
@sharp-edge `isFirstResource` is a good place to start, see [docs](http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/request/RequestListener.html#onResourceReady(R, T, com.bumptech.glide.request.target.Target, boolean, boolean)), however I'm not sure how it behaves if either thumb or full load, or both hits memory cache.

I think if you want to do that, the best may be to write your own loader/fetcher, and/or encoder to steal some info during Glide's processing of the image, so to not rely on something UI related to do some background processing.
