### ISSUE TITLE
How can I load the proper images asynchronously?

### ISSUE THREAD

**Issue by FooBarBacon** [bumptech/glide#1209]
**Issue**
Hi, I have a RecyclerView which displays images. These are getting fetched from the Internet and it might take up to a second to find the perfect image for each list item. Of course this led to fatal performance problems, so I decided to get the images from Runnable (for each Uri) and post them from a Handler to a separate thread. (Looper)
I ran into some weird behavior which comes from the RecyclerView's default ViewHolder recycling activity. While I'm getting the image Uri from a separate thread, the RecyclerView loads the previously loaded Bitmap into my current ViewHolder. When a Uri was returned, the list item starts a Runnable on the UI thread (runOnUiThread) which tells Glide to load the current Uri to the list item.

It looks like this:
Loads image 1 to list item 1.
Loads image 2 to list item 2.
I scroll down.
Loads image 3 to list item 20.
Loads image 4 to list item 21.
Loads image 4 to list item 20.
Loads image 5 to list item 21.
...
In the end, everything is in its place.

**Device/Android Version**:
It occurs on every version and device, except on devices possessing Gb/s Internet, so the Uri fetching is instant.

**Code inside RecyclerView's onBindViewHolder method**

``` java
mHandler.post(new Runnable() {
        @Override
        public void run() {
            // normally 1-2 seconds.
            final Uri artwork = complexFunctionToFindThePerfectUriFromInternet();

            returnActivity().runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    try {
                        Glide
                                .with(returnActivity())
                                .load(artwork)
                                .into(holder.image);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
        }
    });
```

**Comment by paveldudka** [comment]
> Of course this led to fatal performance problems
Could you elaborate on that? Glide is loading images asynchronously (unless synchronous API is used explicitly). What kind of "fatal" performance problems are you talking about?

**Comment by FooBarBacon** [comment]
Yeah, It's not Glide specific, but I guess someone has already met this and successfully solved it. I'm not sure how is this ModelLoader could be used. I know that setting holder.setIsRecyclable(false) makes everything perfect, however that's not a solution.

**Comment by TWiStErRob** [comment]
> In the end, everything is in its place.

That's just a coincidence, it can be worse once Glide starts hitting the memory cache and/or the internet happens to be the right speed.

> I'm not sure how is this ModelLoader could be used.

A `ModelLoader` is a Glide specific interface that helps with these cases. Essentially you need 2 requests: one to get the Uri and one to get the Image stream. There's even a specific class to help with this use case assuming that the complex function's inputs are always the same (model) and it always ends up with the same image (because caching is based on model). Take a look at `BaseGlideUrlLoader`: https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=is%3Aissue+%22extends+BaseGlideUrlLoader%22

Take a look at https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=is%3Aissue+ModelLoader+Factory+DataFetcher for generic implementations: you can do anything in the loader/fecther.

*You'll likely need the latter, because `loader.getResourceFetcher` is called on the UI thread, so make sure you do all your networking in the fetcher.*

**Comment by FooBarBacon** [comment]
Sorry for acting like I have some mental disabilities, but I'm still lost. 
I've taken a look at ModelLoader & DataFetcher, but I have no clue which ModelLoader shall I use. I find a few things, but those didn't work for me.

I have class X with a method named Y. It returns a Uri. Which ModelLoader fits my use case?

**Comment by TWiStErRob** [comment]
Don't worry it's advanced usage; maybe I wasn't clear enough. You need to create a custom loader and fetcher:

if Y doesn't do I/O then subclass `BaseGlideUrlLoader<X>`.
If Y does I/O then crate your own fully custom loader with a factory inner class (like it's done with the builtin ones), and pass X to the custom fetcher (you also need to create that). Inside the fetcher get the uri via `X.Y()` and then you can create a HttpUrlFetcher instance with that and return `urlFetcher.loadData()` so you don't have to reimplement the networking layer.

Feel free to ask more questions if you're stuck.

**Comment by FooBarBacon** [comment]
I implemented (something similar) what you recommended, but it says :
> java.lang.IllegalArgumentException : Unknown type class com.hoba.frostplayer.network.musicservice.lastfm.ArtistArtworkGrabber. You must provide a Model of a type for which there is a registered ModelLoader, if you are using a custom model, you must first call Glide#register with a ModelLoaderFactory for your custom model class

I imported a sample from the web which supposed to work, but I got the same error. My current (simplified)  implementation is the following:

    public class MyImageUriLoader implements ModelLoader<MyImageGrabber, Uri> {
        public static class Factory implements ModelLoaderFactory<MyImageGrabber, Uri> {
            @Override
            public ModelLoader<MyImageGrabber, Uri> build(Context context, GenericLoaderFactory factories) {
                // Inserted, because I thought it might solve the error.
                factories.buildModelLoader(MyImageGrabber.class, Uri.class);
                return new MyImageUriLoader();
            }

            @Override
            public void teardown() {

            }
        }

        @Override
        public DataFetcher<Uri> getResourceFetcher(final MyImageGrabber model, int width, int height) {
            return new MyDataFetcher(model);
        }
    }


    public class MyDataFetcher implements DataFetcher<Uri> {
        private MyImageGrabber mImageGrabber;

            public MyDataFetcher(MyImageGrabber artworkGrabber) {
                mImageGrabber = artworkGrabber;
            }

            @Override
            public Uri loadData(Priority priority) throws Exception {
                return mImageGrabber.doStuff();
            }

             @Override
             public void cleanup() {
        
             }

             @Override
             public String getId() {
                 return Integer.toString(mImageGrabber.hashCode());
             }

             @Override
             public void cancel() {

             }
    }


    public class ImageUriLoaderModule implements GlideModule {
        @Override
        public void applyOptions(Context context, GlideBuilder builder) {

        }

        @Override
        public void registerComponents(Context context, Glide glide) {
            glide.register(MyImageGrabber.class, Uri.class, new MyImageUriLoader.Factory());
        }
    }



How I use Glide in the onBindViewHolder method:

    Glide
                .with(returnActivity())
                .load(getMyImageGrabberInstance())
                .into(image);

**Comment by TWiStErRob** [comment]
That looks ok, did you [add the manifest entry](https://github.com/bumptech/glide/wiki/Configuration#creating-a-glidemodule)?

Two things to note:
* Make sure hashCode doesn't change between runs (i.e. override it to hash the real model). If you let the default implementation return the "memory address" of the object, then caching won't work.
* `buildModelLoader` is used by Glide to create a loader, it doesn't have a side effect, it returns you a loader. I think that code is not even executed, because if it was it would be possibly throwing a StackOverflowError.

Hmm, after writing this down I noticed that you're doing an Uri. If you added the manifest entry, then the problem is that you need `MyImageGrabber -> InputStream` conversion. Glide cannot chain multiple loaders automatically. Try this (unchanged methods omitted):
```java
public class MyImageUriLoader implements ModelLoader<MyImageGrabber, InputStream> {
	private final ModelLoader<Uri, InputStream> uriLoader;
	public MyImageUriLoader(ModelLoader<Uri, InputStream> uriLoader) {
		this.uriLoader = uriLoader;
	}
	@Override public DataFetcher<InputStream> getResourceFetcher(final MyImageGrabber model, int width, int height) {
		return new MyDataFetcher(uriLoader, model, width, height);
	}

	public static class Factory implements ModelLoaderFactory<MyImageGrabber, InputStream> {
		@Override public ModelLoader<MyImageGrabber, InputStream> build(Context context, GenericLoaderFactory factories) {
			ModelLoader<Uri, InputStream> uriLoader = factories.buildModelLoader(Uri.class, InputStream.class);
			return new MyImageUriLoader(uriLoader);
		}
	}
}

public class MyDataFetcher implements DataFetcher<InputStream> {
	private final MyImageGrabber mImageGrabber;
	private final ModelLoader<Uri, InputStream> loader;
	private final int width;
	private final int height;
	private DataFetcher<InputStream> fetcher;
	private volatile boolean cancelled;

	public MyDataFetcher(ModelLoader<Uri, InputStream> loader, MyImageGrabber model, int width, int height) {
		this.loader = loader;
		this.mImageGrabber = model;
		this.width = width;
		this.height = height;
	}

	@Override public InputStream loadData(Priority priority) throws Exception {
		Uri uri = mImageGrabber.doStuff();
		if (cancelled) return null;
		fetcher = loader.getResourceFetcher(uri, width, height);
		return fetcher.loadData(priority);
	}

	@Override public void cleanup() {
		if (fetcher != null) { fetcher.cleanup(); }
	}

	@Override public void cancel() {
		cancelled = true;
		if (fetcher != null) { fetcher.cancel(); }
	}
}

public class ImageUriLoaderModule implements GlideModule {
	@Override public void registerComponents(Context context, Glide glide) {
		glide.register(MyImageGrabber.class, InputStream.class, new MyImageUriLoader.Factory());
	}
}
```
`fetcher = loader.getResourceFetcher` can be replaced with `new HttpUrlFetcher(new GlideUrl(uri))`, but the above loader version it will work with any Uri (not just HTTP) and any integration library (in case you use OkHttp or Volley). In other words you get the full benefits as if you've done: `Glide.....load(getMyImageGrabberInstance().doStuff()).into...`, but with I/O moved to background.

**Comment by TWiStErRob** [comment]
I also suggest you somehow inline `doStuff` and handle cancellation, because if it really takes a few seconds, then it should be aborted immediately by closing the connection because otherwise you may have be too many outgoing operations at the same time (when scrolling a list).

**Comment by FooBarBacon** [comment]
I pasted your sample just to test it and for me, it returns the same (1st) Bitmap for every load request. I haven't actually taken a deeper look at your code, so it might need an easy fix.

**Comment by TWiStErRob** [comment]
Sorry I didn't respond. Did you figure it out?

I think the problem might be `getId()` it should consistently reflect the `MyImageGrabber`. Hash-code is not a consistent way because it can change between runs of the app, well even within the same app. The weird thing is that you complain about the opposite. Are you reusing `MyImageGrabber` instances? Turn on [logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) and compare the cache keys where you expect different images to be loaded.
