### ISSUE TITLE
Can't load image of video

### ISSUE THREAD

**Issue by reaper12** [bumptech/glide#1225]
if DiskCacheStrategy.ALL can't load?

**Comment by TWiStErRob** [comment]
Remote videos (HTTP url) are not supported by default bease it would take possible the whole video, or a significant chunk of it to get a thumbnail. Most services that serve videos have thumbnail links in theIR response. If you have your own you should consider that too.

Local videos should work, except there you need `DiskCacheStrategy.NONE` or `DiskCacheStrategy.RESULT` (the default), because using ALL or SOURCE would duplicate the whole video file in your app's cache, which for a possibly multi-GB file is really bad.

If this didn't help feel free to reopen this issue and give more details than "it doesn't work" detailing what you did, how you did it, what is the expected and actual result. Look athttps://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to get more info.
