### ISSUE TITLE
Loading from file (Raw image) doesn't resize the loaded Image | OOM 

### ISSUE THREAD

**Issue by zetbrush** [bumptech/glide#1234]
**Glide Version**: 4.0.0-SNAPSHOT 20151124.173231-105
**Integration libraries**: no diff
**Device/Android Version**: All/Galaxy S4/GT-I9500 5.0.1

**Issue details / Repro steps / Use case background**: 

When loading raw image from file with for example 2k/4k images, we should override width and height using original width/height which leads to huge memory usages and OOM, as because of loading couple of that size images.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with().asBitmap().load(file).listener(listener).apply(RequestOptions.dontTransform().override(width, height)).into(imageView);
```

as width and height should be the original size Glide loads as is.

So is there any way to override sizes after decode, so glide could load  the low res and put into the cache the low res one?

**Comment by TWiStErRob** [comment]
Do we have built-in RAW decoders in v4? I don't remember that. If we don't, that means you wrote the decoder.

There are two things that contribute to sizing:

 * If you allow Glide to figure out the size and try to downsample in decoder (this is what the built-in BitmapFactory wrapping Downsampler class does, start from `StreamBitmapDecoder`), you get the target size in `ResourceDecoder.decode(...)` and you can adhere to those requested sizes by loading a close enough amount of pixels from the raw image. E.g. you can load every second row/column, or calculate an average of an NxN grid where `N = max(1, sourceWidth / targetWidth)`, this saves memory outright.
 * After this you can apply a transformation to create an even smaller bitmap, again trying to match the target size, from the loaded one, e.g. `.fitCenter()`. This transformed image will be saved in RESULT cache (I think the equivalent is `RESOURCE` in v4).

I think your problem is that you need to tell the decoder somehow how many bytes are there because the raw file doesn't have a header; and you chose `.override()` to do this. Is this correct?

**Comment by zetbrush** [comment]
yeah, thanks for suggestions, you got me right! will something like this case handling be integrated in Glide?

**Comment by TWiStErRob** [comment]
There already is, it's called a custom model and model loader. You need to create a custom model (simple object) that can hold source file, width, height. From that loader create a fetcher for the model. This will prevent Glide from automatically handling loading for you so you need to do a `registry.buildModelLoader(File.class, InputStream.class)` (similar to #1209), or just create a `new FileInputStream` yourself (the registry version is better in case you want to handle other types of loading later which isn't as simple as creating a single object). Then instead of retuning InputStream from fetcher you return another custom object that holds the InputStream, width and height. At this point you need to modify your decoder to decode this custom object instead of streams and voila: you freed the override from being (mis)used and Glide can deliver the target size properly to your decoder as 2nd and 3rd args, and the first argument (this custom object) will contain the source size. This way you can do downsample at decode time, saving memory in the first place, but even if you don't do that letting Glide to use the target size as it was intended means that the fully loaded bitmap can be transformed to target size using `.fitCenter()` or `.centerCrop()`.

Another alternative is that you delay figuring out the size of each image into decoder or, even better if it's possible in the fetcher if it needs I/O.

**Comment by zetbrush** [comment]
Thanks @TWiStErRob great explanation!

**Comment by TWiStErRob** [comment]
Let me know if you managed to implement this flow or stuck somewhere.

**Comment by zetbrush** [comment]
ok, It worked)) but anyway, I notice that every time it decodes the same images and not taking from the pool, should we check this in decoder to return Resource(bitmap) from BitmapPool? if yes how we can do that? or it should check glide before going to decoder?  (and for additional info I,m not setting signature) 
Thanks

**Comment by TWiStErRob** [comment]
I'm not sure I understand that. How did you implement the fetcher's `getId()` it should be `File.getAbsolutePath()` or similar.

You can get Bitmaps from the pool, but that's not the same as memory cache if that's what you mean. You should always query the pool first, before creating a Bitmap yourself to reduce memory churning!

**Comment by TWiStErRob** [comment]
Did you manage to re-use pooled bitmaps and/or hit the memory cache? You can use [logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) to check if you hit the cache, just compare the cache keys.
