### ISSUE TITLE
How to clear image until loaded image is ready, not immediately.

### ISSUE THREAD

**Issue by KyoSherlock** [bumptech/glide#1237]
I want to add shared element transition between activities. 
```
Bundle bundle = ActivityOptionsCompat.makeSceneTransitionAnimation(getActivity(), v, "shareImage").toBundle();
ActivityCompat.startActivity(getActivity(), intent, bundle);
```
The element in first activity is small ImageView, and the element in the second activity is big ImageView. 
I let them to load the same size bitmap, the transition is working well. Then the big ImageView load the big size image to refresh itself, ImageView will flicker. I want to disable the "clear" function to avoid flicker.

**Comment by KyoSherlock** [comment]
I find a solution. load url into bitmap instead of ImageView.
```
Glide.with(this).load(url).asBitmap()
	.into(new SimpleTarget<Bitmap>(imageView.getWidth(), imageView.getHeight()) {
		@Override
		public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
			imageView.setImageBitmap(resource);
		}
	});
```

**Comment by TWiStErRob** [comment]
That doesn't look right. I think you just want a side-effect of your hack which is `.dontAnimate()`. The flickering is probably caused by the default cross-fading.

I usually suggest this flow: show thumbnail on grid, once user clicks load the same thumbnail in the activity and once the transition complete start the full load. You can also try a single load which loads `fullLoad.thumbnail(thumbLoad).into(IV)`, but as far as I know that can behave strangely even with no animation.

**Comment by KyoSherlock** [comment]
Thanks.
