### ISSUE TITLE
is there is a way that i can load bitmap into cache ?

### ISSUE THREAD

**Issue by water54** [bumptech/glide#1238]
i want to draw a bitmap as placeholder for certain ratio or size and give it a path or something like that ,so
next time i can use it get it from glide cache.

**Comment by TWiStErRob** [comment]
You can do a normal load but instead of `into(iv)` end with `preload(w,h)`, then when you need the preloaded image do the same load but this time ending with `.override(w,h).into(iv)`. Make sure you always explicitly call a transformation method (dont/fit/crop) to prevent the automatic `ImageView.scaleType` taking effect and missing the cache.

There's a `ListPreloader` that helps with this so it looks like every image display is sync while scrolling with a reasonable speed.

---

There's a simpler caching method `downloadOnly()` as well which only caches the source file from the internet, you can hit that cached version with `.diskCacheStrategy(SOURCE|ALL)` later.

**Comment by water54** [comment]
i know glide do well in network image.i have the bitmap.but i want glide could cache it.so i can use it as placeholder or thumbnail.

**Comment by water54** [comment]
the bitmap was draw by myself.and i want to add it to glide cache,and give it a path.so next time i could use glide load it as thumbnail before load image.

**Comment by TWiStErRob** [comment]
Ah, I see, check out http://stackoverflow.com/a/31940058/253468
