### ISSUE TITLE
GlideBitmapDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

### ISSUE THREAD

**Issue by tianshaokai** [bumptech/glide#1255]
java.lang.ClassCastException: com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

**Comment by TWiStErRob** [comment]
Because it is not a `BitmapDrawable`: https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/resource/bitmap/GlideBitmapDrawable.java, it's a GlideDrawable that handles Bitmaps.

Your call to getDrawable is probably unsafe anyway. Can you please give more context? What are you trying to do, and who is trying to cast?

**Comment by li13738051517** [comment]
我也同样遇到了这样的问题
