### ISSUE TITLE
Glide image request not cancelled.

### ISSUE THREAD

**Issue by AkashRai1992** [bumptech/glide#1260]
given below is the piece of code:
```java
Glide.with(getContext()).load(imageUrl).placeholder(android.R.color.transparent).into(mProfilePicView);
Glide.clear(this);
```
here all images are downloading and shown up. 
I could not understang how should i cancel an image download request when it is not needed furthter.
or does glide internally handle the image request by itself?

**Comment by TWiStErRob** [comment]
I'm not sure what `this` is, but you should either pass the target returned from `into` or if it was an ImageView, like in this case, then: `Glide.clear(mProfilePicView);`

**Comment by AkashRai1992** [comment]
thanks a ton for the reply,  my concern is that i wanted to know wheather glide cancels the image download request when the imageview passed gets dettached from window?

**Comment by TWiStErRob** [comment]
We usually suggest `onViewRecycled -> Glide.clear(holder.image)` if you want to manually clear in a list.

Yours may not be a list in which case I suggest reading this: http://stackoverflow.com/a/32887693/253468; that's all Glide does for "automatic" clearing there's no "onDetachedListener" and it may not even make sense in some cases if the view is just removed temporarily.

Tip: you can create a RequestManager with `Glide.with(this)` and pass it around, so the Adapter doesn't have to know in which context (fragment or activity) it is used. This is also true if you're working with helper methods for image loading so you don't need to call getContext on anything.

**Comment by AkashRai1992** [comment]
ok , i had another query. In glide we have  this piece of code:
`@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
private static void assertNotDestroyed(Activity activity) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && activity.isDestroyed()) {
        throw new IllegalArgumentException("You cannot start a load for a destroyed activity");
    }
}`
so does this gets called when the image gets downloaded and the image view reference has an enclosing activity that is destroyed?, if thats the case then according  to the link:
http://stackoverflow.com/questions/31964737/glide-image-loading-with-application-context/32887693#32887693 , glide automatically sees for the lifecycle so this case would'nt occur.
I am too confused on this topic, would you please elaborate.

**Comment by TWiStErRob** [comment]
Starting a load and finishing a load is two different things. Starting is when you call `Glide.with...into` and finishing is when the loaded resource gets delivered to the listener/target. We don't like destroyed activities because Glide cannot insert the lifecycle listener fragment into the Activity, because the fragment transaction would fail; you can find examples of this if you search the exception message. The problem usually is that the load is started in a result of an async task or similar and the activity has disappeared from below you. This means that you might have a leak which Glide will signal with an early crash. Look at the other issues and let me know if you need more info.
