### ISSUE TITLE
Does the bitmap pool get used even if memoryCache is disabled?

### ISSUE THREAD

**Issue by badgroover** [bumptech/glide#1270]
My question is about the usage of the bitmap pool.
I load an image from a url while disabling memory caching like this:
request.skipMemoryCache(true);
Will Glide use a bitmap from the bitmap pool to load this image (either from the network or the disk if its the next time)?
I have disabled memory caching within my app due to OOM errors.
I was wondering if the bitmap pool gets used in such a case and if not, can I set its size to a small number in a class that implements GlideModule like so:
builder.setBitmapPool(new LruBitmapPool(BITMAP_POOL_CACHE_SIZE));

**Comment by TWiStErRob** [comment]
A quick check of following the data flow of `isMemoryCacheable` from `Engine#load` it looks like it's only used for memory caching (that is: retrieving the loaded image from memory instead of doing I/O), it does not affect pool re-use.

You can also disable it by setting `new BitmapPoolAdapter()`, but if you have OOMs I think it's better to track down what's causing it instead of turning off one of the best features of Glide.

**Comment by badgroover** [comment]
Thanks for the quick response!
I too am disappointed that I have to take the drastic step of disabling memory caching.
I have examined the app and the hprof files at length.
The main issue in my mind is that my app can ending being a series of activities stacked on top of each other where each will contain a list with rows of images. What this means is that the lower hidden activities do not destroy their views (unless the system is OOM). This in turn means a ton of imageViews and their bitmaps all hanging around. Android Device monitor shows Heap usage mounting as I navigate deeper through the app.

**Comment by TWiStErRob** [comment]
That's solvable:

1. `RecyclerView.Adapter.onViewRecycled`: `Glide.clear(view)`
2. `Activity/Fragment.onStop`: `list.setAdapter(null)`

This will force destroying all the resource hugging stuff. You can try to cache `list.getAdapter` before removing it in an instance field and restore it in `onRestart`, or simply refresh your data in`onStart`.

Because of memory cache (in this case no need to disable) the image will load immediately when the user opens an activity and navigates back to the previous one. It'll behave just like before, but at the same time all the resources will be reclaimable if needed. The deeper you go the more images will be evicted, but Glide will still load them pretty fast from disk cache for the initial activities when you go back.
