### ISSUE TITLE
using .thumbnail() with .transcode()

### ISSUE THREAD

**Issue by LorneLaliberte** [bumptech/glide#1272]
**Glide Version**: 3.8.0-SNAPSHOT

**Device/Android Version**: Nexus 5, 5.0.1

I'm using a `PaletteBitmapTranscoder` to generate a palette, as demonstrated in the [Custom targets](https://github.com/bumptech/glide/wiki/Custom-targets#palette-example) section of the Glide wiki.

However, when using `.thumbnail()` in cases where the thumbnail request finishes after the full request, it ends up using the palette that was generated for the thumbnail instead of the full image.

Since `Palette` generates very different color swatches as an image is resized, this can affect the results.

In my test, the thumbnail palette always gets used the first time the image is loaded, but the full image's palette is used for all subsequent loads. (I think that if the full request is in the cache, the thumbnail does not get generated?)

Is there a way to prevent transcoding of the thumbnail when using a transcoder for the full image request?

I've tried changing the order of where `.thumbnail()` is called when building the request, but didn't have any luck with that approach. Most of those attempts wouldn't compile because of type incompatibility, e.g. not having a compatible `TranscodeType` with the full request.

I also tried using an explicit thumbnail request with its own settings but that didn't work; the full request's resource transcoder still gets called for the thumbnail. Giving the thumbnail its own `PalletteBitmapNullTranscoder` that doesn't generate a palette didn't work either; it just resulted in additional `transcode()` calls (and additional `DecodeJobs` in the log output). The additional `transcode()` calls did what I wanted (namely, not generating a palette) but it didn't replace the original thumbnail `transcode()` call that I was trying to override.

At this point I've disabled thumbnail generation when using a PaletteBitmapTranscoder, but I'm still new to Glide so I wonder if there might be something obvious that I might be missing.

For instance, is there any way to create a thumbnail request that uses a different `TranscodeType`, or a different `ModelType` for that matter?

Or is there some way within a `ResourceTranscoder` to know whether `transcode()` is being called for the full request or the thumbnail request?

**Comment by TWiStErRob** [comment]
Can you please include your current code?

**Comment by LorneLaliberte** [comment]
Sure, the simplest test case was using this:

	Glide
		.with(imageView.getContext())
		.load(id)
		.asBitmap()
		.transcode(new PaletteBitmapTranscoder(this), PaletteBitmap.class)
		.fitCenter()
		.diskCacheStrategy(DiskCacheStrategy.ALL)
		.thumbnail(0.125f)
		.animate(new BitmapContainerCrossFadeFactory<PaletteBitmap>(FADE_DURATION) {
			@Override protected Bitmap getBitmap(PaletteBitmap resource) {
				return resource.bitmap;
			}
		})
		.into(new ImageViewTarget<PaletteBitmap>(imageView) {
			@Override protected void setResource(PaletteBitmap resource) {
				super.view.setImageBitmap(resource.bitmap);

				onPaletteGenerated(resource);
			}
		});


FADE_DURATION was set to `150` and the `id` is an image resource pointing to a jpeg which I've attached. (Using a resource as a repeatable way to get the thumbnail to be generated last.)

For the explicit thumbnail request approach I was using something along these lines:

	Glide
		.with(imageView.getContext())
		.load(id)
		.asBitmap()
		.transcode(new PaletteBitmapTranscoder(this), PaletteBitmap.class)
		.fitCenter()
		.diskCacheStrategy(DiskCacheStrategy.ALL)
		.thumbnail(Glide.with(imageView.getContext()).load(id)
													 .asBitmap()
													 .transcode(new PaletteBitmapNullTranscoder(this), PaletteBitmap.class)
													 .sizeMultiplier(0.125f)
													 .fitCenter())
		.animate(new BitmapContainerCrossFadeFactory<PaletteBitmap>(FADE_DURATION) {
			@Override protected Bitmap getBitmap(PaletteBitmap resource) {
				return resource.bitmap;
			}
		})
		.into(new ImageViewTarget<PaletteBitmap>(imageView) {
			@Override protected void setResource(PaletteBitmap resource) {
				super.view.setImageBitmap(resource.bitmap);

				onPaletteGenerated(resource);
			}
		});

With this transcoder class:

	public class PaletteBitmapNullTranscoder implements ResourceTranscoder<Bitmap, PaletteBitmap> {
		private final BitmapPool bitmapPool;

		public PaletteBitmapNullTranscoder(Context context) {
			this.bitmapPool = Glide.get(context).getBitmapPool();
		}

		@Override
		public Resource<PaletteBitmap> transcode(Resource<Bitmap> toTranscode) {
			Bitmap bitmap = toTranscode.get();
			
			PaletteBitmap result = new PaletteBitmap(bitmap, null);
			return new PaletteBitmapResource(result, bitmapPool);
		}

		@Override
		public String getId() {
			return PaletteBitmapNullTranscoder.class.getName();
		}
	}

I'm using a `Palette' with several custom targets added, and some utility methods that try different swatches in sequence, and it results in either a dark or a light swatch being found, which makes the difference between the palettes obvious. However, you could probably achieve something noticeable enough using `palette.getSwatchForTarget(Palette.Target.DARK_MUTED)` and reducing the sizeMultiplier even further.

![tyrion](https://cloud.githubusercontent.com/assets/700370/16167962/38fe3b18-34c2-11e6-8085-487af552ec9e.jpg)

**Comment by TWiStErRob** [comment]
I don't like this workaround but may help: move the `onPaletteGenerated` line to a listener where you can check if you got a thumb or not. This will still generate the thumb's palette according to your experience, but at least won't display.

Another thing you might want to look into is to not use a `PaletteBitmap`, but transcode into `GlideBitmapDrawable.class` on both the thumb and the full load for compatibility. This way you can use Glide's transcoder on the thumb that doesn't have palette, and use a subclass on the full load that has a palette getter. Though this may have the same problem as the null-transcoder.

I'll try to look into why the transcoder is not applied, later.

**Comment by TWiStErRob** [comment]
Another hacky idea: if Glide forces you to use the same transcoder, make you transcoder more clever by not calculating and image for "small" Bitmaps thus having a null Palette for thumbs.

**Comment by LorneLaliberte** [comment]
Thanks Robert.

I might actually need to work around it in a different way as part of solving another issue. In order to maintain palette stability for the same image at different requested sizes. for example between lists and detail pages, I will need to always generate the palette for a specific image size (regardless of what the target size is).

So it might make sense to generate the palette in another glide request (unless the target happens to already match the desired size).

This would make even more sense if I cached the palette results. I could implement my own cache, but it should really be synchronized with the glide cache.

I've been trying to determine whether glide has any mechanism for including additional data in the cache, alongside the bitmap data, but I haven't found a way yet...

(Or, if that isn't feasible, is there a way to borrow the image signature keys and/or attach a listener to cache writes, to know when a bitmap has been replaced, etc.?)

**Comment by TWiStErRob** [comment]
Hmm, I'm not really sure how to approach this.

You can define your own cache for sure, the problem is that on the interface all you get is the key and the image data writer. So you don't know your model for example. You can't even cast your received key, because `EngineKey` is really secretive (see discussion in #977). If you could get the info out of the key somehow it may be easy to attach more info, because AFAIK `DiskLruCache` allows multiple streams per cache entry.

You could keep the colors quasi-consistent by telling the palette to downsize to a particular fixed size. So regardless of input image the palette is calculated on the same sized image, even though it there might be different number of resizes: 1000 -> 125 -> 50 for thumb, 1000 -> 50 for full image.

If you [animate the transitions between the different colors](https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/github/_1013_palette/TestFragment.java), wouldn't it be less noticable?

I guess if you want hard consistency it might be easier to calculate it on the server, if you can, that way it's always available ahead of time.

**Comment by LorneLaliberte** [comment]
Ah, thanks for #977.

If EngineKey is package-private (default) then it would be trivial to access it -- you just need a static method in the same package as Glide, which is easy. (I've done this several times to workaround issues in the Android support libraries, e.g. to gain access to methods that aren't public.) 

Hmmm.

> You could keep the colors quasi-consistent by telling the palette to downsize to a particular fixed size.

Yes, but only quasi...unless it always downsized from the same decoded source bitmap. Which would work if there was a way to only transcode from the bitmap that ends up in the SOURCE cache (but even when using DiskCacheStrategy.ALL). I'm still not sure how using a different DiskCacheStrategy in separate glide requests works at the moment, but one approach would be to use .override() in the palette-generating request to ensure it gets decoded from the source bitmap (or the already decoded and resized version from the cache) every time.

Animating the transitions between the colors isn't the issue, I need color stability for other reasons (it's being used as part of an overall theming system where consistency across activities etc. is desired).

Calculating on the server won't work as many of the images are only known at run time (e.g. from RSS feeds).

But once a given image is in the source cache, the palette generated for it won't change (assuming a constant size), so optimally I'd like to avoid needing to re-generate the palette and just cache the results.

**Comment by TWiStErRob** [comment]
> I'm still not sure how DiskCacheStrategy works

Does #1314 provide enough?

> the images are only known at run time, once a given image is in the source cache, the palette generated for it won't change

I think your best bet would be to fire two Glide requests. One for the normal image to show with thumbnail and stuff. And another one for the palette, or more specifically the colors of the url. Glide can be used to load anything from anywhere into anything, including Uri -> Bitmap -> PaletteColors -> TextView font and background color; see https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit

The thing is that Glide handles multiple requests for the same source uri (if cache is set properly), so it won't be double-downloaded, but needs to be double-decoded. Consider these:
```java
// normal load
Glide
		.with(this)
		.load(url)
		// don't save the full image resized for the screen,
		// it may be close to original size, which is already cached
		.diskCacheStrategy(DiskCacheStrategy.SOURCE)
		.thumbnail(Glide
				.with(this)
				.load(url)
				// small size for fast show
				.sizeMultiplier(0.125f)
				// save that small image so next time it's really fast
				.diskCacheStrategy(DiskCacheStrategy.ALL)
		)
		// display
		.into(imageView)
;

// palette load
Glide
		.with(this)
		.load(url)
		.asBitmap()
		// make sure you disable Bitmap resizing in Palette: resizeBitmapArea(-1) in the transcoder
		.transcode(new PaletteBitmapTranscoder(context), PaletteBitmap.class)
		// read from already downloaded image
		.diskCacheStrategy(DiskCacheStrategy.SOURCE)
		// use a small size to be fast
		.override(256, 256)
		// won't be used anyway
		.dontAnimate()
		// downsampling to nearest 2s power during decode is enough, save some cycles
		.atMost().dontTransform()
		// use
		.into(new SimpleTarget<PaletteBitmap>() {
			@Override public void onResourceReady(PaletteBitmap resource,
					GlideAnimation<? super PaletteBitmap> glideAnimation) {
				// ... colorize everything
				Glide.clear(this); // get rid of resources immediately (*)
			}
			@Override public void onLoadFailed(Exception e, Drawable errorDrawable) {
				super.onLoadFailed(e, errorDrawable);
				Glide.clear(this); // get rid of resources immediately (*)
			}
		})
;
```
(*) you may want a different choice there without these lines. You could create a much smarter target if you copy `ViewTarget.get/setRequest` and use something like `holder.itemView` to store the request; or you load into the `holder` itself which can store the `Request` object. This would allow you to simply start a load in a list and have all the color resetting magic handled for you. When an item is recycled the new load started will clear the previous one. Just implement `onLoadCleared` in a way that resets the colors to "normal". It may be complicated, there are many many options, I can elaborate more if you want.

This above palette thing could be made much faster if we could use a cacheEncoder/Decoder to serialize the palette. The problem is #707, though it could be worked around by peeking at the first byte.

**Comment by LorneLaliberte** [comment]
> Does #1314 provide enough?

Thanks, it definitely helps. :) That's pretty much how you would expect it should work...but I recall seeing anecdotes on StackOverflow that made it seem like using ALL wouldn't work the same as SOURCE when making offline requests for an image that should already be in the cache...that to get an image to be retrieved from SOURCE when offline, you needed to have originally requested it with SOURCE instead of ALL, which seems very strange me.

> I think your best bet would be to fire two Glide requests.

Yeah, I'm thinking so too (regardless of where I end up caching the palette results).

> Glide can be used to load anything from anywhere into anything, including Uri -> Bitmap -> PaletteColors -> TextView font and background color; see https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit

Hmmm...I'll have to study that more carefully but I think you lost me a bit here. Or rather, I'm not sure what clue that's meant to provide. :) I fear I'm missing something very obvious but that seems to just describe the normal glide pipeline?

> You could create a much smarter target if you copy ViewTarget.get/setRequest and use something like holder.itemView to store the request; or you load into the holder itself which can store the Request object.

Hmmm...not sure what benefit storing the request would offer...I'm definitely missing something I think. :)

Currently I'm creating the request within a custom BindingAdapter in my view model, as I'm using data binding...so each generated palette ends up being held by a model instance and associated with the RecyclerView holder through data binding, e.g. the onBindViewHolder has code like this:

	Item item = createItem( binding.getRoot().getContext()
	                      , position );
	binding.setVariable(BR.item, item);
	binding.setVariable(BR.onItemClick, holder);

The actual mechanics of updating the colors in the view(s) happens pretty simply via something like this:

	.into(new ImageViewTarget<PaletteBitmap>(imageView) {
		@Override protected void setResource(PaletteBitmap resource) {
			super.view.setImageBitmap(resource.bitmap);
			item.onPaletteGenerated(resource);
		}
	});

...which then updates the affected bindings like this:

	private void onPaletteGenerated(PaletteBitmap resource) {
	
		this.palette = resource.palette;
	
		// update any static methods in the layout using item.palette as a parameter
		notifyPropertyChanged(BR.palette);

		Palette.Swatch swatch = PaletteUtils.getAutomaticSwatch(palette, PaletteUtils.getPaletteDarknessByPopulation(palette));
		if(swatch != null) {
			// update item.titleBackgroundColor, item.titleTextColor, etc.
			setTitleBackgroundColor(swatch.getRgb());
			setTitleTextColor(swatch.getTitleTextColor());
			// etc.
		}
	}

> Just implement onLoadCleared in a way that resets the colors to "normal". It may be complicated, there are many many options, I can elaborate more if you want.

I don't think I'm actually implementing `onLoadCleared` yet at all, so I may indeed be missing something.

> This above palette thing could be made much faster if we could use a cacheEncoder/Decoder to serialize the palette. The problem is #707, though it could be worked around by peeking at the first byte.

Hmmm...treating the palette as part of a custom image format, so to speak? (Is there an easy way to insert a wrapper over all encoders/decoders?)

A separate cache for the palette (outside of glide) might work around this, but the problem then is knowing when a palette in the cache needs to be refreshed -- keeping it synchronized it with the glide cache. (At least in terms of avoiding the glide bitmap fetch and decode every time.)

That's a neat solution you proposed in #700 btw.

(Although probably for most situations where large images pose a problem you'd need something more like a tile renderer for scaling/gesture support, etc. That's a problem I'll need to face myself later in this project.)

I toyed with the idea of actually storing the palette results in the bitmap cache...e.g. just overwriting the first n bytes with a transcoder (or transformation?), and letting the glide cache hold the "palette" for me that way (albeit wastefully). That would only work if I could prevent the resulting bitmap from being picked up by any matching "normal" glide requests, though.

BTW, thanks again for all your guidance, Robert! It is invaluable for someone at the base of the learning curve like me.

(Would any of this stuff be easier to do in the 4 snapshot?)

**Comment by TWiStErRob** [comment]
> I recall seeing anecdotes

Well, even if that's true, it didn't come here as a bug report in the last 2 years, so it must be just hearsay. ALL is inclusive of SOURCE as you would expect. However, if you replace all `ALL`s with `RESULT` then those arguments become true. And `RESULT` is the default. I guess people were expecting `SOURCE` to be the default, like in Picasso IIRC.

> that seems to just describe the normal glide pipeline.

Yes, that's the normal one, but notice that everything is generic (albeit inconsistently named), those `File`, `InputStream` are just examples. The takeaway is that you should be able to squeze anything in through the pipeline. I came to Glide because Picasso only allowed loading Strings, but I needed custom objects.

> not sure what benefit storing the request would offer

During normal Glide usage (`into(imageView)`) you're storing the request in `View.tag`, it's just hidden from you. The benefit of storing it in your view/viewmodel is that any time Glide comes in contact with it, it can retrieve a previous load and cancel it. You don't have to worry about it, except you have to store the request somewhere if you have custom targets. This is most useful in lists where you need to stop downloading an image that won't be shown and clear any resources before loading another one. The trick is that if you store the Request in the correct place creating a new target will still recognize the old one even though you don't have an explicit reference to the old target.

> I don't think I'm actually implementing onLoadCleared yet

Doing so is important if you want to be able to deliver consistent experience (i.e. resetting the color when items are recycled). If you implement `onLoadCleared` as the opposite of `onResourceReady` then Glide would have not trace when the target is cleared. Glide assumes ownership over the views/targets it's handling between those two method calls, while the resource is active. If you don't implement clear/started callbacks then your item reuse will show the stale color of the previously bound model while the download/decode is happening.

> treating the palette as part of a custom image format, so to speak?

That's not what I meant, but it's an interesting idea. What I meant is that if you implement a peeking decoder you can see that the decoder received a SOURCE cache image and then decode the Bitmap and calculate the palette. If the peek says that it's not an image then you can simply read a few bytes as opposed to doing a full decode. In my example I decoupled the image showing and the color delivery. This means there's no need for the actual Bitmap in the "palette load", except the first time to fill the cache.

> I toyed with the idea of actually storing the palette results in the bitmap cache [...] appended to the end of the bitmap array

I was curious so I tried it. It wasn't that complicated to do any kind of caching, the hardest part was reconstructing the Palette so it gives the same results as before caching. See the commit just above this comment for details: 2 separate, but similar solutions. It would've been nice to be able to just append the palette after an image, but the Downsampler is too eager because of buffered streams, so it consumes the "junk" after the image file from the source stream. Swapping them or peeking for magic byte works fine.

> Would any of this stuff be easier to do in the 4 snapshot?

Not really sure, I'm not that familar with it yet, because I didn't move to it myself and people are not really using it (for obvious reasons). I know there are some improvements for model loaders/fetchers, but not sure about caching encoder/decoders.

**Comment by LorneLaliberte** [comment]
> I was curious so I tried it

Wow, Robert, thanks! My brain is a big foggy from a summer cold but at a quick glance it looks like one approach uses PaletteBitmapEncoder/Decoder to store the palette with the bitmap (same request), and the other approach uses PaletteCacheEncoder/Decoder to cache the palette on its own (separate request). (Nice attention to details in the serializer btw!)

> Well, even if that's true, it didn't come here as a bug report in the last 2 years, so it must be just hearsay. ALL is inclusive of SOURCE as you would expect. However, if you replace all ALLs with RESULT then those arguments become true. 

Ah, that could definitely have something to do with it. I agree it seemed really odd based on how I would expect it to be designed.

> During normal Glide usage (into(imageView)) you're storing the request in View.tag

Right, which is how Glide is able to respond to the activity/fragment life cycle events (unless I'm missing another benefit of it).

> The benefit of storing it in your view/viewmodel is that any time Glide comes in contact with it, it can retrieve a previous load and cancel it.

Hmmm. Is there a benefit to storing it in the viewmodel if loading into an ImageViewTarget, which I would expect is already storing the request in the view.tag?

Or...

> You don't have to worry about it, except you have to store the request somewhere if you have custom targets.

...do you mean only if you're using a custom Target, i.e. that doesn't extend one of the Targets that handles this already?

> The trick is that if you store the Request in the correct place creating a new target will still recognize the old one even though you don't have an explicit reference to the old target.

Hmmm. I'm trying to think of a scenario for this but so far it's eluding me. 

> If you don't implement clear/started callbacks then your item reuse will show the stale color of the previously bound model while the download/decode is happening.

Ah, I see. It isn't something you normally need to do for the bitmap (since that is handled in ImageViewTarget) but any additional "custom" behaviour -- like making use of the palette -- needs to account for it.

> What I meant is that if you implement a peeking decoder you can see that the decoder received a SOURCE cache image and then decode the Bitmap and calculate the palette.

Hmmm...I understand the peeking decoder to check whether it's a palette or a bitmap, but how could you know whether it's a SOURCE cache image or a RESULT when using ALL? Or do you mean when using a separate request for the palette, where you can explicitly set DiskCacheStrategy.SOURCE?

(If this is happening in both approaches from your commit, I'm really curious how that's possible. Or is it just a side effect of the PaletteBitmapDecoder only getting used initially, when it can be assumed that the SOURCE bitmap is being decoded first?)

> If the peek says that it's not an image then you can simply read a few bytes as opposed to doing a full decode.

It's really cool that Glide's architecture permits this. :)

> In my example I decoupled the image showing and the color delivery. This means there's no need for the actual Bitmap in the "palette load", except the first time to fill the cache.

Again I'm assuming you mean in the example that uses separate requests, correct?

> the hardest part was reconstructing the Palette so it gives the same results as before caching

Yeah, I remember thinking it was a bit surprising that `Target` doesn't have `hashCode`, especially since `Palette.Swatch` already does.

Ok, I need to go over your examples in detail to learn everything I can from this. Thanks so much Robert.

**Comment by TWiStErRob** [comment]
> at a quick glance it looks like [...]

Correct.
There're also two different approaches for peeking: with a "magic byte", or "brute force &rarr; reset &rarr; retry".

> which is how Glide is able to respond to the activity/fragment life cycle events

Not really. Glide uses a view-less magic fragment called `RequestManagerFragment` to follow the lifecycle and instruct the `RequestManager` (which is the same returned by `Glide.with(x)`) to pause/resume/clear the requests. Requests who reference the Targets are contained within, but targets store requests somewhere too. You can think of Target as the public API and Request as an internal thingy.

> I'm missing another benefit of it

Let's try an example: Let's imagine you have a ViewHolder that you create a custom target for:
```java
class HolderTarget extends SimpleTarget<PaletteBitmap> {
	private final ViewHolder holder;
	public HolderTarget(int width, int height, ViewHolder holder) {
		super(width, height); // this is irrelevant in this description
		this.holder = holder;
	}
	@Override public void onResourceReady(PaletteBitmap resource, GlideAnimation glideAnimation) {
		holder.onPaletteGenerated(resource);
	}
}
```
This is using `SimpleTarget` which means `get/setRequest` is storing in a fields in Target. If you have a `ViewHolder` object and want to clear it with `Glide.clear(holder)` that won't compile, you'll need a target: `Glide.clear(new HolderTarget(holder))`, but this won't do anything because there's no request in the just-created target. So to make it work, you'd have to do something like:
```java
class SomethingThatHasViews {
	private Target<?> current;
	void loadImage() {
		Glide.clear(current);
		current = Glide.....into(new HolderTarget(holder));
	}
	void getRidOfImage() {
		Glide.clear(current);
	}
}
```
which I would describe as cumbersome and not conveying clear intentions.

Now, if you implement an "external" storage for request:
```java
class HolderTarget ...
	@Override public void setRequest(Request request) {
		holder.request = request;
	}
	@Override public Request getRequest() {
		return holder.request;
	}
```
it'll make the target stateless and you can do this:
```java
class SomethingThatHasViews {
	void loadImage() {
		Glide.....into(new HolderTarget(holder));
	}
	void getRidOfImage() {
		Glide.clear(new HolderTarget(holder));
	}
}
```
Notice how you don't have to worry about cleaning up when the image is replaced. Also notice that I did't give the example with an adapter, because that would mean keeping track of which holder has which target. What I just described above is how `ViewTarget` works, except instead of holder it's using `View.tag`. Glide also has some convenience methods for creating the appropriate target for ImageViews and clearing views so this is all hidden during basic usage. Worth noting that creating a new target will be only used to get the request, after that the request will know about its original target and clear that, not the just-created one.

Note that you can do `holder.target = this` in `onResourceReady` as convenience. Relying solely on that without storing the request in an external place has some drawbacks. You have to pay extra attention to some things. External Reqeust storage helps recycler adapters a lot.

Sorry if I was confusing before, it's quite complex at first glance. Note that I didn't mention started/cleared callbacks on target, that's a separate issue and it's hidden from most `SimpleTarget` users, because those methods have default empty implementations.

> how could you know whether it's a SOURCE cache image or a RESULT when using ALL?

You don't necessarily have to be aware of this cache distinction. If you think about it:
 * SOURCE will only ever contain the original image, never a palette.
 * RESULT will always have a palette at the beginning of the cache file, in both approaches.

Even if it was possible to implement having <image palette> in the cache stream, you wouldn't really care if it's SOURCE or RESULT. Just read the image and then try to read the palette from the remainder. If you got a palette, use it, otherwise generate it. If #707 was fixed this would be simplified by not having to try or peak, but you could just confidently read whatever format you expect.

> Again I'm assuming you mean in the example that uses separate requests, correct?

Yes, "in my example" and most of that paragraph actually refers to the code in https://github.com/bumptech/glide/issues/1272#issuecomment-231439320, not my curious implementation. It's hard to have a wide-spread conversations like this, but I hope you're getting the hang of it now.

**Comment by LorneLaliberte** [comment]
> There're also two different approaches for peeking: with a "magic byte", or "brute force → reset → retry".

Ah, thanks, I did miss that at first.

> Glide uses a view-less magic fragment called RequestManagerFragment to follow the lifecycle

Thanks for the correction...I had assumed that Glide was storing the request in the tag so that it could stop loading the associated request when a view went out of scope (what I meant by "how Glide is able to respond to the activity/fragment life cycle events"). But of course:

> [...] but targets store requests somewhere too.

Yeah, (duh), of course they must, there's no need for a Target to have an associated View. 

> [...] which I would describe as cumbersome and not conveying clear intentions.

Hmm, it doesn't seem that odd to me...if anything the second example is syntatically a bit more odd looking (you're clearing an existing target by instantiating a new one just to access the existing one). Although I agree that not needing to hold onto the target just to clear it is beneficial, and I do get what you're explaining (finally)...

> Now, if you implement an "external" storage for request:

...it took me a bit of effort to understand what you meant by "external" there.

It wasn't really clear until I went looking for what interface was being fulfilled in order for those `getRequest` and `setRequest` to work (largely because I didn't remember `Target` being an interface -- having played around with `Palette.Target` too much lately perhaps). As soon as I saw that I realized why you were calling it "external."  You are overriding the built-in `setRequest()` and `getRequest()` methods in `BaseTarget` to get and set the request stored in the holder instead of in `BaseTarget` itself. So the `HolderTarget` here is just a way of overriding the `BaseTarget.getRequest()` and `.setRequest()` implementations. Neat.

> What I just described above is how ViewTarget works, except instead of holder it's using View.tag

Yeah...that part I understood (to some extent), but didn't understand in detail enough to describe it correctly at all. Thanks very much for the example.

> External Request storage helps recycling adapters a lot.

Yeah, I could see that. I'll have to see where I can fit this in with my data binding implementation. Currently my `BindingHolder` basically holds the `ViewDataBinding` that the data binding system generates. (It also provides the glue for some custom listeners like OnItemClick etc., but with data binding there isn't really much to do in the holder itself.)

I could create a custom `Target` for my viewmodel, e.g. an `ItemTarget` that gets/sets the palette request "externally" in the viewmodel. (I can access the viewmodel from the `Adapter` through the binding, e.g. to handle `onViewRecycled`.)

Although looking at your commit again, I see that you implemented the same `getTag()`/`setTag()` approach in `PaletteViewTarget`, like in `ViewTarget`. Aha.

If I'm understanding correctly, that should be equivalent to storing the request "externally" anywhere else -- I'd just need to construct a `PaletteViewTarget` with the view passed to `onViewRecycled` in the adapter, so it can get the request and clear it.

> You don't necessarily have to be aware of this cache distinction. [...] Yes, "in my example" and most of that paragraph actually refers to the code in #1272 (comment), not my curious implementation.

That answers my original question, thanks!

I wasn't actually referring to getting a palette from the RESULT cache but rather generating a palette from a RESULT bitmap (as in your `TestFragment_Inclusive` example), as in, I didn't think there was anything forcing it to only generate the palette from the SOURCE bitmap if for some reason the RESULT bitmap was cached already, but the palette wasn't. (Which may not actually be likely to happen, but it's a moot point anyway as I think using separate requests makes more sense overall.)

**Comment by TWiStErRob** [comment]
> if anything the second example is syntatically a bit more odd looking

That's where `HolderTarget` can be changed a little:
```java
this.holder = holder;
holder.target = this;
```
which means
```java
void getRidOfImage() {
    Glide.clear(holder.target);
}
```
but creating a new target to read the request is easier because it doesn't require you to change whatever the target is wrapping. You can easily create a `HolderClearTarget` to reduce confusion of that odd constructor call.

> ...it took me a bit of effort to understand what you meant by "external" there.

Yeah, sorry about that. You got it in the end. I was hoping "it'll make the target stateless" helps, but for that, yes, you have to know `interface Target` and `class BaseTarget`.

>  So the HolderTarget here is just a way [...]

Yeah, you get a lot of free stubs from `BaseTarget`, but if you implement a fully functioning target you'll likely override everything anyway so you can just implement the interface.

> so it can get the request and clear it.

If you use `View.tag` to store the request, you can simply call `Glide.clear(view)`, check the implementation of that method!

>  I didn't think there was anything forcing it to only generate the palette from the SOURCE bitmap if for some reason the RESULT bitmap was cached already

That really can't happen, because the RESULT cache key includes the encoder's ID. If you have written a palette to cache it'll be there. The Palette is always read from RESULT cache, or generated from SOURCE image. The only reason the decoder has to be ready for a missing palette during cache decode is because of #707.

**Comment by LorneLaliberte** [comment]
> but creating a new target to read the request is easier because it doesn't require you to change whatever the target is wrapping

Yeah, and it doesn't seem as weird once you look more closely at `BaseTarget`, or `Glide.clear(target)` for that matter.

> If you use View.tag to store the request, you can simply call Glide.clear(view), check the implementation of that method!

Oh, that's quite slick. I like it.

> That really can't happen, because the RESULT cache key includes the encoder's ID.

Good point about the key.

> If you have written a palette to cache it'll be there. The Palette is always read from RESULT cache, or generated from SOURCE image.

Yeah, what I meant wasn't so much about the palette being retrieved from cache, but rather the palette getting generated for a _bitmap_ that was retrieved from the RESULT cache...as in, to make it so the palette would only get generated for a SOURCE bitmap -- specifically in the "Inclusive" example, where a single request is used for the bitmap and the palette -- and not possibly be generated in the future based on a resized RESULT bitmap and getting different swatches generated.

For example, if another glide request had already caused the bitmap to be cached at the RESULT size, without generating a palette. My original question was related to how the "Inclusive" example would _not_ end up generating a palette for the RESULT bitmap, rather than generating it from a SOURCE bitmap at all times.

It isn't a real concern in any way though, just my reaction to something that seemed even more magical before clarification of which example/comment your explanation was referring to. Sorry. :)

I feel like my understanding has really skipped ahead thanks to your generous responses, though. Thanks again, Robert!

Hopefully some day I'll find a way to return the favour or pay it forward. :)

**Comment by TWiStErRob** [comment]
> getting generated for a bitmap that was retrieved from the RESULT cache

Ah, I see what you mean now, you wording confused me. The image is always decoded from SOURCE cache, but then it is transformed to target size. This transformed version is written to RESULT along with palette. 

>  already caused the bitmap to be cached at the RESULT size, without generating a palette

Again, key includes encoder's ID, so if it was cached without palette it cannot be read by the palette cache decoder (except when you play some tricks with getId).

> My original question was related to how the "Inclusive" example would not end up generating a palette for the RESULT bitmap

Ok, that's true. The inclusive version has the issue of slightly varying palette. But it's emphasized if you run it, and included in the class comment. I created that to double-check and someone finding it may not be that bothered about it.

---

If you can share, I would be curious to see the end result (app).
