### ISSUE TITLE
Enable debugging in code based on user variable

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#1288]
Is it possible to enable all glide debug messages in code? Is saw following https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

I can run this commands with `Process process = Runtime.getRuntime().exec("setprop log.tag.GenericRequest DEBUG");` from code probably and so on...
1. Is there a list with all currently valid debug options?
2. Is there a simple way to enable ALL debug messages at once?

Another question for this type of debugging appears:
Do I have to reset debugging levels? If yes, how to do that?

**Comment by TWiStErRob** [comment]
The current options are what's on the wiki and maybe a little more in the thread pools executors.

To reset replace VERBOSE with ERROR.

I guess the view is that: in order to see logging you need and and hence physical access to the device, so controlling from code doesn't make much sense.

**Comment by MFlisar** [comment]
If I enable logging and then call `Process process = Runtime.getRuntime().exec("logcat -d");` from my app and then send the result via mail, this won't work?

My app is running on the device so it has access, this should work, shouldn't it?

**Comment by MFlisar** [comment]
PS: another question: setting the build.prop, will this affect ALL apps on the device?

**Comment by TWiStErRob** [comment]
I think so, setting log level is device-wide and it's persistent until restart as far as I know. So any other apps that use Glide will also start logging.

**Comment by MFlisar** [comment]
Setting the debug levels from within the app is not working without root. I think it would make sense to make debugging enabeable via code as well...

Thanks for the help

**Comment by MFlisar** [comment]
Running following commands from a root console on my phone does not add any log messages:

    su
    setprop log.tag.Engine VERBOSE
    setprop log.tag.EngineJob VERBOSE
    setprop log.tag.DecodeJob VERBOSE

Afterwards I start my app, it's loading images in a `RecyclerView` adapter and then it loads an image in full resolution.

Not a single additional log line is visible in the output... Am I doing something wrong?

**Comment by TWiStErRob** [comment]
That looks correct, but do you really need su? I don't have root and always just do `adb shell` from computer. Does that work for you? Only try messing on the phone once you confirm that the logging normally works. Also are you on Glide 3.x?

**Comment by MFlisar** [comment]
Yes, glide 3.8.5...

I want this to be done by one of my users, my app works fine, but one guy tells me, loading camera images in full resolution is not working (all other resolutions work though and all images not taken by his camera as well).

I thought, I use su as using `setprop` is changing the system settings and an app without root probably does not have permissions for that.

Calling from my android studio, it works though... Then I at least get a transcode and decode log messages...

**Comment by TWiStErRob** [comment]
I looked around, but didn't find a way to programmatically set log levels. Some claim that `System.setProperty` would do the trick, but `isLoggable` uses native calls to figure it out so setting anything in JVM won't make a difference. If you have native part of your app you can try hacking around `<sys/_system_properties.h>`, because that's where the properties are read from: https://github.com/android/platform_system_core/blob/master/liblog/log_is_loggable.c#L90-186 I'm pretty sure it won't work though.

I think with the current implementation you have a few options:
 * try to remove the isLoggable checks with proguard (`assumenosideeffects`), though I don't know how it will behave for `if (isLoggable)`: will it change to `if (false)` or `if (true)`?!
 * create a temporary custom build for yourself from Glide sources and change logging the way you want
 * explain the user how to use ADB to enable logging then gather the logs the way you wanted  
Note that you don't necessarily need a full Android SDK to use ADB, see for example http://forum.xda-developers.com/showthread.php?p=48915118#post48915118

*I was wrong earlier: the default log level is INFO, not ERROR.* See `FifoPriorityThreadPoolExecutor` for more logging, though it should be logging any error by default. It is possible that you get a silent OOM. Just few days ago I found that some JPEG images need rotating because of exif and they may not fit into memory. My issue wasn't related to Glide, but it is still a plausible explanation, especially since you mentioned "full res" and "camera".

@sjudd any other ideas? What do you think about having some pluggabble logging inside Glide? e.g. SLF4J?

**Comment by MFlisar** [comment]
Thanks for the infos and for the idea of the root cause of my problem... I will let my customer enable debugging via a command from his laptop and send him the adb tool and a shell script, that's probably easier... Thanks for the link, I may have tried sending the adb.exe alone otherwise.

By the way, in my projects I use a custom wrapper class around the `slf4j` logger and use a boolean flag, which I check before logging... This way, I have the power to enable and disable logging from code whenever I want. Could be extendet to use tags instead of a boolean flag of course...

**Comment by sjudd** [comment]
This can be done with http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/GlideBuilder.html#setLogLevel-int-. 

It doesn't apply to all logs though. If there's demand for other types of logging we could consider adding them, but let's file new issues for specific requests.
