### ISSUE TITLE
Volley and Glide integration: retrying

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1308]
yes there is a note for glide and volley integration

so if i register with volley in module in the method
```java
@Override
public void registerComponents(Context context, Glide glide) {
    volley registration with glide code..
}
```

* now how can i setup like retry policy because volley does some retry when it fails some request right
* and also if i do something like this (remember i got this code from somewhere..), does glide will retry downloading or loading image according to the retry setup by volley like this during volley and glide integration

```java
RequestQueue queue = new RequestQueue( // params hardcoded from Volley.newRequestQueue()
        new DiskBasedCache(FileUtils.getDiskCacheDir(context, FileUtils.ImageCacheDirectory), FileUtils.DEFAULT_DISK_USAGE_BYTES),
        new BasicNetwork(new HurlStack())) {
    @Override
    public <T> Request<T> add(Request<T> request) {
        request.setRetryPolicy(new DefaultRetryPolicy(10000, 2, 2));
        return super.add(request);
    }
};
queue.start();
glide.register(GlideUrl.class, InputStream.class, new VolleyUrlLoader.Factory(queue));
```

Thanks

**Comment by TWiStErRob** [comment]
If you registered your `GlideModule` [correctly](https://github.com/bumptech/glide/wiki/Integration-Libraries#overriding-default-behaviour), then this queue will be used. The retry policy will be used when Glide loads from the network only. In this case Volley should try to retry as many times it wants and only then return the `InputStream` to Glide. As soon as something is returned there's no more retrying, so if the streaming dies midway Glide will simply fail with `.error(drawable)`. The next time the same image is loaded, Glide will try from the network again (because partial files are not cached).

**Comment by prabinshrestha** [comment]
thanks
* i want glide to retry as much as it can according to setup on glidevolley integration
* and also when i use like this it is using 

new DiskBasedCache() and new BasicNetwork (look above code)

but on this method we are overriding dischcahe like- so which cache it will use
    public void applyOptions(final Context context, GlideBuilder builder) {
     builder.setDiskCache(
                new DiskLruCacheFactory(path.DISK_MAX_SIZE));

**Comment by TWiStErRob** [comment]
`DiskBasedCache` is Volley's configuration, Glide's `DiskLruCacheFactory` is different from that.
So here you're essentially double-caching each file retrieved through Volley.

**Comment by TWiStErRob** [comment]
> i want glide to retry as much as it can according to setup on glidevolley integration

Glide will never retry. You can retry like I said before with click listener or `RequestListener`, and Volley can retry. Glide doesn't have a retry feature.

**Comment by prabinshrestha** [comment]
thank you very very much
Can you provide me a sophisticated example with click listener and request listener both
this is just a request from me, you dont need to if you dont feel like giving it but i dont want to see other's people example i want to see yours

Thanks again, really i am smiling now and i am happy

**Comment by TWiStErRob** [comment]
```java
class Model { String url; }
class MyAdapter extends RecyclerView.Adapter<MyAdapter.MyViewHolder> {
	// rest of the adapter with inflation and list
	@Override public void onBindViewHolder(MyViewHolder holder, int position) {
		holder.bind(list.get(position));
	}
	@Override public void onViewRecycled(MyViewHolder holder) {
		holder.unbind();
	}

	static class MyViewHolder extends RecyclerView.ViewHolder {
		private final RetryListener listener; // use a single listener per holder
		private final ImageView imageView;
		private Model model; // remember which model was bound to the holder
		public MyViewHolder(View itemView) {
			super(itemView);
			imageView = (ImageView)itemView.findViewById(R.id.image);
			listener = condition? new AutoRetryListener() : new UserRetryListener();
		}
		public void bind(Model model) {
			this.model = model;
			this.listener.reset(); // reset because our model changed
			loadImage(); // bind the model to the image view
		}
		public void unbind() {
			this.model = null;
			Glide.clear(holder.imageView);
		}
		private void loadImage() {
			Glide
					.with(itemView.getContext())
					.load(model.url)
					.listener(listener)
					.into(imageView);
		}
		private interface RetryListener extends RequestListener<String, GlideDrawable> {
			void reset();
		}

		private class UserRetryListener implements RetryListener {
			private final OnClickListener reloadListener = new OnClickListener() {
				@Override public void onClick(View v) {
					loadImage(); // force a load in response to user interaction
				}
			};
			@Override public void reset() {
				imageView.setOnClickListener(null);
			}
			@Override public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
				imageView.setOnClickListener(reloadListener); // load failed, allow user to try again
				return false; // show error image too
			}
			@Override public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
				reset(); // load successful, turn off retry-ability
				return false; // show loaded resource
			}
		}

		private class AutoRetryListener implements RetryListener {
			/** Number of retries, remember: the first load is not a retry, so a value of 2 means 3 Glide loads. */
			private static final int RETRY_COUNT = 2;
			private int retried;
			public void reset() {
				retried = 0;
			}
			@Override public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
				if (retried < RETRY_COUNT) { // async recursion's stop condition
					retried++;
					loadImage(); // async recursion to try loading image again
				}
				return true;
			}
			@Override public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
				return false;
			}
		}
	}
}
```

**Comment by prabinshrestha** [comment]
wow this is great, you are great.

  listener = condition? new AutoRetryListener() : new UserRetryListener();

*now i think i only need to introduce the value like isAutoRetryListenerEnabled and use it like
private boolean isAutoRetryListenerEnabled=true;
   listener = (isAutoRetryListenerEnabled)? new AutoRetryListener() : new UserRetryListener();

and inside
 @Override public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                if (retried < RETRY_COUNT) { // async recursion's stop condition
                    retried++;
                    loadImage(); // async recursion to try loading image again
                }else{
isAutoRetryListenerEnabled=false; // look at this
}
                return true;
            }

**Comment by prabinshrestha** [comment]
Thanks for your great help and i bless you from my heart.

also can you give the example if you have something requirement like this
*a main viewpager which consist of a message on top and below a sub viewpager
* and this sub viewpager consist of the photo at least two
* this photo should load with glide and there should be autoretrylistener like above and also include userretrylistener if it fails its maximum retry.

now how you are gonna design an adapter for that with glide...

Again if you dont feel like doing it, its ok because you already helped me a lot.I wanted to know this because there are so many newbie developer like me who wants to do exactly like that.

This might be the question related out of the glide
* As an android developer, which framework do you use for networking??
* which framework you use if you have to upload photo on server??(httpclient is deprecrated so)
* which persistence framework are you using ??
* do you know any best discussion forum related on topic above??

Anyways I had a great time discussing with you.

**Comment by TWiStErRob** [comment]
(There was a bug in `AutoRetryListener.onException`, which I fixed above by editing)

> isAutoRetryListenerEnabled

Changing the value won't change anything, because there's only one listener per ViewHolder. If you want to dynamically change it you need to re-assign the listener in the holder; or even simpler, just get rid of the listener field and decide when creating the Glide load: `.listener(condition? new AutoRetryListener() : new UserRetryListener())`. Just make sure you clear the click listener somewhere so the user doesn't observe stale behavior.

> if you have something requirement like this

Double-scrolling ViewPager is not a good idea, but if you want to, try just creating everything as you normally would. The main pager's item the adapter is a layout with TextView and ViewPager. Set an adapter for that sub-ViewPager in the outer's `instantiateItem`. Binding images with Glide is the same as calling `ImageView.setImageBitmap`, so there's no difference there. The problem that comes up often is that ViewPager keeps too many off-screen pages and items are not recycled, so you end up with a lot of images in memory that are not visible and this may lead to OOM. To prevent this you need to `Glide.clear` the views when they go out of sight and re-bind them when they come back or decrease the page limit.

> As an android developer, which framework do you use for networking??

http://stackoverflow.com/q/16902716/253468

> which framework you use if you have to upload photo on server??(httpclient is deprecrated so)

same as networking, they handle downloading and uploading

> which persistence framework are you using ??

https://developer.android.com/guide/topics/providers/content-providers.html backed by an SQLite DB

> do you know any best discussion forum related on topic above??

StackOverflow and check the project's GitHub page, for example Glide has a [Getting Help section](https://github.com/bumptech/glide#getting-help).

-----

I think we have diverged enough from the original issue and you should be writing your own code...
Keep at it, to learn more; and good luck!
