### ISSUE TITLE
sequence of executing while caching

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1314]
if we do .diskCacheStrategy(bla bla).skipMemoryCach(false) which is equivalent to diskCacheStrategy(bla bla) only 

* i want to know the sequence of executing whether memory cache is execute first or disk cache or both in asynchronous manner.

Thanks

**Comment by TWiStErRob** [comment]
Memory cache is queried first, if allowed by `skipMemoryCache`. This is sync, which means that by the the time`into` returns your listener and target will have been called. This assumes that your view is laid out and visible. If not, that can delay to a later point in time.

-----

Anything else from here on is executed in the background, because they involve potential disk or network I/O. The results are delivered asynchronously.

The next try is RESULT cache (if allowed by `diskCacheStrategy`), because it's better to load a perfectly sized and transformed image, than loading the original and doing stuff to it.

The next try is SOURCE cache (if allowed by `diskCacheStrategy`), because loading a local file is better than potential networking.

If neither caches hit Glide will get a model loader and ask for a fetcher. This fetcher will somehow return a Stream (most of the time, it can be anything though) which will be loaded.

If SOURCE caching is enabled via `diskCacheStrategy`, then the resulting stream is first fully saved to the cache and decoded from there.
One the final image is decoded it'll be saved in RESULT cache (if allowed by `diskCacheStrategy`).

Notice that all of the caching is symmetric, the stuff will only be put in the cache if that particular cache is enabled, and stuff will be read from the cache if that particular cache is enabled.
