### ISSUE TITLE
what features glide adopt when volley is integrate in module

### ISSUE THREAD

**Issue by prabinshrestha** [bumptech/glide#1315]
hello guys i just need the feature that glide will adopt from volley integration

**Comment by TWiStErRob** [comment]
Can you please rephrase/expand the question?

**Comment by prabinshrestha** [comment]
well i mean we integrate volley so :
* is the Glide going to use the thread pool of volley while networking ?
* what is the main point for integration with these great library ?

**Comment by TWiStErRob** [comment]
> is the Glide going to use the thread pool of volley while networking ?

Glide has it's own thread pool, but the concurrency of your app will depend on all of the players. If Glide has 4 threads, but Volley only has 2, it means that only 2 requests will be executing in parallel.

> what features glide adopt 

Now I understand this too, thanks. The answer is: none and all.
None, because Glide is unaware of Volley. It just calls the model loader and uses the data fetcher to get your images.
All, because the implementation of the loader/fetcher can use any feature of the integration library. This includes caching, cookies, headers, authentication, etc... How much is used depends on how you configure Volley.

> what is the main point for integration with these great library ?
https://github.com/bumptech/glide/wiki/Integration-Libraries#introduction

In the end these libraries all do the same thing: retrieve some data over the Internet for Glide to decode as an image, so either one should work fine. The question is what features you want (e.g. retry).
