### ISSUE TITLE
 Decode from source & cache not the same image quality

### ISSUE THREAD

**Issue by luke1989** [bumptech/glide#1317]
**Glide Version**: 3.7.0

**Device/Android Version**: 6.0

**Issue details / Repro steps / Use case background**: 

dump the image when resource ready and check the quality that decode from resource & cache

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(image.getContext()).load(uri).asBitmap().diskCacheStrategy(DiskCacheStrategy.RESULT)
.signature(key).listener(new GlideImageListener() {

					@Override
					public boolean onResourceReady(Bitmap resource, Uri uri,Target<Bitmap> target,boolean isFromMemoryCache, boolean isFirstResource) {
						BitmapUtils.dumpBmp(resource, "res_" + System.currentTimeMillis());
						return super.onResourceReady(resource, uri, target, isFromMemoryCache, isFirstResource);
					}
				}).into(new GlideImageTarget(image));
```

dump compressed bitmap to jpeg & quality 100 and save the file.
the resource bitmap and the cache are the same size(width&height) ,but different file length!!
and resource bitmap quality is better than cahce one , they are different !!!

I don't know which part changed the image quality
so I write new ImageDecoder&ImageEncoder to test the part different , and still the same that save to cache before and decode from cache , the image quality had been changed. 

```java
Glide.with(image.getContext()).load(uri).asBitmap().diskCacheStrategy(DiskCacheStrategy.RESULT).imageDecoder(new ImageDecoder(image.getContext())).encoder(new ImageEncoder())
.signature(key).listener(new GlideImageListener() {

					@Override
					public boolean onResourceReady(Bitmap resource, Uri uri,Target<Bitmap> target,boolean isFromMemoryCache, boolean isFirstResource) {
						BitmapUtils.dumpBmp(resource, "res_" + System.currentTimeMillis());
						return super.onResourceReady(resource, uri, target, isFromMemoryCache, isFirstResource);
					}
				}).into(new GlideImageTarget(image));

```

so can you help me to check this issue ?

**Comment by TWiStErRob** [comment]
The cached file's length doesn't necessarily mean real quality loss. For example the images taken by the camera are really wastefully compressed most of the time. Do you see visual differences between original and result cached? Tip: use `diskCacheStrategy(ALL)` to have both files in cache next to each other for debugging.

However Glide does compress and lost quality for saving space. The recompression only happens once though not every image showing. You can set the output format by setting `encoder(new BitmapEncoder(...))`. The Glide default is also to save memory, and is using 565 Bitmap format and not 8888. See https://github.com/bumptech/glide/issues/1069#issuecomment-198327734 and #305.

Note that all these quality losses Glide is having are mostly unnoticeable to the average user and it saves a lot of resources (memory, disk space, CPU cycles, battery) to intentionally use some quality.

I'm gonna close this as duplicate because it has been exhaustingly discussed. Please let me know if you have any additional info though. I'm curious exactly which problem of the above you had.

If you really care about quality you should know that even Android's `Bitmap.compress(JPEG, 100)` has been buggy since the beginning: http://stackoverflow.com/q/36487971/253468

**Comment by luke1989** [comment]
Thanks
