### ISSUE TITLE
Caching Inconsistencies

### ISSUE THREAD

**Issue by andrachekm** [bumptech/glide#1327]
I'm using glide 3.7.0, with OkHttp 3.3.1.

OkHttp is configured without a cache.
Glide is configured va a custom module.

I've got an avatar that's used throughout the application. The user can upload a new avatar through the application.  The avatar's url doesn't really change, it points to a constant location which then does a redirect to the actual resource (which is also currently a static url, but may not be in the future). This final URL includes all the necessary headers for caching - last modified, etag, etc.

When the new image is uploaded, I clear the disk cache, and the memory cache (which was a pain since I couldn't do both from an IntentService).

The first request after clearing the disk cache and memory cache to the new URL appears to work properly, but any subsequent requests, say in other activities, continue to return old copies of the image. It doesn't appear to actually clear the cache, even though I'm loading the images in onResume(), so it should be getting the new ones.

My requests use helper functions that look like this:

```
    public static void loadAvatar(Activity context, String url, ImageView view) {
        Glide.clear(view);
        Glide.with(context)
                .load(url)
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .cacheDecoder(new SecureBitmapDecoder(context))
                .sourceEncoder(new SecureSourceEncoder(context))
                .encoder(new SecureBitmapEncoder(context))
                .dontAnimate()
                .placeholder(R.drawable.default_profile)
                .centerCrop()
                .transform(new GlideCircleTransformation(context))
                .into(view);
    }
```

I was finally able to work around this, by doing a very bad thing - in my GlideModule, I'm setting a new BitmapPool and MemoryCache that do nothing/have max size of 0.  Now almost all my images are actually updated when the new avatar is uploaded (at big performance expense).

I said almost?  I have an image in my navigation drawer's view header, that I can't get to update reliably. 

Sometimes it does, sometimes it does not, and sometimes it does, but then it gets replaced with the old image again (which should not be possible unless I've got more than one image in the cache and it's randomly picking one?!?)

(OkHttp is configured without a cache, because I need to encrypt the contents of the cache, hence the Secure*Encoder/Decoder's).

**Comment by TWiStErRob** [comment]
> Glide is configured va a custom module.

This configuration may help to diagnose the issue.

> This final URL includes all the necessary headers for caching

This is irrelevant, because Glide doesn't care about that. Only OkHttp's disk cache would if you had enabled it.

>  I'm setting a new BitmapPool and MemoryCache that do nothing/have max size of 0.

There are built-in classes for that `BitmapPoolAdapter`, `MemoryCacheAdapter`.

> which was a pain since I couldn't do both from an IntentService

Yeah, you need some posting to do. This is because when memory cache releases resources it has to be done on the UI thread. Empty memory cache could be cleared before without exception, but as soon as clearing actually did something you got an exception.

> It doesn't appear to actually clear the cache

Memory cache doesn't actually clear everything, because there're some active resources currently visible on the UI, here's an example:
 * show image in ImageView
 * navigate to another activity (first one in background, but Bitmap is still tied to the ImageView)
 * clear memory cache
 * navigate back to the first one
 * reload image:
  * clear current Bitmap -> puts it into the memory cache
  * load "new" image, ah, it's in memory cache!

So you need to `Glide.clear` all your targets before clearing caches to prevent this from happening.
Your drawer not being updated is likely something similar. If the drawer was opened before then it stays inflated and the image is active there. When you open it after the upload/clear it's still active and that's why it may not update. If it wasn't opened before it should show the new avatar.

> `.centerCrop().transform(new GlideCircleTransformation(context))`

`centerCrop` is overwritten by `transform` see `centerCrop`'s source code. What you likely want is:`.transform(new CenterCrop(context), new GlideCircleTransformation(context))`, unless the circle one actually does cropping too. By the way, you're forcing Glide to always to these transformation, because you didn't enable RESULT cache. If you have consistent avatar views across the app you can gain from enabling it. But I guess if it's displayed in a lot of places it'll be memory cache anyway.

> `Glide.clear(view); Glide.with(context).....into(view)`

`clear` is redundant. If the view contains an active resource it'll be automatically cleared, see `GenericRequestBuilder#into(Target)`.

> Now almost all my images are actually updated when the new avatar is uploaded (at big performance expense).

I agree, but currently there's no way to mess around with the cache, it's all or nothing. If you want you can try hacking around with `.downloadOnly().get().delete()` to remove a single SOURCE cached file, but there're no guarantees there on how disk cache will react later.

I think the best solution would be to use `.signature` to handle this. You can store the current `lastUpdated` somewhere where it's persitent and application-wide (e.g. shared prefs). Using `.signature(new StringSignature(lastUpdated))` will invalidate all memory-cached and RESULT cached older avatars.

**Comment by andrachekm** [comment]
> Glide is configured va a custom module.
>> This configuration may help to diagnose the issue, though you later explained what you have there.

Here you go:
```
public class MyGlideModule implements GlideModule {
    @Inject
    @Named("glideClient")
    OkHttpClient okHttpClient;

    @Inject
    Crypto crypto;

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);

        builder.setBitmapPool(new BitmapPool() {
            @Override
            public int getMaxSize() {
                return 0;
            }

            @Override
            public void setSizeMultiplier(float sizeMultiplier) {

            }

            @Override
            public boolean put(Bitmap bitmap) {
                return false;
            }

            @Override
            public Bitmap get(int width, int height, Bitmap.Config config) {
                return null;
            }

            @Override
            public Bitmap getDirty(int width, int height, Bitmap.Config config) {
                return null;
            }

            @Override
            public void clearMemory() {

            }

            @Override
            public void trimMemory(int level) {

            }
        });

        builder.setMemoryCache(new MemoryCache() {
            @Override
            public int getCurrentSize() {
                return 0;
            }

            @Override
            public int getMaxSize() {
                return 0;
            }

            @Override
            public void setSizeMultiplier(float multiplier) {

            }

            @Override
            public Resource<?> remove(Key key) {
                return null;
            }

            @Override
            public Resource<?> put(Key key, Resource<?> resource) {
                return null;
            }

            @Override
            public void setResourceRemovedListener(ResourceRemovedListener listener) {

            }

            @Override
            public void clearMemory() {

            }

            @Override
            public void trimMemory(int level) {

            }
        });

        builder.setDiskCache(new InternalCacheDiskCacheFactory(context, "glide", 10*1024*1024));

    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        if (okHttpClient == null) {
            CVApplication.getComponent(context).inject(this);
        }
        glide.register(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(okHttpClient));

    }
}
```

> I'm setting a new BitmapPool and MemoryCache that do nothing/have max size of 0.
>> There are built-in classes for that: BitmapPoolAdapter, MemoryCacheAdapter.

Yes, and I'm overriding those so that they're skipped so that the images will actually update. Otherwise, even with ```clearDiskCache()``` and ```clearMemory()``` I cannot get any updated images until the application is terminated (force stopped, or swiped away from recents).

> This final URL includes all the necessary headers for caching
>> This is irrelevant, because Glide doesn't care about that. Only OkHttp's disk cache would if you had enabled it.

And I can't use OkHttp's disk cache, because I can't find a way to encrypt it. :(

> So you need to Glide.clear all your targets before clearing caches to prevent this from happening 
I can't Glide.clear() targets that only exist in other activities.

> Glide.clear(view); Glide.with(context).....into(view)
clear is redundant. If the view contains an active resource it'll be automatically cleared, see GenericRequestBuilder#into(Target).

Then why did I have issues with incorrect images in my RecyclerViews prior to adding the clear before loading?

> I think the best solution would be to use .signature to handle this. You can store the current lastUpdated somewhere where it's persitent and application-wide (e.g. shared prefs). Using .signature(new StringSignature(lastUpdated)) will invalidate all memory-cached and RESULT cached older avatars.

Ok.  I guess I'm going to have to maintain a list of all the images a user may encounter, and their last modified/etags/whatever.  I probably have to use OkHttp interceptors to get that information from the second request.  It would be nice if I could then use ```DiskCacheStrategy.ALL```, and re-enable the memory cache and bitmap pool - if it works reliably.

**Comment by TWiStErRob** [comment]
> There are built-in classes for that: BitmapPoolAdapter, MemoryCacheAdapter.

The above are the actual class names, you're implementing the `BitmapPool` and `MemoryCache` interfaces. What I'm saying is there are already null-implementations ready for you. Updated the above comment for brevity. (Notice that `MemoryCacheAdapter` actually has required functionality!)

> I can't use OkHttp's disk cache, because I can't find a way to encrypt it.

Wow, you can only change the folder of the disk cache and the class is final.
I think if you take a step back from the cache, you may be able to do it. Don't look around changing the cache, but the actual response, something like:
```java
new Interceptor() {
	@Override public Response intercept(Chain chain) throws IOException {
		Response res = chain.proceed(chain.request());
		return res.newBuilder()
		     .body(new RealResponseBody(res.headers(), new EncryptingSource(res.body().source())))
		     .build();
	}
}
```
If you do this Glide will already receive an encrypted stream, you don't need a secure `sourceEncoder`, but need a secure `cacheDecoder`. I've seen someone totally disregard Glide's cache (`.diskCacheStrategy(NONE)`) and using only OkHttp's cache: #1257.

> Then why did I have issues with incorrect images

That's an interesting question. Is it possible you changed more than that during that deploy? If you can create a repro for that, it would be amazing. If there's a weird issue that would need to be fixed. Though I don't think there's one until proven otherwise ;)

> maintain a list of all the images a user may encounter

Oh, I though this is for only the current user. if you want to display perfectly up-to-date avatars for all users, that's gonna be interesting. How do you know on a single device if another user on another device has updated their avatar? If you hit the Glide caches you can't even revalidate the ETag(etc) headers for detecting changes.

**Comment by andrachekm** [comment]
> Wow, you can only change the folder of the disk cache and the class is final.
> I think if you take a step back from the cache, you may be able to do it. 

I haven't tried to work with Okio before.  It's certainly not as straightforward as just dealing with InputStream and OutputStream. Implementing a BufferedSource looks quite complicated, and I don't think it's nature will make it very difficult to integrate with Encryption, where the IV and other data get added to the beginning of the stream.

> How do you know on a single device if another user on another device has updated their avatar?

GCM push messages, and pull to refresh on certain screens will also clear the Glide cache and force refreshes in the case that GCM messages are missed.

**Comment by TWiStErRob** [comment]
> also clear the Glide cache and force refreshes

That sounds really wasteful. Have you considered changing the responses so that the user field of a conversation, or whatever your entities are, contain the avatar last update time/etag next to the user ID and/or avatar Url? This rarely changing thing can be mixed into the cache key with `signature`.

---

Let me know what you can figure out, I'm curious.

**Comment by andrachekm** [comment]
We have user objects, but they don't currently have the direct url (or last modified time), we have to make api calls for that.  Still, those would probably only be updated on push, or a pull to refresh. We're looking at getting rid of the redirect, which should help at least a little bit.
