### ISSUE TITLE
How do we tell Glide to release ImageView references but to not cancel ongoing image loads on activity/fragment destruction ?

### ISSUE THREAD

**Issue by sandy-8925** [bumptech/glide#1329]
**Glide Version**: 3.7.0

**Integration libraries**: None

**Device/Android Version**:  Emulator/6.0, Nexus 6/6.0

**Issue details / Repro steps / Use case background**:
We currently get an instance of Glide request manager using Glide.with(appContext), but found that this will temporarily leak views when image load takes some time (e.g slow network connection).
(reproducible using this: https://github.com/sandy-8925/glide_appcontext_memory_leak if you use device/emulator with slow network speed (EDGE) )

We are planning to switch to using Glide.with(activity)/Glide.with(fragment) but we don't want Glide to cancel any ongoing image loads when the activity/fragment is destroyed. We do want Glide to release it's references to the ImageViews into which it's trying to load images.

**Comment by sandy-8925** [comment]
In our app, we load profile pictures from our servers, and these are shown on several screens, so we want to avoid canceling ongoing image loads, since we will most likely load it again on another screen.

**Comment by TWiStErRob** [comment]
I think you can work around the automatic destroy like this:
```java
// normal load trying to display the image
Glide.with(activity).load(url).diskCacheStrategy(SOURCE|ALL).....into(imageView);
// when the user decides to back out of the activity execute this before `super.onStop()`:
Glide.with(appContext).load(url).downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);
```
The original load will be cancelled automatically, but because there's another load depending on the same mode,l it'll keep the download alive. As far as I know Glide latches on to existing loads and all the loads complete at the same time once the data is available from SOURCE cache. Note that if the image was already displayed then the `downloadOnly` will simply find it in SOURCE cache and do nothing. The thing to be mindful of is to *not* start the `downloadOnly` if the other load wasn't started. You can work around this by simply firing both of the above at the same time.

**Comment by sandy-8925** [comment]
@TWiStErRob Thank you for that suggestion!

**Comment by TWiStErRob** [comment]
Please let me know how it works out.
