### ISSUE TITLE
Don't overwrite my placeholders

### ISSUE THREAD

**Issue by j-garin** [bumptech/glide#1332]
Hi.

Is it possible not to use placeholders? When I don't use them, Glide still replaces the images in my ImageViews with null.

I am loading image urls async. And before I call Glide I want to have some placeholders there, so i use src="@drawable/foo.bar" in my layout files. However, when I call Glide.load().into() those placeholder images are overridden by Glide. Is there any way to leave them there?

I don't want to use Glide.load().placeholder() because it causes 2 times more memory consumption for placeholders as they are loaded twice.

Thanks.

**Comment by TWiStErRob** [comment]
Yes, the default is `.placeholder(null)`, there's no way around that. Glide takes full ownership of the ImageView's contents between `.into()` can `Glide.clear(view)`. Notice there's a `.placeholder(Drawable)` method. You don't need to let Glide to inflate the drawable for you based on resource ID. In the adapter constructor you can do `this.placeholder = resources.getDrawable(R.drawable.foo_bar)` and then when loading the images: `.placeholder(this.placeholder)`.

However, the double load may be **because** you're using the drawable in XML. Try to remove all references to that drawable statically hard-coded into your XMLs, and use the `.placeholder(int)` method. If you want to see something in the editor, then add `tools:src="@drawable/..."`; using `android:src` AND Glide makes inflating the `src` redundant.

**Comment by j-garin** [comment]
Thank you for fast reply. Trying that now.

**Comment by j-garin** [comment]
Now everything works as expected. You were very helpful. Thank you so much!

**Comment by TWiStErRob** [comment]
So the issue was really having both the `src` and `.placeholder(int)`?

**Comment by j-garin** [comment]
Yes. The first instance of Drawable was loaded by LayoutInflater, the second one - by Glide.
