### ISSUE TITLE
Cache directories not created post Android M permission grant.

### ISSUE THREAD

**Issue by humblerookie** [bumptech/glide#1333]
Glide version 3.7.0
Nexus 5 : on 6.0.1

I'm not sure if this question has been asked before and I'm unable to find any resource that links up to the same. But with Android M my cache directories are not being created as per my module instructions. 

I understand that this needs runtime permission from Android M but how do I reinitialize this post permission grant. The initialization was working perfectly before targeting Android 23. 

My GlideModule looks like this 
```java
public class GlideDefaultModule implements GlideModule {

    private static GlideDefaultModule glideDefaultModule;

    private GlideBuilder glideBuilder;

    public static GlideDefaultModule getModule() {
        return glideDefaultModule;
    }

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        glideDefaultModule = this;
        this.glideBuilder = builder;

        MemorySizeCalculator calculator = new MemorySizeCalculator(context);
        int defaultMemoryCacheSize = calculator.getMemoryCacheSize();

        int cutOff = (int) (Runtime.getRuntime().maxMemory() / 6f); // 16% of total memory for bitmaps

        if (cutOff < 0 || cutOff > defaultMemoryCacheSize) {

            cutOff = defaultMemoryCacheSize;
        }

        builder.setMemoryCache(new LruResourceCache(cutOff));
        builder.setBitmapPool(new LruBitmapPool(cutOff));

        Runtime.getRuntime().maxMemory();
        if (BaseUtil.isSDCardAvailable()) {
            builder.setDiskCache(
                    new DiskLruCacheFactory(new DiskLruCacheFactory.CacheDirectoryGetter() {
                        @Override
                        public File getCacheDirectory() {
                            return createDirectoryIfNeeded();
                        }
                    }
                            , BaseConstants.DISK_CACHE_SIZE));
        } else {
            builder.setDiskCache(new InternalCacheDiskCacheFactory(context, BaseConstants.DISK_CACHE_SIZE / 10));
        }
    }

    public File createDirectoryIfNeeded() {
        File folder = new File(Environment.getExternalStorageDirectory() + "/" + BaseConstants.PIC_DIRECTORY);
        if (!folder.exists()) {
            folder.mkdir();
        }
        return folder;
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
    }
}
```

**Comment by TWiStErRob** [comment]
You can delay initializing the GlideModule by making sure `Glide.get(context)` is not called. This means you can't load any image (`Glide.with(...)` calls `get`) until the user has authorized to write to the SD card.

Based on the flow of the File object returned from `getCacheDirectory` it may be sufficient to not use the Glide cache until the authorization, by explicitly disabling the cache: `.diskCacheStrategy(NONE)`. Up until that point it the File object is just passed around. If you want to go this way, you'll need to implement your own `DiskCache.Factory` based on `DiskLruCacheFactory` that doesn't ensure that the directory exists. Because that `mkdirs` and `exists` will likely fail before permissions are granted. However you must make sure that the directory exists before making the first Glide load with a non-NONE strategy.

**Comment by humblerookie** [comment]
Thanks for your prompt response.  We are incorporating the cache within the private directory of our app henceforth. 

Additionally needed a confirmation from you regarding the state of glide during a cycle of grant->revoke->grant. 
In this case with every request if i check whether the app has been granted permission to write to external media and only then set the diskCacheStrategy accordingly will suffice?

Also you probably meant `If you don't want to go this way, you'll need to..`

**Comment by TWiStErRob** [comment]
> Also you probably meant

No I meant what I wrote, the reason is in that and the next sentence. You'll need to create your special factory to handle the permission potentially handed out later.

> check whether the app has been granted permission to write to external media and only then set the diskCacheStrategy accordingly

The disk cache can't change runtime, unless you implement one yourself that can handle permission lost and relocate to a writable place on the fly internally. I was saying to set the strategy while you don't have permission to delay the lazy init as long as possible, see: `DiskLruCacheWrapper.getDiskCache`. But I think the cleaner approach is what I wrote first: don't do anything with Glide until there's a permission.

Though, you are saying something: if the user revokes the permission you can simply just start adding NONE to your loads to prevent the disk cache from freaking out, because it'll prevent Glide from using it. Once the user grants again you can start using the other strategies. This will be a graceful fallback: the user can trade "a permission + disk space" for "time + network usage".

**Comment by humblerookie** [comment]
Yes. 

> This will be a graceful fallback: the user can trade "a permission + disk space" for "time + network usage"

This is exactly what I'm going for. Thanks for the help once again.
