### ISSUE TITLE
Having some problems in loading .webp image

### ISSUE THREAD

**Issue by zzwwws** [bumptech/glide#1340]
**Glide Version**: 3.7.0

**Integration libraries**: Default

**Device/Android Version**: Nexus 5, 6.0

**Issue details / Repro steps / Use case background**: 
Hi, i met a strange problem when using Glide to load .webp image, Some images (always specific) cant be shown normaly at first time, but shown normaly when i scroll the list. And it works fine when loading images with other format (.jpg or .png). 
### loading .webp image

![glide_1](https://cloud.githubusercontent.com/assets/2063712/16827396/deeacfb8-49b8-11e6-8a2b-d7b1bf4d041f.png)
### load .jpg image

![glide_2](https://cloud.githubusercontent.com/assets/2063712/16827399/e7031156-49b8-11e6-8874-986f6cd0fb71.png)

I feel confused when debuging Glide source code, as shown:

``` java
    @Override
    public void onResourceReady(Z resource, GlideAnimation<? super Z> glideAnimation) {
        if (glideAnimation == null || !glideAnimation.animate(resource, this)) {
            setResource(resource);
        }
    }
```

Everything is fine util running onResourceReady, glideAnimation.animate(resource, this) equals true, so setResource(resource) will not be executed, leading the problem mentioned above. My question is
- i did not set drawable to target actively. why glideAnimation.animate(resource, this) equals to true?
- Glide cache strategy settings seems not work when the problem occurres, it always load .webp image from network

I use Glide like this:

``` java

Glide.with(context).load(url).placeholder(R.drawable.default_product_bg_nano).diskCacheStrategy(DiskCacheStrategy.SOURCE).into( holder.image);

```

the context is a Fragment. The .webp image url which not shown is http://omsproductionimg.yangkeduo.com/images/label/610/GS4X5Ojt5TlVPuAtNGqr2hywByGs2FHN.jpg@120w_1l_50Q.webp

**Layout XML**:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:layout_marginBottom="11dp"
              android:layout_marginTop="5dp"
              android:gravity="center"
              android:orientation="vertical">

    <ImageView
        android:id="@+id/iv_image"
        android:layout_width="60dp"
        android:layout_height="60dp"/>

    <TextView
        android:id="@+id/tv_opt_name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:ellipsize="end"
        android:maxLines="1"
        android:textColor="#333333"
        android:textSize="12sp"/>
</LinearLayout>
```

**Comment by TWiStErRob** [comment]
> why glideAnimation.animate(resource, this) equals to true?

The default is the same as if you added `.crossFade()`. It'll animate between the placeholder and the image. To confirm this try to add `.dontAnimate()`.

> so setResource(resource) will not be executed

Yes, it's true that won't be executed. It's because the animation returned true, because it already set the drawable. Follow the call chain into `animate`.

> Glide cache strategy settings seems not work when the problem occurres

Use RESULT, SOURCE or ALL, but the issue is not related to `diskCacheStrategy`.

> cant be shown normaly at first time, but shown normaly when i scroll the list. 

This suggests he issue is not with the file itself, but the animation. The animation only happens if the image was loaded asynchronously. After scrolling they're loaded from memory cache. Which is sync.

---

The weird thing is that this should work fine. Please try adding a listener and see why that image is not loaded: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
The empty space suggests there was an error, because I assume your placeholder to have some content. You can also add some different-than `default_product_bg_nano` drawable as `.error` and `.fallback` to visually confirm.

**Comment by zzwwws** [comment]
@TWiStErRob Thank you for quickly reply, I'll try it
