### ISSUE TITLE
CenterCrop AspectRatioView

### ISSUE THREAD

**Issue by Brianvdb** [bumptech/glide#1341]
**Glide Version**: 3.7.0

**Integration libraries**: Default

**Device/Android Version**: All.

**Issue details / Repro steps / Use case background**:
Possibly related to #613 #705

Using [this custom ImageView](https://gist.github.com/JakeWharton/2856179)

I am using CenterCrop and it is not filling the whole ImageView. When I start scrolling it will reload the image and than it is showing just fine. It is working perfectly with Picasso.

 Context: I am using a RecyclerView. The images are loaded in an Adapter in onBindViewHolder method. All items are using the same custom ImageView with the same aspect ratio. I am using a LinearLayoutManager for the RecyclerView but I believe the GridLayoutManager has the same problem. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with(context).load("http://example.com/image.jpg").centerCrop().into(image);
```

**Layout XML**:

``` xml
<RelativeLayout 
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

  <mypackage.AspectRatioImageView
        android:id="@+id/image"
        android:layout_width="140dp"
        android:layout_height="wrap_content"
        app:aspectRatio="1.58"
        app:aspectRatioEnabled="true"
        app:dominantMeasurement="width" />

</RelativeLayout>
```

Screenshot:

![screen](http://i.imgur.com/BeB4pyj.png)

I know I can fix the problem by just setting a fixed height instead of wrap_content but this is not really an ideal solution..

**Comment by TWiStErRob** [comment]
I think what Glide sees is `140dp` and "I don't care" as dimensions and hence the image loaded will be cropped into `140 x screenHeight`, which is then displayed with `scaleType="fitCenter"` (the default on ImageView) and that's why you see the full image in case of the flame.

Try `android:layout_width="match_parent"`, that's the opposite of 2 fixed dimensions. I think that's what you want anyway. If you want a `140dp` wide list then set the width on the `RecyclerView`, not the items themselves. The effect of setting a `match` dimension is that Glide will wait for layout to figure out the size of the view and only then start loading an image with the correct dimensions. Previously `wrap` was essentially a hardcoded value for the device's screen height.

**Comment by Brianvdb** [comment]
@TWiStErRob Thanks for your response. Yes it works fine with match_parent but I have views next to the ImageView. I simplified my layout file in this issue for the sake of readability.

Also the problem is the top two images, not the lowest image. I need it like the image at the bottom, which is 140dp wide and has the right height. 

Anyhow, I tried the following solution and it is working:

```xml

<RelativeLayout 
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

  <RelativeLayout
        android:layout_width="140dp"
        android:layout_height="wrap_content">

        <mypackage.AspectRatioImageView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:aspectRatio="1.58"
            app:aspectRatioEnabled="true"
            app:dominantMeasurement="width" />

    </RelativeLayout>

</RelativeLayout>
```

This is however, not a very good solution as it requires nesting views which is [not great for performance](https://developer.android.com/training/improving-layouts/optimizing-layout.html#Revise).

This issue can be closed but this feels rather hacky and this issue seems like a bug since it is working fine with Picasso.

**Comment by TWiStErRob** [comment]
> This issue can be closed but this feels rather hacky and this issue seems like a bug since it is working fine with Picasso.

Don't give up so fast, here're two more things to try.

---

As far as I know Picasso doesn't make as much effort to downsize the image to match view's size, or if it does, the interpretation of `wrap_content` may differ. You can help Glide to figure out the size you want without the wrapping layout:
```java
Glide
    .with(context)
    .load("http://example.com/image.jpg")
    .centerCrop()
    .override(image.getWidth(), Math.round(image.getHeight() * image.getAspectRatio()))
    .into(image)
;
```

---

**Alternatively** you may be able to trick Glide into doing what you want by doing:
```xml
<mypackage.AspectRatioImageView
            android:layout_width="140dp"
            android:layout_height="match_parent"
            tools:layout_height="wrap_content"
            app:aspectRatio="1.58"
            app:aspectRatioEnabled="true"
            app:dominantMeasurement="width" />
```
Notice that since the custom view measures itself specially you'll end up with the correct sizes. Tools attribute added to prevent the Preview in the IDE looks weird.

**Comment by Brianvdb** [comment]
@TWiStErRob Setting `match_parent` on `layout_height` made it work and seems like the cleanest solution!

**Comment by TWiStErRob** [comment]
Do you understand why it works?
