### ISSUE TITLE
how can we set priority High to visible items in recyclerview ?

### ISSUE THREAD

**Issue by nageshnallapu** [bumptech/glide#1346]
Below code in MainActivity.
```java
fullRequest = Glide.with(this)
                .from(Webphotos.class)
                .placeholder(android.R.drawable.progress_indeterminate_horizontal)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .crossFade(R.anim.fade_in, 150);

        thumbnailRequest = Glide.with(this)
                .from(Webphotos.class)
                .dontAnimate()
                .dontTransform()
                .centerCrop()
                .placeholder(android.R.drawable.progress_indeterminate_horizontal)
                .override(pageSize, pageSize)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
        ;

        preloadRequest = true ? thumbnailRequest.clone().priority(Priority.LOW) : fullRequest;

```
Below is my code for adapter onBindViewHolder()

```java
MainActivty.fullRequest
                .load(photo)
                .thumbnail(true ? MainActivty.thumbnailRequest.load(phot) : null)
                .into(((NormalViewHolder)viewHolder).imgThumbnail);
```
If the user scrolls the recyclerview ,how to load the visible items first?

After scrolling the recycleview to bottom.when scrolling  back to top,Images are loading again with placeholder(ic_launcher),how can i restrict reloading and remove  the placeholder(ic_launcher)?

**Comment by TWiStErRob** [comment]
How does `ic_launcher` come into the picture?

You found the priority method already, that should work, but I think the preloader manages that automatically anyway. You have SOURCE caching, so that means everything is on disk already (if you waited for the first viaible page to load). Scrolling to the end means that all requests except those on the last page are cancelled. Also memory cache is not unlimited, I think you're expecting the memory cache to hold all thumbnails and full images from the first page and from the last page in memory, along with any number of stuff in between. Seeing the placeholder should be really quick as they're loaded from the disk. Btw, how many items are you preloading?

Tip: centerCrop after dontTransform makes dontTransform meaningless.

**Comment by nageshnallapu** [comment]
Thank you for reply,
For every request i am  loading 10 images.Here ic_launcher is app icon .I didn't use this icon as placeholder but While scrolling  it is displaying some times as placeholder .Is there any problem with SOURCE caching?

**Comment by TWiStErRob** [comment]
No, SOURCE is correct. Maybe you have `android:src="@drawable/ic_launcher"`, change it to `tools:src`.

**Comment by nageshnallapu** [comment]
Thank you for your quick respone.
As We already have images in the cache,Is there any way to save the image into gallery from cache when the user wants to save?

**Comment by TWiStErRob** [comment]
See #459, but instead of `getUriForFile` you can just copy it wherever you want.
