### ISSUE TITLE
downloadOnly results in NoSuchElementException

### ISSUE THREAD

**Issue by timusus** [bumptech/glide#1362]
**Glide Version**:
3.7.0

**Integration libraries**:
okhttp3-1.4.0

**Device/Android Version**:
Nexus 6P / Android N DP5

**Issue details / Repro steps / Use case background**: 
I'm trying to pre-load a bunch of images into the disk cache, using `downloadOnly` in an `AsyncTask`. I'm using a custom `Glide module` with a custom `DataFetcher`, which eventually leads to an `InputStream` being obtained via an `OkHttp Call`.

The `downloadOnly` request is performed in the background thread (via an AsyncTask running in a Service). Multiple `downloadOnly.get()` calls are made in series, as I iterate over the items I wish to pre-load.

I end up with an `ExecutionException: NoSuchElementException` for any non-cache-hit. Since artwork loading via my custom module elsewhere in the app, (using normal asynchronous Glide requests like `Glide.load().with().into()`), I figure this isn't a problem in the custom module/data fetcher, but rather some problem with trying to execute multiple `downloadOnly.get()` calls in series, on the background thread..

I've been trying to dig around to figure out what the 'NoSuchElementException' means or why it's thrown, but I just don't understand. I figure my approach is wrong, but I'd like to know in what way.

Thanks for your assistance.

The Glide request looks like this:

```
...
Void doInBackground(Void... params) {

    for (model myModel : aWholeLottaModels) {
        Glide.with(MyService.this)
            .load(myModel)
            .downloadOnly(SimpleTarget.SIZE_ORIGINAL, SimpleTarget.SIZE_ORIGINAL)
            .get(15, TimeUnit.SECONDS);
    }
}
```

**Stack trace / LogCat**:
```
Exception: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: No value present
```

**Comment by timusus** [comment]
Well, it took me several hours of debugging to decide to post an issue, and then about 5 minutes after posting the issue to find the problem.

The problem was indeed coming from my custom data fetcher. Somewhere in the mix I wasn't catching a `NoSuchElementException`.. Didn't really have anything to do with Glide :(

**Comment by TWiStErRob** [comment]
Ah, so Glide was just nice to propagate that error to you.

**Comment by timusus** [comment]
Yep, I've been caught out by this a couple of times. I'm not used to.. how do I put this? Working on code that's wrapped in something which catches and logs exceptions. So when it happens, I always think it's something under the hood of Glide which is throwing an exception, rather than the code I've written to be executed by Glide.

Good learning process!

**Comment by TWiStErRob** [comment]
Btw, `Glide.load().with().into()` won't use the `downloadOnly`'d request, you have to use one of `.diskCacheStrategy(SOURCE|ALL)`.

Also make sure you're clearing these requests. Just firing them will make Glide hold onto them because you're using a Service (therefore AppContext). `FutureTarget<?> target = ...downloadOnly(); target.get(...); Glide.clear(target);`. Clearing won't delete the cached file, but will make Glide forget about the request object. See `RequestFutureTarget` JavaDoc for more.

**Comment by TWiStErRob** [comment]
> Working on code that's wrapped in something which catches and logs exceptions.

This is required because Glide is passing stuff between threads. In a normal load scenario your custom fetcher is in the background, but the `RequestListener.onException` is on the UI thread. If Glide wasn't catching the exceptions the background threads would just die without you knowing or crashing the whole app.

**Comment by timusus** [comment]
Thanks for the info, all very helpful.
