### ISSUE TITLE
How can I get cookies from glide?

### ISSUE THREAD

**Issue by cxss** [bumptech/glide#1378]
**Glide Version**:
3.7.0

**Integration libraries**:
no other network libraries

**Device/Android Version**:
all

**Issue details / Repro steps / Use case background**: 
  In our app we use Glide for an image loader with android original network module. In some cases we need to load an image and get the cookies from network response, then put the cookies into another module (such as a WebView). I wonder how can I get cookies from glide after an image is loaded? Many thanks!

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
GlideUrl glideUrl = new GlideUrl(url, builder.build());
Glide.with(context).load(glideUrl).into(view);
```

**Comment by TWiStErRob** [comment]
You'll probably need to replace your networking library to do that. `HttpUrlGlideUrlLoader -> HttpUrlFetcher` is the default. OkHttp and others probably have an easier way to intercept stuff.

If you want to fetch the cookies per request it'll be very interesting, because you'll have to replace everything in the [pipeline](https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit) to get the cookies to the listener/target. Alternatively use a similar technique to this to capture what you need: https://gist.github.com/TWiStErRob/08d5807e396740e52c90
