### ISSUE TITLE
Imageview always taking wrap_content even its match_parent

### ISSUE THREAD

**Issue by GauravP123** [bumptech/glide#1381]
**Glide Version**:
3.7.0

**Integration libraries**:
Retrofit

**Device/Android Version**:
All

**Issue details / Repro steps / Use case background**: 
i am using `Glide.with(mCon).load("url").placeholder(image).into(holder.image);` but with this image is not taking match_parent it always showing as per image size  even i have define match_parent

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with(mCon).load("url").placeholder(image).into(holder.image);
```

**Layout XML**:

``` xml
<ImageView
            android:id="@+id/imageIcon"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />
```

**Comment by TWiStErRob** [comment]
Not sure what your expectation are here. This view will match the parent size. If the parent is `wrap_content` on the width, then you may have weird behavior. Make sure the view looks ok without setting any image into it (set `android:background="@android:color/black"` to see the bounds). You may need to change height to some fixed value because wrapping a non-image will probably measure as 0. After that looks ok, try using Glide to fill it; now you can restore the `wrap` height.

**Comment by GauravP123** [comment]
so when i am setting match parent to my imageview then it should take full width as it is match parent . parent layout is also match and ya if i set color to parent it giving me black for rest of the space where image is not present . i think it should cover full width

**Comment by TWiStErRob** [comment]
So even though you set match for width Glide loads a smaller image and you have black bands on left and right side if you set the background? Black background is just for diagnostics, it's not a solution. How much space is available vertically? Not filling width probably means there's not enough height. fitCenter (default scaleType and therefore default Glide transformation) will fit one of the sides only, the other one will be banded, because it always keeps aspect.

**Comment by GauravP123** [comment]
yes on left and right side background is present . space is enough

**Comment by TWiStErRob** [comment]
Does it work if you add `.dontAnimate()`?
If not, can you please give the surrounding xml and a screenshot?

**Comment by TWiStErRob** [comment]
Do you mess with layout params in code?

**Comment by GauravP123** [comment]
no i am not

**Comment by TWiStErRob** [comment]
I was thinking your placeholder size may be the cause, see [#363](https://github.com/bumptech/glide/%69ssues/363).

**Comment by TWiStErRob** [comment]
So, can you please share a screenshot and more XML?

**Comment by GauravP123** [comment]
i am using same image as a placeholder for now

**Comment by GauravP123** [comment]
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
  
  >

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="10dp"
        android:background="@color/denim_blue">

        <ImageView
            android:id="@+id/imageIcon"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
 </RelativeLayout>
</RelativeLayout>`



![screen](https://cloud.githubusercontent.com/assets/16499701/17397286/efbf9e52-5a54-11e6-82f6-188ab2e7c17e.png)


  
so image should take full till blue color is visible see right and left side

**Comment by TWiStErRob** [comment]
Hmm, interesting, because of wrap it should be taller. Are you sure the Bitmap is not padded? Try to give a different background to relative layout and image view to verify that the ImageView is indeed matching width (tip: use alpha `background="#66FF0000"`). It also looks like a viewpager in a list, does the viewpager have (max) height?

**Comment by TWiStErRob** [comment]
What's the orientation of the grid? What's the span count?
From the looks it's a horizontal with 2 rows, which means that each row is half the screen height, leaving no space for the full square to fill screen width. For this to work the screen would have to be 2:1 (18:9) ratio, most are 16:9. This 2-row constraint is harder than the wrap content.

**Comment by GauravP123** [comment]
Grid is vertical with 2 rows

**Comment by TWiStErRob** [comment]
I'm lost then, what is this on the screenshot?
![image](https://cloud.githubusercontent.com/assets/2906988/17431912/8910d38a-5afc-11e6-8b99-00a5a51e6ea6.png)

**Comment by GauravP123** [comment]
dont worry i have taken screenshot and crop it

**Comment by TWiStErRob** [comment]
Based what you've shared so fair I don't see any issues and it should "just work". I'm trying to help you out, but without enough information it's really hard. I hope you understand that layout of Android views depends on the parent hierarchy and potentially even cousins in the hierarchy, so showing only part of what's there and giving half-information in sentence fragments won't help here; I can only guess.

What do you mean exactly when "Grid is vertical with 2 rows"? I can read it in two ways:
 * `new GridLayoutManager(context, VERTICAL, 2, false)`  
in which case it's "Grid is vertical with 2 columns"
 * new GridLayoutManager(context, VERTICAL, 1, false)` + an adapter with 2 items in it  
in which case it's "Grid is single column, vertical with 2 items"

Based on the partial screenshot it looks like `new GridLayoutManager(context, HORIZONTAL, 2, false)`. Please re-describe from scratch how your layout that has this problem is structured, potentially with code+xml that sets up any viewpager, recyclerview, layoutmanager, including their adapter's binding methods.
