### ISSUE TITLE
Preview the image first then allow user to save without downloading again

### ISSUE THREAD

**Issue by zeroarst** [bumptech/glide#1383]
**Glide Version**: 3.7.0

**Integration libraries**: no

**Device/Android Version**: 
Android Virtual Device and Samsung S7 edge 6.0

**Issue details / Repro steps / Use case background**: 
I have a view where the app shows the user image to preview, then there is a button in the preview screen. User can click the button to save that image in the device. Images are loaded from URLs. 

I know there are already many topics regarding this being discussed but I still cannot get it. #459 #509 #828 ..etc

Based on some solutions from those topics, I came up with these code but I am not sure if I am doing it correctly. The main point is to load the original size of the image to preview therefore no longer requires user to download again.

This is the code to show the preview image.
```java
Glide.with(MyFragment.this).load(mImgUrl).diskCacheStrategy(DiskCacheStrategy.ALL).into(mPrviewImageView);
```

This is the code to save the image.
```java
new AsyncTask<Void, Void, Exception>() {
    @Override
    protected Exception doInBackground(Void... params) {
        try {
            File file = Glide.with(MyFragment.this)
                             .using(new NetworkDisablingLoader<String>())
                             .load(mImgUrl)
                             .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                             .get();
            FileUtils.copyFile(file, new File(AppConfig.APP_DIR_IMG_BG + "/" + SystemClock.currentThreadTimeMillis()));
        } catch (InterruptedException | ExecutionException | IOException e) {
            Log.e(TAG, "save image file error. url: " + mImgUrl, e);
            return e;
        }
        return null;
    }

    @Override
    protected void onPostExecute(Exception e) {
        if (e == null)
            Toast.makeText(getActivity(), "Saved", Toast.LENGTH_SHORT).show();
        else
            Toast.makeText(getActivity(), "Error occurred", Toast.LENGTH_SHORT).show();
        }
}.execute();
```
My question is: Does Glide actually returns the cache file with downloadOnly method? I was trying to fine some callback methods to validate if the image is from cache but I was not able to.

**Comment by TWiStErRob** [comment]
> Does Glide actually returns the cache file with downloadOnly method?

Yes, it defaults to SOURCE cache. Also since you're using `NetworkDisablingLoader` you can be sure no traffic happens.

---

Worth noting that `.downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)` doesn't mean anything in your case, but keep it that way. Read the JavaDoc of `FutureTarget` to see how to use it properly (need to clear it). (`into(w,h)` works similar to `downloadOnly` in this regard.)

---

Since you're dealing with the same image many times, I suggest the following:
 * for a thumbnail in an adapter use `.diskCacheStrategy(ALL)`  
fast reload when scrolling and prevents duplicate download in the future
 * for a single-screen preview, use ``.diskCacheStrategy(SOURCE)`  
no need to cache the resized image, it's a waste of space and probably doesn't make the display faster
 * for the background `downloadOnly` use ``.diskCacheStrategy(SOURCE)`  
 automatically done

>  I was trying to fine some callback methods to validate if the image is from cache but I was not able to.

See https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling for debugging tips.

---

Apart from changing `ALL` to `SOURCE` for the preview load, you got it right. Does it work?

**Comment by zeroarst** [comment]
Thanks your suggestion. Will be using `.diskCacheStrategy(SOURCE)` as it suits my case. (Only provide a single screen to preview)
