### ISSUE TITLE
Manual clear when loading with application context

### ISSUE THREAD

**Issue by BobOtike** [bumptech/glide#1401]
@TWiStErRob I have already read this [post](http://stackoverflow.com/a/32887693/5146776) of you on SO (which for some reason I could not comment on, otherwise I wouldn't have opened this issue because it seems a trivial question). The one thing I'm wondering is this:

When I use the application context for a load and I want to cancel it, I have to do so manually as you stated. Does the same apply for resource re-use? I mean, if my view that was loaded into with the application context gets nulled out, does that also automatically allow for bitmap recycling or do I have to manually clear the view before forgetting it in order for Glide ro re-use the resources? I'm not too familiar with how all of that bitmap magic works and confused whether just nulling the view without clearing it creates a memory leak.

**Comment by TWiStErRob** [comment]
I think that leaks. If the request is not cleared (happens when clearing the target/view), then as far as Glide is concerned the resource is still in use. This means that for app-context loads no re-use will be done until Glide knows that they're not used any more. The resource (Bitmap) won't be put into the pool until Glide knows it's safe to re-use it.

**Comment by BobOtike** [comment]
Thanks for clarifying, I'll just make sure to clear all app-context loads myself so that I don't accidentally create a leak.
