### ISSUE TITLE
Grab image from cache without url after comparing with expected size in bytes

### ISSUE THREAD

**Issue by thieu75** [bumptech/glide#1416]
Hi guys,

I have developed an app on iOS and created a fine management of photo files.
I don't find any way to reproduce this with Glide. You have a better knowledge for sure. What do you think?

**What I'd like**
- My app grab photos from a Firebase/Google Cloud server

First time reading a photo:
- In order to grab those photo I request the server the url for the download [First call]
- I download the photo and store it in the cache
- display image

Second time reading the same photo:
- First the download url from the server may have change (?session=...) so when I have previously cached the image, the key need to be 'uri' independent.
- I ask the cache if the image for the known key exist (key that i compose without the uri)
- if the image exist, I compare the data byte length to an expected value stored with my object on the server
- if the size is the same, I display the image 
- else, I ask GoogleCloud to give me the download URL, download and store in cache then display

My problems:
- be sure that I can grab a stored image from the cache thanks to a known key without URI
- be able to evaluate the download size in byte of the stored image in the cache.

This use case allow me to:
- don't request the download URL if I have already the image in cache. 
- update the image cache if I have updated the image on the server (same name)

From the documentation, I don't see any way to grab the image from cache without the uri. Any ideas?
Thanks

**Comment by TWiStErRob** [comment]
The image cache key is the model + signature. You cannot replace a cashed item, nor manually delete it. The LRU algorithm will do that for you.

As far as I understand you have 3 things you're asking for:
* Custom model loader (Google it, or https://github.com/bumptech/glide/issues/556#issuecomment-126535794 for an untested sample for Firebase)  
The fetcher's getId is part of the cache key, and is usually a simple, but uique representation of the model.
* Cache key from part of the url (#501)
* Mixin size into cache key (simple with `.signature`)

Due to the complexity of mixing all this (most notably the double fetch and size check), I think you may be better off skipping Glide's cache and implementing your own: something based in Teovald's sample in #1033.

**Comment by thieu75** [comment]
Hi @TWiStErRob 
Thanks for all those input. To my understanding of your feedbacks, it is possible for me to:
- establish my own key so I can avoid a network fetch for the download url
- I'll have to create my Custom loader and override the getId part to put a key that's fit my needs (basically a UDID). This custom loader will allow me to grab from cache thanks to the key without needing a uri
- Gonna scratch my head a lot :-)

I'm gonna give it a try. Do you know if there is a way to calculate the size of the file store in the cache once this one is identified ?

The algorithm seems simple:
- does file is in cache?
> Yes : Does the size is right? YES: display, NO: request download url and display (cache will receive it also)
> No : request download url and display (cache will receive it also)

2nd possibility, I can create my own cache system. Which is a challenge in it :)
Thanks for you advise,
Mat

**Comment by TWiStErRob** [comment]
Teovald showed that if you disabled Glide cache (NONE), then you can still decide in the fetcher if you want to serve from disk or make network requests. Didn't you already implement this in IOS? You would just need a direct port of that, which then you can integrate wih Glide.

If you didn't need the size check the custom loader would be enough. The problems are:
* There's no direct access to cache from fetcher
* You need the size available at the time before the fetcher has a chance to contact the cloud
 This is to have it in cache key. If you have your own caching solution then you can easily read the size of the file in getId. But it doesn't matter because it won't be used. I'll try to think about this more, it's confusing even for me.

Actually it seems to me you already know at load time the following: <cloud service, image path within service (uuid you mentioned), expected size> and that is your model, right? I assume you have a list of these the user can scroll. Do you have the expected size available at first load as well? Is that number always correct the first time? Is your expected size always the freshest in sync with the cloud storages? If so, or you can make it so: using signature + a normal custom fetcher is enough for your use case, and you can utilise the full Glide cache.

**Comment by thieu75** [comment]
Hi @TWiStErRob 
Thanks again for your support.

Here is the answers to your questions:
- Do I know the expected size ? 
Yes, I grab a list of object from the server. One of the property of those objects is the expected size. So before even requesting the display of the image, my model contains the expected size.

- Maybe you are speaking about the size of the list of object to display!
Yes and No, depending on the method I use to grab those objects. I can have all objects in one call or the callbacks will be triggered each time. In the end I can have a list of all the objects. But this is only at this moment that I will new the size

- freshesness
Yes always in sync with server

Thanks again for your feedbacks. To be honest my use case doesn't seem to me so unique! I was thinking is wasn't so complicated to be aligned with the iOS version!

**Comment by TWiStErRob** [comment]
> To be honest my use case doesn't seem to me so unique!

It's possible, sometimes I over-assume things.

---

> Maybe you are speaking about the size of the list of object to display!

Good point, which is it? I was thinking about byte size so far, but now I'm not sure. Is it w×h or content-length?

---

In any case based on the latest info I got from you can use the method described in #634/#556 to create your custom loader/fetcher. You don't have to worry about stripping the session-id, because that's hidden inside your fetcher. The cache key from the fetcher will only contain the cloud/id. Oh, dang, I just noticed, I didn't escape a `<` so it hid some text:

> Actually it seems to me you already know at load time the following: and that is your model, right?

was meant to contain (corrected above)

> &lt;cloud service, image path within service (uuid you mentioned), expected size&gt;

So in addition to registering a model loader factory for your custom model, you should also add a `.signature(...)` that has the size. It doesn't actually matter what your expected size is (w/h/bytes), because it'll always match, and if it doesn't it'll force a cache miss and a download.

Your algorithm

> does file is in cache? > Yes : Does the size is right? YES: display, NO: request download url and display (cache will receive it also) > No : request download url and display (cache will receive it also)

can be rephrased into Glide terminology as:

Does the cache have the UUID (custom model returned via `fetcher.getId`) with a signature containing the expected size? YES: load and display, NO: call fetcher, request Uri, request stream, fill cache, load and display.

**Comment by thieu75** [comment]
hey @TWiStErRob 
I'm starting to see a clear path thanks to your support :)
If I may, I will update any progress/code here in order to share with people with the same concerns!

PS: for the size, it was about bytes. Any simple way in mind to grab the size of the download file before it is load in memory as uncompressed bitmap?
Thanks again Rob!

**Comment by TWiStErRob** [comment]
> Any simple way in mind to grab the size of the download file before it is load in memory as uncompressed bitmap?

Not simple, fairly hard. That's why I asked if you have the size ready and fresh all the time. It's hard to pull it from the request, but you can just tell Glide I want to use "this size" and the cache should resolve whichever is found (or missed).

Take a look around `.downloadOnly` (and `FutureTarget`'s javadoc), which may allow you to get the cached File object (and hence its size) if you really need it.

> If I may, I will update any progress/code here in order to share

Fine by me, there are a lot of long code-only comments around here.
