### ISSUE TITLE
How does you know if the integration library is working?

### ISSUE THREAD

**Issue by JeffreyCA** [bumptech/glide#1425]
Are there any ways to tell from cache files or other methods if the integration library I installed is working?

**Comment by TWiStErRob** [comment]
Depends in which one. 
If the lib is just some helpers, like recyclerview, then you'll get a compile error.

Most others have a `GlideModule`, which will be loaded. If load fails Glide throws. You can check the merged manifest, I think it's `aapt dump badging file.apk`.

If you don't trust that:
I think OkHttp adds a header to each request, so you could snoop that, or check on server side.
If it's your own, then add a log line.
Otherwise, you could debug `Glide.get`.

**Comment by JeffreyCA** [comment]
Alright, thanks for the information
