### ISSUE TITLE
MediaStoreThumbFetcher is too restrictive, can't be extended easily

### ISSUE THREAD

**Issue by sandy-8925** [bumptech/glide#1435]
**Glide Version**: 3.7.0

**Integration libraries**: -

**Device/Android Version**: Nexus 6

**Issue details / Repro steps / Use case background**: 
We need to to subclass MediaStoreThumbFetcher in order to fetch thumbnails for video (we need to override getId()), however MediaStoreThumbFetcher code will fail if the width/height we specify exceeds arbitrary limits specified in the class.

MediaStoreThumbFetcher has a static inner class ThumbnailStreamOpenerFactory, which is used to create a ThumbnailStreamOpener instance, however it will return null if the width and height you specify exceed some arbitrary size specified in MediaStoreThumbFetcher - these sizes are private and thus hidden from subclasses.

Please allow subclasses of MediaStoreThumbFetcher to override these sizes.

**Comment by TWiStErRob** [comment]
It's not arbitrary, check the docs of `android.provider.MediaStore.Images.Thumbnails` and `android.provider.MediaStore.Video.Thumbnails`.

That class was probably designed in a way that there's no point in getting a small thumbnail if the requested size is bigger than that, because it'll upscale.

As for extending, yes it may be too encapsulated, however you can work around most of the limitations. Depending on your needs you can either lie in the constructor (*composition over inheritance*) and pass that "arbitrary size" in case you always want to fetch the thumb; or you can capture the value in your extended (or wrapping fetcher's) constructor and override loadData to only call `super` in certain cases. You can probably even trick it from outside where you initiate the load via `.override(w,h)`.

If you really want to replace the guts of it, then you can put your own fetcher in the same package and use the default visible ctor, classes and interfaces to do that.

If the above is not satisfactory enough you can always open up the class and submit a PR.

**Comment by sandy-8925** [comment]
Thank you for replying! I've also observed that sometimes, MediaStoreThumbFetcher fails to fetch video thumbnails. However, if you call MediaStore.Video.Thumbnails.getThumbnail(), MediaStoreThumbFetcher can fetch the thumbnail for the same video afterwards.

**Comment by TWiStErRob** [comment]
Isn't it possible that `MediaStoreThumbFetcher` would fetch it the second time too? As far as I know sometimes the thumbs are generated on the fly, and Glide may time out?, I'm not sure. Do you know if there's any difference between your call and `VideoThumbnailQuery`?

**Comment by sandy-8925** [comment]
Earlier, we were using MediaStore.Video.Thumbnails.getThumbnail(context.getContentResolver(), videoId, MediaStore.Video.Thumbnails.MINI_KIND, options) to directly fetch the Bitmap and that always worked. MediaStoreThumbFetcher seems to work only if the thumbnail is already generated.

**Comment by TWiStErRob** [comment]
That's a fully different path than using a contentResolver directly. You can always write a simple fetcher to wrap your `getThumbnail` call, you don't have to rely on Glide's implementation.

**Comment by sandy-8925** [comment]
Thank you, I was planning to do that, but `MediaStore.Video.Thumbnails.getThumbnail()` returns a `Bitmap`, and it doesn't look like I can create a `DataFetcher<Bitmap>` easily - atleast, there's no inbuilt `ResourceDecoder<Bitmap, Bitmap>` and even if I created one, none of the `BitmapRequestBuilder` methods accept `ResourceDecoder<Bitmap, Bitmap>`.

**Comment by TWiStErRob** [comment]
Ah, true that; sorry I forgot about it. You can try something like this https://gist.github.com/TWiStErRob/0b0b083225f2869b5cb1 from #122, except `.from(Uri.class)` and your custom Uri -> Bitmap loader. If that doesn't work you can always compress the thumb into a `ByteArrayOutputStream` and return that (or use `Piped*Stream`), though it's not the nicest approach. You can use `.transform(new CenterCrop())` if needed.

**Comment by sandy-8925** [comment]
Ok, thanks for your help!
