### ISSUE TITLE
Image is not centered with .fitCenter()

### ISSUE THREAD

**Issue by dazhiyu** [bumptech/glide#1444]
xiaomi5---android6.0
compile 'com.github.bumptech.glide:glide:3.7.0'

加载方法：
```java
Glide
                    .with(context)
                    .load(url)
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .placeholder(R.drawable.loading)
                    .error(R.drawable.loading)
                    .crossFade()
                    .fitCenter()
                    .into(imageView);
```

![device-2016-09-01-192040](https://cloud.githubusercontent.com/assets/19526348/18165851/3f3c84c8-707a-11e6-9a26-4fcf4e1b3acf.png)

**Comment by TWiStErRob** [comment]
What is the XML of that ImageView?

Also try: `.dontAnimate()` and double-check the original image at the url that it doesn't have that gray area.

**Comment by dazhiyu** [comment]
<ImageView
            android:id="@+id/iv_recommend_pic_left"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_loading"
            android:scaleType="center" />

**Comment by dazhiyu** [comment]
在.java中
 RelativeLayout.LayoutParams rlp = new RelativeLayout.LayoutParams(width, height);
改过大小

**Comment by TWiStErRob** [comment]
wrap-wrap will signal Glide to load a screen-sized bitmap. It looks like you're using a grid layout, in that case you can use match-match as well which will load the correct sized image, so I suggest this:
```java
<ImageView
            android:id="@+id/iv_recommend_pic_left"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            tools:src="@drawable/ic_loading"
            android:scaleType="fitCenter" />
```
and in code:
```java
// RelativeLayout.LayoutParams rlp = new RelativeLayout.LayoutParams(width, height); // not needed match determines automatically
// .fitCenter() // read from XML
```

If the list is a linear layout manager then you should refactor your xml to [use `layout_weight="0.5"`](http://stackoverflow.com/a/4517358/253468) or similar instead of calculating half-screen width in code, again this enables you to use `match_parent` which is more compatible with Glide.

(Tip: use `tools:src` instead of `android:src` to prevent unnecessary loading of `ic_loading` at runtime in production)

**Comment by dazhiyu** [comment]
我加入.dontAnimate()后的确没有这个问题了，但这样直接显示图片很难看

**Comment by TWiStErRob** [comment]
The placeholder and the image probably have different aspects (#363). Try to use a placeholder that matches that  squarish aspect.
