### ISSUE TITLE
Images load with extra padding randomly

### ISSUE THREAD

**Issue by Andrew-Quebe** [bumptech/glide#1458]
**Glide Version**: 3.7.0

**Device/Android Version**: Nexus 6P, Android 7 Nougat

**Issue details / Repro steps / Use case background**: I'm using Glide to load images into a recycler view. The image URL's are loaded through JSON. Basically, for some reason, when the images are loading, or first loaded (hard to tell really), there is extra padding above and below the images. It appears to randomly happen on top or bottom...just depends. When scrolling through the recycler view, the images load (and I guess cache too?) and sometimes appear correctly. However, most of the time, they don't. 

It seems once everything actually loads, the padding issues go away and the images appear in the cards as they're supposed to.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
// WallpaperAdapter.java
import android.annotation.SuppressLint;
import android.content.Context;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;

import com.bumptech.glide.Glide;

import java.util.Collections;
import java.util.List;

class WallpaperAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

    private Context context;
    private LayoutInflater inflater;
    private List<Wallpaper> data = Collections.emptyList();

    WallpaperAdapter(Context context, List<Wallpaper> data) {
        this.context = context;
        inflater = LayoutInflater.from(context);
        this.data = data;
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = inflater.inflate(R.layout.wallpaper_container, parent, false);
        return new MyHolder(view);
    }

    @SuppressLint("SetTextI18n")
    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {

        MyHolder myHolder = (MyHolder) holder;
        Wallpaper current = data.get(position);

        // ----------------------------------------------
        // ----------------- GLIDE CODE -----------------
        // ----------------------------------------------
        Glide.with(context).load("http://userdata.amqtech.com/andrew/" + current.wallpaperURL)
                .dontAnimate()
                .into(myHolder.ivWallpaperSRC);
        // NOTE: I tried using a placeholder image, and that led to even more glitches. 
        // I also tried using crossfade() for the anims, but the bug was still there...just...more animated ;)
    }

    @Override
    public int getItemCount() {
        return data.size();
    }
    
    private class MyHolder extends RecyclerView.ViewHolder {

        //TextView tvWallpaperName;
        ImageView ivWallpaperSRC;

        MyHolder(View itemView) {
            super(itemView);
            //tvWallpaperName = (TextView) itemView.findViewById(R.id.wallpaperName);
            ivWallpaperSRC = (ImageView) itemView.findViewById(R.id.ivSRC);
        }
    }
}
```

```java
// MainActivity.java
import android.app.ProgressDialog;
import android.os.AsyncTask;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.Toolbar;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    public static final int CONNECTION_TIMEOUT = 10000;
    public static final int READ_TIMEOUT = 15000;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        toolbar.setTitle("Example");

        new AsyncFetch().execute();
    }

    private class AsyncFetch extends AsyncTask<String, String, String> {
        ProgressDialog pdLoading = new ProgressDialog(MainActivity.this);
        HttpURLConnection conn;
        URL url = null;

        @Override
        protected void onPreExecute() {
            super.onPreExecute();

            pdLoading.setMessage("\tLoading...");
            pdLoading.setCancelable(false);
            pdLoading.show();
        }

        @Override
        protected String doInBackground(String... params) {
            try {
                url = new URL("http://www.amqtech.com/java_dev/testing.json");
            } catch (MalformedURLException e) {
                e.printStackTrace();
                return e.toString();
            }
            try {
                conn = (HttpURLConnection) url.openConnection();
                conn.setReadTimeout(READ_TIMEOUT);
                conn.setConnectTimeout(CONNECTION_TIMEOUT);
                conn.setRequestMethod("GET");
                conn.setDoOutput(true);
            } catch (IOException e1) {
                e1.printStackTrace();
                return e1.toString();
            }

            try {
                int response_code = conn.getResponseCode();

                if (response_code == HttpURLConnection.HTTP_OK) {

                    InputStream input = conn.getInputStream();
                    BufferedReader reader = new BufferedReader(new InputStreamReader(input));
                    StringBuilder result = new StringBuilder();
                    String line;

                    while ((line = reader.readLine()) != null) {
                        result.append(line);
                    }
                    return (result.toString());
                } else {
                    return ("unsuccessful");
                }
            } catch (IOException e) {
                e.printStackTrace();
                return e.toString();
            } finally {
                conn.disconnect();
            }
        }

        @Override
        protected void onPostExecute(String result) {
            pdLoading.dismiss();
            List<Wallpaper> dataList = new ArrayList<>();
            try {
                JSONArray jArray = new JSONArray(result);

                for (int i = 0; i < jArray.length(); i++) {
                    JSONObject json_data = jArray.getJSONObject(i);
                    Wallpaper wpData = new Wallpaper();
                    wpData.wallpaperName = json_data.getString("name");
                    wpData.wallpaperURL = json_data.getString("url");
                    dataList.add(wpData);
                }

                RecyclerView recycler = (RecyclerView) findViewById(R.id.wallpaperList);

                WallpaperAdapter adapter = new WallpaperAdapter(MainActivity.this, dataList);
                recycler.setAdapter(adapter);
                recycler.setLayoutManager(new GridLayoutManager(MainActivity.this, 2, 1, false));

            } catch (JSONException e) {
                Toast.makeText(MainActivity.this, e.toString(), Toast.LENGTH_LONG).show();
            }
        }

    }
}
```

**Layout XML**:
```xml
<!-- Main Activity Layout -->
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"
        tools:targetApi="lollipop" />

    <FrameLayout
        android:id="@+id/frame_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/toolbar">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/wallpaperList"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_margin="4dp" />
    </FrameLayout>
</RelativeLayout>
```

```xml
<!-- Image Container Layout -->
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="4dp"
    app:cardCornerRadius="2dp">

    <ImageView
        android:id="@+id/ivSRC"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:scaleType="fitCenter"
        android:contentDescription="@string/acc_content_desc"/>

</android.support.v7.widget.CardView>
```

**Stack trace / LogCat**:
```
No error messages...just glitches on the main UI. See screenshots below.
```

**Screenshots & Video:**

| Info  | Screenshot/Video |
| ------------- | ------------- |
| Screenshot when app is first opened (no scrolling or anything yet)  | http://imgur.com/a/1HVKM |
| Screenshot with layout bounds on (no scrolling still)  | http://imgur.com/a/RPFKl |
| Video showing bug (layout bounds disabled)  | https://youtu.be/_B3EGU-EXD4 |
| Another video showing the bug with bounds enabled  | https://youtu.be/jpYipnNx2Oc |
| Debug APK download | http://goo.gl/FOwbjJ |

**Comment by TWiStErRob** [comment]
*Oh, man, I wish every question was like this!*

**Few quick things**:
 * ImageView having wrap-wrap is not good for Glide (it loads images as screen size, which is too big considering you have two colums -> 4x memory waste). Use match-match instead.
 * `GridLayoutManager` should give you a uniform Grid and I think it gets confused by wrapping the items (the items have no content right after binding because the loads are async).
 * I think you should consider using `StaggeredGridLayoutManager`, because your images can be different sizes (I guess, they're wallpapers and wallpapers come in different sizes/aspects).

**Details**:
I think the main problem is the wrap-wrap. If you look at the size of the cards with gaps you can see that they're as tall as the screen, this is likely because Glide created a screen-sized bitmap, and so when the ImageView measured itself after setting that, it said: "I want to be screen size tall", but Grid sayeth "No can do, I need to put two of y'all side-by-side", so you ended up with `half-screen-width x screen-height` items. Later when the items are recycled there's some measure state left over from the previous load or the sync load makes it so, that the views are measured correctly. By changing to `match-match` you'll tell Glide to wait until the grid layout figures out the constraints, It'll likely give the cards `half-screen-width x 0` size, which is not good, because it'll make the adapter inflate a lot of viewholders and bind them all at once (exactly the reason we're using a recycler). So a more close approximation of what you're trying to achieve is probably `match-wrap`, but even then you'll probably end up with the same problem. So the best solution is to constrain the height of the items, I suggest [percent layout](https://github.com/bumptech/glide/issues/864#issuecomment-193883234). This will help Glide and the Grid to figure out the correct size. Your item layout should look the same (have the same bounds) with or without images bound to them for Glide to work best.

**Comment by Andrew-Quebe** [comment]
First off, thanks for the knowledgeable info! Second, I tried changing the size to `match-match` as you said, but that ends up making nothing show in the RV. Interestingly enough, it also throws an error in the logcat.

**Screenshot:**
http://imgur.com/a/6YjHq
**Logcat error:**
`09-08 06:03:47.654 24904-24904/? E/RecyclerView: No adapter attached; skipping layout`

I also tried switching to a staggered layout manager (that's actually what I used in the beginning), but, with `match-match` on the image view, nothing shows up at all.

**Adjusted Code:**
```xml
<!-- Container Layout -->
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="4dp"
    app:cardCornerRadius="2dp">

    <ImageView
        android:id="@+id/ivSRC"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="fitCenter"
        android:contentDescription="@string/acc_content_desc"/>

</android.support.v7.widget.CardView>
```

```java
// Staggered layout change
...
RecyclerView recycler = (RecyclerView) findViewById(R.id.wallpaperList);
WallpaperAdapter adapter = new WallpaperAdapter(MainActivity.this, dataList);
recycler.setAdapter(adapter);
recycler.setLayoutManager(new StaggeredGridLayoutManager(2, 1));
...
```

**Questions:**
1. Did you mean for me to use match_parent on the cardview block as well? 

2. Would using a cardview versus just a plain imageview have any effect on the matter?

**Comment by TWiStErRob** [comment]
> E/RecyclerView: No adapter attached; skipping layout

Don't know about this. Just changing the XML shouldn't cause an issue like that. Maybe you modified something else too!?

> Did you mean for me to use match_parent on the cardview block as well?

No, Glide reads the layout params of the ImageView only, and if it sees match_parent it waits for a later when the view is laid out and ready to draw. This is why "Your item layout should look the same (have the same bounds) with or without images bound to them for Glide to work best." is really important.

> Would using a cardview versus just a plain imageview have any effect on the matter?

Probably not. because it doesn't affect the inside image view, other than constraining it's width even more to roughly `screenWidth/2 - 2*4dp - 2*2dp`.

> The best solution is to constrain the height of the items, I suggest percent layout.

I said this because I don't remember ever having achieved a UI where the images dictate the size, always the views dictate the image size. The only way I was able to get staggered grid working is via this hack: https://github.com/TWiStErRob/glide-support/commit/a1572179430e837d8410cc9f915d7c4737e584dd#diff-9b721ee4cbe0e6ed14a1f208ea8192d4R62 (this is linked from https://github.com/bumptech/glide/issues/864#issuecomment-193883234).

If you're not happy with the aspect ratio constraint, you can try another workaround: figure out how wide the ImageView can be and use that in `.override(width, Target.SIZE_ORIGINAL)`, this way the XML can stay wrap, but you're helping Glide to know how big an image is required to fill the view.

---

Hmm another idea: reset everything to original, except:
```xml
  <ImageView
        android:id="@+id/ivSRC"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="100dp"
        android:scaleType="fitCenter"
        android:contentDescription="@string/acc_content_desc" />
```
This may prevent the issue with 0-height views, trigger Glide to wait for layout (because of width), and render the items as talls as the images.

**Comment by TWiStErRob** [comment]
Btw, staggered grid and Glide don't like each other, because when a grid item is reused the heights are there from the previous layout (containing another image) and this makes Glide believe that the size is constrained to that. This is why sometimes I suggest an `iv.layout(0,0,0,0)` just before the Glide load.

**Comment by Andrew-Quebe** [comment]
Alright, well at this point (and about 4 hours of testing), I still can't get it to work. I've moved everything into a Fragment as that is the real use case. I've tried different combinations of wrap-wrap and match-match and wrap-match. Nothing works!! I may result to using a different Image loader...I have an old favorite still, but it's a more complex set up than Glide. Which is why I wanted to get Glide to work, but I guess not.

Thanks for your help.

**Comment by Andrew-Quebe** [comment]
Update: I got it to work by changing the layout container code to this...

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <android.support.v7.widget.CardView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="4dp"
        app:cardCornerRadius="2dp">

        <ImageView
            android:id="@+id/ivSRC"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:contentDescription="@string/acc_content_desc"
            android:adjustViewBounds="true"
            android:scaleType="fitCenter" />

    </android.support.v7.widget.CardView>
</FrameLayout>
```

Note the adjustViewBounds and wrap-wrap on the card as well as the imageview. Now everything renders properly...except in landscape mode. But that's my fault! :P

**Comment by umesh0492** [comment]
Hi @TWiStErRob, having same issue on marshmallow and throughout the application regarding loading image into imageview, whether from server or local file. It is always loading image with around 20% whitespace in its surrounding. Happens only at first load and afterward its load perfect as expected (if it's fragment or activity is in memory). But in recyclerview, if it is recycled sometimes it show as expected and sometimes it doesn't. Tried with putting wrap_content, match_parent, constant params in xml on imageview with or without adjustViewBounds. By calling clear, by calling override. I am using bitmap transformation throughout.

Have tried solution in discussed in different-different issues. Need help to fix it.

Glide.with (mActivity)
                        .load (Uri.fromFile (new File (mainApplication.pm.getPrefProfilePicUri ())))
                        .diskCacheStrategy(DiskCacheStrategy.ALL)
                        .fitCenter ()
                        .bitmapTransform (new CircleTransform (mainApplication))
                        .error (R.drawable.ic_user)
                        .into (ivProfileImage);

**Comment by chetanrm** [comment]
I can't load the image
