### ISSUE TITLE
Very pixelate images loaded glide in some devices

### ISSUE THREAD

**Issue by chihau** [bumptech/glide#1463]
I am trying to load images with glide but in some devices (like nexus 7 2014) the images are shown very pixelated 

Images loaded without glide
![nexus7_sin_glade](https://cloud.githubusercontent.com/assets/352200/18397866/7e03ed8c-76a0-11e6-8c73-ed3bdf2a161d.png)

Images loaded with glide 3.7
![nexus7_con_glide](https://cloud.githubusercontent.com/assets/352200/18397882/96e26040-76a0-11e6-9551-8765700f2f04.png)

In other devices like Nexus S, Nexus 4 and Nexus 5x the difference is minimal

**Comment by TWiStErRob** [comment]
Glide reads the minimum necessary Bitmap size from the ImageView's laid out size. On a Nexus 7 TVDPI you may end up with a smaller `px` size than the other devices. Is it really visible on the device? (not on a screenshot, because the screenshot is viewed on a high-resolution computer screen)

For test try to add `.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)`.

Add `.listener(new LoggingListener())` from https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/utils/LoggingListener.java it will log you all the numbers Glide is working with, so you can see the root cause of the different behavior on different devices.

**Comment by chihau** [comment]
It's works! thank you!

**Comment by TWiStErRob** [comment]
I urge you not to use that `override` in production, it disables what Glide is for and you might get OOMs on low-end devices, and it uses much move power than necessary. Try to get to the bottom of why it's loading a small resolution.

Keep in mind that older devices don't need 4k images to look good. Remember how it was (if you're old enough) with 800x600 PC wallpapers, they were just fine for those monitors. Of course now they're laughable, but that doesn't mean you need fullHD images for old screens.

If you want you can try to load the images into a custom target, extending for example `GlideBitmapDrawableTarget`. If you override `getSize` and wrap and delegate the callback before passing it to super, you can for example multiply the result Glide receives through the callback (e.g. 1.5x) for low-end while keeping the results for high-end.
