### ISSUE TITLE
Empty Or Static ImageView

### ISSUE THREAD

**Issue by AdamSHurwitz** [bumptech/glide#1470]
**Glide Version**: 3.7

**Integration libraries**: No

**Device/Android Version**: Nexus 5X 6.0.1

**Issue details / Repro steps / Use case background**: 

**Issue:** The following methods outlined in this [Glide tutorial](https://futurestud.io/tutorials/glide-displaying-gifs-and-videos#comment-2888799837) for displaying Gifs resulted in an empty ImageView or static image.

**Intended Behavior:** Animated Gif appearing in ImageView

**Actual Behavior:** Static or Empty ImageView

**Solution:** Using a GlideDrawableImageViewTarget

What ended up working was adding a GlideDrawableImageViewTarget described in this [StackOverflow](http://stackoverflow.com/questions/31082330/show-gif-file-with-glide-image-loading-and-caching-library). 

GlideDrawableImageViewTarget:

```
ImageView imageView = (ImageView) findViewById(R.id.imageView);
GlideDrawableImageViewTarget imageViewTarget = new GlideDrawableImageViewTarget(imageView);
Glide.with(this).load(R.raw.sample_gif).into(imageViewTarget);
```

**Did not work details:**

//loads static image
```
Glide.with(this)
.load(url)
.asGif()
.into(staticGif);
```

//loads static image

```
Glide.with(this)
.load(url)
.placeholder(R.drawable.ic_error_black_48px)
.error(R.drawable.ic_error_black_48px)
.into(staticGif);

```
//loads error
```
Glide.with(this)
.load(url)
.asGif()
.error(R.drawable.ic_error_black_48px)
.into(staticGif);
```

//loads static image
Glide.with(this)
```
.load(url)
.asBitmap()
.into(staticGif);
}
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

**Layout XML**:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:tools="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.carpe.jify.MainActivity"
    android:orientation="vertical"
    android:gravity="top|center">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hola jify!" />

    <ImageView
        android:id="@+id/static_gif"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

</LinearLayout>

```

**Comment by TWiStErRob** [comment]
Only `.asBitmap()` should load still images. Others should be working. Add a listener and see what exception triggers the error drawable. When the ImageView is empty it probably means that you have a placeholder (long load) or error (failed load) drawable shown to you, but since you didn't provide it, Glide shows you null.

Now, I have a feeling your GIFs are huge and it just takes a lot of time to process them with default settings. Specifying the target explicitly has the same effect as `.dontTransform()`, which speeds up loading. You specified wrap-wrap so the target size is 2k or 4k resolution of the device with fitCenter implied from ImageView.

You can see how all these add up to slow and probably OOM loading. The only thing you really need is `.diskCacheStrategy(SOURCE)` so Glide doesn't try to decode the whole GIF into memory and re-encode it. This helps the OOMs, but you still need to refactor your layout to include at least one fixed dimension or a `match_parent`.

**Comment by AdamSHurwitz** [comment]
Thanks - The above worked for me in all iterations of the methods above!

**Comment by TWiStErRob** [comment]
It may work, but it's really resource intensive. GIFs and SOURCE cache go hand in hand, and using `match_parent` just makes your memory consumption much better.
