### ISSUE TITLE
Simple Targets not saving image in correct orientation

### ISSUE THREAD

**Issue by gabbimark** [bumptech/glide#1482]
Hi, we had issue on android where when taking pictures and saving the image, and sending it to our server, image is flipped on android, ios and web applications that we use to view the image. So we tried simple target with glide in hopes that when saving the image locally before sending to server, glide would work its magic and image would be in correct orienation. This does not happen, Here is what we did:

1. Take the picture and save the image in temporary location. 
2. Pass the image uri into glide and resave the image again
3. Send final glide image to server

QUESTIONS:

1. Do i need to save the image twice? or is it possible for glide to load the taken photo from memory without having to temporarily save the file in order to obtain a file path location?
2. Is it possible to use simple targets to automatically put images in correct rotation when saving image to local storage? Images will be displayed on web, other social media outlets, android and ios app. So they need to be correctly oriented before sending to our server
3. If number 2 is not possible are there any advantages of saving the image file with Glide Simple Targets?

Please see my attached code

```java
private class CameraPhotoImageTask extends AsyncTask<String, Void, Bitmap> {
        int h=0;
		int w=0;
		private File imageFile = null;
		private File temporaryImageFile = null;

		public CameraPhotoImageTask() {
		}

		protected Bitmap doInBackground(String... urls) {
			/* Image taken is represented into byte array and passed into "urls" array.
			 We will first convert byte array from urls[] into bitmap image called "loadedImage" */
			//
			Bitmap loadedImage = null;
			byte[] decodedString = android.util.Base64.decode(urls[0], android.util.Base64.DEFAULT);
			loadedImage = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);

			// Get the height and width of loadedImage. We will need this to pass into Glide
			 w = loadedImage.getWidth();
			 h = loadedImage.getHeight();
			Log.i("Test", "Chosen resolution: " + w + ", " + h);

			/*Here we will temporarily save the bitmap image(loadedImage) into a temporary file and directory
             so that we can pass it to glide for processing. */
			try {
					 ByteArrayOutputStream ostream = new ByteArrayOutputStream();
					 loadedImage.compress(CompressFormat.JPEG, 70, ostream);
					 temporaryImageFile = makeFilewithDir(AppTools.PHOTO_DIR,temporaryImageFile);

					 if (temporaryImageFile == null) {
						 Toast.makeText(getBaseContext(), "Image Not saved",
								 Toast.LENGTH_SHORT).show();
					 }

					 FileOutputStream fout = new FileOutputStream(temporaryImageFile);
					 fout.write(ostream.toByteArray());
					 fout.close();

				 }catch (Exception e) {
				 e.printStackTrace();
			     }

			/*Now we need to get the directory path of the temporary image file and represent it as a uri
			before loading it into glide for processing */
			final File tempFile = new File(temporaryImageFile.getPath().toString());
			Uri imageUri = Uri.fromFile(tempFile);
			Log.i("Test", "loaded image is " +imageUri);


			// Now we can pass the imageURI file path into Glide and process the image into a newBitmap from Glide
            //WARNING!!!!: Glide .into does not work on background thread. So we need to put it into UI thread before calling .into
			CameraDemoActivity.this.runOnUiThread(new Runnable() {
				@Override
				public void run() {
					final File tempFile = new File(temporaryImageFile.getPath().toString());
					Uri imageUri = Uri.fromFile(tempFile);
				//Pass imageUri into Glide
					Glide.with(getApplicationContext())// Need to use Application Context
							.load(imageUri)
							.asBitmap()
							.diskCacheStrategy(DiskCacheStrategy.ALL)
							.centerCrop()
							.into(new SimpleTarget<Bitmap>(w, h) {
								@Override
								public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
							/*Assign the newly converted bitmap to newImageFromGlide then save the location of the bitmap
							to our local database. Reminder: Need to delete the temporaryImageFile once newBitmap from
							Glide is saved will handle this later*/
									try {
										ByteArrayOutputStream ostream = new ByteArrayOutputStream();
										Bitmap newImageFromGlide = bitmap;
										newImageFromGlide.compress(CompressFormat.JPEG, 70, ostream);

										imageFile = makeFilewithDir(AppTools.PHOTO_DIR, imageFile);

										if (imageFile == null) {
											Toast.makeText(getBaseContext(), "Image Not saved",
													Toast.LENGTH_SHORT).show();
										}
										FileOutputStream fout = new FileOutputStream(imageFile);
										fout.write(ostream.toByteArray());
										fout.close();
										ContentValues values = new ContentValues();
										values.put(MediaStore.Images.Media.DATE_TAKEN,
												System.currentTimeMillis());
										values.put(MediaStore.Images.Media.MIME_TYPE, "image/jpeg");
										values.put(MediaStore.MediaColumns.DATA,
												imageFile.getAbsolutePath());

										CameraDemoActivity.this.getContentResolver().insert(
												MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);

										//We need to load the image into the active status and set local database parameters for the image
										Log.i("Test", "loaded image is " +"Now we are taking");
										Cursor activeStatus = myStatus.getActiveStatus();
										if (activeStatus.getCount() > 0) {
											activeStatus.moveToFirst();
											final int id = activeStatus.getInt(activeStatus.getColumnIndex(myStatus.COLUMN_ID));
											MyStatusMediaDB.insertMedia(id, 1, imageFile.getPath().toString(), "", 0, "", "");
										}
										activeStatus.close();
										if (newImageFromGlide != null) {
											newImageFromGlide.recycle();
											newImageFromGlide = null;
										}


										CameraDemoActivity.this.runOnUiThread(new Runnable() {
											@Override
											public void run() {
												captureImage.setEnabled(true);
											}
										});
									} catch (Exception e) {
										e.printStackTrace();
										CameraDemoActivity.this.runOnUiThread(new Runnable() {
											@Override
											public void run() {
												captureImage.setEnabled(true);
											}
										});
									}

									CameraDemoActivity.this.runOnUiThread(new Runnable() {
										@Override
										public void run() {
											captureImage.setEnabled(true);
										}
									});
								}});  //End of Glide
				}
			});
```

**Comment by TWiStErRob** [comment]
Once you have a Bitmap you lose all orientation information, and since you used `decodeByteArray` you took the responsibility of rotating it. If you want no temp files you can throw a lot of things out right after `byte[] decodedString` ;)

An approach using tasks:
```java
class Activity {

	private interface Callback {
		void done(File file);
	}

	private static class DecodeImageTask extends AsyncTask<String, Void, byte[]> {
		private final Context context;
		private final Callback callback;
		public DecodeImageTask(Context context, Callback callback) {
			this.context = context.getApplicationContext();
			this.callback = callback;
		}

		@Override protected byte[] doInBackground(String... urls) {
			String url = urls[0];
			// put this in a task, because I suspect this may be megabytes large, unless you're saving icons
			return android.util.Base64.decode(url, android.util.Base64.DEFAULT);
		}
		@Override protected void onPostExecute(byte[] bytes) {
			Glide
					.with(context)
					.fromBytes()
					.asBitmap()
					.toBytes(Bitmap.CompressFormat.JPEG, 70)
					.load(bytes)
					.into(new SimpleTarget<byte[]>() {
						@Override public void onResourceReady(
								byte[] resource, GlideAnimation<? super byte[]> glideAnimation) {
							new MediaSaveTask(context, callback).execute(resource);
						}
					});
		}
	}

	private static class MediaSaveTask extends AsyncTask<byte[], Void, File> {
		private final Context context;
		private final Callback callback;
		public MediaSaveTask(Context context, Callback callback) {
			this.context = context.getApplicationContext();
			this.callback = callback;
		}

		@Override protected File doInBackground(byte[]... params) {
			try {
				byte[] imageBytes = params[0];
				File imageFile = new File(context.getExternalFilesDir(Environment.DIRECTORY_PICTURES), "name.jpg");
				FileOutputStream fout = new FileOutputStream(imageFile);
				fout.write(imageBytes);
				fout.close();

				context.getContentResolver().insert(...);
				...other media storage manipulation
				return imageFile;
			} catch (Exception ex) {
				return null;
			}
		}
		@Override protected void onPostExecute(File file) {
			callback.done(file);
		}
	}
}
```
a better solution would be to use a bound service, so that you can juggle big amounts of data around.

Things I noticed while reading the code that are generic:

 * Make sure inner class tasks are static, otherwise it leaks the activity.
 * `CameraDemoActivity.this.runOnUiThread(() -> captureImage.setEnabled(true));` should be in `try-catch-finally`'s finally instead of duplicating it.
 * `.getContentResolver().insert` is I/O, it shouldn't be called on the UI thread (`onResourceReady` is called on the UI thread)
 * You don't need to pass a size to `SimpleTarget` unless you want to override. There's a `Target.SIZE_ORIGINAL` constant if you need it, but the default constructor does that anyway.
 * You can recycle `newImageFromGlide` right after `compress`, it's better earlier, otherwise something may throw and it won't be dismissed.
 * JPEG 70 has visible artifacts, I suggest 80-85.

**Comment by gabbimark** [comment]
Ok thanks for all your corrections. This is good info. Ok so now that glide will not automatically rotate the image in this case when saving to local, what is the benefit of me using Glide simple targets to save the image vs using standard android tools to save the image to local?

**Comment by TWiStErRob** [comment]
Oh, yes, actually the current impl I provided doesn't do anything to the image except rotate. Glide rotates if you directly from source, but what you did was:
 * String -> base64 -> byte[]
 * byte[] -> decodeFromBytes -> Bitmap
 * Bitmap -> compress -> File
 * File -> Glide -> Bitmap
 * Bitmap -> compress -> File

you lost the rotation info at `decodeFromBytes`. I don't really get why you decoded the image, you could've done this:
 * String -> base64 -> byte[]
 * byte[] -> write -> File
 * File -> Glide -> rotated Bitmap
 * Bitmap -> compress -> File

but I went one step further and removed the temporary file, because Glide can load from byte[]:
 * String -> base64 -> byte[]
 * byte[] -> Glide -> byte[]
 * byte[] -> write -> File

My question is: do you really need to rotate the image? If you upload/save an image any app should be able to open it and display it in the correct orientation (given proper EXIF data).

`toBytes()` is really powerful if you want to manipulate the image, because it can do transformations on the image and can resize/crop it as well.

**Comment by gabbimark** [comment]
Hi thank you for your clarifications. Your code manner is very clean. We have implemented the glide code and it is working now and saving the images in correct orientation. This is such a relief.  The only thing extra we had to do was account for front camera vs back camera as front camera images were showing flipped. To answer your question, we do need to save and rotate. Unfortunately due to android having so many different phone manufactures and no real set standard, some of the android phones are saving the images with incorrect orientation. So unless we are using libraries such as glide to display the image in the view on the viewer's end, the image shows up flipped also on the receiving end many times. There are lots of forums on this issue. So in order to display the images correctly across a wide range of devices and applications we need to first of all save the image in correct orientation by manipulating EXIF data before sending out to our server. We did not want to handle that manually.

Questions that i have:
1. Where should we put the rotation code for handling front vs back camera for best performance? There are two options . Rotate the image before sending it to Glide, or post rotate it inside of glide code before saving it to local. 

2. Do i really need to recycle the image, or does glide handle this automatically. I read in glide docs that we should not recycle the images ourselves. But above you mentioned recycling the image right after compression. In this scenario we are passing in bytes[] data directly into glide without saving the image first as you suggested. Do we still need to recycle the image in this case?

**Comment by TWiStErRob** [comment]
Glide doesn't do more than read the EXIF orientation, so your byte stream probably has a header. Based on my experiences with camera, you only need to flip front if you're dealing with the preview stream. The actual captured image will be correctly oriented. To demonstrate this open the camera app and switch to front camera: it should work as a mirror, but after you capture an image the saved picture will be as if someone has taken a picture of you from behind the device. Regardless, there's a way to flip efficiently.

My comment on rotation on client side is about having to upload rotated. I mean any app that shows images from random sources must be able to deal with EXIF. Browser handle it and image viewing software handle it. So even if you upload an unrotated version (containing EXIF), all clients that display it later should be able to handle it. That said, I too re-orient the images taken in my app with the camera API to conserve resources later when showing them.

1) If you're sure you're dealing with proper captured data and not the preview images, and you still need to flip you do the following for best performance: you should look at the code of `ExifOrientationStream` and `ImageHeaderParser` to see how an EXIF header is handled. After that you can mimic `ExifOrientationStream`'s behavior and set the orientation byte directly in the `byte[]` before you pass it to Glide. Use one of the constants at `ExifInterface.ROTATE_*` to replace with what you think is the correct one.

2) My comment was more geared towards freeing up resources as soon as they're not needed, not 30 lines later for no apparent reason. You have to be careful when dealing with bitmaps because they're huge. In one of my transformation functions I needed to clear local variables to null to make sure the GC can re-use that memory while still doing the same transformation.
That said you probably shouldn't directly `.recycle()` any Bitmaps that were created by Glide. Instead use the mechanism built into Glide to clean up resources: `Glide.clear((Target)this)` at the end where you don't need the Bitmap any more. In normal situations targets are cleared when the scope dies, e.g. fragment/activity destroyed; or when the target is wrapping a view, and a new load is started into the same view (i.e. recycling an item). Since you're using app context none of these apply so you need to make sure the target is cleared otherwise it stays until your app is terminated, which is essentially the definition of a leak. This is true for any Glide load into SimpleTarget not just Bitmaps, so I updated my above code to reflect this (look for variable `that`).
