### ISSUE TITLE
how to save gif to sd card

### ISSUE THREAD

**Issue by Ccixyj** [bumptech/glide#1492]
for somehow ,my gif file is broken and size was only 1kb,so i want to save again to sdcard ; 
but i just can get gifdrawable ,how can i do  

``` java
@Override
public boolean onResourceReady(final GlideDrawable resource, final Uri model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
    KLog.d("onResourceReady", model, target, resource, isFromMemoryCache, isFirstResource);
    Observable.just(1).doOnNext(new Action1<Integer>() {
        @Override
        public void call(Integer integer) {
            try {
                if (resource instanceof GifDrawable) {
                    File cache = Glide.with(context).load(uri).downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).get();
                    KLog.d("cache", cache, cache.getAbsolutePath(), cache.length()); // 1kb
                    File file = new File(model.getPath());// 1kb , broken
                    KLog.d("file ", file, file.getAbsolutePath(), file.length());
                    File newfile = new File(file.getParent() + "/" + System.currentTimeMillis() + ".gif");
                    if (newfile.exists()) {
                        newfile.delete();
                    }
                    newfile.createNewFile();
                    InputStream in = new FileInputStream(cache);
                    OutputStream out = new FileOutputStream(newfile);

                    // Transfer bytes from in to out
                    byte[] buf = new byte[1024];
                    int len;
                    while ((len = in.read(buf)) > 0) {
                        out.write(buf, 0, len);
                    }
                    in.close();
                    out.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }).subscribeOn(Schedulers.io()).subscribe();

    return false;
}
```

**Comment by StrangerMosr** [comment]
Like this
`Glide.with(this).load(url).diskCacheStrategy(DiskCacheStrategy.ALL).into(imageView);`

**Comment by Ccixyj** [comment]
@StrangerMosr   mmm ,i want to save as a new file

**Comment by TWiStErRob** [comment]
@StrangerMosr is right, you need to use `ALL` or `SOURCE` in the outer load so that the inner `downloadOnly` doesn't re-download the image.

Note that you don't need to have an outer load if you just want to save the file, you can simply call the code inside the `instanceof` on a background thread.

`model.getPath()` will only work if the Uri represents a `file:///` otherwise it's just garbage. And if you already have a File uri why are you trying to squeeze it through Glide, just copy the file.

Tip: `exists/delete/createNewFile` is not necessary, as far as I know `FileOutputStream` should truncate it.

If none of the above helps can you check the model and the contents you see? If it's a remote file you may be getting a forbidden or similar HTML message, that's why it's only 1k.
