### ISSUE TITLE
Error in loading specific image!

### ISSUE THREAD

**Issue by siavashabdoli** [bumptech/glide#1509]
it seems impossible but I can't load this image on any device!

`Glide.with(mContext).load("http://www.sheypoor.com/image/7c8891/497x280_S/1/3347d1934b418cbe2076df053d9a667c.jpg")`

and here is the log from listener in 2 different type of widget in 2 different activity

.mobile D/GLIDE: onException(null, http://www.sheypoor.com/image/7c8891/497x280_S/1/3347d1934b418cbe2076df053d9a667c.jpg, Target for: uk.co.senab.photoview.PhotoView{10e2441 V.ED..C.. ........ 0,0-1080,750 #7f10007f app:id/image}, true)

`.mobile D/GLIDE: onException(null, http://www.sheypoor.com/image/7c8891/497x280_S/1/3347d1934b418cbe2076df053d9a667c.jpg, Target for: android.widget.ImageView{84ce3a0 V.ED..... ........ 552,0-1032,480 #7f10010d app:id/offerImage}, true)
`

`compile 'com.github.bumptech.glide:glide:3.7.0'`

I can't understand anything! all other images load properly! but this one can't load on any device

**Comment by TWiStErRob** [comment]
I can't open that image in Google Chrome 53 on Android either. It works on my laptop though.

The key is right before that log line:
> D/skia: --- SkImageDecoder::Factory returned null

Which means that Android's `BitmapFactory` cannot decode the image. Surprising to see on Android 5+, but this JPEG is not decodeable. Quick comparison of metadata with a JPEG that's created by my phone's camera:

Property | Camera image | Your image
--- | --- | ---
Compression | JPEG, quality: 96, subsampling ON (2x2) | JPEG, progressive, quality: 85, subsampling ON (2x2)
Comment | none | "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 85"
EXIF | yes, usual camera stuff | none

From this I suspect that the comment or progressive is the culprit, however I can't really confirm. I've seen progressive JPEGs loaded before on Android, so that should be OK. The color space and subsampling values look the same. I used http://regex.info/exif.cgi and IrfanView to compare.

Without doing our own native decode we can't do anything about this, so I'm gonna close this.

**Comment by AppsolutEinfach** [comment]
We got exactly the first and second error line when reading an Base64-encoded image with prefix `data:image/png;base64,` resp. `data:image/jpeg;base64,`. Stripping this prefix all gonna fine.

**Comment by TWiStErRob** [comment]
@AppsolutEinfach Base64 is not supported by Glide out of the box, see #556

Though, if I understand you correctly, when you strip the prefix, it just works, which suggests that something is really strange with your model that you load.
