### ISSUE TITLE
How to cache bitmap to DiskCache in Glide4.0.0

### ISSUE THREAD

**Issue by jacklydoudou** [bumptech/glide#1518]
I want know How to cache bitmap to DiskCache in Glide4.0.0

4.0.0-SNAPSHOT
**Glide Version**:

ths for your help

**Comment by TWiStErRob** [comment]
Please give a little more info of **what** you want and **why** you want it.
Note that doing the most basic: `Glide.with(this).load(url).into(iv)` **will** cache.

**Comment by jacklydoudou** [comment]
i got a bitmap, and i want to put it into the diskcache of Glide with the specific url,  if i load the specific url next time, Glide will read the bitmap insteal of fetching online.

**Comment by TWiStErRob** [comment]
That's not directly possible, only through a hack.

Where do you get that Bitmap from? You should create/decode it with Glide, because it handles concurrency and caching for you. See http://stackoverflow.com/a/31940058/253468 and http://stackoverflow.com/a/28207674/253468 for examples (in Glide v3, but should be pretty easy to translate it).

**Comment by jacklydoudou** [comment]
i get a bitmap from the camera, i hope glide load it with a specific url through DiskCache when i open app next time, not from net

**Comment by TWiStErRob** [comment]
It seems #906 is what you want then, but it's a hack, so you're on your own from there.

**Comment by jacklydoudou** [comment]
Key key = new StringSignature(url);

StringSignature class was gone, i can't use it in Glide 4.0.0,

**Comment by TWiStErRob** [comment]
The `Key` interface still exists, just take a look at it's implementations and notice `ObjectKey` which is a generalized `StringSignature`.
