### ISSUE TITLE
RequestListener onException should always deliver a non-null exception

### ISSUE THREAD

**Issue by pvegh** [bumptech/glide#1528]
I have seen crashes on some devices that are out of our hands, not being able to tell much about the circumstances.

```
new RequestListener<String, GlideDrawable>() {
        @Override
        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
```

glide:3.7.0

**Comment by TWiStErRob** [comment]
Glide load can fail with no exception, that's a valid case.

For example `Glide.with...load(null).into(iv)`.
Another possibility is when stuff in the [pipeline](https://drive.google.com/open?id=1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g) returns null instead of throwing an exception.

**Comment by pvegh** [comment]
The documentation does state that e can be null, so it is documented, I still find it disturbing considering:
* The documentation starts with "Called when an exception occurs during a load" so I am really missing an exception there.
* The callback method is called onException so I am *really* missing an exception in there

Thanks for the input though, handled this case in my listener.

**Comment by TWiStErRob** [comment]
Did you double-check that your Glide model cannot be null? There's no point in hiding the problem.

I kind of agree with your arguments. How do you propose to make things better?
Note this change should probably only be made in v4, because it's a big change if people handle `null` already. Maybe this behavior is already changed. Notice that the method was renamed: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/request/RequestListener.java#L44

@sjudd what's your take?

**Comment by pvegh** [comment]
Renamed method AND nullable annotation are enough, it's what I had hoped for.
