### ISSUE TITLE
How should I use Glide.with(fragment) in my custom views?

### ISSUE THREAD

**Issue by electrolobzik** [bumptech/glide#1529]
**Glide Version**: 3.7.0

**Issue details / Repro steps / Use case background**: 

What is the best practice for getting `RequestManager` inside custom views? When I use `Picasso` I have a singleton `Picasso` instance which I inject with `Dagger2` in the target view. But with `Glide` I should use `RequestManager` attached to the fragment but not just `Glide.with(context)`. 

I see 2 ways to solve this issue but I don't like them.

1. Add constructor parameter to the custom views.

   - pros: Can pass any needed `RequestManager`
   - cons: It will not work for views inflated from xml. We need to have fallback for such case with `Glide.with(activity)`
   - cons: The code becomes very awkward especially when having deep view hierarchy.

2. Just always use `Glide.with(activity)` inside custom views

   - pros: Don't need to change the code outside the view
   - cons: We will get `RequestManager` attached to the activity instead of the fragment

Is there any other good way for solving this?

**Comment by TWiStErRob** [comment]
I didn't do this yet, hence just ideas: I think it depends on your custom view. If that custom view `extends ImageView` then I see why not extract that logic into another class that handles image loading. If the custom view is a widget then you can also use setter injection or from [this sample](http://frogermcs.github.io/dependency-injection-with-dagger-2-the-api/#provides-annotation) it looks like you can do parameterized injection. Maybe try injecting a RequestManagerProvider not a RequestManager directly. That way, based on context(activity, fragment) you can change it somehow.

The only drawback of `Glide.with(((CustomView)this)getContext())` or `Glide.with(activity)` is that the resources may linger around longer, which is only a problem if you use these custom views inside fragments that appear and disappear a lot with transactions within the same activity.

**Comment by electrolobzik** [comment]
No, it is not about views `extending ImageView`. 

Setter injection is very unhandy and unpredictable: it's easy to forget to inject `RequestManager` and either get error in runtime or get wrong `RequestManager` (depends on logic). It's also difficult to track the order of setting dependency and using it inside the view. 

So do you think that it's okay to use just `Glide.with(activity)`?

**Comment by TWiStErRob** [comment]
Yeah, activity should be fine as I said above, but I suggest your app satisfies those conditions. The important thing is that you understand the consequences of your choice: http://stackoverflow.com/a/32887693/253468

Have you considered making RequestManager passing part of the API of the custom view? So whenever you need to use it, you require the user of the object to provide it, something like: `public void loadImage(RequestManager, Uri)`. Alternatively I'm sure there's a phase when the view is initialised and that init method could have the same requirement (except if that's the ctor which you said wouldn't work).

*Btw, setter injection itself is not problemati; it works really well in Spring, for example, with `afterPropertiesSet`. The problem comes if the DI framework is not designed to support it. I think custom views are weird in this sense, because it's not the DI framework creating the so it can't work the usual magic.*

**Comment by electrolobzik** [comment]
Thank you!

**Comment by TWiStErRob** [comment]
If you find some approach that looks good please share it here so others can benefit!

**Comment by electrolobzik** [comment]
1. I am using `Glide.with(fragment)` everywhere where it is possible: fragments, adapters.
2. I am using the code below to get activity and call `Glide.with(activity)` in my custom views:

```
public static FragmentActivity getActivity(Context context) {
	if (context instanceof FragmentActivity) {
		return (FragmentActivity) context;
	}

	while (context instanceof ContextWrapper) {
		if (context instanceof FragmentActivity) {
			return (FragmentActivity) context;
		}
		context = ((ContextWrapper) context).getBaseContext();
	}
	return null;
}
```
