### ISSUE TITLE
How can i use Glide with dagger2

### ISSUE THREAD

**Issue by kienvtqhi** [bumptech/glide#1533]
Hello

**Glide Version**: 3.7.0

**Integration libraries**: OkHttp3 + Dagger2

**Device/Android Version**: Android Emulator + Asus zenfone 5

**Issue details / Repro steps / Use case background**: 
I am developing a music application. I want to load artist's image from LastFM so i do this this way
1. I created a class `ArtistImageLoader extends BaseGlideUrlLoader`. 
2. In the `getUrl` method i used retrofit2 to get the artist's image url from LastFM via [getArtistInfo](http://www.last.fm/api/show/album.getInfo) method. 

My problem is i didn't know how to inject the service of retrofit to make the request in `ArtistImageLoader`. I did this way but i got a NOP exception. `lastFmService` wasn't be not injected.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
// GlideModule
glide.register(MLocalArtist.class, InputStream.class, new ArtistImageLoader.Factory());

// Use it in onCreate method of ArtistsFragment
DaggerLastFmComponent.builder().activityModule(new ActivityModule(getActivity()))
                .netComponent(getNetComponent())
                .build().inject(this);

// use this code in onBindViewHolder method of artists recycler adapter
Glide.with(getContext())
                .from(MLocalArtist.class)
                .load(localArtist)
                .into(localArtistViewHolder.ivArtwork);
```

**ArtistImageLoader**

``` java
public class ArtistImageLoader extends BaseGlideUrlLoader<MLocalArtist> {

    @Inject
    LastfmService lastfmService;

    public ArtistImageLoader(Context context) {
        super(context);
    }

    @Override
    protected String getUrl(MLocalArtist model, int width, int height) {
        Call<List<MArtist>> call = lastfmService.getArtistInfo(model.artistName);
        try {
            List<MArtist> artists = call.execute().body();
            if (artists != null && artists.size() > 0) {
                Timber.e(artists.get(0).toString());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    public static class Factory implements ModelLoaderFactory<MLocalArtist, InputStream> {
        @Override public ModelLoader<MLocalArtist, InputStream> build(Context context, GenericLoaderFactory factories) {
            return new ArtistImageLoader(context);
        }
        @Override public void teardown() {
        }
    }
}
```

Can you help me to do it? Thank you so much!

**Comment by TWiStErRob** [comment]
I'm not sure how dagger would know to set the loader's field, since the activity has no reference to it and you've created the object manually. I think you need to do the injection earlier, either in `Factory.build` or in the `GlideModule`.

One thing that's really important with your attempt is that `getUrl` is called on the UI thread! Check out #634 (and related) to see how to do a double dispatch in the background.

**Comment by kienvtqhi** [comment]
@TWiStErRob How could I do the injection in `Factory.build` or in my custom `GlideModule`?

**Comment by TWiStErRob** [comment]
The loader/factory is application wide so you should be creating a component in the Application setup, not in every activity. You can control the order because Glide will be only initialised with the module on first interaction, so you can do the Dagger setup first.
If you have multiple netComponents you may want to consider creating multiple custom models for them.
