### ISSUE TITLE
How can you force Glide.clear([view]) in a RecyclerView.Adapter

### ISSUE THREAD

**Issue by donpwilson** [bumptech/glide#1536]
I have a RecyclerView adapter within a fragment to display albums of photos loaded using Glide. Glide loads thumbnails and then full images. I've noticed that, if I switch to a different album, Glide continues to initiate loads of the full images for the previous album.

I'd like to clear both pending and ongoing loads. Presumably this would work automatically if I created a new fragment but I'd rather not have to rework my app so significantly without good reason. 

As I understand it, Glide.clear([view]) should work but I can't see how best to apply it. I've thought about some type of loop within the adapter but it seems messy.

I've also tried recyclerView.setRecycledViewPool(new RecyclerView.RecycledViewPool()) before populating the adapter with the new album but it didn't work.

Can you point me in the best direction?

**Comment by donpwilson** [comment]
I've researched further and found #550. 

I'm using Glide 3.7.0. I load photos into an ImageViewTarget and note that it does not include getRequest and setRequest and so, according @TWiStErRob  in #550 Glide.clear will not work. So this is my issue!

I tried using BaseTarget instead and this appeared to have the desired effect of invoking Glide.clear but photos were not displayed. in the views. I've also experimented with ViewTarget but to no avail.

Would ImageViewTarget work if I upgrade to use a SNAPSHOT of the latest Glide?

How best should I proceed?

**Comment by donpwilson** [comment]
I've made 3 changes / corrections. These changes appear, subject to further testing, to have solved the issue. I would appreciate any comments and confirmation that this approach should not introduce other issues, thanks.

1. Following comments in #1504, I moved the main content of my Glide Builders into a separate class. When I used static references to access the methods very few Glide cancel()s were performed. Switching to use separate instances of the class resulted in more Glide cancel()s, but not on all the images removed from view in the RecyclerView.

2. I added a boolean flag in the DataFetcher, set to true on cancel() and checked in loadData() to avoid loads after a cancel.

3. After careful study of the documentation of Glide.clear() I've concluded that much of the issue is that cancel(0 is not being called when views are recycled unless the views are being reused. In my app this does not occur if all I do is clear the contents of the adapter. I've therefore added the following in the adapter:

```java
@Override
    public void onViewRecycled(final ViewHolder viewHolder) {
        Glide.clear(viewHolder.getImageView());
        super.onViewRecycled(viewHolder);
    }

**Comment by TWiStErRob** [comment]
Ah, man sorry to have not replied earlier.

1) Not fully understand what you mean by static, but it must be a good change if you experienced better behavior.

2) The flag likely only helps with a fling where the load may be cancelled before even begun. You should consider implementing hard cancels, meaning to close the input stream (and any other wrapper object around it) to stop the BitmapFactory decoder from continuing the download. This should speed up image display when user stops after a fast scroll.

3) Yes, that's a good approach. `into` cancels existing load, but when RV just decides to not use an item any more, you need this new logic. I've also used this technique before, and can confirm that it works as expected, even if you use the application context to load the image; the only thing to watch out is that you have to clear the adapter when the fragment view is being destroyed.

Btw, when you clear the full adapter and then populate the same adapter with new data, won't some of the items be reused again? Assuming the item type didn't change, there's no point in inflating new views/holders? I'm asking because this should've lessened the pain of reusing the same fragment/adapter.

**Comment by donpwilson** [comment]
1. Yes, I'm implementing hard cancels. I get a crash if I attempt to call cancel on the UI thread so that keeps me honest!

2. I use the fragment context for loading images in the adapter so I don't think I need to clear the adapter when the fragment is destroyed but I'll keep an eye on the logcat to check.

3. I only clear the adapter when I'm really finished with that dataset. Otherwise I use all of the nice "notifyItemMoved/Inserted etc methods in recyclerView. Indeed when I clear the data, I still use DiffUtil.calculateDiff(...) to generate the changes needed in the adapter. I've also set setHasStableIds(true) which I believe should avoid unnecessary inflation of new view/holders.
