### ISSUE TITLE
The video thumbnails and confused the thumbnail of the picture

### ISSUE THREAD

**Issue by rainmeterLotus** [bumptech/glide#1541]
I use glide load sdcard videos and pitures,but there are confused!
load picture:

``` java
Glide.with(mContext).load(rFile).diskCacheStrategy(DiskCacheStrategy.ALL).into(gridViewHolder.albumItem);
```

load video:

``` java
Glide.with(mContext) .load(Uri.fromFile(rFile)).into(gridViewHolder.albumItem);
```

video thumbnails use picutre thumbnails ,there are confuse!!!!
I think this may be the result of  caching strategies!

**Comment by TWiStErRob** [comment]
How are they confused? What do you see and what do you expect?

Mind you that `rFile` and `Uri.fromFile(rFile)` generate two different cache keys and hence the image will be cached twice. Also there's no point in SOURCE caching local `File`s, because they already exist on disk, and if they don't then you probably don't need to be able to show the image of it again: for local files use RESULT or NONE strategy.

When mixed-up images came up in the past it was mostly due to changing resources, but no change in names. If you have a File on disk that you show with Glide once the image will be cached and no further queries go to the actual File on disk. If the file changes, Glide will still load from cache. To force re-loading use `.load(file).signature(new StringSignature(String.valueOf(file.lastModified())))`.

Another possible reason is async loading: is your Glide code being in `onBindViewHolder` or some other callback or anonymous inner class?

**Comment by TWiStErRob** [comment]
In that case signature very likely won't help much. There must be some conflicting file names. Did you double-check that your model (File list) is different for each adapter? Check out https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling on how to see what Glide is doing (you'll see EngineKeys, compare their IDs to see what's the same for the loads).
