### ISSUE TITLE
Duplicate image request

### ISSUE THREAD

**Issue by safarullahj** [bumptech/glide#1548]
**Glide Version**: com.github.bumptech.glide:glide:3.7.0

**Integration libraries**: com.github.bumptech.glide:okhttp3-integration:1.4.0@aar

**Device/Android Version**: All devices

**Issue details / Repro steps / Use case background**: We have a RecyclerView and each item contains ImageView
In Recycler view adapter's onBind() method, We have Glide request for that image loading.
## Scenario (Duplicate Image Request)
1. Activity loads
2. Image request is gone and under process
3. We scroll fast and comes back to same position(Note that image is still not loaded), the same image request is gone again.
4. Once image is cached, the view will have the image from cache.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with(context).load(url)
            .diskCacheStrategy(DiskCacheStrategy.SOURCE)
            .into(viewHolder.imageView);
```

**Layout XML**:

``` xml
<!-- Item -->
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/item_container"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:clickable="true"
    android:focusable="true"
    android:foreground="?selectableItemBackgroundBorderless"
    tools:ignore="MissingPrefix">

    <ImageView
        android:id="@+id/home_item_image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        android:clickable="false"
        android:contentDescription="@string/content.description.category_image"
        android:scaleType="fitXY" />

    <TextView
        android:id="@+id/home_item_name"
        style="@style/text_style_heading4_white"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:background="@drawable/gradient"
        android:gravity="center"
        android:padding="@dimen/spacing.normal"
        android:text="@string/hint.category.name" />

</FrameLayout>


<!-- Fragment -->
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/refresh_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/vertical_recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </android.support.v4.widget.SwipeRefreshLayout>

    <me.zhanghai.android.materialprogressbar.MaterialProgressBar
        android:id="@+id/progressbar"
        style="@style/Widget.MaterialProgressBar.ProgressBar.Large"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:indeterminate="true" />

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/network_error"
        android:visibility="gone"/>

</FrameLayout>

```

**Stack trace / LogCat**: Checked with a third party network monitoring tool, Headspin

``` ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Consider what you're expecting.

Actual:
You want to start 5 loads (assumed no. of items on screen at a time). Let's consider a slow case (network, server, large image), a response takes 1 second. So the activity is loaded, first 5 are bound and fired. Now, you fling through 20 items, and arrive at 25-30 and then fling up to the top immediately. What happens in Android/Glide, items 1-5 are reused 5 times, each time firing a new network requests for the appropriate images; this happens twice: fling down and up. At every reuse the previous request into that ImageView is cancelled, forcing Glide to restart it later. At any time the only requests in flight are the ones currently on screen.

Expected:
Let's imagine that Glide has 5 background threads for simplicity (YMMV based on cores). Further, let's assume that the request is not cancelled (your expectation). This means that all the previous requests have to finish before dealing with the one that was just started (FIFO queue). So, in order to show items 25-30, 1-25 must have finished over the background threads. This gives the user a 5 second delay waiting for 25 images to download, wasting their time and network quota for images they don't see and potentially don't want, because they're looking at the last ones. Mind you that the one second was a really generous estimate for real world.

Solution:
There's a way to make it look smoother on scroll, but won't help your use case 100% (=flinging like a crazy person). Use a preloader to load a few images off-screen, so when the user scrolls it's likely that the next image will be already in cache and another load will be started for the next one down the line. See #1189.

If you really want to support flinging that much, you'll need to `downloadOnly()` all the images in the list before opening the list. That way all requests will be cached and downloaded once.

**Comment by safarullahj** [comment]
Is there any way to manage image request queue in `Glide`, or any way to set my own `EngineJob` key
to manage it with Adapter ?

**Comment by TWiStErRob** [comment]
You can use `.signature()` to mix in info to the load (it makes requests more specific), for example if you use `System.currentTimemillis() / 24*60*60*1000` then the cache will miss every day and request a new image.

You can also replace the executor with a GlideModule and manage threads yourself, see https://github.com/bumptech/glide/wiki/Configuration; however this won't help, because cancellation will still happen.
