### ISSUE TITLE
Can not cache hit when restart launcher

### ISSUE THREAD

**Issue by jasonzxs** [bumptech/glide#1553]
My app is a android Set-Top Box  launcher, when  restart the STB, glide allways to start re-download all images ,do not use disk cache. 

```
private void loadNormal(String url, ImageView imageView, Priority priority,int defaultImg) {
        Glide.with(imageView.getContext()).load(url)
                .priority(priority)
                .signature( ApplicationVersionSignature.obtain(imageView.getContext()))
                .placeholder(defaultImg)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .crossFade()
               /* .centerCrop()*/
                .into(imageView);
    }
```

I have give a signature to keep EngineKey is same for same image URL. 
Why?  thanks  a lot.

**Comment by TWiStErRob** [comment]
That type of signature makes Glide reload the url on every install/update, however not in debug, unless your Gradle is set up to auto increment version code on each assemble.

The caching should happen automatically without any tricks. Since you are using SOURCE cache all Glide needs is the url (and signature) to hit the cache. Does your url have a changing token in it maybe?

Check out the techniques shown at https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to see why EngineKeys may not match.

Is your cache located on permanent storage on STB? Maybe it has a memory-mapped partition for caches and stuff and it's lost when restarted?

**Comment by jasonzxs** [comment]
Hi,TWIStErRob, thank you very much.
I open the debug info for glide.  the following was the logs for one image (f.e.)

when restart STB.
10-28 17:51:59.032  20991-20991/xx.xx.xx.xxx V/Engine﹕ Started new load in 0.23158299999999998ms, key: EngineKey{http://111.111.11.11:8888/image/201609/29/2016092922303973783157.png+StringSignature{signature='15'}+[60x60]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-28 17:52:00.632  20991-21057/xx.xx.xx.xxx V/DecodeJob﹕ Decoded transformed from cache in 11.674209, key: EngineKey{http://111.111.11.11:8888/image/201609/29/2016092922303973783157.png+StringSignature{signature='15'}+[60x60]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-28 17:52:00.632  20991-21057/xx.xx.xx.xxx V/DecodeJob﹕ Transcoded transformed from cache in 0.111708, key: EngineKey{http://111.111.11.11:8888/image/201609/29/2016092922303973783157.png+StringSignature{signature='15'}+[60x60]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

when refresh page for same image.
10-28 17:52:45.339  20991-20991/xx.xx.xx.xxx V/Engine﹕ Loaded resource from cache in 0.195042ms, key: EngineKey{http://111.111.11.11:8888/image/201609/29/2016092922303973783157.png+StringSignature{signature='15'}+[60x60]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}


I find glide indeed use cache when after restart STB. I misunderstand "Started new load "(compare with 'Loaded resource from cache') means to redownload image.

now I has another question:
All iamges ( 10 pages ,about 100 pics,20-50k for every one ) from index page always appear together when they are all loaded finished. it spend about 2-3 second.

1,Is 2-3 second  a  normal loading spent from cache ? whether it is too long.
2.are there any solution to let images to appear immediately if it has been ready.(rather than all them appear together)
3,how can I let 1 page to load and appear immediately, other page  following.

thanks again.

**Comment by TWiStErRob** [comment]
Image loads should be independent, and appear as each finished. Priority may affect this, try without it. For example if you pass low priority for those 10 pics, but there are 2 big images that are higher priority, then obviously those 2 may block the 10 small ones. The probably appear together because it takes milliseconds to load that resolution. There must be something blocking somewhere: either the aforementioned big images or simply just the disk is busy and cannot serve fast (however that would show up in `DecodeJob` logs as a high number.

Since this is the first interaction I see no way of pre-loading the images. You could start the loads before the activity is launched so it starts on a background thread while the activity is launching but I don't think you would gain more than a few milliseconds. You can use a `ListPreloader` to make scroll look like there's an infinite memory cache available, but it doesn't affect the first page's first load.

The other pages shouldn't be loaded immediately, because ListView/RecyclerView doesn't bind those items yet.
