### ISSUE TITLE
OOM When loading many images

### ISSUE THREAD

**Issue by cohenran** [bumptech/glide#1554]
**Glide Version**:3.7.0

**Device/Android Version**:Galaxy S7

I have a ScrollView that uses glide to load thousands of images. Alas, my memory runs out. Can I cache the images not displayed right now to load more? How do I do that? Why am I getting OOM if glide uses cache defaultly?

**Comment by TWiStErRob** [comment]
ScrollView loads everything at once. If you want to have off-screen images in cache and on-screen in memory, you need ListView or RecyclerView (latter is more flexible).

**Comment by cohenran** [comment]
My scroll view doesn't load everything on the start, only when scrolled down. Can't the image on the top be recycled somehow when it is scrolled down?

**Comment by TWiStErRob** [comment]
Yes it can, it's called RecyclerView :) Any other attempt would likely be re-invening the wheel.

If you really want to go that way, which I'm strongly against, you can try to detect if an image is off-screen via a scroll listener and double-check bounds are off-screen. If both these are true, call `Glide.clear` on that image.

**Comment by TWiStErRob** [comment]
Why do you have/want a ScrollView instead of the well-established list implementations?

**Comment by cohenran** [comment]
I didn't thought there was a major difference when implementing I guess.
I I call `Glide.clear` - How can I load an Image when you scroll to it?

**Comment by TWiStErRob** [comment]
I thought you already had that based on "doesn't load everything on the start, only when scrolled down". I guess its a similar process, check if the view is on-screen on scroll and load it. If you load an url that was already loaded Glide will serve it quick from cache.

Notice that you're asking about how ListView/RecyclerView works internally. I strongly suggest you read/skim this:
https://developer.android.com/training/material/lists-cards.html#RecyclerView
and watch this video:
https://youtu.be/imsr8NrIAMs?list=PLWz5rJ2EKKc_Tt7q77qwyKRgytF1RzRx8
It'll either convince you to reconsider using RV, or help you implement your own solution, because you'll understand how it works.

**Comment by cohenran** [comment]
Now that I think of it hard - I don't have all the data when I display the list - I download the data as the user scrolls... So problably thats why a ScrollView fitted. So should I still use the RecycleView or is now the ScrollView fits?
Also - because the data gets downloaded - a waiting circle gets displayed like in google play. The RecycleView supports that?

**Comment by TWiStErRob** [comment]
Yes, the keyword is "infinite RecyclerView". You can have two item types: 1 for normal images and another for a spinner. When the user reaches the end you can insert an item or lie how many items there are and TV will create and bind your spinner. Once the data arrives, you can update your model (e.g. `List<X>`) and call `notify*` with the changes you made to the model. RecyclerView handles everything else: efficiency, animations.
