### ISSUE TITLE
Image Quality much lower than picasso on images longer than screen size

### ISSUE THREAD

**Issue by topcoderme** [bumptech/glide#1573]
**Glide Version**: 3.7.0

**Integration libraries**: None

**Device/Android Version**: Moto G2 Lollipop...Actually applicable on any device I Tested

**Issue details / Repro steps / Use case background**: 
I have a listView of Images In which I load images that can vary from (1/3)X of Screen Size to 3X of Screen Size in terms of Height.  On Comparing Picasso and Glide. Glide loads wayy faster than Picasso. Image Quality is Similar till ImageSize <= 1X of Screen Size, but deteriorates badly on trying with longer images.

Presumably the Issue seems to be arising because Picasso uses fullSize Images and compresses it later whereas Glide seemingly puts an upper limit on the basis of screenSize and saves compressed image.

Please suggest some easy alternative or some way to bypass this in case of incredibly long images or some hidden functionality to remove that seemingly upper limit.
![picasso](https://cloud.githubusercontent.com/assets/4686436/20092689/7a831680-a5bf-11e6-94eb-4354e4a5b509.png) --> Picasso snapshot of the same image

![glide](https://cloud.githubusercontent.com/assets/4686436/20092644/4b3ab18a-a5bf-11e6-94b5-e15fbe2f405d.png) --> Glide snapshot of the same image

This image is 2.5X the screen size.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(sourceUrl).fitCenter().crossFade().into((ImageView) row.findViewById(R.id.image2));
```
I have also tried using custom Implementation of GlideModule with PREFER_ARGB_8888

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
What is you layout xml for list items? Do you mess with layoutparams from code?

**Comment by topcoderme** [comment]
No, not at all. It's a simple ImageElement done with

Single Item:
<ImageView
                android:id="@+id/image2"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"/>

ListView:
<android.support.v4.widget.SwipeRefreshLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/swiperefreshHome"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="2dp">
            <ListView
                android:id="@+id/listHome"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:divider="@android:color/transparent">
            </ListView>
        </android.support.v4.widget.SwipeRefreshLayout>




I have also tried it in a simple Independent Activity with:


Xml Code:
 <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <ImageView
            android:id="@+id/image"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:adjustViewBounds="true"
            android:scaleType="fitCenter"/>
    </ScrollView>

Activity Code:
 String sourceUrl = "";

Glide.with(this).load(sourceUrl).fitCenter().crossFade().into((ImageView) findViewById(R.id.image));
Vs
Picasso.with(this).load(sourceUrl).into((ImageView) findViewById(R.id.image));


The quality is still bad as compared to me trying picasso on the same.

**Comment by topcoderme** [comment]
P.S: The issue is only with images with Height more than screenSize where picasso shows it perfectly but it gets blurred in Glide. I have just recently switched over to Glide from Picasso.

**Comment by TWiStErRob** [comment]
Glide loads a smaller bitmap to save memory, because it uses the view size to load the "perfect" image. You're using wrap that introduces a circular dependency which is broken by Glide by assuming that the view won't be bigger than screen height. That may sound weird, but in practice the OpenGL texture size limits you anyway. You have these options (in decreasing preference order):
* if you know the aspect (or size) of the image, use a PercentFrameLayout to help Glide figure out the best Bitmap size. Note that you may still bump into OpenGL texture size with this.
* try to tell Glide to ignore the wrap with: `.override(w, Target.SIZE_ORIGINAL)` which, again, may reach the OpenGL texture limit. (w is the laid out width of the `ImageView`)  
*I'm not exactly sure how Picasso works, but I assume this is their behavior.*
* use a library that focuses on large images (or roll your own: #700)
* load the original full size image with `override(SIZE_ORIGINAL, SIZE_ORIGINAL)`

To better understand sizing you may want to read #613

**Comment by topcoderme** [comment]
Thanks a lot. 

The second suggestion worked to perfection. The Image quality is actually mildly better than picasso. There won't be any OOM/memory issues in this right ? It's just a way to convey to glide on what size the image should be & It automatically "fitCenter"s the image in a compressed format according to the required pixel sizes and caches the image as well?

**Comment by TWiStErRob** [comment]
Yes, it'll be resized to that size, but you have to keep in mind the OpenGL texture limit. OOM will only happen if you load a lot of these, but, if it's a list and you do recycling correctly, it should only ever have 2 items in memory at the same time. Since the width constrains the loaded size (=height, because of fitCenter). Hence, the memory usage depends on the width.

**Comment by topcoderme** [comment]
Thanks a lot man. This just resolved all my issues. Including the GIF thingy as bonus :D

**Comment by TWiStErRob** [comment]
Don't forget to [use `.diskCacheStreategy(SOURCE)` for GIFs](https://github.com/bumptech/glide/issues/281) to prevent surprises.
