### ISSUE TITLE
Override Caches and Pool Per Request

### ISSUE THREAD

**Issue by eygraber** [bumptech/glide#1580]
Expouding on [my comment](https://github.com/bumptech/glide/issues/1569#issuecomment-258542719) I think it would be awesome if we could override the memory and disk caches, and the bitmap pool with each request.

My use case (although there is a general one as well) is where my app deals with images (profile photos) in 2 different ways. One is where profile photos are loaded from the internet and displayed throughout the app, which is the main use case. 

The other is where the user chooses or edits their profile picture. We display all the photos on the device in a `RecyclerView`. When the user selects one of those photos we display it in a cropper, and after they've cropped it we upload it.

When we load the device photos, we would like to be able to skip the disk cache and just use the memory cache and bitmap pool. The problem is that this doesn't occur very often, and I don't want to pollute the cache and pool with bitmaps that likely won't be displayed again.

If I could override the cache and pool for those requests I'd be able to clear them once the user selects and crops a photo without impacting the main cache and pool.

**Comment by TWiStErRob** [comment]
I don't think having the memory cache polluted should be such a big deal, once the user starts using the app again, they'll be evicted very quickly. In the meantime if they don't like the image they chose and choose again, they'll get quick response, because some images are left in cache.

Pool pollution is even less likely to cause problems, because the Bitmaps are reconfigured and reused even if their size doesn't match (i.e. the requested size can fit inside the buffer of the other Bitmap).

That being said, for the sake of flexibility this may be a good feature.

Note: I've seen some commits regarding getting rid of the Glide singleton accesses (`Glide.get(context)`) in internal code. I think if Glide becomes a multiton all these issues go away.

**Comment by sjudd** [comment]
No plans to do this. Even the attempts at getting rid of the singleton were for dependency injection, not to allow multiple instances. 

If you have unusual loads that you do not want to cache, you can avoid caching them with a request option. A better argument is the bitmap pool, but you could solve that by writing a custom bitmap pool or a wrapper for the existing bitmap pool that rejected the bitmaps you think are unusually sized.
