### ISSUE TITLE
Image has a ripple again when use 3.8.0 with catch OutOfMemory decoder

### ISSUE THREAD

**Issue by SimplySu** [bumptech/glide#1581]
**Glide Version**: **3.8.0-SNAPSHOT**

**Integration libraries**: okhttp-3.2.0

**Device/Android Version**:  android 19

**Issue details / Repro steps / Use case background**: 
I got the same Issues like #820 (The image quality has changed, and the image has a ripple)
when I use version glide-3.7.0 ,it  load OK and fixed no problem.

when I changed to 3.8.0-SNAPSHOT, it load OK and fixed no problem when no use the decoder .
**but when use the decoder( which can catch the outOfMemory Exception,decoder from #859 )**, 
it happened this phenomenon again. I want to know why and how to fix it? 
@TWiStErRob @sjudd thx very much.

OK and fixed showing:
https://cloud.githubusercontent.com/assets/10938249/11804194/e3f537be-a33c-11e5-97a1-b620fbda6947.jpg

phenomenon showing:
https://cloud.githubusercontent.com/assets/10938249/11804168/aee6ad3c-a33c-11e5-9afe-5185e9dd997a.png

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
//GlideModule
builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);

//showing picture in a fragement
// It will showing OK and fixed it
Glide.with(this)
     .fromString()
     .asBitmap()
     .format(DecodeFormat.PREFER_ARGB_8888)
     .dontAnimate().dontTransform()
//  .imageDecoder(new OOMBmpReadyStreamBmpDecoder(this.getContext()))
     .load(mMediaItem.getUrl()).into(mImageView);

//but when I set the imageDecoder (which can catch outOfMemory Exception, got phenomenon again
Glide.with(this)
     .fromString()
     .asBitmap()
     .format(DecodeFormat.PREFER_ARGB_8888)
     .dontAnimate().dontTransform()
     .imageDecoder(new OOMBmpReadyStreamBmpDecoder(this.getContext()))
     .load(mMediaItem.getUrl()).into(mImageView);

//the OOMBmpReadyStreamBmpDecoder is from the issue #859
public class OOMBmpReadyStreamBmpDecoder extends StreamBitmapDecoder
{
    public OOMBmpReadyStreamBmpDecoder(Context context)
    {
        super(context);
    }

    @Override
    public Resource<Bitmap> decode(InputStream source, int width, int height)
    {
        try
        {
            return super.decode(source, width, height);
        } catch (OutOfMemoryError err)
        {
            throw new RuntimeException(err);
        }
    }
}
```

**Comment by TWiStErRob** [comment]
1. if you use `.imageDecoder()` you override the default decoder, which means that you're overriding the format set by GlideModule. See how `BitmapRequestBuilder` constructor uses the format set on the builder.
2. if you use `.imageDecoder()` you override the default decoder, which means that you're overriding the format set by `.format()`. See how `BitmapRequestBuider.format` overwrites the `imageDecoder` field.
3. you're already using 3.8.0 which has OOMs propagated as load failures since #1057 so you don't need any customization regarding that. If you want to specifically detect an OOM add a `.listener()` and check for `e != null && e.getCause() instanceof OutOfMemoryError`

**Comment by SimplySu** [comment]
Thank you! It works great as your response.
 👍
