### ISSUE TITLE
[Question] How to load video thumbnail by remote URL?

### ISSUE THREAD

**Issue by stepango** [bumptech/glide#1582]
Glide 3.7.0

I tried to load video thumbnail using this approach https://github.com/bumptech/glide/issues/699
But for video's `retriever.getEmbeddedPicture()` returns `null`. Instead, I tried to access Bitmap directly by using this code, which is allow me to get thumbnail without downloading whole video.
```java
@Override public Bitmap loadData(Priority priority) throws Exception {
        MediaMetadataRetriever retriever = new MediaMetadataRetriever();
        try {
            retriever.setDataSource(model.path, emptyMap());
            return mediaMetadataRetriever.frameAtTime;
        } finally {
            retriever.release();
        }
    }
```
Obviously it does not work because `Bitmap` is not valid generic type for `DataFetcher`. Instead of using `Bitmap` directly i forced to convert it to `InputStream` or `FileDescriptor`.

In this case, is it possible yo use bitmap directly without additional convertations

**Comment by TWiStErRob** [comment]
As far as I know [it's not possible](http://stackoverflow.com/a/15828898/253468) to use remote (HTTP) sources. See #1225, #862.

However if you can load a Bitmap given your model you can make Glide consume it as [any parts are replacable](https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit). In your code above you're trying to do the decoder's work in the fetcher, that's why it fails. Check out http://stackoverflow.com/a/31940058/253468 for an advanced case, when there's no InputStream involved. Also see https://github.com/TWiStErRob/glide-support/search?utf8=%E2%9C%93&q=.using%28 for more examples of pipeline customization.
