### ISSUE TITLE
android 7.0  cache does not update? please solve intime ~  Thank you!

### ISSUE THREAD

**Issue by twlk-jzy** [bumptech/glide#1593]

**Comment by TWiStErRob** [comment]
We need more info than "it doesn't work".

**Comment by Benjiko99** [comment]
Maybe it has something to do with the new packager for 7.0

[Understanding APK packaging in Android Studio 2.2](http://android-developers.blogspot.sk/2016/11/understanding-apk-packaging-in-android-studio-2-2.html)

In the **"Release builds for smaller APKs"** section it says:

- _"All file timestamps and metadata are zeroed out."_

Don't you use those for cache invalidation?

**Comment by hamedmohammadi** [comment]
i had the same issue .in my case , 
i had custom directory in device storage and 
problem was with new permission mechanism since android 6 that you need to ask from user inline .
[look at this](https://developer.android.com/training/permissions/requesting.html)

**Comment by TWiStErRob** [comment]
Please reopen or comment with more info than "it doesn't work".

re @Benjiko99 I don't see how that could be related because it's talking about the APK ZIP metadata.
re @hamedmohammadi that sounds like a different issue, you have to make sure to make the first Glide request after the user has enabled you to write to their sd card. The default folder Glide uses doesn't require permission.
