### ISSUE TITLE
glide load bitmap from the netwok, not from the diskCache

### ISSUE THREAD

**Issue by KinaZhen** [bumptech/glide#1594]
**Glide Version**: 
3.7.0

**Integration libraries**:
Okhttp3

**Device/Android Version**:
 Galaxy S6

**Issue details / Repro steps / Use case background**: 
glide load bitmap from the netwok, not from the diskCache

first i use Glide：

Glide.with(fragment).load(imgUrl))
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .fitCenter()
                .into(imageview);

then i use ：

 Glide.with(fragment)
                .load(imgUrl)
                .asBitmap()
                .override(newWidth,newHeight)
                .into(new SimpleTarget<Bitmap>() {...};

but it still get pictures from the network not from diskcache,why?

**Comment by TWiStErRob** [comment]
Because the second load doesn't allow accessing the SOURCE cache. You need to add `.diskCacheStrategy(SOURCE or ALL)`. `.diskCacheStrategy` toggles the caches you give to it; it needs to toggle read/write together otherwise you couldn't say "just use RESULT cache, but not SOURCE".

---

Note: if you save that resulting Bitmap, consider using Glide via `.toBytes()`:
```java
Glide
        .with(this)
        .load(uri)
        .asBitmap()
        .toBytes(CompressFormat.JPEG, 80)
        .atMost()
        //.fitCenter() // add if you want perfect resize (given aspect ratio allows)
        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
        .skipMemoryCache(true)
        .override(newWidth, newHeight)
        .into(new SimpleTarget<byte[]>() {
```
or on a background thread instead of `.override.into(new ...)`:
```java
byte[] resizedImageFile = Glide.....into(newWidth, newHeight).get();
```
