### ISSUE TITLE
Don't display anything when load some images~

### ISSUE THREAD

**Issue by melodyxxx** [bumptech/glide#1597]
example image url : http://ww3.sinaimg.cn/woriginal/b1072857gw1f9wbmwzehej20hsdgfb2b.jpg

code one: (working)
``` java
        Glide.with(this)
                .load("http://ww3.sinaimg.cn/woriginal/b1072857gw1f9wbmwzehej20hsdgfb2b.jpg")
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(mImageView);
```
It's work and correct display into ImageView.

code two: (not working)
``` java
        Glide.with(this)
                .load("http://ww3.sinaimg.cn/woriginal/b1072857gw1f9wbmwzehej20hsdgfb2b.jpg")
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                        mImageView.setImageBitmap(resource);
                    }
                });
```

I get nothing use code two. and `onResourceReady()` called. Where am I wrong?

> glide version : 3.7.0

**Comment by shangmingchao** [comment]
You should use Application context if you use `SimpleTarget<Z>` as the Target. You can learn more from taht Wiki page: [Custom targets](https://github.com/bumptech/glide/wiki/Custom-targets)

**Comment by melodyxxx** [comment]
@shangmingchao I tried , and not working.

**Comment by shangmingchao** [comment]
You can learn more from that Wiki page: [Custom targets](https://github.com/bumptech/glide/wiki/Custom-targets). the constructor of `SimpleTarget<Z>` should hava width and height. Glide need to know the size you want load.

**Comment by melodyxxx** [comment]
@shangmingchao Thanks for your reply, I tried `SimpleTarget`  and `ViewTarget` , and not working.Finally , I add `mImageView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);` and it's working, but drag is not smooth(mImageView is a SubsamplingScaleImageView instance,which extends View)

**Comment by TWiStErRob** [comment]
The first code defaults to loading the bitmap as big as the view (extremely downsampling it in your case), think of it like you have an implicit `.override(view.width, view.height).fitCenter()` on the load.

The second code uses a `SimpleTarget` which has a similar effect to: `.override(SIZE_ORIGINAL, SIZE_ORIGINAL).dontTransform()`. Size is hardcoded in the constructor and there's no transformation because you're calling a different overload of `.into()` that cannot read ImageView.scaleType to automatically do the transformation.

If you look more closely you should see a log line stating that the Bitmap is too big to fit in the OpenGL texture memory: "Bitmap too large to be uploaded into a texture". Glide cannot do anything about this, it supports normal images, not edge cases like this. You need to find a specialized library to do this or read #700 for more info related to Glide.

Using `SubsamplingScaleImageView` you should use `ImageSource.uri`, not `setImageBitmap`.
