### ISSUE TITLE
Blurring bitmap

### ISSUE THREAD

**Issue by Yura-Yaskevich** [bumptech/glide#1613]
Can you help me
I use GLIDE and want to make blur transformation
how cant i pass bitmap for transformation

**Comment by TWiStErRob** [comment]
Where did you get the bitmap from?

**Comment by Yura-Yaskevich** [comment]
I make screenshot and result bitmap trying to load with GLIDE 

`View view = getActivity().getWindow().getDecorView().getRootView();
        Bitmap b = Bitmap.createBitmap(view.getWidth(), view.getHeight(), Bitmap.Config.ARGB_8888);
        Canvas c = new Canvas(b);
        view.draw(c);`

**Comment by TWiStErRob** [comment]
If you got the Bitmap from another source you could have done something like http://stackoverflow.com/a/31940058/253468, but since it's a View that's on-screen, you need to render it from the UI thread. Look around #122 for trick how to squeeze a Bitmap through Glide, or consider alternatives, since in this case Glide doesn't provide you more than doing the blur in the background.
