### ISSUE TITLE
Gif loaded from sd card not working 

### ISSUE THREAD

**Issue by Feroz-Istar** [bumptech/glide#1618]
Glide.with(this)
                .load(filePath)
                .into(imageView);

This is not working as expected.

**Comment by TWiStErRob** [comment]
What happens if you wait some time? I suspect it would work, if the problem is that you're missing a `.diskCacheStrategy()`.

So the problem can be either that  the default RESULT cache strategy is slow, because it decodes and re-encodes all GIF frames before anything is shown. For local GIFs use NONE, for remote (http) GIFs use SOURCE, for anything else RESULT is a pretty good way to go. (This is made better in v4 already.)

Regardless of the above, your solution may still not work if the `filePath` variable is invalid, i.e. file doesn't exists, or has weird chars or prefix. To figure out what exactly is the problem add a [`RequestListener`](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) to see any potential exceptions and act upon those.
