### ISSUE TITLE
API request: Fading edge

### ISSUE THREAD

**Issue by chjan** [bumptech/glide#1630]
In our case, loading radiostation images of all sorts into "preset" ImageButtons, it would be a very good thing with a feature that blurs the edge between the radio image and the button. Why? Because the radio station buttons are of all sorts of qualities. Possible?

**Comment by TWiStErRob** [comment]
It sounds like you just want a simple transformation. Take a look at examples at https://github.com/wasabeef/glide-transformations. You'll need something like:
```java
.bitmapTransform(new FitCenter(context), new EdgeBlur(...))
```

**Comment by chjan** [comment]
TWiStErRob, in my ignorance, I cannot find the javadoc for your code. Would you please suggest how to add EdgeBlur() into this code? Many thanks.

`Glide.with(activity)
                .load(url)
                .asBitmap()
                .into(new BitmapImageViewTarget(stationButton) {
            @Override
            protected void setResource(Bitmap res) {
                RoundedBitmapDrawable bitmapDrawable =
                        RoundedBitmapDrawableFactory.create(activity.getResources(), res);
                bitmapDrawable.setCornerRadius(cornerRadius);
                stationButton.setImageDrawable(bitmapDrawable);
            }
        });`

**Comment by TWiStErRob** [comment]
Press `.` after `asBitmap()` and pick a transformation method from content assist. You need to write `EdgeBlur` yourself extending `Transform<Bitmap>` or `BitmapTransformation` (preferred, easier).

**Comment by chjan** [comment]
I wrote my own, yes and working, but it would be a good thing to extend this library with an .edgeBlur(dip); feature. It is kind of a basic need when blending two images.

**Comment by TWiStErRob** [comment]
Glide already has an API for transformations, and in v4 the API is actually simplified, not extended, but designed for extensibility.

I think you should consider adding your transformation to wasabeef's library. I don't think it's common enough to worth the extra code in the core. I, for one, am not even sure how this transformation looks like, haven't heard about it before. Can you share a screenshot or a Google Image Search please?

**Comment by chjan** [comment]
Take a look at NRK P1 button, it is made with rounded corners, and inner and outer blur. I originally used an async task to load the url and put it as a resource to the underlying rounded buttong, but then I discovered Glide and changed to the use of that API. The question I have now, is why I should use Glide at all? There are a only a few extra lines of codes with the previous solution, and all the complex things that I want as a "one liner" code element, I need to write myself. I did not gain much by switching to Glide, not for this very small images. Therefore I anticipate that Glide has other benefits in the efficient use of memory etc, but this is beyond scope for me. 

I attach the code I use in the next reply

![screenshot](https://cloud.githubusercontent.com/assets/69140/20833678/2839b9da-b891-11e6-80d6-22a12b4de055.png)

**Comment by chjan** [comment]
The code used: 

In the override of setResource (bitmap), I add a call to this method, which I suggest should be part of this API: 

`    public static Bitmap addEdgeBlurToBitmap(Bitmap src, int blurValue){


        int width = src.getWidth();
        int height = src.getHeight();

        BlurMaskFilter blurMaskFilter;
        Paint paintBlur = new Paint();

        Bitmap dest = Bitmap.createBitmap(width, height, Bitmap.Config.RGB_565);
        Canvas canvas = new Canvas(dest);

        //Create background in White
        Bitmap alpha = src.extractAlpha();
        paintBlur.setColor(0xFFFFFFFF);
        canvas.drawBitmap(alpha, 0, 0, paintBlur);

        //Create outer blur, in White
        blurMaskFilter = new BlurMaskFilter(blurValue, BlurMaskFilter.Blur.OUTER);
        paintBlur.setMaskFilter(blurMaskFilter);
        canvas.drawBitmap(alpha, 0, 0, paintBlur);

        //Create inner blur
        blurMaskFilter = new BlurMaskFilter(blurValue, BlurMaskFilter.Blur.INNER);
        paintBlur.setMaskFilter(blurMaskFilter);
        canvas.drawBitmap(src, 0, 0, paintBlur);

        return dest;
    }`

**Comment by TWiStErRob** [comment]
If I see it correctly this is a static list (hor LinearLayout), potentially in a ScrollView (P7 is under the navbar). In this case you're essentially using Glide without resource re-use, because there's no recycling going on. The benefits you gain still are: remote url fetching, parallel loading, disk caching, memory caching. You don't have to do any of those yourself. You have had implemented some of those partially, but Glide is mature enough to say that it's a solid replacement for any hand-written code. Solves some issues with fragmentation etc. It also forces you to separate code into reusable chunks (e.g. transformation).

Use case in which Glide may be helpful is, for example rotation, or repeated visits to this activity. Since these images will stay in memory for a while (memory cache) you can destroy the activity and upon re-show all the images will still be in memory and there won't be need for any I/O or expensive CPU operation (blur). Even if an image is evicted from memory cache, Glide stores the result of the blur on disk, so it's faster to load next time.

Regarding your code I think that's too specific for your use case. We can ask @sjudd what he thinks though.

**Comment by sjudd** [comment]
This is a pretty specific transformation that may not belong in the general library. It might be a good addition to a transformations library though, maybe reach out to https://github.com/wasabeef/glide-transformations?
