### ISSUE TITLE
dose glide support breaking point during loading image

### ISSUE THREAD

**Issue by sherlyme** [bumptech/glide#1631]
if the image haven't been finished loading, will glide keep current breaking point when the network is disconnected.  when the network connect again, will the image continued load??

**Comment by TWiStErRob** [comment]
There's some network listener, but I think if you lose network, running Glide loads will simply fail and `.error()` will be shown. I think any new loads will be queued, but not executed until network comes back, but not sure.

Hmm, a quick look at
`DefaultConnectivityMonitor` and `RequestManager.RequestManagerConnectivityListener` suggests that it should do what you want.

**Comment by sherlyme** [comment]
Thanks a lot! 
I've checked classes as you suggested above, but i still in maze.
Dose this function in my question is decided by Glide default request HttpURLConnection in HttpUrlFetcher? If so, glide dose not support the function as i asked, because in  HttpUrlFetcher, there are no judge about whether the image file is exit or not. 
BTW, How can get the log of glide by Android studio?

**Comment by TWiStErRob** [comment]
Check out https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

If anything, Glide will fail with an IOException in that fetcher, because there's no connection. So any partially downloaded file will be lost, but it looks like it'll be retried later. I suggest you find 4MB+ sized images online, create a list and load them, and then turn off and on WiFi to see what happens.

Tip: the word for questions is `does`, "dose" means "a portion of medicine".

**Comment by sherlyme** [comment]
Solved the problem by adding breaking point logic for image request in my own ImageDataFetcher, which implements  DataFetcher.

Thanks for your tip, really helpful.
