### ISSUE TITLE
Request Listener not invoking as expected.

### ISSUE THREAD

**Issue by neerajmathur91** [bumptech/glide#1633]
**Used case scenario**: I want to download a bitmap from a URL using Glide, I don't have an imageView to show that bitmap, after downloading that bitmap I will put that bitmap in a pdf writer which will place that bitmap at desired coordinates of a paper. So there is no imageView in picture here, I just want to download that bitmap and get notified approprietly. I am using Request listener for this - 

**Code**:

    Glide.with(context).load(imageUrl).asBitmap().listener(new RequestListener<String, Bitmap>()
                {
                    @Override
                    public boolean onException(Exception e, String model, Target<Bitmap> target, boolean      isFirstResource)
                     {
                        e.printStackTrace();
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target,    boolean isFromMemoryCache,
                                                   boolean isFirstResource)
                    {
                        return false;
                    }
                });

**Expected**: I believe the image is getting downloaded but the listener's methods i.e onException() or onResourceReady() never get called. Please suggest a solution.

**Glide Version**: compile 'com.github.bumptech.glide:glide:3.5.2'

**Comment by TWiStErRob** [comment]
First: upgrade to latest version for bugfixes.

The problem is that you're creating and configuring a builder, but not calling a build termination method, which is `into` in Glide's case. Request is not stàrted at all, so obviously there won't be any lifecycle callbacks. Check out the wiki for custom targets (`SimpleTarget`), or better yet, the wiki for loading on background threads (`into(w,h).get()`).
