### ISSUE TITLE
Glide correct usage

### ISSUE THREAD

**Issue by mgarg** [bumptech/glide#1639]
Hi, I have created an app in which I have a single activity and three Fragments. Activity has a recycler view (horizontal) at the bottom and each fragment has a recycler view (Grid). Only one fragment is attached at a time. All the recycler views display images using Glide. I have the following questions regarding the correct usage of Glide.

1.  What context should i pass in Glide?? Currently i am passing the application context in all usages. Also, does using Glide four times using different contexts make four different instances of Glide?? If I now override GlideModule, what does the context in applyOptions() refer to??

2. I have overridden the method onTrimMemory() in my activity. It is getting called with different levels as per expected. But onTrimMemory () of Glide is never being called. I have a break point there and the control is never reaching that function.  When is onTrimMemory() expected to be called??

3. onTrimMemory() and onLowMemory() callbacks are called when the overall memory of the device is low. Is there a way to check when app memory is low?? I want to change the MemoryCategory (Low or High) depending upon the app memory. What is the best way to do this??

4. I am thinking of reducing memory cache size and bitmap pool size to half its original value (by overriding GlideModule) inorder to reduce OOM errors. Will this have any effect on performance??

5. Should i call clearMemory() on onDestroy() of my activity??

**Glide Version**: 3.7.0

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**:  I was getting a lot of OOM crashes in my application. Some of the things i asked above helped me reduce them but not sure of the correct way of implementing these.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 Glide
                            .with(((ViewHolderImage) holder).imgPhoto.getContext().getApplicationContext())
                            .load(imgPath)
                            .asBitmap()
                            .placeholder(R.drawable.default_image)
                            .override(Define.PHOTO_PICKER_SIZE, Define.PHOTO_PICKER_SIZE)
                            .crossFade()
                            .centerCrop()
                            .into(((ViewHolderImage) holder).imgPhoto);
```

Define.PHOTO_PICKER_SIZE is dynamically calculated depending upon the screen size

**Layout XML**:
```xml
 <ImageView
        android:id="@+id/img_thumb"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:adjustViewBounds="true"
        android:src = "@drawable/default_image"
        android:scaleType="centerCrop" />
```

**Comment by TWiStErRob** [comment]
> I was getting a lot of OOM crashes in my application.

This was very likely because "Currently i am passing the application context in all usages.", which means you were leaking fragments/views/Bitmaps whenever you switched fragments within the activity. Anyway, here's some more info:

1. contexts
 a) which context: http://stackoverflow.com/a/32887693/253468
 b) `applyOptions`: always gets application context, but it's lazily called at first Glide usage to speed up application startup
2. those callbacks only work if `[Support]RequestManagerFragment` can be added, which in turn is only possible if you use Activity on an API level where fragments are available, or support's `FragmentActivity`.
3. that's a query for StackOverflow, it's out of scope for Glide. Though I don't think you can get better callbacks than `onTrimMemory`/`onLowMemory` without polling `Runtime.freeMemory`.
4. It should be ok, the performance you lose will be the cost of creating new Bitmaps, because less pre-created ones can be stored in the pool/memory cache. Less re-use means more creating Bitmaps/decoding/GC'ing. But if you don't put crazy constraint on the pool/cache it should be ok. Only you know how much your app can utilize the pool/cache.
5. See SO answer linked in 1); you get that for free if you use the correct "context".
