### ISSUE TITLE
Cache when using .get()

### ISSUE THREAD

**Issue by minas90** [bumptech/glide#1678]
Hi there,
 I'm doing something like this to get bitmap synchronously and set it as image by using imageView.setImageBitmap(bitmap);

```
    return Glide
        .with(mContext)
        .load(url)
        .asBitmap()
        .into(width, height)
        .get();
```

I need to do it synchronously because I'm doing it inside AsyncTask's doInBackground. I need to fetch image url from the backend before loading it with glide.  Later I'm loading the same url into view directly with glide.
The problem is that image is not cached in the disk. I even tried to add .diskCacheStrategy(DiskCacheStrategy.ALL) and it doesn't do anything I guess. 
I think it's a bug. The same solution works perfectly when I load image directly into imageview.
 Any solution for this?

**Comment by TWiStErRob** [comment]
`.diskCacheStrategy(SOURCE)` part of `ALL` should prevent re-downloading the image. However the `RESULT` part of it won't match, because you don't have a transformation on this load. You have to match up the `scaleType` in XML (for the other load) so that they use the same transformation: `.centerCrop()`/`.fitCenter()`, and also you need to make sure that the size matches on both loads. You can force this same size with `.override(width, height)`. Compare `GenericRequestBuilder.into()` overloads' codes.

**Comment by minas90** [comment]
Hi Róbert,
Thank you very much for your response!
I think I'm very close to find a solution. I'm struggling last 2 days haha.
I did the calculation and checked .into(width, height) size exactly matches up with the imageView size in pixels, so I just added .centerCrop() to match up transformation and voila re-downloading part is solved with .diskCacheStrategy(RESULT).
The only problem now is delay / flickering even with .dontAnimate() which was not happening when I was loading image directly to the view with glide.
Can you please suggest me what can I try to fix it as well? :)

**Comment by TWiStErRob** [comment]
Can you please rephrase the question about flickering and provide relevant code/repro steps?

**Comment by minas90** [comment]
ok, so here is the shortest code snippet to reproduce it.
First I'm getting bitmap with 
```
                    return Glide
                            .with(mContext)
                            .load(ogImage)
                            .asBitmap()
                            .centerCrop()
                            .into(mScreenWidth, height)
                            .get();
```
and setting it as recyclerView's imageView image ( doesn't matter I guess, you can try the same with any imageView )
imageView.setImageBitmap(bitmap);
I even added AlphaAnimation to imitate glide's crossFade. So the only issue now is flickering, which is happening when later I already have the cached image url and item's onBindViewHolder is called after onResume when returning to the screen for example, so I just use glide to load the same url into the same imageView. ( you can just load the same url with glide into the same imageView after some delay ).

```
            Glide.with(view.getContext())
                    .load(link)
                    .centerCrop()
                    .crossFade(250)
                    .placeholder(R.color.placeholder)
                    .into(view); 
```

 It doesn't re-download, but flickering is happening, image disappears and appears shortly. It doesn't happen when I load image with .into(imageView); the first time. Also on the next screen I have an imageView with the same size and transformation .centerCrop(), it also has some delay to load the same url with glide and also when image is loaded with .into(view) in the previous screen loads instantly.

**Comment by TWiStErRob** [comment]
Did you check the cache keys [via logging on the wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow)? I think you need to add `.asBitmap()` to the second load.

This is because the `get()` may put it into the memory cache, but `into(view)` won't hit that, because one is a Bitmap and the other is a `GlideBitmapDrawable`.

Be prepared though that the flicker may happen at any time if the cache is not hit, because the placeholder is set. If you have the Bitmap handy from the first load you can try `.placeholder(new BitmapDrawable(bitmap))` to force a proper cross-fade. But remember: calling `.getDrawable()` to do the same on an ImageView that Glide loaded into is not safe. It's only safe because you're still in possession/control of the bitmap.

**Comment by minas90** [comment]
Now I tried with .asBitmap() and delay is a little bit shorter for some reason, but flickering is still there.
Based on your recommendations I came up with a trick to avoid flickering. Now I just check if bitmap is still there, if yes I do imageView.setImageBitmap(bitmap); otherwise I use glide.
When item is recycled and bitmap is gone and you scroll back to the same item, image url is cached and this time it's fully handled with glide perfectly.

I spent few days and you helped me a lot. So again thank you very much :)
