### ISSUE TITLE
About use skipMemoryCache(true)  question。

### ISSUE THREAD

**Issue by YuJunKui1995** [bumptech/glide#1683]
My colleague write "skipMemoryCache(true)" config , I don't think it should be like this。Now I don't know how to convince him,Can give an official answer？ 

Thanks!

**Comment by YuJunKui1995** [comment]
Please forgive my Chinese style of English

**Comment by TWiStErRob** [comment]
That option disables one of the core values given by Glide, namely: resource reuse. When a list is scrolled up and down, or when the same image is displayed in multiple places (think a profile image) Glide will **have to** go to the disk and do I/O to load the image. Allowing memory cache in these cases sometimes results in even a synchronous load, because it's just as simple as "`imageView.setImageDrawable(cachedDrawable)`".

There are patterns where `skipMemoryCache` has it's place, but they're very special use cases.

**Comment by YuJunKui1995** [comment]
Thanks!

**Comment by YuJunKui1995** [comment]
Thanks!
