### ISSUE TITLE
Glide and gzipped .png files.

### ISSUE THREAD

**Issue by attacco** [bumptech/glide#1699]
It's sad, but on my server i have png files, that already gzipped. In other words, file extension is png, but it's bytes presents a gzipped png bytestream. And the only way to GET this files from web-server is to add header: Accept-Encoding: gzip on the client side, then find in response headers "Content-Encoding: gzip", and if it present, wrap connection inputstream into GZIPInputStream.

But now i'm using Glide and it seems, that Glide (by default) can't work with gzipped png files. Is there any recommended way to add gzip-support into Glide?

Thank you!

**Comment by TWiStErRob** [comment]
It's easy to see why Glide doesn't support gzip'd images: all the image formats that Android supports are well-compressed already: GIF, PNG, JPG, WEBP. GZIP is explicitly disabled in `LazyHeaders.Builder` (linked to #440). I'm not exactly sure why we need the content-length/`available` for image decoding, but there has been a lot of effort made by @sjudd to implement stuff around this area, so it must be important.

Since you added a header Glide is getting an input it can't handle. One way to go around this is to create a custom fetcher that creates an input stream that is a valid image for Android. The side-effects of this are unknown to me, so proceed with caution. Take a look at `HttpUrlGlideUrlLoader`, I suggest you wrap that and `HttpUrlFetcher` so that they handle gzipping. You can then either override the default `register(GlideUrl.class, InputStream.class, new HttpUrlGlideUrlLoader.Factory());` (in `Glide` constructor) with your wrapper, or create a different model that handles this and register your loader/fetcher for it.

An alternative solution may be to use OkHttp or Volley to somehow get the correct stream to Glide.
