### ISSUE TITLE
Download progress problem

### ISSUE THREAD

**Issue by Drizzlezhang** [bumptech/glide#1735]
**Glide Version**:3.7.0

**Integration libraries**:okhttp3-1.4.0

**OkHttp libraries**:okhttp3-3.5.0

**Device/Android Version**:Any device

**Issue details / Repro steps / Use case background**: I try to use your example code [link](https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_232_progress)
to show download progress view, but when the item in the RecyclerView has been recycled, the connection of the item will be reset. Here is my code [GlideProgressTargetProject](https://github.com/Drizzlezhang/GlideProgressTarget), copy from your code completely. I have tried many ways and I need help...

**Comment by TWiStErRob** [comment]
Reset is because Glide is not a networking library with a downloader engine. It downloads images on demand, and when it's outside the screen it needs to stop pending loads. Otherwise, a fling would download every single image to the full, meaning the last image would take a very long time to load, which is horrible UX.

If you want more control over the download, then I suggest you use a networking library, and download into a folder, then when it's done you `.load((File)downloadedFile)`.

**Comment by Drizzlezhang** [comment]
But I find when the target is outside the screen the connection won't stop, and when the target enter the screen, the old connection will stop and a new connection will be connected.
For example, I have a target in a listview and it has started to load image, now start a new activity which has the same target with a same url, finish the activity,  and then the connection of old target will never stop.

**Comment by TWiStErRob** [comment]
A lot depends on how you use Glide, see http://stackoverflow.com/a/32887693/253468.

As to item going outside screen: Glide, by default, only stops the connection when there's something new loaded into the same view! That's because `.into()` does the cancelling. Note that even though the item may be off-screen, it's possible that you'll get the same view back without it being re-bound; in which case the load may have finished off-screen.

**Comment by Guang1234567** [comment]
@TWiStErRob 

I using ` .using(new GlideOkHttpUrlProgressLoader(mProgressListener)) ' to listen the progress of the download  in  `Glide 3.x`

```java
Glide.with(getContext()) //getContext() reture ApplicationContext, no memory leak.
                    .using(new GlideOkHttpUrlProgressLoader(mProgressListener)) // <---------------- here
                    .load(getGlideUrl())
                    .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);

```


Question:

How to code in **Glide 4.x** ?
