### ISSUE TITLE
Delete cached images (again)

### ISSUE THREAD

**Issue by breakline87** [bumptech/glide#1737]
I've seen several questions regarding deleting images but none of them are good for me.

Let's have a use case like this:

- user adds an entity to a list ("favorites")
- we load all the images for the entity and store them via Glide cache
- now user can have the images even in offline mode
- user removes entity from the list

Now what? I dont want to clear the cache completely (I want to keep all the images of the other favorites) but I don't want to keep images in cache I dont need (seems to pile up). 

Havent checked the internal implementation but what stops from Glide to find and delete an image of a particular URL if you're hashing it anyway? In our case the URL's rarely if ever change too. I'm very happy with Glide but this seems to be an issue which doesnt sound hard to fix.

Any future plans to do something like this?

Thanks

**Comment by TWiStErRob** [comment]
> which doesnt sound hard to fix. Any future plans to do something like this?

I agree it should be an easy change, the problem is that it's a breaking public API change. Probably there could be a way around it with some deprecation and wrapping classes. I think so far it has been deemed too much effort for a requirement that shouldn't be part of Glide. There are more pressing issues/enhancements that Glide needs, I think this would be down the priority queue. You (or anyone) may attempt a PR if you want as long as it adheres to non-breaking public API (`3.0`) or do it against v4 (`master`), because that's unreleased.

> we load all the images for the entity and store them via Glide cache

That's where your solution breaks apart.  As far as I understood during my career a cache is always volatile, items can be evicted any time. So we shouldn't store important (user requested) items in them.

> now user can have the images even in offline mode

A cache can usually be refilled on a miss, however with offline mode that's impossible. So even if you can remove images from cache, your requirements are not satisfied.

> Havent checked the internal implementation

Glide has a DiskLruCache inside, which is size-bound. So if you fill it up enough it'll start evicting (deleting) items. The default size is a bit south of 250MB. You can [restrict it more](https://github.com/bumptech/glide/wiki/Configuration#size) so it starts evicting sooner. The problem is that this constrains the user from favoriting many items.

> Now what?

Option 1 (most stable): do a proper pinning by downloading the files (with a networking library) into your own controlled folders and use `.load(File).diskCacheStrategy(NONE or RESULT)` to show them. You can have a folder per favorite so you can easily clean up.

Option 2 (freakishly unstable): use `.downloadOnly()` to cache the file, and use `.downloadOnly().get().delete()` to remove it. This will remove the file from under DiskLruCache's nose; don't know what side-effects will it incur.

**Comment by breakline87** [comment]
I agree with your point of a cache being volatile, however manually removing an item from a cache should not matter. Simply if the hash is consistent i.e. there is a 1-1 connection between the url and the hash Glide should re-download it as requested if not found in the cache. If I understand correctly Glide itself removes some items from the cache if it has reached the upper limit.

Obviously if the item is not in the cache and the device is offline then Glide will fail to download/display it. But this can happen anyway as of now, so it's no different. This wasn't a crucial point, we're using the cache to make things faster, not necessarely that every image ever is present for the user.
