### ISSUE TITLE
Loading images with HTTP POST

### ISSUE THREAD

**Issue by HassanJawed** [bumptech/glide#1751]
I want to download images into RecyclerView using http post, how can I achieve that with glide?

**Comment by TWiStErRob** [comment]
You need to write your own model loader / fetcher. See the existing [Integration Libraries](https://github.com/bumptech/glide/wiki/Integration-Libraries) for examples. Create a PostImage class and register for that model instead of overwriting String/GlideUrl behavior (unless your whole app needs this without exceptions).
