### ISSUE TITLE
 Failed resolution of: Lcom/bumptech/glide/Glide;

### ISSUE THREAD

**Issue by songmeitao** [bumptech/glide#1777]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;

why???

**Comment by TWiStErRob** [comment]
Good question, depends on what you're doing.
First step: clean build, second step: update this issue with more info if it still doesn't work.

**Comment by irwing844** [comment]
The same issue.......

**Comment by TWiStErRob** [comment]
@irwing844 @songmeitao can you please provide a bit more info than "it doesn't work"?

**Comment by irwing844** [comment]
@TWiStErRob sure:


Exception java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
com.telollevamosapp.telollevamosapp.MainActivity$1$1.onDataChange (MainActivity.java:242)
com.google.firebase.database.Query$1.onDataChange ()
com.google.android.gms.internal.zzbpx.zza ()
com.google.android.gms.internal.zzbqx.zzZS ()
com.google.android.gms.internal.zzbra$1.run ()
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5272)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:909)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:704)
arrow_drop_down
Caused by java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.Glide" on path: DexPathList

**Comment by TWiStErRob** [comment]
multidex?

**Comment by irwing844** [comment]
Yes

**Comment by TWiStErRob** [comment]
I mean: did you try removing a few libraries to see if going into a single Dex solves the problem? There are also some parameters to make the build put some classes/jars in the main Dex, worth a try.
