### ISSUE TITLE
Loading svg from string

### ISSUE THREAD

**Issue by zvvadim** [bumptech/glide#1781]
Hi. I'm using  GenericRequestBuilder to load svg. 
```java
GenericRequestBuilder<Uri, InputStream, SVG, PictureDrawable> requestBuilder = Glide.with
                (context)
                .using(Glide.buildStreamModelLoader(Uri.class, context), InputStream.class)
                .from(Uri.class)
                .as(SVG.class)
                .transcode(new SvgDrawableTranscoder(), PictureDrawable.class)
                .sourceEncoder(new StreamEncoder())
                .cacheDecoder(new FileToStreamDecoder<SVG>(new SvgDecoder()))
                .decoder(new SvgDecoder())
                .animate(android.R.anim.fade_in)
                .listener(new SvgSoftwareLayerSetter<Uri>());

        requestBuilder
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .load(uri)
                .into(binding.fruitImageView);
```

Is there any possibility using String parameter with actually svg data?
Like that:
```xml
<svg height="100" width="100">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg> 
```

Something like:

```java
GenericRequestBuilder<String, InputStream, SVG, PictureDrawable> requestBuilder = Glide.with
                (context)
                .using(Glide.buildStreamModelLoader(String.class, context), InputStream.class)
                .from(String.class)
                .as(SVG.class)
```

There is no documentation at all on using GenericRequestBuilder. 

Thanks for any help.

**Comment by TWiStErRob** [comment]
`Glide.buildStreamModelLoader(*.class, context)` is reusing Glide's default loaders. So for String that means Uris and File paths. What you want is to load the actual string. You can either write your own loader/fetcher that creates an InputStream from the SVG XML String and the custom decoder/transcoder, or use `.load(byte[])` overload/`buildStreamModelLoader(byte[].class...` with the custom decoder`.

As per docs, yes there isn't much, because there are so many cases. Look at each method to know what they do an the built-in subclasses for tips. That's where I learned from as well. Also look at https://github.com/TWiStErRob/glide-support for runnable examples. Take a look at each method in the chain as well to better understand the steps to build a Glide request.

I usually noticed that if you can get it to compile (e.g. generics and builder order) with the parts you want to replace, then it'll very likely work at runtime as well, or if not it should throw a meaningful exception.

**Comment by TWiStErRob** [comment]
See also https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit

**Comment by zvvadim** [comment]
Thanks.
