### ISSUE TITLE
How to listen to preload()

### ISSUE THREAD

**Issue by zekun-hello** [bumptech/glide#1796]
Hi, I want to use preload image, then jump to another activity and show the image from cache when preload is finished. So I used `Glide.with().load().listener(listener).diskCacheStrategy(DiskCacheStrategy.SOURCE).preload()`. I set a break point in the listener before sending intent and turn off internet access at the break point.  When I continue from the break point, the image is not shown in the second screen. So I think either the image was not preloaded or listener is triggered before preload finished.

I thought of using `Glide.with().load().diskCacheStrategy(DiskCacheStrategy.SOURCE).into(SimpleTarget)` and use SimpleTarget as cache callback. But I still don't know why `listener().preload()` does not work. Can anyone help me out?

**Comment by TWiStErRob** [comment]
Listener cannot be called when resource is not ready. Did you add `.diskCacheStrategy(SOURCE)` on the second screen? You need to tell Glide to look in the SOURCE cache.

**Comment by zekun-hello** [comment]
Hi, I tried .diskCacheStrategy(All) in the second screen and nothing happened.

**Comment by TWiStErRob** [comment]
When you do preload with SOURCE Glide saves the whole original JPEG stream on the disk, only after that's finished it decodes from the File. The second time (ignoring memory cache) Glide will just decode from SOURCE cache, so the speed difference is the downloading time.

Memory cache can only be hit if the transformation and the target size matches exactly. See https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow how to enable EngineKey logging to see why you hit/miss the cache. When you use `preload()` without arguments, you're preloading the original sized image to memory, but on your second screen you're probably loading into an ImageView, which has a specific size, so that's a mismatch and hence Glide goes to SOURCE cache to decode the image in the size of the ImageView.

**Comment by zekun-hello** [comment]
@TWiStErRob I doubt about "so the speed difference is the downloading time". I don't go to second screen until preload is finished and listener gets called. What I meant slower is, **after** listener is called and I get to the second screen, it takes some time to load the image. If I close it and go to the second screen again, it shows the image immediately.

**Comment by TWiStErRob** [comment]
If you went to the second screen once, the image will be in memory cache.

Let me repeat this: "When you use preload() without arguments, you're preloading the original sized image to memory". This means a full decode of an image that will never be displayed. This could also cause a delay. You need to figure out the ImageView size on the second screen (or use `.override()`) to make sure caches are hit. Make Glide log cache keys to see what I'm talking about.

**Comment by zekun-hello** [comment]
It make sense now. Thank you.
