### ISSUE TITLE
How does the Glide.with(context).pauseRequests() work ? 

### ISSUE THREAD

**Issue by lbpeisen** [bumptech/glide#1825]
Glide version: 3.7.0
I use the Glide.with(context).load( video file path).into(imageView). Then i want to stop the load by myself. what shuld i do?  I try Glide.with(context).pauseRequests(); But it doesn't work, it will still load the before video file.
thanks

**Comment by lbpeisen** [comment]
I want to stop the previous file , and then i will use the same context to Glide.with(context).load( video file path).into(imageView). I try pauseRequests, onDestroy ,clear ,but it all doesn't work, it will still finish the before load then begin the new load.

**Comment by lbpeisen** [comment]
and there is another bugs, i use Glide.with(context).load( video file path).into(imageView). but when the video endswith mpg,mpeg,mov. Glide can't get the thumbs ...

**Comment by TWiStErRob** [comment]
Glide can only get thumbs for [file types supported by Android](https://developer.android.com/guide/topics/media/media-formats.html#video-formats). If you want more you may want to write a custom loader/fetcher using `ffmpeg` or similar native decoder.

The cancellation (`clear`, loading on top of previous) doesn't work, because it's not implemented: see `LocalUriFetcher.cancel`. Not sure why, but a guess is: it's better to let the load complete, anticipating that the user will scroll there again and then it'll just hit the cache. This works well in most cases. You can always register your own loader/fetcher and implement cancellation the way you want. `HttpUrlFetcher` has a clue why it's not implemented: the cancel method is called on the UI thread. Also see JavaDoc of `DataFetcher`.

`pauseRequests` calls `cancel` as well, and does not work as you expect because of the same reason.

**Comment by lbpeisen** [comment]
thank you !
