### ISSUE TITLE
how use different Glide decodeformat for one app

### ISSUE THREAD

**Issue by larry19840909** [bumptech/glide#1830]
Our App is a photos app, there are two important Activities.
Activity 1 is album cover list
Activity 2 is showing the every photo of album.

For displaying high quality images in Acitivity 2, we set the decode format is ARGB8888, but it will be cause more memory usage. so we want to config the decode format of glide is ARGB565

But we don't know how to config.

Glide Version 3.7.0

**Comment by TWiStErRob** [comment]
Set the default format to whatever you seem fit: https://github.com/bumptech/glide/wiki/Configuration#bitmap-format

...and change the special places to the one that you need there:
```java
Glide.with(this).load(url).asBitmap().format(DecodeFormat.PREFER_ARGB_8888).into(imageView);
```
(`.asBitmap()` turns off `.crossFade()`, if you need that (#1096), you can start using the [3.8.0 snapshot](https://github.com/bumptech/glide/wiki/Snapshots))

Note: 565 doesn't have alpha channel: 5 bits of Red, 6 bits of Green, 5 bits of Blue, so it's only 16 bits, hence half the space as an 8888 (32 bit) image, but lower quality, because not all colors can be expressed.

**Comment by larry19840909** [comment]
Thanks
