### ISSUE TITLE
Can't get the right thumbs ?

### ISSUE THREAD

**Issue by lbpeisen** [bumptech/glide#1841]
**Glide Version**:3.7.0

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(video file path).into(imageView);
```

I use Glide to get video thumbs. when the file end with "mov", some files can get the right thumbs , others can not  . The OnResourceReady can get a glideDrawable , but it's not right thumbs , glide will get a black background or a stripe (striation with black and white) image , the # problem is the onException  is not be called . so i don't know which file can get the right thumbs. which can not . May be is not clear , so when the file end with "mov" , and  video encode formats is "JPEG" , "ITU H.26n" , "H.264" , "MPEG-4 Video" or some others , you will get the stripe image .
I know Glide can only get thumbs for file types supported by Android , i don't want to custom loader/fetcher , i just need onException can be called , then the error image can load right , it is my target .

it will occurs when file end with "mpg", "mpeg". 

what shuld i do? 

thank you very much.

**Comment by TWiStErRob** [comment]
Wow, that's an interesting issue. I don't know how to solve it with the constraints you gave.
The problem is that the Android system "thinks" it supports the given format, but it cleary doesn't (or reads the wrong frame which has no meaningful data).

I don't think it's possible to do this without writing a custom decoder that supports these formats. You can try hacking by checking if the Bitmap you get is stripy: use `.asBitmap()` to get a Bitmap and peek into some of the pixels to see if they're black/white (`b.getPixel(b.width()/2, b.height()/2) == Color.BLACK`); if they're assume they're stripy and show something else: `.listener()` callbacks can `return true` to signify that you've set a fallback image, and the bad Bitmap will be not displayed.
