### ISSUE TITLE
Glide 3.7 doesn't resize images correctly

### ISSUE THREAD

**Issue by sandy-8925** [bumptech/glide#1842]
**Glide Version**: 3.7.0

**Integration libraries**:

**Device/Android Version**: Nexus 6/7.1.1

**Issue details / Repro steps / Use case background**: 

1. Load image using requestManager.load(uri).asBitmap().into(new CustomTarget(...., width = 400, height = 400))

CustomTarget extends SimpleTarget<Bitmap>, and passes the width and height as is to the constructor of SimpleTarget - the image read from the URI was a JPEG image taken using the phone's camera app, it's a pretty large image (e.g) 2560*1440

Since I've passed in 400 as width and height, I believe that Glide will resize the image to a max of 400x400, before giving me the Bitmap. However, I find that Glide resizes the image to 1040x780. If I pass in a value of 300 for the width and height, Glide gives me a Bitmap of size 520x390 - which doesn't make sense, based on the parameters I provided to it.

**Comment by TWiStErRob** [comment]
Glide doesn't resize if you don't give it a transformation. When you use custom targets, you lose the magic of `GenericRequestBuilder.into(ImageView)`. You have two options:

1. add `.fitCenter()` as an explicit transformation which will work as you expect
2. add `.atMost()` to change the downsampler to treat the `.override()` size as max

The second option is faster, because it does less processing. Downsampling/resize is done at decode time. Don't add both options, because that will just waste memory, processing time and quality.

**Comment by sandy-8925** [comment]
Ok, thank you!

**Comment by sandy-8925** [comment]
Hello, I tried your suggestions and found that only fitCenter() works correctly - .override(400, 400).atMost() still provides an image with 1040 x 780 size.
