### ISSUE TITLE
while i use Gif to ListView/Recycle

### ISSUE THREAD

**Issue by ycpbyht** [bumptech/glide#1859]
use the  Glide.asgif.into(ImageView) into  ListView/RecycleView,   the Gif play not smooth, it lose some frame.

**Comment by TWiStErRob** [comment]
How many GIFs are playing at once? If each item is a GIF, that's expected. Glide decodes each frame on the fly (to prevent pre-loading all frames to memory like other GIF drawables do), so there may be contention between list items for the thread to decode.

**Comment by TWiStErRob** [comment]
Please add more info to this issue and reopen if you need more help.

**Comment by ycpbyht** [comment]
my getViewtype＝6，just one item use gif.
just  scroll the recycleview ,the gif lose some frame。if i don't scroll the recycleiew the gif display well.
so  i don't not what info i can provide，because it‘s no log or error info

**Comment by TWiStErRob** [comment]
That may be because the normal images and the GIF frames are loaded in the same queue. So when you scroll the images block the frames from getting queued and delivered. You can try to play around the `.priority()` (e.g. set GIF to high and leave other normal), however I suggest thinking hard of what's more important: smooth playback, or showing what the user asked for. When the user scrolls they want to see the images out of screen, right? so prioritizing something that they're *scrolling away from* may not be a good idea.
