### ISSUE TITLE
Preload RecyclerView/transformation/sizing and cache questions

### ISSUE THREAD

**Issue by FaultException** [bumptech/glide#1887]
Hi,

I'm integrating Glide into my app. I have a RecyclerView that displays covers. The covers are fitted to a static size, however the cover images themselves are not transformed and are just fitted using ImageView.

When using RecyclerViewPreloader (Glide 3.7, the class is from #1189), it wants me to specify a size, but normally I don't know what the size will be. I do know the frame size, so I guess I could do a transform. 

1. Is there a benefit to using a Glide transform instead of just letting ImageView do the fitting? Is there a performance hit by transforming the Bitmap when the ImageView could just do it?

2. Is there a way to use RecyclerViewPreloader without specifying a size? What's the rationale if it's not possible, since I can manually load an image without a size, and I can manually preload() without a size.

3. All my covers are already on disk. When I load an existing file from disk (using load(String)), is Glide still trying to write it to a disk cache? What about if I use a transform?

4. Is there a benefit to specifying a size when loading?

I'm not currently specifying any size, transform or cache strategy.

Thanks.

**Comment by TWiStErRob** [comment]
> I'm not currently specifying any size, transform or cache strategy.

Yes, you are, by using the defaults ;) size comes from ImageView's laid out size, transform comes from ImageView.scaleType (see `GenericRequestBuilder.into(ImageView)`), `.diskCacheStrategy(RESULT)` is the default.

> Is there a benefit to using a Glide transform instead of just letting ImageView do the fitting? Is there a performance hit by transforming the Bitmap when the ImageView could just do it?

Yes, the benefit is that the Bitmap in memory will be smaller and the image doesn't have to be transformed on every single draw (1:1 pixel drawing).

>  Is there a way to use RecyclerViewPreloader without specifying a size? What's the rationale if it's not possible,

Glide needs to know the requested size in order to do the above optimization. In a list, you can simply steal the first layout's image size, and use that as a template (assuming they're the same). `glide-support` commit in #1189 has this trick.

> since I can manually load an image without a size, and I can manually preload() without a size.

No, you can't load without a size, or at least not efficiently. Peek into `preload()` to see what it does. A good example of the waste `SIZE_ORIGINAL` produces is if you have a profile image that's a 3000px wide hi-res JPEG, but you display it only as a 48dp icon out of it.

> All my covers are already on disk. When I load an existing file from disk (using load(String)), is Glide still trying to write it to a disk cache? What about if I use a transform?

Yes, if you don't specific `NONE` strategy, Glide will try to cache the transformed image. Again, you're using transformations by default unless you specified `dontTransform()`.

> Is there a benefit to specifying a size when loading?

Most of the time it's a bad idea. Nothing can predict the size of the image on screen better than doing an actual layout... You'll be either under or overshooting the size, which will result in extra transformation on draw and hence potential quality loss of visible image.

---

Let me know if something is not fully clear yet. A lot of things are going on behind the scenes.

**Comment by FaultException** [comment]
Thanks for the reply.

> No, you can't load without a size, or at least not efficiently. Peek into preload() to see what it does. A good example of the waste SIZE_ORIGINAL produces is if you have a profile image that's a 3000px wide hi-res JPEG, but you display it only as a 48dp icon out of it.

My images are already stored primarily for displaying in the list, so they're pre-scaled (albeit to about 320dp, an example display size is about 160dp by 212dp).

> Yes, if you don't specific NONE strategy, Glide will try to cache the transformed image.

What is the default limit to the disk cache? The user can end up having quite a lot of covers (i.e. 3000 or more), all persisted to disk already, taking up quite a lot of room and ideally I won't have to have it double that.

> Again, you're using transformations by default unless you specified dontTransform().

So if I specify the frame size where an ImageView has fitCenter even though I don't tell Glide fitCenter() explicitly it will preload correctly?

> Most of the time it's a bad idea. Nothing can predict the size of the image on screen better than doing an actual layout... You'll be either under or overshooting the size, which will result in extra transformation on draw and hence potential quality loss of visible image.

Doesn't this contradict with what you just said about efficient loading?
