### ISSUE TITLE
Clearing resources

### ISSUE THREAD

**Issue by mattinger** [bumptech/glide#1890]
I have a flow which requires lots of animations across several activities.  What i'm noticing is that my memory usage is going through the roof (almost 5mb every time i show a new animation).  I'm deliberately clearing the animations on activity pause:

    Glide.clear(imageView)

As a result, I'm running out of memory on some devices (specifically a galaxy S5)

**Glide Version**:  3.8.0-SNAPSHOT

I'm not sure what i'm doing wrong here, but i can't really tell yet if GifDecoder is getting it's memory cleared, due to an Android Studio code mismatch :(

**Comment by TWiStErRob** [comment]
There was a leak re gif, but it was fixed in 3.7.0 (#892). How do you load your GIFs? How big are your gifs (byte and pixel size)?

**Comment by mattinger** [comment]
Glide.with(activity).dontAnimate().into(new GlideDrawableImageViewTarget(imageView, GlideDrawable.LOOP_INTRINSIC));

The largest of the images is 4439160 bytes and 750x530 pixels.  I realize that's probably quite large.

**Comment by mattinger** [comment]
I'm generally ok until i get into the instances that live in a view pager.

**Comment by TWiStErRob** [comment]
aaah, yeah, ViewPager is tricky, because it actually holds in memory and plays at least 2 of those large GIFs. The off-screen pages need to be treated as visible when dealing with memory!

Try to add `.diskCacheStrategy(SOURCE)` to the load to prevent excessive processing, maybe it will help to not re-encode those large GIFs.
