### ISSUE TITLE
Problem with StreamModelLoader

### ISSUE THREAD

**Issue by Sourav-21** [bumptech/glide#1911]
I am using Kinvey Backend service for my app. So I implement `StreamModelLoader` for loading images from Kinvey server. Here is the code-
```java
class ImageLoader implements StreamModelLoader<KinveyID>{
    @Override
    public DataFetcher<InputStream> getResourceFetcher(KinveyID kinveyID, int width, int height) {
        return new ImageFetch(kinveyID);
    }
    private class ImageFetch implements DataFetcher<InputStream> {
        private Client client;
        private InputStream inputStream;
        private String id;
        private String url;

        ImageFetch(KinveyID kinveyID) {
            //For getting Kinvey Client and image id and it is working perfectly
            this.client= kinveyID.getClient();
            this.id= kinveyID.getId();
        }

        @Override
        public InputStream loadData(Priority priority) throws Exception {
            //Following codes are for getting download url of the file
            client.file().downloadMetaData(id, new KinveyClientCallback<FileMetaData>() {
                @Override
                public void onSuccess(FileMetaData fileMetaData) {
                    url = fileMetaData.getDownloadURL();
                    Log.e("success", url);
                }

                @Override
                public void onFailure(Throwable throwable) {

                }
            });

            //I think problem is here
            inputStream = new URL(url).openStream();
            return inputStream;
        }

        @Override
        public void cleanup() {
            if (inputStream != null) {
                try {
                    inputStream.close();
                    inputStream = null;
                } catch (IOException e) {
                    Log.w("error", "Could not close stream", e);
                }
            }
        }

        @Override
        public String getId() {
            return id;
        }

        @Override
        public void cancel() {

        }
    }
}
```
and I use the following code for showing the images in imageview
`Glide.with(context).using(new ImageLoader()).load(new KinveyID(client, thumbId)).into(holder.thumbnail);`

But no images is showing in imageview. I checked with Log data that Kinvey returns correct download URL all times. I am using `URL(url).openStream()` for getting `Inputstream` from the URL. I think the problem is here. Is there any better way to get inputstream from URL?

**Comment by TWiStErRob** [comment]
First, add a `LoggingListener` from https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling to see what the actual problem is.

My guess is that `downloadMetadata` gives you the result on the UI thread, so the order of operations is:
 * `loadData`
 * `downloadMetadata`
 * `new URL(null)`
 * `url = getDownloadURL()`

if you add more logging you can confirm this very easily. see http://devcenter.kinvey.com/android/reference/api/reference/com/kinvey/android/AsyncFile.html#downloadMetaData(java.lang.String,%20com.kinvey.java.core.KinveyClientCallback(com.kinvey.java.model.FileMetaData))

The simplest hack is to wait for the file name sync, because the fetcher is on a background thread, so it's ok to block it:
```java
final CountDownLatch doneSignal = new CountDownLatch(1);
client.file().downloadMetaData(id, new KinveyClientCallback<FileMetaData>() {
                @Override
                public void onSuccess(FileMetaData fileMetaData) {
                    url = fileMetaData.getDownloadURL();
                    Log.e("success", url);
                    doneSignal.countDown();
                }   //                   ^ is called
            });     //                   |
doneSignal.await(); // blocks until -----/
// at this point `url` must be assigned and synchronized between threads because of `await`'s threading promises.
```

However, the above would be just improper use of Kinvey's API, and a waste of threading, consider using a blocking method instead:
```java
return inputStream = client.file().downloadMetadataBlocking(id).executeAsInputStream();
```

Another alternative is to use a pipe that flows bytes written by Kinvey to be read Glide:
```java
PipedOutputStream out = new PipedOutputStream();
PipedInputStream in = new PipedInputStream();
out.connect(in);
kinveyId.getClient().file().download(..., out);
return inputStream = in;
```

Remember: the `ImageFetch` constructor may be called on the UI thread, so I hope `getClient()` and `getId()` are not blocking. `loadData` is in the background and can be blocked to your heart's content.

Disclaimer: you may need to adjust the above slightly, because I only had the online Kinvey JavaDoc at my disposal and don't fully understand the difference between ID, filename and Query; never heard about Kinvey before.

**Comment by Sourav-21** [comment]
Thank you very much for your suggestion. First I used blocking method and it is not working. I got error log like this-
`D/skia: --- SkAndroidCodec::NewFromStream returned null`
I think the inputStream is not returning the data of image file.
Then I use the alternative method and it working fine. 
Before posting this question I used several method for converting OutputStream to InputStream, But I never tried Pipe. Thank you for the trick.

**Comment by TWiStErRob** [comment]
Hmm that `NewFromStream` may be a sign that the `InputStream` they return doesn't behave as we expect it to, for example you can't mark or buffer it. Not sure exactly what. Take a look at how `Downsampler` is trying to read the header and then rewind/reset and decode the image.

Another alternative is that you're getting the metadata as the `InputStream` contents and not the actual image bytes. The only way to figure out the root cause is to dump your stream and debug.
