### ISSUE TITLE
how does .override() decide bitmap's width and height?

### ISSUE THREAD

**Issue by ZekunWang** [bumptech/glide#1919]
I was having issue showing long image(larget height), getting `W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2432x4320, max=4096x4096)`. I read [https://github.com/bumptech/glide/issues/547](url) and updated the overridden size, then the issue was gone. But it confuses me on how the `.override()` method resize the bitmap.

Below is what I did:
Setting `Glide.with(context).load(uri).asBitmap().override(2048, 2048).into(simpleTarget);`
prints `bitmap width: 2432, height: 4320`, and gives `W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2432x4320, max=4096x4096)`.

Setting `Glide.with(context).load(uri).asBitmap().override(1024, 2048).into(simpleTarget);`
prints `bitmap width: 1216, height: 2160`, and shows image.

Setting `Glide.with(context).load(uri).asBitmap().override(1024, 1024).into(simpleTarget);`
prints `bitmap width: 1216, height: 2160`, and shows image.

Looks like setting `.override()` did affect the bitmap, but the calculation by Glide is very confusing.
@TWiStErRob Can you explain about how `.override()` affect the bitmap's size?

**Comment by JaydevM** [comment]
@ZekunWang 
Here is what i understand:
If you load image directly into an ImageView without glide, then it will follow width and height of ImageView.
In addition, you can specify [scaletype](https://robots.thoughtbot.com/android-imageview-scaletype-a-visual-guide).

Now if you use simple Glide into ImageView without `.override()`, It **looks** same as if Glide was not used, but in reality, Glide does these things:
1. Calculates width and height of ImageView.
2. Automatically puts ImageView\'s height and width into `.override()`
3. Generates a new bitmap with width and height mentioned in `.override()` (which was calculated in step-1)
4. Displays generated bitmap in ImageView.
5. Generated bitmap gets resized based on ImageView's scaletype. (**NOTE:** Generated bitmap has width and height same as ImageView\'s width and height. Hence, nothing happens to generated bitmap OR ImageView in this step, but Android still executes this step.)

Now if you use Glide with `.override()`, Glide does this things:
1. Generates a new bitmap with width and height mentioned in `.override()`
2. Displays Generated bitmap in ImageView.
3. Generated bitmap gets resized based on ImageView's scaletype. (**FYI:** If you don't explicitly specify scaletype, android will assume default value for it, which is "center inside" i think.)

**NOTES:**
- I'm not sure what happens in Glide when aspect rations of Image, ImageView and `.override()` are different. For that you can see [this](https://github.com/bumptech/glide/wiki/Transformations)
- If you want to cross check my answer, then use `.override(10,10)`. You will get low quality Image, but it will still fill 1216*2160 pixels on screen. (dimensions assumed based on your description.)

**Comment by ZekunWang** [comment]
@JaydevM thank you for your reply. But I was printing the bitmap's width and height and Glide should never know what image view I am going to set the bitmap to in the simple target callback. I can even just print the bitmap's size and do nothing.

But I still try `.override(10, 10)` and I did get a low quality image. But it is giving `bitmap width: 19, height: 33` instead of `10 and 10`.

**Comment by JaydevM** [comment]
@ZekunWang It makes sense from [this comment](https://github.com/bumptech/glide/issues/547#issuecomment-234507423).

> downsampling will happen to the nearest sampleSize just above the requested size

19x33 is almost same aspect ration of original image 2432x4320.
If you want exact 10x10 bitmap then try `.centerCrop()`. This will crop top and bottom of original image because height is higher than width in original image.
If you use `.fitCenter()`, it will give you bitmap with 6x10 OR 5x10 because it want to maintain aspect ratio.
If you want to break aspect ratio then use `.transform()` where you can manually scale you bitmap's width and height.

**Comment by ZekunWang** [comment]
@JaydevM Thank you very much

**Comment by TWiStErRob** [comment]
@JaydevM well quoted!

A few things to clear up in your first answer:

> If you load image directly into an ImageView without glide, then it will follow width and height of ImageView. In addition, you can specify scaletype.

It will render inside the ImageView, but note that there may be significant downscaling being done if the original Bitmap is bigger than the view. This is where Glide's magic of reading the laid out size and resizing an exact-fit Bitmap comes in.

> Generates a new bitmap with width and height

This sounds like magic at first glance, as you expanded in your later comment this is actually two steps:
1. decode with "nearest" sampleSize (see `Downsampler` implementations)
2. transform according to scaleType (if `into(ImageView)`) or explicit transformation (otherwise).

> If you don't explicitly specify scaletype, android will assume default value for it, which is "center inside" i think.

`fitCenter` is the default, see code of `ImageView.initImageView()`  
Note: this is also the reason why Glide shows the aspect-downscaled full image by default (`Glide.with.load.into`) instead of cropping it.

> I'm not sure what happens in Glide when aspect rations of Image, ImageView and .override() are different. For that you can see this.

Exactly, remember the above two steps, the transformation decides what to do. `centerCrop()` will match the size exactly by throwing away unneeded pixels, and `fitCenter()` will fit the image inside, but the Bitmap aspect will be different. You can write your own if these defaults don't fit your needs.

Take a look at https://github.com/bumptech/glide/issues/613#issuecomment-144762087, it may help or confuse you ;)

**Comment by nvmnghia** [comment]
@TWiStErRob Hi, I'm new to Glide. So basically Glide will decode, resize, and cache an *exact-fit* image for `ImageView`, right? I think Glide can only do so if `ImageView` scale type is known precisely, which rules out custom `ImageView`, or `ImageView` with `scaleType="matrix"`. Please correct me if I'm wrong. Thanks!

**Comment by TWiStErRob** [comment]
Yes, that sounds right, never thought about that. I'm not sure about v4's API, but in v3 you could have created a custom image view and wrote your own SizeDeterminer, that unprojected the laid out view size based on the matrix. Actually not sure why this wouldn't be built in to Glide, isn't all we need is to invert the marix and apply it to the size? Maybe because of translation, rotation, scaling combined, this is a hard problem. Anyway, a [custom view target](https://bumptech.github.io/glide/doc/targets.html#sizes-and-dimensions) could be all you need.
