### ISSUE TITLE
About cancel request

### ISSUE THREAD

**Issue by Caij** [bumptech/glide#1927]
GenericRequestBuilder.into()
```java
    public <Y extends Target<TranscodeType>> Y into(Y target) {
       .....

        Request previous = target.getRequest();

        if (previous != null) {
            previous.clear();
            requestTracker.removeRequest(previous);
            previous.recycle();
        }

        .....

        return target;
    }
```

Glide.clear()
```java
    public static void clear(Target<?> target) {
        Util.assertMainThread();
        Request request = target.getRequest();
        if (request != null) {
            request.clear();
            target.setRequest(null);
        }
    }
```
1. Glide.clear()     Why not recycle request?
2. Glide.clear()     Why not  requestTracker.removeRequest? if request in pendingRequests , then request cancel , it not check status in Request.begin(),  I think it can be designed like this Glide.with(content).clear(target) .

**Comment by sjudd** [comment]
Glide.clear() probably could recycle the Request, I can't recall any specific reason why it wouldn't. Glide.clear doesn't have a request tracker because it's a static method. That can't easily be fixed in 3.x but it is already fixed in 4.x.

Check on the 4.x branch and if you see any issues, feel free to send a PR. Thanks!
