### ISSUE TITLE
Image can not be displayed   url:  http://p3.pstatp.com/obj/2218000b57075b8ebfcd

### ISSUE THREAD

**Issue by kaka2009** [bumptech/glide#1964]
The picture of this address can not be displayed

http://p3.pstatp.com/obj/2218000b57075b8ebfcd

**Comment by sjudd** [comment]
Please fill out the issue template before re-opening.

**Comment by kaka2009** [comment]
what do you say? if you can not solve it,please do not close it

**Comment by TWiStErRob** [comment]
We don't have enough information, please edit your initial comment and fill in the [issue template](https://raw.githubusercontent.com/bumptech/glide/master/ISSUE_TEMPLATE.md). We can ask all those questions one by one, but it's easier if you just answer them before they come up. In general "it doesn't work" is not a technical issue report; at least a [log line or an exception](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling) should be available.

*(people on GitHub usually close issues without enough info, because most of the time there's no response to request for more details; that way we don't waste time with unanswerable questions, and we can move our efforts to other issues)*
