### ISSUE TITLE
[Question] Using the downloadOnly() API as alternative to cache any downloaded files?

### ISSUE THREAD

**Issue by bhargavms** [bumptech/glide#2008]
Would it be possible to use the downloadOnly() api to download and cache random files off the server? For example I download videos from the server and then if the video exists in the disk cache want to re-use it instead of downloading again, been looking for an easy to use API to do this and since I am already using Glide for loading images why not just use its caching module for caching other things too?

**Comment by sjudd** [comment]
You can actually, you just have to be ok with the behavior. Glide's disk cache is LRU, which means two things:

1. If you use downloadOnly one second and try to open the file the next second, you may not be able to find your file because it may have been evicted from the cache.
2. If the items you're downloading are large in comparison with your disk cache size, you may blow out Glide's cache and find that your cache hit rates for images/videos that are normally in the cache is very low.

1 and 2 are highly dependent on the number of items you're downloading, how large they are, and how much space you allocate to your disk cache.

**Comment by bhargavms** [comment]
Thank you very much for the swift response.
For point 1,  are you saying that the file could be deleted while it's being downloaded? As for point number 2, I am planning the cache size based on the size of the files that will actually get downloaded

**Comment by sjudd** [comment]
1. No the file can't be deleted during the download, but it can be deleted at any point after the download finishes.
2. Great!

**Comment by bhargavms** [comment]
1.Yes the files are deleted on LRU basis aren't they? So a new file that's just got downloaded is pushed to the end of the LRU queue isn't it? If there are other files ahead of it they would be deleted first wouldn't they?
