### ISSUE TITLE
MemorySizeCalculator is package private now?

### ISSUE THREAD

**Issue by minas90** [bumptech/glide#2011]
My app is memory intensive, so I halved memory size with a code like this in AppGlideModule.

        MemorySizeCalculator calculator = new MemorySizeCalculator(context);
        builder.setMemoryCache(new LruResourceCache(calculator.getMemoryCacheSize() / 2));
        builder.setBitmapPool(new LruBitmapPool(calculator.getBitmapPoolSize() / 2));

It worked on <= 3.8, but now the constructor is package private. Is there any good reason to make it package private? If no, please make it public again.

**Comment by TWiStErRob** [comment]
I think it was mistakenly public originally (or due to Java packages) based on the changes in this commit: https://github.com/bumptech/glide/commit/bf3d5a9fe15538191a9e0429afb8bbca837b3bca

Notice that there's now a `Builder` for it, so the API is more public and flexible than before.

Try `calculator = new MemorySizeCalculator.Builder(context).build()`.

**Comment by minas90** [comment]
Ok great. Thanks a lot for explanation!
Will take a closer look what is new in 4.0
