### ISSUE TITLE
.placeholder() not working when I use onResourceReady

### ISSUE THREAD

**Issue by giftonian** [bumptech/glide#2097]
**Glide Version 3.5.2**:
When I use onResourceReady(), my placeholder animation doesn't show up. Following is my code which is **NOT** working:
`Glide.with(this)
               .load(data.get(img_seq).get("URL"))
               .animate(R.anim.abc_fade_in)
               .error(R.drawable.not_found)
               .diskCacheStrategy(DiskCacheStrategy.SOURCE)
               .placeholder(R.drawable.progress_animation)
               .into(new SimpleTarget<GlideDrawable>() {
                   @Override
                   public void onResourceReady(GlideDrawable drawable, GlideAnimation anim) {
                       // Do something with bitmap here.
                       final ImageView iv = (ImageView) findViewById(R.id.qt_container);
                       iv.setImageDrawable(drawable);
                       Toast.makeText(getApplicationContext(),
                               "Image loaded successfully",
                               Toast.LENGTH_LONG)
                               .show();
                   }
               });`

// but the following code works fine, which shows my desired animation of placeholder

`Glide.with(this)
               .load(data.get(img_seq).get("URL"))
               .animate(R.anim.abc_fade_in)
               .error(R.drawable.not_found)
               .diskCacheStrategy(DiskCacheStrategy.SOURCE)
               .placeholder(R.drawable.progress_animation)
               .into(iv);`

**Comment by TWiStErRob** [comment]
If you remove the code that does the animation, it has no chance to run; notice you ignored the param `anim`.

Look into the source code of `into(ImageView)` and notice that it's using a complex target that's built-in to Glide.

If you want to "do something with Bitmap" that does not affect the result, try using a `listener` instead of a custom target. If you need to affect the result, consider either [simple to advanced]: 1) BitmapTransformation, 2) custom target which extends the defaults and overrides using super, 3) custom transcoder.

Also try out `.asBitmap()` if you're hacking (need to downcast) the bitmap out the drawable.

**Comment by giftonian** [comment]
Thank you @TWiStErRob . I am using `listener` now, it worked for me.

**Comment by dw129** [comment]
Glide 4.0 will not support this method. please check new implementation for placeholder

Glide.with(mContext).load(Uri.fromFile(loadedFile)).apply(**new RequestOptions()
                                                .placeholder(R.drawable.image_placeholder)**).into(textImageTypeViewHolder.imgView);

**Comment by TWiStErRob** [comment]
The same builder chain should work if you're using the [Generated API](https://bumptech.github.io/glide/doc/generatedapi.html)
