### ISSUE TITLE
BLOB images are not cached correctly

### ISSUE THREAD

**Issue by boylenssen** [bumptech/glide#2107]
I'm am loading a BLOB (from Azure) into an ImageView using Glide.

This is my code (it is in Kotlin, using RxJava and Retrofit)

            someApi.getImageForProduct(item.id, "unvalidated")
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe( {
                        Glide.with(itemView.context)
                                .load(it.bytes())
                                .apply(RequestOptions().diskCacheStrategy(DiskCacheStrategy.NONE))
                                .into(image)},
                            {error -> run { Timber.e(error) } })

It is loaded in an Adapter (for a RecyclerView). If I don't use `DiskCacheStrategy.NONE`, all the items in the list have the same image. What is going on here?

I'm using 4.0.0-RC1.

I tested it on a Nexus 5x.

**Comment by TWiStErRob** [comment]
Loading a `byte[]` is kind of a chicken-egg problem. To calculate the cache key we need the array, but the cache contains the array, so if we have it in memory to calculate the key, then what's the point of caching?!

@sjudd might know more. as far as I know all types of caching except memory should be disabled for arrays due to above reasons.

**Comment by boylenssen** [comment]
omg, this is quite stupid indeed! Why would I want to cache while I have the bytes already !
I'm just going to keep it like this I guess, i won't be able to check if the image has changed on the server or not
