### ISSUE TITLE
onResourceReady not working

### ISSUE THREAD

**Issue by ryandailey100** [bumptech/glide#2278]
Please don't close this issue until I get this working, as this is my third time having to ask the same question.

I cannot get this to work. I have followed this tutorial (https://futurestud.io/tutorials/glide-callbacks-simpletarget-and-viewtarget-for-custom-view-classes), but it still does not work. Maybe the tutorial isn't updated for Glide v4. I cannot find .asBitmap(), which is required for this to work according to the tutorial. Also, with the .into(target), I am getting an error message, as shown in the picture below. Please help as I need this working in order to release my app. Thank you.

<img width="736" alt="screen shot 2017-08-21 at 3 03 28 pm" src="https://user-images.githubusercontent.com/15038444/29533926-0a83d5aa-8682-11e7-9802-901ba0036857.png">

This is the code I have right now: 
`val target = object : SimpleTarget<Bitmap>() {

                        override fun onResourceReady(resource: Bitmap?, transition: Transition<in Bitmap>?) {
                            //Image Loaded

                            img_Post.setImageBitmap(resource)
                            view_Loading.hide()
                        }
                    }

Glide.with(layout).load(url).into(target)`

**Comment by ryandailey100** [comment]
Got it working! Just needed to add the .asBitmap() after .with() instead of after .load()

**Comment by sjudd** [comment]
Glad you got it working! The only previous issue I could find was closed because it didn't fill out the issue template. The additional details you've provided here are super helpful and give us enough information to provide a useful answer (though you don't need it :)). 

If you open issues in the future, this is a much better level of detail to provide than your other issue. Thanks again!
