### ISSUE TITLE
Why do you do？

### ISSUE THREAD

**Issue by adwilme110** [bumptech/glide#2289]
SupportRequestManagerFragment getSupportRequestManagerFragment(
      final FragmentManager fm, Fragment parentHint) {
    SupportRequestManagerFragment current =
        (SupportRequestManagerFragment) fm.findFragmentByTag(FRAGMENT_TAG);
    if (current == null) {
      current = pendingSupportRequestManagerFragments.get(fm);
      if (current == null) {
        current = new SupportRequestManagerFragment();
        current.setParentFragmentHint(parentHint);
        pendingSupportRequestManagerFragments.put(fm, current);
        fm.beginTransaction().add(current, FRAGMENT_TAG).commitAllowingStateLoss();
        handler.obtainMessage(ID_REMOVE_SUPPORT_FRAGMENT_MANAGER, fm).sendToTarget();
      }
    }
    return current;
  }

first,you add current,then you move it?

**Comment by sjudd** [comment]
Are you referring to this line?: https://github.com/bumptech/glide/blob/48754e616b85e2324117188c90307bb5fa708b70/library/src/main/java/com/bumptech/glide/manager/RequestManagerRetriever.java#L305

If so, ``ID_REMOVE_SUPPORt_FRAGMENT_MANAGER`` is used to remove the ``Fragment`` from ``pendingSupportRequestManagerFragments`` only, it doesn't not remove the ``Fragment`` from the ``FragmentManager``: https://github.com/bumptech/glide/blob/48754e616b85e2324117188c90307bb5fa708b70/library/src/main/java/com/bumptech/glide/manager/RequestManagerRetriever.java#L313.

This logic is necessary because we cannot use ``commitNow()`` or ``executePendingTransactions()`` because doing so causes recursive ``Fragment`` changes in some circumstances. Adding the ``Fragment`` to a temporary set allows us to avoid adding multiple ``Fragments`` if multiple loads are started during the brief period between when we first ``commit`` the ``FragmentTransaction`` and when the transaction actually runs.
