### ISSUE TITLE
using circleCrop() and thumbnail doesn't work well

### ISSUE THREAD

**Issue by monajafi** [bumptech/glide#2324]
I used following code and used both thumbnail and circleCrop() together:
```
GlideApp.with(MainActivity.this).load(url).thumbnail(0.1f).circleCrop().placeholder(R.drawable.manwh).transition(DrawableTransitionOptions.withCrossFade())
                            .into(riderImage);
```
the final image after loading get completed did not cropped completely inside circle , small blurred effects remains around circled image. the issue resolves by removing thumnail(0.1f) or .transition(DrawableTransitionOptions.withCrossFade()) 
also I don't see any thumbnail before loading original image

**Comment by sjudd** [comment]
What is riderImage? an ImageView?

**Comment by monajafi** [comment]
riderImage is ImageView

**Comment by sjudd** [comment]
Ah I missed that you're always using crossFade: http://bumptech.github.io/glide/doc/transitions.html#cross-fading-with-placeholders-and-transparent-images.

There's not much the library can do, you can either remove the cross fade or try to play with the sizes and scaling in your View so that the the thumbnail is displayed smaller than or equal to the full request.

If you have thoughts on how to improve this, I'd welcome them, but I can't think of a generic way to do this.

**Comment by monajafi** [comment]
I removed cross fading. the problem is now I don't see thumbnail image( smaller size) before loading original image. just original image shows here is the code I've used:
```
GlideApp.with(MainActivity.this).load(url).thumbnail(0.1f).circleCrop().placeholder(R.drawable.manwh)
                            .into(riderImage);
```

**Comment by sjudd** [comment]
The first time you load the thumbnail, Glide still has to generate it. It may take about the same amount of time to generate the thumbnail as load the full image. Subsequent requests should be much faster because the thumbnail is stored as smaller image in the disk cache.
