### ISSUE TITLE
Glide (v4.0) - How to check if cache is available or not?

### ISSUE THREAD

**Issue by jclova** [bumptech/glide#2362]
I am sharing the Glide image cache between the listView and the OpenGL.
If I already downloaded some images from loading onto an ImageView, I grab the cache path and display inside the OpenGL:
```
File file = Glide.with(context).download(imageUrl).submit().get();
```
Above line also "downloads" the image if not already downloaded.

I just want to know if the cache is available or not. 
Or only provide the cache path if available "without" downloading if the cache does not exist.

```
File file = Glide.with(context).asFile().load(imageUrl).submit().get();
```
I tried above code instead, but it still downloads if the cache does not exist.

Is there a way?

**Comment by sjudd** [comment]
You can prevent the download by using [``onlyRetrieveFromCache()``][1]. You can't get at the cache file if the image hasn't been downloaded though. I believe the Future will throw an exception if it fails to load the image from cache with ``onlyRetrieveFromCache()`` is set.

[1]: http://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/request/RequestOptions.html#onlyRetrieveFromCache-boolean-

**Comment by oakkitten** [comment]
while this works, retrieving the image from cache takes time. my layout depends on whether there is an image in cache or not, so it would help a lot if i could use the correct one right away (or at least earlier) instead of waiting for for the callback.

is there a way to check the cache without waiting for the drawable to load?
