### ISSUE TITLE
"Could not get unknown property 'sourceSets'" for disklrucache, why?

### ISSUE THREAD

**Issue by kangdawei** [bumptech/glide#2371]
Could not get unknown property 'sourceSets' for project ':third_party:disklrucache' of type org.gradle.api.Project. 
Open File

**Comment by TWiStErRob** [comment]
which branch? Did you follow the setup instructions from the branch's Readme?

**Comment by dede1314** [comment]
I meet the same issue. and how to solve this problem?
I use the latest relase  4.1.1.
Could anyone give me some advice? thx

**Comment by TWiStErRob** [comment]
Just to clarify, are you compiling Glide from sources, or are you getting this in your own project?

**Comment by dede1314** [comment]
I was trying to compiling Glide from source. this problem occured.

**Comment by AchillesPeng** [comment]
I meet the same issue.
@TWiStErRob 
Can you help me to solve this problem ? 
 thx

**Comment by DukeLee1989** [comment]
I also  meet the same issue.

**Comment by 103style** [comment]
i also meet the same problem in master branch when i build the source code  , 
use Android Studio 3.0.1 on Windows 10

**Comment by brianfpeters** [comment]
I saw same problem. I had unpacked the glide-master.zip file and noticed that  glide-master/third_party/ disklrucache directory was empty. I managed to get things working by downloading the version of disklrucahe refrenced [here](https://github.com/bumptech/glide/tree/master/third_party) into that empty directory. Android Studio built for me and I could run the svg demo. 

I suspect that github's zip file of a project does not like the sort of indirection to another project, but I am not certain.

**Comment by bernaferrari** [comment]
git clone git@github.com:bumptech/glide.git works
but downloading the archive from the page does not.

**Comment by TWiStErRob** [comment]
Follow the instructions here: https://github.com/bumptech/glide#build and it should "just" work.

If you're trying to build from ZIP files, you likely will have problems because not everything will be available. `-src` ZIP/JAR files are usually provided to be attached in the IDE for code navigation, not for build reproducibility. "Source code.zip" at the release page is the repo's source code, but there are git submodules present in the repo (see `.gitmodules` and `settings.gradle`), which cannot be fetched when built from ZIP because there's no `.git` folder.

If you want a specific version, just clone as described in Readme and then `git checkout <tag>` before `gradlew`. List of `<tag>`s can be found via `git tag`.

**Comment by nvquockhtn** [comment]
Try run `git submodule update` to make sure all submodules downloaded
