### ISSUE TITLE
Glide 4+: performance struggles when calling load on a File object

### ISSUE THREAD

**Issue by sheamartinson** [bumptech/glide#2372]
**Glide Version**: 4.1.1 (but has been an issue since 4.0)

**Integration libraries**: OkHttp, RecyclerView

**Device/Android Version**: All tested devices, which includes a variety of Galaxy and Nexus devices from 4.4 to 8.0

**Issue details / Repro steps / Use case background**:  For local files we have been calling load on a File object since Glide 3.6. After upgrading to 4.0 there has been a noticeable decrease in performance when loading thumbnails, particularly when loading thumbnails for video files. After changing the load call to use a Uri instead of a File, performance was back to normal. Changing the load call to use a Uri obviously isn't much of an issue, but it took a bit of time to figure out why performance was struggling so it might be worthwhile to investigate the issue because for some sending a File is just as intuitive as sending a Uri.

**Comment by sjudd** [comment]
Can you quantify the difference in performance? How much slower was using files vs uris?

Video decoding is the least changed in v4, it's determined mostly by the speed of Android's decoder.

For both images and videos, when given a media store Uri, we do try to load the corresponding thumbnail from MediaStore if it has been previously generated. If the size you request allows for it and the thumbnail already exists, it can be substantially faster. That's one way Uris can be faster than Files.

The only other major difference applies only to images. For images data from Uris is loaded with a buffered InputStream but data from Files is loaded from a ByteBuffer. Videos are always loaded with a FileDescriptor since that's what the framework API allows.

**Comment by sjudd** [comment]
I did a quick check of this on a Pixel running O in Glide's gallery sample app on v4:

https://docs.google.com/a/google.com/spreadsheets/d/e/2PACX-1vQVKs5NE90MccOraqN_6hHqsaLhhwQWWE-DQYH1SoU6x2LXtGcAq16BQQ2ua67x1YSQchfJuRxiy5dh/pubhtml

It looks like loading from Files is faster for the image size we're using, though there's not a huge difference. The sample set didn't include videos, though I could try throwing some of those in as well.

Here's the sizes the gallery sample was loading:
```
09-11 12:00:10.345 V/Downsampler(20659): Decoded [1053x1405] ARGB_8888 (6220800) from [3036x4048] image/jpeg with inBitmap [1053x1405] ARGB_8888 (6220800) for [1054x1478], sample size: 2, density: 1000, target density: 694, thread: glide-source-thread-2, duration: 196.396582
09-11 12:00:10.394 V/Downsampler(20659): Decoded [1079x1439] ARGB_8888 (6210724) from [3036x4048] image/jpeg with inBitmap [1079x1439] ARGB_8888 (6210724) for [1080x1478], sample size: 2, density: 1000, target density: 711, thread: glide-source-thread-3, duration: 277.086278
```

**Comment by sheamartinson** [comment]
Videos do cause the device to skip, the only uncertainty for me is whether it also applies to images. I didn't do any rigorous testing because I switched to loading media from Uris before I really got into it and I didn't have the patience at the time to separate images from video when throwing media at Glide. I did however run Systrace when first debugging the frame skips and saw that every noticeable skip resulted from a decode function.

It never really occurred to me that accessing media via File doesn't allow Glide the chance to grab thumbs from the MediaStore. I'm sure that explains the difference in performance.
