### ISSUE TITLE
当服务器返回一个字符串时候，占位图不显示

### ISSUE THREAD

**Issue by kamike** [bumptech/glide#2384]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Muyangmin** [comment]
你好，无意冒犯，但请注意两个问题：
* 在Glide论坛(以及其他你只看到English的社区里)，请尽量使用英语提问和交流，参见 #571 
* 请仔细阅读Issue templates里的注释，理解每段话的含义之后再提交，而不是直接写个标题就提交(这会导致像现在这样提交一些模板代码到issue中，很影响其他人理解)

---
No offense, but only warm tips:
* Please write comments in English here (and any other forum where you only see English entries by others), see #571 
* Please carefully read comments of Glide's Issue template, try to understand them and delete those you don't really need before you submit issues here. Otherwise you will end up with lots of unused contents.
---

> FYI, 以下文字节选自#571:  
@jimmyet Google translate only produces readable text if the sentences are simple, they also need to be grammatically correct and even then it mostly works only between latin languages in my experience. For example they can't contain literal names like "Glide" or tech words, like "webp"; because it's hard to figure out for an AI what they represent in a sentence. According to it you said: 
 Webp format you want to use, but does not support glide, write your own set of tools and found that many pit, Glide's request Great God who quickly support webp 
@start141 replied:  Haha, upstairs do not speak English, do not understand the big fear is God ah 
I don't really understand how "God" comes into picture when talking about image formats. Different word order in grammar of English and Chinese also produces kind of Yodaspeak. All in all the translated text sounds more like an really artsy poem than tech talk. 
 Please make your best effort to write comments in English here (and any other forum where you only see English entries by others), otherwise you're likely to have problems communicating your views. Worst case you can ask a friend to help translate if you don't speak English. Thank you for understanding! (I'm not a native English speaker either.)
