### ISSUE TITLE
 gif play slow on Android O(26)

### ISSUE THREAD

**Issue by Caij** [bumptech/glide#2389]
**Glide Version**: 4.1.1

 gif play slow only on Android O(26)

**Comment by sjudd** [comment]
All gifs? One particular gif? One particular device?

**Comment by Caij** [comment]
Part of the device.  but glide gif play slower than [android-gif-drawable](https://github.com/koral--/android-gif-drawable)

**Comment by sjudd** [comment]
It's only slow on one particular device? Which one? Or does glide generally play slower than android-gif-drawable?

I might expect Glide to be somewhat slower because Glide's decode is java only. If you wanted to though, you could write your own ``ResourceDecoder`` in Glide that used ``android-gif-drawable``'s decoders for your project, so you can get the best of both worlds.

**Comment by Caij** [comment]
Thanks. most device glide gif play slower than android-gif-drawable， the reason should be what you describe.
