### ISSUE TITLE
Rotate bitmap or byte array in place.

### ISSUE THREAD

**Issue by HBBrennan** [bumptech/glide#2416]
**Glide Version**:
4.1.1

**Device/Android Version**:
Galaxy S5

**Issue details / Repro steps / Use case background**: 
Is there any way to avoid copying a bitmap when rotating it?
Currently my app uses the CameraView api. The onPictureTaken callback passes the picture as a byte array. Currently I am converting it to a bitmap then rotating the bitmap with a matrix. This results in two 47MB bitmap allocations creating out of memory exceptions. The bitmap needs to be rotated for OCR parsing. Is there a way I can avoid this using Glide?

    private CameraView.Callback mCameraCallback =
                @Override
                public void onPictureTaken(CameraView cameraView, byte[] data) {
Matrix rotationMatrix = new Matrix();
rotationMatrix.postRotate(rotationAmount);

Bitmap img = BitmapFactory.decodeByteArray(data, 0, imageData.length);
Bitmap img2 = Bitmap.createBitmap(img, 0, 0, img.getWidth(), img.getHeight(),
                rotationMatrix, true);
}

I apologize for formatting.

**Comment by sjudd** [comment]
Do you need the full size Bitmap for OCR parsing? If not, you could downsample the image at decode time so you'd end up rotating a much smaller Bitmap.

Glide itself is stuck rotating the same way you are. Our only trick is that we try pretty aggressively to downsample images to match the size the user wants so that we're not allocating that much memory when we do it. Glide also re-uses Bitmap which can cut down on new allocations, though it won't change the fundamental amount of memory required for rotate a Bitmap of a given size.

If you're ok downsampling the image, Glide can help. If you only want to rotate the Bitmap at its original size, there's probably not much Glide can do for you.
