### ISSUE TITLE
Animated GIF makes lib heavy. Could we split it into new module such as "com.github.bumptech.glide:glide-gif"

### ISSUE THREAD

**Issue by anticafe** [bumptech/glide#2498]
**Glide Version**: 4.2

**Integration libraries**: No

**Device/Android Version**: All devices/versions

**Issue details / Repro steps / Use case background**: Animated GIF makes lib heavy. Could we split it into new module such as `com.github.bumptech.glide:glide-gif` - if advanced users need that feature, they can include it into project. Otherwise we won't need it.

**Comment by sjudd** [comment]
It's a big breaking change and it requires either a worse API or a heavy reliance on the generated API, but it's mostly done: https://github.com/bumptech/glide/pull/1798.

I haven't merged it because I wanted to see how the generated API goes first. It also turns out that it doesn't save much size in the library I think (I don't remember the exact numbers).

Why do you think it's especially heavy weight?

**Comment by anticafe** [comment]
Ah, if there is also a PR exists, then it's safe to close this issue. Sorry because I don't search before creating this one.
I mean "heavy" in feature, because most of user will use Glide to load image. There is no statistics on how many percent to use Glide with GIF yet, but I think it's less than 1%. IMHO, we should have Glide as core library for downloading image, while GIF can be an "extension" - if any bug in GIF library found, it would not affect to core library.
