### ISSUE TITLE
[Glidev4] disable write to disk cache but enable for read operation

### ISSUE THREAD

**Issue by oneroman** [bumptech/glide#2507]
Hi there,

I have one more question.
At some moment of time in an app I use default Glide's cache strategies, so I am sure that data is cached on Disk diffidently. 

Then I do `GlideApp.get(context).clearMemory();` and call `RequestOptions.diskCacheStrategy(DiskCacheStrategy.NONE)` for every request. I am expecting that the same images will be taken from disk cache, since they definitely there(due to initial default configuration), but I guess because I set Disk Cache to None, then it applies for both *read and write operations*. So, the behavior is I am seeing is that Glide continues to do network request.

Is it possible somehow to configure Glide still check disk cache before executing every network request (for read operation) and disable write as it is (in case of `RequestOptions.diskCacheStrategy(DiskCacheStrategy.NONE)`)?  

Thanks a lot!

**Comment by TWiStErRob** [comment]
You can inject your own cache wrapper that conditionally delegates the read/write methods based on a flag that you set.

Can you please explain why you would want to throw away hard-earned network bytes, instead of writing them to disk? And why are you clearing memory cache, didn't you mean to use `skipMemoryCache(true)`? But even why that?

(Answering why? instead of what? helps us to suggest better alternatives, if available, and you to think more about what you're doing and what you actually want to achieve.)

**Comment by oneroman** [comment]
@TWiStErRob Let me try to explain my scenario (I am trying to simplify it)

I have a server in local network which has image resources with *low quality* for my app. Also I have another server which have *high quality* asset for the same image resource.

So, the urls for the same
1) The app first of all talks to local server and requests an image. Because that image is low quality and server is locally, so I could get response very quickly, that's why I want to cache it only in memory and do not cache it on disk. that's why I do `RequestOptions.diskCacheStrategy(DiskCacheStrategy.NONE)`

2) then later on(I know exactly when) the app talk to second server which have higher quality asset for the same image, that's why I am removing whole memory cache and enabling disk cache and memory cache as well. So, user could see a image with better quality. (I use default instance of `RequestOptions`)

3) later when app will talk to local server then we already have that image cached on disk, so that's why I want to show it to user from the disk cache instead of requesting lower quality image from the local backend. So, by doing `RequestOptions.diskCacheStrategy(DiskCacheStrategy.NONE)` I expected that write to disk will be disabled, but reading will be enabled. Seems, that's not the case.


Also I should mentioned that as a key for cache for Glide I use latest part of urls. The key is `image_1.png` for the following urls (for remote and local servers)
http://localserver.com/**image_1.png**
http://remoteserver.com/**image_1.png**

**Comment by sjudd** [comment]
[``DiskCacheStrategy``][1] is an abstract class, so you can implement your own version of it if none of the defaults do what you want.

That said, in 3. above, it sounds like you want to read the low quality image from the disk cache, but don't want to request it from the server if it's not present. No ``DiskCacheStrategy`` can prevent you from making the request if the item isn't in the disk cache. Instead you can use [``onlyRetrieveFromCache``][2] and a normal ``DiskCacheStrategy`` so that you don't request the low quality image if you don't have it, but you do use it if it you do have it.

In particular you probably want to use the [``thumbnail()``][3] API with the low quality only from cache request as the thumbnail of the full quality request. 

For this to work you do need to make sure that the disk cache keys for the low and high quality images are different. If you can't do it any other way, consider [``signature()``][4]. See also: http://bumptech.github.io/glide/doc/caching.html#custom-cache-invalidation

[1]: https://github.com/bumptech/glide/blob/dd5f0f1944a20c436d3e600cdaee6059791ebb5e/library/src/main/java/com/bumptech/glide/load/engine/DiskCacheStrategy.java#L9
[2]: http://bumptech.github.io/glide/javadocs/420/com/bumptech/glide/request/RequestOptions.html#onlyRetrieveFromCache-boolean-
[3]: http://bumptech.github.io/glide/javadocs/420/com/bumptech/glide/RequestBuilder.html#thumbnail-com.bumptech.glide.RequestBuilder-
[4]: http://bumptech.github.io/glide/javadocs/420/com/bumptech/glide/request/RequestOptions.html#signature-com.bumptech.glide.load.Key-
