### ISSUE TITLE
Consider dropping Bitmaps when View not visible

### ISSUE THREAD

**Issue by shaybarak** [bumptech/glide#2520]
In many apps that I looked at, Bitmaps were the top contributor to RAM usage. Often times these Bitmaps are held by Views that are not visible, either because the app is not in the foreground, or because the View is tied to a Fragment that is currently not visible but also not destroyed.

I wonder if Glide could allow developers to specify that certain Views should aggressively release their Bitmaps when they're not visible, and re-inflate the Bitmaps when they become visible again.

**Comment by TWiStErRob** [comment]
`Glide.clear()/Glide.with().clear()` could help with this, as you know when the image becomes invisible/visible again.

I wouldn't worry about app not in foreground. Since each app has so little VM heap associated to it, there's no point in cleaning that up. It is all yours (and fully reserved to you, even if it's empty) until Android thinks to kill the whole process, at which point it doesn't matter any more how full your quota was.

**Comment by sjudd** [comment]
We actually used to do this in G+. It leads to a pretty substantial increase in grey squares/ui jank if users navigate back and forth between image heavy Activities. The image cache gets blown out quickly or has to be very large to make up for the difference. 

It's a good idea as an option or on low RAM devices though if developers have control over when it happens.

**Comment by sjudd** [comment]
@shaybarak I have something that might work, though it's a bit of a hack in its current form. Let me know if you have someone in mind who'd be interested in trying it.

**Comment by sjudd** [comment]
Added here: d0fd96780dccf00b5cffa43befa2d5566cacd1db
