### ISSUE TITLE
I can't get Glide to insert into TouchImageView

### ISSUE THREAD

**Issue by ImageViewGlide** [bumptech/glide#2525]
**Glide Version**:4.2.0

I have been trying to use glide in my app, but it won't load any images:

    Glide.with(this).load(urinormal).into(exampleTouchImageView);

before that I was using this code which worked fine:

    exampleTouchImageView.setImageURI(urinormal);

Using `Glide` with a normal `ImageView` also works, but I need zooming.

I also tried putting it into a bitmap, but I couldn't do that on the main thread and `AsyncTasks` get buggy here as I have a `ViewPager`.

**Comment by sjudd** [comment]
Does the ``exampleTouchImageView`` have a valid size? See [the debugging docs page][1] for tips.

[1]: http://bumptech.github.io/glide/doc/debugging.html

**Comment by ImageViewGlide** [comment]
I am now trying to use 
```
Glide
.with(this)
.load(urinormal)
.override(getActivity().findViewById(R.id.pager).getMeasuredWidth(),getActivity().findViewById(R.id.pager).getMeasuredHeight())
.into(exampleTouchImageView);
```

But I am facing some issues. First off, .override() doesnt resolve on 4.2.0, so I had to downgrade to 3.8.0 and remove the annotationprocessor. Not sure why, but this is the only thing that worked for me.

It now loads the images, but it seems that the size isn't quite right. On Some images I will get a really weird pattern that disappears if I insert lower number into .override(). 

Just to clarify I should insert the size that my view is allowed to take up in pixels, right?

**Comment by TWiStErRob** [comment]
[`override` is on `RequestOptions`](http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/RequestOptions.html#override-int-int-), so it should be available as a `GlideApp` builder method. Even if it's not you can always do `.apply(RequestOptions.overrideOf(...))` without APT.

**Comment by TWiStErRob** [comment]
The size of the target view is usually the target size, which means that Downsampler/decoder/etc are aiming to produce a Bitmap/Drawable with that size. ViewTarget automatically reads the view size to load the perfect size for a view. For TouchImageView this method of guessing is not correct, since you need to have more pixels in memory, because not the whole image is visible all the time (pan) and/or there's no 1:1 correspondence of Bitmap pixel to visual pixel (zoom). If you load with the view size as target size you'll get a low-res image that cannot be zoomed. Mostly the first thing to try is `.override(Target.SIZE_ORIGINAL)`, but be careful because that may be bigger than the max allowed texture size or the available heap size, if the input file is huge.

**Comment by ImageViewGlide** [comment]
Hello! Thanks for your help, it now works well enough for me with Target.SIZE_ORIGINAL. I also tried applying the size of my view and didn't see anything wrong with the resolution, even when I zoom in. But if I use it, a really weird pattern is created. It isn't an issue for me, but it would be interesting to know why if you can explain it. 

It mainly exists on pictures that have been taken by my camera horizontally, but there are exceptions and no other patterns.

[Original picture](https://i.imgur.com/sI772I5.jpg)
[Picture in View](https://i.imgur.com/mtZARFZ.jpg)
[Zoomed up View](https://i.imgur.com/PbnLUK5.jpg)
