### ISSUE TITLE
GIF load error

### ISSUE THREAD

**Issue by learner1999** [bumptech/glide#2531]
```java
GlideApp.with(this).asGif().load(R.drawable.hello).into(imageView);
```

```
10-30 14:52:02.063 5074-5074/com.example.glidedemo W/Glide: Load failed for 2130837587 with size [1080x1692]
                                                                      class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AssetInputStream->GifDrawable->GifDrawable}, LOCAL
                                                                          Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetInputStream->GifDrawable->GifDrawable}
10-30 14:52:02.063 5074-5074/com.example.glidedemo E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

My problem is same as #1849 , Glide 4.1.1 or 4.2 fixed it? What should I do to display the invalid file or as a bitmap? Thanks!

@sjudd @TWiStErRob

**Comment by sjudd** [comment]
We tend not to display invalid images. If you really need to display broken images, consider forking our GifDecoder I guess.

You're not getting a ``Bitmap`` here because you're specifically requesting a GIF using ``.asGif()``. If you want to try to fall back to a ``Bitmap``, you could leave that line off and just load a ``Drawable``. Depending on how corrupt the file is, that may not work if the GifDecoder reads too much of the stream before failing.

**Comment by learner1999** [comment]
Thanks a lot!
