### ISSUE TITLE
Custom ModelLoader question

### ISSUE THREAD

**Issue by frel** [bumptech/glide#2569]
Hi,

I have a renderscipt implementation that takes a POJO as input and generates a bitmap. ~~Currently I have a slightly hacky transformation implemented in order to load what I need, but~~ for what I'm doing it makes much more sense to load it like:

Thumbnail request: `thumbnailRequest = requestManager.load(pojo)`
Main request: `requestManager.load(imageUri).thumbnail(thumbnailRequest).into(imageView)`
 
The main glide request loads a normal URI (jpeg), but the thumbnail request should
load the pojo. I wish to use Glide for that since it handles the bitmaps already.

In Glide 4 how can I achieve that?

Thank you for any help!

Regards
Fred

**Comment by sjudd** [comment]
Are both your thumb and main request loading ``Bitmaps``? If so, this will probably work?
```java
requestManager
  .asBitmap()
  .load(imageUri)
  .thumbnail(thumbnailRequest)
  .into(imageView);
```

Otherwise can you share your hacky transformation? I'm not totally sure what isn't working?

**Comment by frel** [comment]
Apologies If I'm being vague.
The thumbnails request is loading a POJO. Not a bitmap. It's basically a color palette, but that's besides the point. The transformation right now does the same as a simple blur transformation, however it doesn't actually use the input bitmap.

**Comment by sjudd** [comment]
Ah got it, so the main request loads a Bitmap but the thumbnail request loads a POJO? 

Unfortunately Glide is type safe, so it might work if you do ``as(Object)`` and then write a custom Target that casts the Object it receives and does whatever you want it to do, but it does require casting. You won't be able to use ``into(ImageView)`` because ImageViews won't know how to display an arbitrary POJO. 

How do you use the color pallete? You might be able to write a Drawable that uses your color pallete and then add a decoder that decoders your custom Drawable instead?

**Comment by frel** [comment]
Hm, ok. I thought it was possible to add custom loaders, like the Flickr sample (although it's URI based).

I'm basically using a color palette to generate a four corner gradient. I actually used Drawables before, but in order to get the four corner gradient I needed to wrap ComposeShader inside another ComposeShader. Android doesn't support hardware acceleration for that, and thus the only way to get it to work was by disabling it. In short, the UI became really slow and animations was just not possible. 

The renderscript implementation solves that, but I'm now stuck handling the bitmap, which is what I would like to have Glide do :)

Thanks

**Comment by sjudd** [comment]
You can add custom loaders, but your Target has to have a specific type. In other words you can add as many ModelLoader<Type1, Type2> as you want (ditto for decoders), but a Target has a single type. As a result, RequestBuilder has a single type. If you can find a common super type, you can use a thumbnail. Otherwise you'll have a RequestBuilder<Bitmap> and a RequestBuilder<POJO> and a Target<Bitmap> or a Target<POJO>, which won't work because the types don't match.

How do you draw the gradient? Just on a canvas?

**Comment by frel** [comment]
Ok I see. Thanks for clearing that up. The renderscript implementation uses a pixel shader (root in renderscript) and creates the bitmap based on vector distances. The script then returns a bitmap and that bitmap is set on the image view. There is no canvas involved.

**Comment by sjudd** [comment]
So does your thumbnail request produce a Bitmap then? It goes POJO -> Bitmap? And your main request goes Uri -> BitmapDrawable?

**Comment by frel** [comment]
I'm afraid not. That's what I'm trying to achieve. Currently I'm not able to do this with Glide. I realise the transformation I'm mentioning is confusing. Just ignore that for now. What I'm trying to figure out is how I can use Glide to load a URI (bitmap), and as a thumbnail load a POJO that returns a generated bitmap.

**Comment by sjudd** [comment]
So you need the POJO on the main thread to then do something that turns it into a generated Bitmap? And that can't be done on a background thread in a custom ResourceDecoder or ResourceTranscoder?

If so, then I'm back to my original idea of using as(Object.class). You'll have to write your own ViewTarget subclass to handle the casting and it's not very neat, but it will probably work.

**Comment by frel** [comment]
It sounds like it might be a task for ResourceDecoder or ResourceTranscoder. That's what I'm trying to figure out :) I'll do some more research. Thanks for your help.

**Comment by frel** [comment]
Hi again, I've made a test repo just to figure out how I can approach this.  It builds, runs and crashes :) https://github.com/frel/GlideCustomLoader 

The issue I'm having is that when the resource is loading it crashes with `IllegalStateException: Can't compress a recycled bitmap`

The bitmap is created in PaletteDecoder. Please see https://github.com/frel/GlideCustomLoader/blob/master/app/src/main/java/com/subgarden/glidecustomloader/PaletteDecoder.kt

Do you have any ideas of what I'm doing wrong? Also, is this approach feasible?
Thank you
