### ISSUE TITLE
Memory management in deep activity stack

### ISSUE THREAD

**Issue by bsscco** [bumptech/glide#2684]
**Glide Version**: 4.3.1

**Integration libraries**: okhttp3-integration:4.3.1

**Device/Android Version**: AndroidStudio Emulator

**Issue details / Repro steps / Use case background**:  
The app I'm building is structured so that activities can be stacked indefinitely.
OOM is generated when lots of activities are accumulated.
Is there a way to release the Glide image from the first activity when memory runs out?
And when I get back to the activity in the front, I want to show the Glide image.

**Comment by vipinhelloindia** [comment]
**OOM** may be generated due to some other leaks. 
Use Android Studio Heap memory Analyzer to find the source where memory is consumed more and hold for long time . 
Glide Uses Bitmap Pool to avoid creating bitmap again to avoid redundant allocation. 
**Glide** has implemented Activity and Fragment Life Cycle Listener . Once You activity in background all the call will be paused .
I hopes you must be using **Activity** and **Fragment** Context instead of **ApplicationContext** . 
Android too manages kill and restoring or deep back stack Activity and Fragment , you can save your model and data in SaveInstance .

**Comment by sjudd** [comment]
There is no API that automatically clears views when memory is low and we probably wouldn't add one.

There are APIs that reduce the cache/bitmap pool size when memory is low via the ``ComponentCallbacks`` interfaces. 

You might be able to get some value out of [``clearOnDetach``][1], see [the Glide 4.4.0 release notes][2] for an example usage.

[1]: http://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/request/target/ViewTarget.html#clearOnDetach--
[2]: https://github.com/bumptech/glide/releases/tag/v4.4.0

**Comment by sjudd** [comment]
... and as soon as I said this someone else had the same request. It might be reasonable to clear out views from Activities that are no longer in view because they're far down the back stack. Arguably it would be better to fix deeply nested back stacks, but maybe that's not feasible in some applications.

**Comment by bsscco** [comment]
Thanks guys.

@vipinhelloindia I'm using activity and fragment context...
I call override() on every glide image if possible. That's because the loading speed is fast.
Could this be a major cause of poorly utilized bitmap pools?

@sjudd I have read your issue before. But I did not understand well...
Some apps that use Glide seem to have their Glide images turned off from the bottom of the activity when they have dozens of activities. This is because if I close the activities and return to the activity at the bottom, I can see that the Glide image is FadeIn. I want to know how to implement this.

**Comment by sjudd** [comment]
@bsscco the only automatic management Glide does to clear requests is in onStop. Even then only in progress requests are cleared. 

Other apps are probably implementing something manually? Maybe someone will share their solution?

One other thing you could use is try the new [``pauseAllRequests()``][1] API. It was added after 4.4, so you'd need to use the [``4.5.0-SNAPSHOT``][2] version until 4.5 is released. 

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/RequestManager.html#pauseAllRequests--
[2]: http://bumptech.github.io/glide/dev/snapshots.html#gradle

**Comment by bsscco** [comment]
@sjudd Thanks for your answer.
When the Activity is in the onStop state, it frees the memory using the Glide.with(context).clear(view) method, and when it is in the onStart state, it tries to reload using the Glide.load().into() method.
