### ISSUE TITLE
Unable to load large image when using Target

### ISSUE THREAD

**Issue by kafji** [bumptech/glide#2725]
Glide is unable to load large image when using `Target` instead of actual image view.

**Glide Version**: 3.8.0

**Integration libraries**: -

**Device/Android Version**: Fails on Samsung Galaxy J5/SM-J510FN, works fine on OnePlus 3T.

**Issue details / Repro steps / Use case background**: 
I'm trying to load a [large image](http://pancam.sese.asu.edu/images/Greeley_Pan_wDeck_L257F.jpg) using Glide. The image resolution is 23096x7981 px and the size is 98,8 MB. I successfully load the image when loading the image with ImageView as its target, but when I use `Target` as its target I get error message saying bitmap is too large to be uploaded into a texture.

Apparently when targeting ImageView Glide will [applies center crop or fit center transformation](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/GenericRequestBuilder.java#L688) which going to resize the image to ImageView size, but Glide is not doing that transformation when I'm loading the image to a `Target`.

My current solution is to apply the transformation manually:
```java
Glide.with(activity).load(new File(filePath))
    .transform(GifBitmapWrapperTransformation(Glide.get(activity).getBitmapPool(), new FitCenter(activity)))
    .into(target);
```

Is there any reason of this different behaviour?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Target target = new GlideDrawableImageViewTarget(imageView);
Glide.with(activity).load(new File(filePath)).into(target);
```

**Layout XML**:
```xml
<FrameLayout
  android:layout_width="match_parent"
  android:layout_height="match_parent">
  <ImageView
    android:id="@+id/imageView"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
</FrameLayout>
```

**Stack trace / LogCat**:
```ruby
W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (5774x1996, max=4096x4096)
```

**Comment by sjudd** [comment]
By default Glide applies power of two downsampling to downsample the image based on the ``Target``'s width and height. To preserve quality, Glide v3 downsamples images so that they are between 1x the requested size and 2x the requested size. In this case, the size of the view must be sufficiently large that 5774x1996 is the smallest size Glide can downsample without creating an image that's smaller than the view you're loading the image into. 

The transformation doesn't have the same power of two limitation, so it can scale the image to precisely the requested size, though it uses more memory to do so than the downsampler.

Glide v4 handles this a bit better and in most cases can downsample precisely by manipulating the BItmapFactory API to do a native scale of the Bitmap to a more or less arbitrary scale.
