### ISSUE TITLE
Save Image to file with correct orientation

### ISSUE THREAD

**Issue by ingsaurabh** [bumptech/glide#2759]
**Glide Version**:4.4.0

**Device/Android Version**: Xiomi mi A1/ 7.1.2

**Issue details / Repro steps / Use case background**: I am serving local phone images for casting but in some phones captured images have wrong orientation, so need to save file with correct orientation as, displaying same images with glide in ImageView produced correct orientation. 

  ```
FutureTarget<Bitmap> target = null;
                RequestManager requestManager = Glide.with(context);
                target = requestManager.asBitmap().load(metadataCompat.getString(MediaMetadataCompat.METADATA_KEY_MEDIA_URI)).submit();
                try {
                    serve = new File(Util.getAppDir(), "temp.jpg"); 
                    FileOutputStream fOut = new FileOutputStream(serve);
                    Bitmap bitmap = target.get();
                    bitmap.compress(Bitmap.CompressFormat.JPEG, 100, fOut);
                    fOut.close();
                    fOut.flush();
                } catch (Exception e) {
                    e.printStackTrace();
                    serve = new File(metadataCompat.getString(MediaMetadataCompat.METADATA_KEY_MEDIA_URI));
                } finally {
                    if(target != null) {
                        target.cancel(true);
                    }
                }
```

I am asking is there any better way to achieve above functionality?

**Comment by sjudd** [comment]
Glide doesn't really deal with writing Files. 

You should close the FileOutputStream in your finally block and probably wrap your FileOutputStream in a BufferedOutputStream (worth measuring at least), but otherwise this doesn't seem unreasonable if it's run on a background thread. At least Glide doesn't provide you with any other build in options for writing files.

**Comment by ingsaurabh** [comment]
Thanks Sam for letting us know, one more question you mentioned if running from background thread due to furture, how will the above can be achieved from main UI thread

**Comment by sjudd** [comment]
You can do the same thing, but use a custom ``Target``, obtain the ``Bitmap`` in ``onResourceReady()`` and kick off a new background thread to compress the ``Bitmap``.

**Comment by AllanWang** [comment]
@sjudd is there any application to using Glide to save images in its original size, and make use of the cache to retrieve duplicate calls without downloading the image again? Namely to avoid a bitmap target, as the images may theoretically be quite large. Or is it better in this case to simply use OkHttp and manage caching ourselves

**Comment by sjudd** [comment]
@AllanWang I'm not totally sure what you're asking, but it probably belongs in a new issue since it doesn't seem related to orientation? 

By default Glide v4 will save the original unmodified image to cache for remote images. OkHttp or other networking libraries are usually only useful for caching if they implement additional functionality that you need, like obeying various http headers.
