### ISSUE TITLE
Why image is constantly refreshing while loading the byte array into the image?

### ISSUE THREAD

**Issue by gelbertgel** [bumptech/glide#2761]
I have an image and if I load file path into imageView which isn't refreshing at every app starts or adapter refreshing. But loading byte array into same imageView that is constantly trying to load from image in this cases (every app starts or adapter refreshing). I want to be like downloading file path, not renewal.

Please help me.

I used 4.4.0 glide version. 

 ```
private void loadImageWithGlide(String filePath, ImageView imageView) {

        glideRequests.load(filePath)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .transition(withCrossFade())
                .into(imageView);
    }

    private void loadImageBytesWithGlide(byte[] imageBytes, ImageView imageView) {

        glideRequests.load(imageBytes)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .transition(withCrossFade())
                .into(imageView);
    }
```

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/javadocs/440/com/bumptech/glide/RequestManager.html#load-byte:A-.

By default memory caching and disk caching are disabled when loading byte arrays because there's no reasonable or efficient way for Glide to compare one `byte[]` to another. If you're planning on using exactly the same instance of the `byte[]` more than once, you can just use `skipMemoryCache(false)` and rely on instance equivalence. 

Otherwise if you can attach an identifier to your `byte[]`, define a custom POJO that contains the `byte[]` and the identifier and [write a custom `ModelLoader`][1] that loads your POJO types, using the identifier as the `Key`.

[1]: http://bumptech.github.io/glide/tut/custom-modelloader.html

**Comment by gelbertgel** [comment]
I rewieved your links very thanks. 

I would like to directly byte array into imageView and it is possible Glide v4. My question is how its caching image. It is provide that image loading is faster. Please help me

**Comment by sjudd** [comment]
The two paragraphs directly below the link address how you can add caching.
