### ISSUE TITLE
Warning:com.bumptech.glide.load.resource.bitmap.VideoDecoder: can't find referenced method 'android.graphics.Bitmap getScaledFrameAtTime(long,int,int,int)' in library class android.media.MediaMetadataRetriever

### ISSUE THREAD

**Issue by holoduke** [bumptech/glide#2807]
During a build i get the error:
Warning:com.bumptech.glide.load.resource.bitmap.VideoDecoder: can't find referenced method 'android.graphics.Bitmap getScaledFrameAtTime(long,int,int,int)' in library class android.media.MediaMetadataRetriever

with the following proguard settings
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

glide 4.5.0
buildTools 27.0.3
googleLibs 11.8.0
supportLib 27.0.2

Android 3 version 3.0.1

I reverted back to version 4.3.0 where the error does not happen.

**Comment by sjudd** [comment]
Can you include the full error message? Does the warning prevent you from building? What version of Android are you compiling against? 

See http://bumptech.github.io/glide/doc/download-setup.html#android-sdk-requirements.

If you're just seeing a warning, you can ignore it .The method in question was added in API 27.

**Comment by felislynx-silae** [comment]
I've stumbled on same issue here. Proguard is preventing here from successful build is there any proguard rule for that? or just ignore this one?

**Comment by sjudd** [comment]
@felislynx-silae can you answer any of the questions in my first comment?

**Comment by felislynx-silae** [comment]
compileSdkVersion 27
buildToolsVersion '26.0.2'
minSdkVersion 21
targetSdkVersion 21
implementation 'com.github.bumptech.glide:glide:4.5.0'
Without :  -dontwarn com.bumptech.glide.load.resource.bitmap.VideoDecoder in proguard rules, build is failed, with this  line, build is success.
Error message is like  holoduke wrote. Before this line some standard lint infos and after that message gradle output that build has failed because of proguard forces to fix this warning

**Comment by sjudd** [comment]
Does targeting API 27 fix the issue?

**Comment by felislynx-silae** [comment]
@sjudd Can't confirm that. Since GearVR had some strange requirement for manifest values like min/target = 21 :/ Other project which targets 27 works fine. But i don't think that should be a solution

**Comment by sjudd** [comment]
Yeah I realize targeting API 27 may not be a practical solution, but it's helpful to know as a debugging step. This is the first year we're being relatively aggressive about targeting new APIs and next year it's likely we'll be even more aggressive. Since we've already made the changes this year, hopefully we can use what we learn now to make next year go a bit smoother.

Probably adding dontwarn is the right answer here, but other ideas are welcome.

**Comment by holoduke** [comment]
Where do you add the don't warn then. in the proguard file? It is not causing any runtime exceptions?

**Comment by felislynx-silae** [comment]
@holoduke Yes, in proguard file. I've done full app checks with many scenarios before release. Right now, i don't see any crash reports :). So so far so good

**Comment by noState** [comment]
1. COMPILESDK_VERSION=27
   BUILDTOOLS_VERSION=27.0.2
   MINSDK_VERSION=16
   TARGETSDK_VERSION=27
2.# Glide4.5.0 支持API27以上,在不影响使用的情况下添加如下混淆
   -dontwarn com.bumptech.glide.load.resource.bitmap.VideoDecoder

**Comment by tekinarslan** [comment]
I added this ,resolved.
-dontwarn com.bumptech.glide.load.resource.bitmap.VideoDecoder
