### ISSUE TITLE
Best strategy to clear cache on Glide 4.5

### ISSUE THREAD

**Issue by willywijaya** [bumptech/glide#2841]
Hi, I'm new on using Glide.
I have a problem on updating new image from application drawable folder (not from url).
I'm using recyclerview with gridlayout to display image with Glide.
It was very fast loading image with Glide and scrolling does not lag anymore (I was using ImageView before and scrolling is a bit lag even crash on some devices.)

```
Glide.with(context)
.load(R.drawable.img)
.apply(requestOption)
.override(100,100)
.placeholder(R.drawable.placeholder)
.into(imageView)
```

When I try to change image to a new one with same name, Glide always using the old one.
Then I'm trying using diskCacheStrategy and skipMemoryCache:

```
Glide.with(context)
.load(R.drawable.img)
.apply(requestOption().diskCacheStrategy(DiskCacheStrategy.NONE).skipMemoryCache(true))
.override(100,100)
.placeholder(R.drawable.placeholder)
.into(imageView)
```

It works, but then the scrolling speed become a bit lag again, because it reload the images every time scrolling(Not save the cache). I have tried the signature approaching, but it is same as diskCacheMemory. So, what is the best strategy to update images? Why don't Glide destroy cache when isDestroy on app? Could anyone help me?

**Comment by sjudd** [comment]
Signature is your best bet, just increment the signature or use a new UUID or whatever each time the image changes.

You can also manually clear the disk cache with [``clearDiskCache()``][1] on a background thread.

See http://bumptech.github.io/glide/doc/caching.html#custom-cache-invalidation and http://bumptech.github.io/glide/doc/caching.html#clearing-the-disk-cache if you haven't already.

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/Glide.html#clearDiskCache--

**Comment by willywijaya** [comment]
What is UUID? There is no explanation on the doc.
Please give me example on using the signature.
I'm using this one:

`.signature(new ObjectKey(Long.toString(System.currentTimeMillis())))
`
This one make the scroll a bit lag.

**Comment by sjudd** [comment]
Using ``System.currentTimeMillis()`` will cause the disk cache key to change every time you load the image. Instead you only want to change the signature whenever you know that the image has changed. How exactly you do that depends on when the image changes.

If the image will only change when the application version changes, you can use [``ApplicationVersionSignature``][1]. Otherwise you can do something like generate a new [``UUID``][2] or increment an integer whenever the image changes. If go that route, you'll have to keep track of the current signature for each image somewhere.

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/signature/ApplicationVersionSignature.html
[2]: https://developer.android.com/reference/java/util/UUID.html
