### ISSUE TITLE
Get memory cache current size

### ISSUE THREAD

**Issue by SmasSive** [bumptech/glide#2921]
**Glide Version**: 4.3.1

Hello, on Glide version 3.7.0 I used to get for debug purposes the actual cache size, you can check it thought this repo: https://github.com/palaima/DebugDrawer/blob/master/debugdrawer-glide/src/main/java/io/palaima/debugdrawer/glide/GlideModule.java

As you can see, the author used reflection as in this issue states: https://github.com/bumptech/glide/issues/1403

So I was trying to do the same but for Glide v4 but with the same code, I'm getting a `currentSize` from `LruResourceCache` of 0, always... So I think something is broken or there has te be another way to get the current cache size.

Could you help me please?

**Comment by sjudd** [comment]
MemoryCache has a getCurrentSizeMethod: http://bumptech.github.io/glide/javadocs/460/com/bumptech/glide/load/engine/cache/MemoryCache.html#getCurrentSize--. Although we don't expose the `MemoryCache` in a getter, you can pass an implementation into `GlideBuilder` and retain a reference to it via a singleton or something similar and  use that for debugging.

Otherwise you're on your own for the reflection part, the memory cache is retained here: https://github.com/bumptech/glide/blob/53b5147d35b2365e66a8f328081618aeef9b78de/library/src/main/java/com/bumptech/glide/Glide.java#L107

**Comment by SmasSive** [comment]
Yes, I did just what you say but I was confused because I always got 0 bytes... But then I realised that going to a new screen and coming back to the original one the cache size increased, so my guess is that Glide only stores in memory the images that were visible but then they are not, like the images of the second screen.
This is just a guess... Maybe I'm wrong but now I can see the memory cache size.

**Comment by sjudd** [comment]
The `MemoryCache` only contains resources that aren't currently in use by a View or Target. If images are displayed in Views, those images are tracked in what Glide calls active resources. Only once the corresponding View or Target is cleared does the image end up in the `MemoryCache`. 

There isn't a direct way in the API to view the size of all the resources that are currently displayed in Views or Targets. If you think that might be useful, could you describe the use case?
