### ISSUE TITLE
Reasons to migrate from v3 to v4

### ISSUE THREAD

**Issue by AngleV** [bumptech/glide#2933]
First of all i must give my compliments for the authors of this awesome library.
About 2 years now i am using version 3.8.0 in one of my apps and it works flawless!!!

Last few days i decided to do some work to my app and starting to read the documentation for v4 of this library.
I discovered that the library v4 has a lot of changes in it's structure thing which means that i must do a lot of refactor in many areas of my app.

After changing to v4 in my gradle file and do a rebuild i get about 101 errors in different classes that makes use of Glide library. 
That means i have to spend a lot of time to refactor my code.

So my question is : Why should i upgrade to v4 ? Is it much better? Is it performs better and so on.

I would appreciate a straightforward reply from the authors about my thoughts.
Thank you

**Comment by Tolriq** [comment]
Rule number 1: Do not change something that works :)
Rule number 2: Try to no use deprecated things as it will break at some point :)

There's many reasons to migrate to v4 and sjudd will probably list some. But the fact that v3 is no more updated or really maintained is a reason by itself to start planing your migration because at some point there will be Android changes that will break v3 and you'll be forced to migrate in an hurry. Planning that before ensure that you'll always have support when you need.

BTW the fact that updating a library triggers so much errors means that you may want to implement things a little differently and use wrappers to avoid issues in the future (This is always true). The more you link a library to everywhere in your code, the more problems when that library is deprecated and you need to change it.
With v4 this decoupling is wayyyyyyyyyy easier.

**Comment by sjudd** [comment]
The simplest answer is what @Tolriq said, v4 is supported and we'll fix bugs and continue to improve it over time. v3 is no longer supported.

v4 does have better performance than v3 in a variety of ways. It has better downsampling logic that reduces memory usage when loading larger images, it allocates fewer objects, GIF performance is significantly improved etc. 

The biggest difference is in the API though as you've found. The API should allow you to avoid repeating yourself quite so much by sharing RequestOptions. The API also isn't as generics/subclass heavy so options are consistently available regardless of which type you're using. The generated API offers some more advanced configuration that help with fluency and consistency.

There's a lot more described in this relatively out of date design doc: https://docs.google.com/document/d/13jhhlAqcKU2kweY2PlKW8HMPgTxXvu3Qv8A8dPBJP0Q/edit#

**Comment by AngleV** [comment]
After spending about an hour refactoring i managed to migrate to v4.
The main problem was that the GlideApp class was not generated! 
After remove all GlideDrawable imports the class finally generated. 
The migration was easy then.
Also i found out something strange regardless contentLength and download progress  that i will discuss it in a new issue!
