### ISSUE TITLE
Question: HttpUriLoader and UrlUriLoader both used when image has 404: Expected?

### ISSUE THREAD

**Issue by calvarez-ov** [bumptech/glide#2943]
**Glide Version**: 4.6.1
**Integration libraries**: None
**Device/Android Version**: Robolectric environment
**Issue summary**: When attempting to load an https image which returns a 404 error, the request is performed twice.
**Issue details / Repro steps / Use case background**: 
I have a test case which requests an image url, and the server returns a 404 not found. I use Wiremock for the server.

The glide code in the test:
```java
        String url = "https://127.0.0.1:31626/static/country/FR/image.jpg";
        GlideApp.with(RuntimeEnvironment.application)
                .asBitmap()
                .load(url)
                .into(new SimpleTarget<Bitmap>(100, 100) {
                    @Override
                    public void onLoadFailed(@Nullable Drawable errorDrawable) {
                        super.onLoadFailed(errorDrawable);
                        System.out.println("error");
                    }

                    @Override
                    public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                        System.out.println("ready");
                    }
                });
```
I noticed from Wiremock logs that the request for the image is actually being requested twice.

When debugging, I noticed:

A `MultiModelLoader` is being used. Its `modelLoaders` field has six loaders, two of which are a `HttpUriLoader` and a `UrlUriLoader`.  In `buildLoadData()`, both of these match the `handles(model)` test, so their corresponding fetchers are added to the `fetchers` field. In this case both fetchers are of type `HttpUrlFetcher`.

I didn't follow the debugger further than this to understand more, but it looks like the first fetcher fails to load the image (the 404), and so the second one must be attempted (which will also fail with a 404). I'm not sure this is efficient. Is this expected?

**Comment by sjudd** [comment]
Thanks for pointing this out, super helpful. This is redundant, I'll look in to how easy it is to fix.

**Comment by calvarez-ov** [comment]
Is there any way to avoid this?

**Comment by dlew** [comment]
As far as I can tell, the fact that both loaders are used (in any situation) is a bug, because they way they handle Uris is identical. There is never any reason for both of them to run on the same model.

(Technically, one is generic and the other is not, but that fact is never used since both are `<Uri, InputStream>` in the registry by default).

Would you accept a PR where we get rid of one or the other (or at least, stop registering one of them by default)? I would probably get rid of `UrlUriLoader` since it's naming is more obscure and the generic doesn't get used.

**Comment by dlew** [comment]
As a workaround, you can replace Glide's default registry for `ModelLoader<Uri, InputStream>` minus one of the two duplicate loaders:

```
/**
* Reproduces Glide's default Uri/InputStream ModelLoaders, but minus the `UrlUriLoader`.
*
* `HttpUriLoader` and `UrlUriLoader` do the exact same thing and that can lead to double-loading the same (if the
* first model loader fails). There's no reason for that extra work.
*
* This implementation uses all the same registrations as [Glide], minus `UrlUriLoader`.
*/
private fun fixDoubleHttpModelLoaderInRegistery(context: Context, registry: Registry) {
  registry
    .replace(Uri::class.java, InputStream::class.java, DataUrlLoader.StreamFactory<Uri>())
    .append(Uri::class.java, InputStream::class.java, HttpUriLoader.Factory())
    .append(Uri::class.java, InputStream::class.java, AssetUriLoader.StreamFactory(context.assets))
    .append(Uri::class.java, InputStream::class.java, MediaStoreImageThumbLoader.Factory(context))
    .append(Uri::class.java, InputStream::class.java, MediaStoreVideoThumbLoader.Factory(context))

  if (Build.VERSION.SDK_INT >= 29) {
    registry.append(Uri::class.java, InputStream::class.java, QMediaStoreUriLoader.InputStreamFactory(context))
  }

  registry.append(Uri::class.java, InputStream::class.java, UriLoader.StreamFactory(context.contentResolver))
}
```

**Comment by sjudd** [comment]
I've seen this with other loaders as well. The issue, I think at least, is that Glide doesn't really understand specific failures. When a ModelLoader fails, the next matching one is attempted. This is fine in some cases where one really doesn't work at all (ie it's a video that can't be decoded from an InputStream). But it's not good when they're both going to fail the same way (certain http errors). 

One option might be to try to give ModelLoaders a way to indicate a recognized permanent failure (ie I know what this is and it's never going to work) but it's a little tricky to define that generically and I'd imagine it would be a breaking API change. 

We could also try to solve it more specifically for this problem. Maybe there's never a case where the UrlUriLoader is actually doing anything that isn't already handled by the HttpUrlLoader.

**Comment by dlew** [comment]
Interesting, yeah. I'm particularly interested in this case because [UrlUriLoader](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/UrlUriLoader.java) and [HttpUriLoader](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/stream/HttpUriLoader.java) are identical implementations (just parameter names are changed). They will always move in lock-step, except when the underlying network layer fails (in which case this becomes an accidental "retry twice" policy).

(I need to reproduce it so I can file it separately, but what originally lead me here was a race condition where a Fragment would go away, the first ModelLoader would be paused/canceled, but somehow the *second* ModelLoader would fire without ever having the cancel/cleared callbacks called, which was causing problems for us.)

**Comment by dlew** [comment]
Hello - I opened #4316 in order to fix this bug. Is there anything I can do to get it merged (so that stale bot stops trying to close it)?
