### ISSUE TITLE
Glide skips disk cache file of other processes

### ISSUE THREAD

**Issue by redmanit** [bumptech/glide#2956]
For some reasons my application uses more than one process and all of them use Glide to load images. I want to preload image in one process to use in other processes later so I tried using preload() or downloadOnly()
`Glide.with(...).load(...).downloadOnly(...);`
or 
`Glide.with(...).load(...).diskCacheStrategy(DiskCacheStrategy.SOURCE).preload();`

In other processes to load the preloaded images without connection
`Glide.with(....load(....asBitmap().diskCacheStrategy(DiskCacheStrategy.ALL).override
                            (...).transform(...).into(...);`
This call always fails unless I kill the app and call it again. So I think disk cache is not synchronized between processes because it doesn't check the cache file directly. How to overcome this issue?
Thanks

**Comment by sjudd** [comment]
I'm not actually sure. You can write your own [`DiskCache`][1] if you can figure out how to read from whatever cache directory Android is using for the other process. If it turns out that both processes are using the same directory, then it's possible that you have two different processes trying to use the DiskCache simultaneously, which is likely to break things because synchronization won't work across processes. 

[1]: http://bumptech.github.io/glide/doc/configuration.html#disk-cache
