### ISSUE TITLE
Support incremental annotation processing

### ISSUE THREAD

**Issue by stephanenicolas** [bumptech/glide#2983]
Gradle 4.7 provides support for incremental annotation processing.
https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing
Gradle feature discussion: gradle/gradle#1320

It would be nice to see glide's annotation processor supporting it. 

I started to have a look at the code and I was surprised to find such a complex annotation processing. I don't think I can do the PR quickly by myself. But I would be happy to provide all the information I can to help a maintainer doing it.

**Comment by CristianGM** [comment]
Is it happening? or just forgotten?

**Comment by bingranl** [comment]
@stephanenicolas Hi Stéphane, I am going to work on it and it would be great if you can help. I find it is an aggregating AP(e.g. Looking all types annotated with `@GlideExtension` to create GlideOptions.java and other source files). But it violates "Aggregating AP can only read CLASS or RUNTIME retention annotations" because `@GlideExtension` and `@GlideModule` are SOURCE retention annotations. Correct me if I am wrong. Thanks @sjudd

**Comment by stephanenicolas** [comment]
Hi @sjudd sorry, but it's à base timing. I am taking a month off. I can't
help.

Everything should vers pretty well documented on gradle's website.

I must say I got some doubts about the possibility of making glide's AP
incremental. I am not sure but it looks like an aggregating AP.

Don't take my words for granted though!
Good luck !
Si.
