### ISSUE TITLE
Android Studio 3.1 Glide 4.6.1 build failed

### ISSUE THREAD

**Issue by wl386123298** [bumptech/glide#2995]
implementation 'com.github.bumptech.glide:glide:4.6.1' 
annotationProcessor 'com.github.bumptech.glide:compiler:4.6.1'

failed message:
` glide <a href="openFile:D:/AndroidProject/PentaQ_Android/pentaq/app/build.gradle">Open File</a>`

**Comment by jerinamathews** [comment]
This error is happening when you update the gradle or android studio to the latest version. Heres the fix for this problem.

Check your project gradle file. If there's `jcenter` in repositories, remove it and build the project.
The project gradle will look like :


    allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

If the error came again, after removing `jcenter()`, add `maven { url 'https://maven.google.com' }` inside the repositories and build again.

This will solve your issue.

**Comment by wl386123298** [comment]
thanks , i have a try!

**Comment by Joslyn-Chen** [comment]
@jerinamathews I tried it, but this will cause problems with other libraries.
`Unable to resolve dependency for ':delivery@debug/compileClasspath': Could not resolve org.jetbrains.anko:anko-commons:0.10.4.`
and many more.

**Comment by bastolasushan** [comment]
After removing jcenter() , Error: Failed to resolve: com.android.volley:volley:1.0.0

**Comment by slobglob** [comment]
Same happens to me, tried the above - didn't work.
Anyone has a clue?

**Comment by wl386123298** [comment]
use glide 4.5.0 work for me

**Comment by Joslyn-Chen** [comment]
@wl386123298 Still have errors.
`Failed to resolve: glide
Open File`

**Comment by sjudd** [comment]
Maybe #3006?
