### ISSUE TITLE
Show last successful .error() image as placeholder during load

### ISSUE THREAD

**Issue by emilieroberts** [bumptech/glide#3003]
**Issue details**: 
I may be doing something wrong or this may be a feature request.

App shows a number of profile photos, each which have 3 possible urls (best, ok, poor) and then a fallback resource if none of the others exist. 

Loading with .error() works. On the first load, people without only "ok" or "poor" urls take a bit of time for the photos to show up. This makes sense.

However, on subsequent loads or while scrolling in a RecyclerView, it goes through the error chaining process again and the pictures show up blank again during the fetch, even if the view was just scrolled down and back up again.

I would hope that Glide would fetch and display the last successful image from the cache while it tries to fetch best_url again.  Is there a way to do this?

**Glide load line**:
```java
        RequestOptions requestOptions = new RequestOptions();
        requestOptions.diskCacheStrategy(DiskCacheStrategy.ALL);
        requestOptions.placeholder(R.drawable.no_profile_image);
        requestOptions.fallback(R.drawable.no_profile_image);
        Glide.with(context).asBitmap().load(best_url).apply(requestOptions)
                .error(Glide.with(context).asBitmap().load(ok_url).apply(requestOptions)
                .error(Glide.with(context).asBitmap().load(poor_url).apply(requestOptions)))
                .into(image_view);
```

**Glide Version**: 4.6.1
**Integration libraries**: None
**Device/Android Version**: Nougat, Oreo, Pixel XL, HTC 10

**Comment by sjudd** [comment]
It sounds like you want to use ``.thumbnail()`` instead of ``.error()``, or maybe in addition to if you only want the cached images to load until the primary load fails.

``.thumbnail()`` is eager, so it starts the loads in priority order and runs them in parallel. ``.error()`` only runs the load if the main request fails. You can use [``onlyRetrieveFromCache()``][1] and ``thumbnail()`` together to load the ok_url and poor_url as thumbnails only if they're in cache in parallel with loading best_url. You can then use ``.error()`` to load the ok_url without onlyRetrieveFromCache only if the main request fails.

It's going to be a bit clunky to get the nesting right for all three urls, but it should work. A helper method or methods would probably make it clearer.

**Comment by emilieroberts** [comment]
Thank you, this is exactly what I needed. I had misunderstood `.thumbnail()`. I used `onlyRetrieveFromCache()` with the thumbnail calls and ended up with something like this:
```
load(best)
    .thumbnail(ok)
        .thumbnail(poor)
    .error(ok)
        .thumbnail(poor)
    .error(poor)
```
And it works perfectly. Thank you!
