### ISSUE TITLE
ConcurrentModificationException when resuming requests

### ISSUE THREAD

**Issue by mjurkus** [bumptech/glide#303]
I have a scroll listener that pauses/resumes request loading when `ListView` is flinged.

And from time to time I keep getting crash like this:

```JAVA
java.util.ConcurrentModificationException
       at java.util.WeakHashMap$HashIterator.next(WeakHashMap.java:165)
       at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:68)
       at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:142)
```

Using version 3.4.0.

**Comment by sjudd** [comment]
Are you starting or canceling new requests when other requests complete? To do so you'd either have to be starting or canceling requests in a custom Target or RequestListener.

**Comment by neworld** [comment]
If I understand correctly this happens when one thread add item to queue while other thread is in progress of resuming (technically iterating through map)

**Comment by sjudd** [comment]
All of these methods are only called on the main thread. The concurrent modification exception occurs because calling resume on a request() either adds or removes an existing request from the tracker. I don't think Glide does this by default, but if you start or cancel a request when another request finishes, that's one way this might happen.
