### ISSUE TITLE
Issue with Gif Images resize using Glide library

### ISSUE THREAD

**Issue by murali219** [bumptech/glide#3031]
**Glide Version**: 4.6.1

**Integration libraries**: NO

**Device/Android Version**: LG G6/ Android 8.0

**Issue details / Repro steps / Use case background**: 

Basically I am using Glide librray to load the Gif images into my ImageView. I have few queries related to Glide librray w.r.t Gif.
1. Does Glide library resize original gif image passed? If so what is the criteria for resize and display in ImageView?
 -> Used below mentioned code block, but observed that Gif image is never resized, always original Gif is rendered  on the ImageView.

2. In case if Glide library resizes Gif images, how can i save the gif Image from GifDrawable so that i can use the resized Gif image for some other purpose in my code?( may be like sending the resized image to someone else)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(mContext)
    .asGif()
	.load(mUri) // Local uri present in the device
    .apply(new RequestOptions().placeholder(new BitmapDrawable(thumbnail)))
    .into(new SimpleTarget<GifDrawable>(250,250) { // Gif image is not resized even if mentioned new size.
		@Override
		public void onResourceReady(@NonNull GifDrawable drawable, Transition<? super GifDrawable> glideAnimation) {
		}
	});
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
GIF resizing/transforming is done by applying a transformation after each frame is decoded. 

You can use the GifEncoder library to write a compressed version of the transformed GIF: https://github.com/bumptech/glide/tree/master/integration/gifencoder/src/main/java/com/bumptech/glide/integration/gifencoder. Glide no longer supports GIF encoding by default because it's slow and tends to produce very large GIF files. Keep that in mind if you choose to use it.

**Comment by CrackerKSR** [comment]
Did you get success?
