### ISSUE TITLE
Glide is not showing to latest release via dependency update plugin for gradle

### ISSUE THREAD

**Issue by wezley98** [bumptech/glide#3156]
**Glide Version**: 4.8

**Issue details / Repro steps / Use case background**: 

Glide is still showing v3.6.1 as the latest version when using this plugin for gradle:
https://github.com/ben-manes/gradle-versions-plugin

The following dependencies exceed the version found at the milestone revision level:
 - com.github.bumptech.glide:glide [4.7.1 <- 3.6.1]
     https://github.com/bumptech/glide

Can this be updated on Glide's side please?

**Comment by ben-manes** [comment]
Please add Maven Central to your repository listing.

JCenter proxies fixed version queries to central transparently. Unfortunately for dynamic queries, `+`, it instead uses the locally hosted version. If a developer takes ownership of a dependency, e.g. to see the download stats, it then becomes fixed and updates stop occurring. This is because JCenter assumes the developer is switching the release process, not merely curious, and require the owner release the dependency back to Bintray to resolve this. In your case, you are seeing [sam-a-judd / maven / com.github.bumptech.glide:glide](https://bintray.com/sam-a-judd/maven/com.github.bumptech.glide%3Aglide).

The easiest is just to have Maven Central as a repository. Its usually faster and has management saner rules.

**Comment by wezley98** [comment]
Makes sense, thanks Ben.
