### ISSUE TITLE
AndroidX without Support

### ISSUE THREAD

**Issue by Semper-Viventem** [bumptech/glide#3229]
Hello!
Now, for Glide to work, you need to implement the Support Library. Tell me, how soon will it be possible to completely move to Android X without support library?

**Comment by Shusshu** [comment]
Once they release Glide 4.8.0

**Comment by friederikewild** [comment]
I can see [Glide v4.8.0](https://github.com/bumptech/glide/releases) was released yesterday. Following the comment by @Shusshu I checked the changelog and it does indeed mention a change regarding androidX...

@sjudd Does this mean a project relying on Glide can now be updated to use AndroidX without breaking? _By the way: It seems the github readme was forgotten to get the version bump since the doc still mentions to integrate v 4.7.1 ;-)_

**Comment by technoir42** [comment]
> Does this mean a project relying on Glide can now be updated to use AndroidX without breaking?

@friederikewild yes, 4.8.0 works perfectly fine with AndroidX and Jetifier. But be aware that there are some issues (unrelated to Glide) with Lint not recognizing some AndroidX stuff.
