### ISSUE TITLE
Why DecodeFormat has just Two Option?

### ISSUE THREAD

**Issue by tonyjs** [bumptech/glide#323]
Hello !

I'm using Glide thanks well.

I experienced a bug, When do not use DecodeFomat.ALWAYS_ARGB_8888 to Default Option.

I have two Questions.

DecodeFormat has Two Option, ALWAYS_ARGB_8888 or PREFER_RGB_565.

Why not has another Bitmap.Config?

And Why ALWAYS_ARGB_8888 option is default option to More than KITKAT ?

**Comment by sjudd** [comment]
The four available ``Bitmap.Configs`` are ``alpha_8``, ``argb_4444``, ``rgb_565``, and ``argb_8888``. alpha_8 is meant for masks and doesn't contain color information, so we don't offer it as a general use option. ``argb_4444`` was deprecated in API 13 because of [quality issues][1] and on newer platforms ``Bitmap.createBitmap`` will actually return ``argb_8888`` bitmaps even if you specify ``argb_4444``.

We allow *prefer* ``rgb_565`` rather than all you to *require* ``rgb_565`` because ``rgb_565`` doesn't include an alpha channel and can't be used for images that contain transparency. Finally, ``always_argb_8888`` is an option because it provides the highest quality and performance at the expense of some additional memory.

Second, ``always_argb_8888 ``is hard coded on KitKat and Lollipop to fix #301.

Feel free to re-open if this doesn't answer your questions.

[1]: http://developer.android.com/reference/android/graphics/Bitmap.Config.html
