### ISSUE TITLE
How to use LruBitmapPool

### ISSUE THREAD

**Issue by Euphrates-Media** [bumptech/glide#326]
Hi
I am newbie in Glide, how can I use LruBitmapPool?
Please provide a simple sample.
Thank you.

**Comment by sjudd** [comment]
If you simply use Glide and either re-use ``Views`` or re-use ``Targets`` to load multiple items, Glide will handle re-using Bitmaps with the bitmap pool for you. 

The only thing you can do with the BitmapPool manually (outside of custom components) is pre-fill it with Bitmaps if you know the sizes you're going to be requesting: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/Glide.html#preFillBitmapPool(com.bumptech.glide.load.engine.prefill.PreFillType.Builder...).

**Comment by Euphrates-Media** [comment]
Thanks for the reply.
How can I re-use targets?
And how can I make sure app is using Bitmap pool, any kind of logging?

Thanks again.

**Comment by sjudd** [comment]
Re-using a target is simple:

```java
Target target = new MyTarget();
// Sometime later:
Glide.with(fragment).load("url").into(target);
```

You can also see the readme for an example of how this works when re-using views in a ListView (and the same process applies for RecyclerView).

You can enable the [bitmap pool log tag][1]:

```
adb shell setprop log.tag.LruBitmapPool VERBOSE
```

Doing so will print every hit and miss. You can use ``DEBUG`` instead of ``VERBOSE`` to print only misses. 

[1]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/bitmap_recycle/LruBitmapPool.java#L22

**Comment by Euphrates-Media** [comment]
Thank, I'll try it and hope it solves my problem.

**Comment by sjudd** [comment]
Great I'm going to close this for now, feel free to re-open if you still have questions.
