### ISSUE TITLE
Target.SIZE_ORIGINAL is ignored

### ISSUE THREAD

**Issue by rayevg** [bumptech/glide#333]
I'm trying to load an original image into ImageView with code like this:
```java
Glide.with(context).load(url)
        .dontTransform();
        .diskCacheStrategy(DiskCacheStrategy.SOURCE);
        .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
        .into(imageView);
```

But it looks like ``` .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)``` line is always ignored here https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/request/GenericRequest.java#L258

**Comment by sjudd** [comment]
Looks like you're correct, thanks for the report. 

As a work around you can override  ``getSize()`` (add a subclass with an optional constructor?) in [``GlideDrawableImageViewTarget``][1] and pass in a new Target instead of just the view.

[1]: http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/request/target/GlideDrawableImageViewTarget.html
