### ISSUE TITLE
Custom model, data and transcoded types load fails

### ISSUE THREAD

**Issue by debugmoov** [bumptech/glide#3369]
**Glide Version**: 4.8.0

Hello,

I'm trying to add a custom model (let it be `Image`), data type (let it be `ImageData`), and to eventually get a custom object (let it be `AnchoredBitmap`)

I added `ImageModelLoader<Image, ImageData>` and `ImageDataFetcher<ImageData>` and `ImageModelLoaderFactory<Image, ImageData>` to load the image data.

I added `ImageDataEncoder<ImageData>` to encode the image data.

I added `AnchoredBitmapDecoder<ImageData, AnchoredBitmap>` to decode the image data to the anchored bitmap resource.

The loading failed, and I understood that I didn't add anything that load/decodes the data from the disk cache.

First question: Why the entire load fails if the inserting to the cache or extracting to the cache fails?
I mean, in the case that the data was loaded from remote anyway, I saw in the code that the data is retrieved from the cache even if it was just retrieved from the remote server.

Second question: What do I need to add so the load will succeed?

Because there is an implementation of `FileLoader<File, InputStream>` I thought I can added a `ResourceDecoder<InputStream, ImageData>` or `ResourceTranscoder<InputStream, ImageData>` but it didn't work.

Can you explain the flow of a load a little clearer?

**Comment by sjudd** [comment]
It depends on your DiskCacheStrategy. If you use NONE, then nothing will be written to the disk cache and your data will be loaded from whatever the remote source is directly.

If you use DiskCacheStrategy.ALL or DiskCacheStrategy.DATA, whatever data your ModelLoader retrieves will be written to disk and then decoded from disk. 

To answer your first question, if writing your data to disk fails, it's only safe to try decoding it if no data was consumed. Since we can't force every ModelLoader to buffer their data in memory, we can't assume that all of the data will be available to decode. There's also typically a reason why the write to the cache failed and there's no good reason to expect that fetching the data again will result in a different outcome. 

To answer your second question, you probably want a ModelLoader<File, ImageData> to match your non-cache flow as closely as possible. The flow is always the same, even for items decoded from cache (ie ModelLoader -> ResourceDecoder -> ResourceTranscoder). From cache though the model will always start as a File.

**Comment by debugmoov** [comment]
I have another question ( I'm sorry if maybe I should open a new issue for it)

I added a ResourceTranscoder<AnchoredBitmap, Bitmap> and if the request is used with `asBitmap()` it doesn't work but if I use with `as(Bitmap.class)` it works.

Is it intentional or is it a bug?

**Comment by sjudd** [comment]
It's actually kind of intentional, see `asBitmap()` here: https://github.com/bumptech/glide/blob/f7d860412f061e059aa84a42f2563a01ac8c303b/library/src/main/java/com/bumptech/glide/RequestManager.java#L356.

`asBitmap()` does two things:

1. It forces the output of your request to be a `Bitmap`
2. It forces the output of your ResourceDecoder to be a `Bitmap` (DECODE_TYPE_BITMAP)

Step 2 is helpful by default because it eliminates some redundant load paths that Glide might otherwise attempt that aren't likely to succeed. It's basically a performance optimization.

Whether it's worth keeping or not could definitely be up for debate.
