### ISSUE TITLE
question about performance

### ISSUE THREAD

**Issue by sahandmax** [bumptech/glide#3379]
hi to glide developers
i have question about glide performance in recyclerview
 my partner said it be better to use static requestOptions like below code

final static RequestOptions defaultGlideOptions = new RequestOptions().error(R.drawable.ic_launcher).placeholder(R.drawable.ic_launcher);

Glide.with(context).load(R.drawable.ic_launcher)
                    .apply(defaultGlideOptions)
                    .into(holder.productImage);

but i say using like below is better

Glide.with(context).load(R.drawable.ic_launcher)
                    .apply(new RequestOptions().error(R.drawable.ic_launcher).placeholder(R.drawable.ic_launcher))
                    .into(holder.productImage);

please help me in my way , thanks a lot

**Comment by sjudd** [comment]
The second example allocates a new RequestOptions object per request, the first does not. Allocating fewer objects is often preferable, especially on dalvik devices that don't have great GC implementations.

You could also just create an instance variable, rather than a static variable, for your RequestOptions.
