### ISSUE TITLE
Loading from Multiple sources

### ISSUE THREAD

**Issue by AkshayChordiya** [bumptech/glide#338]
Hi,

Thank you for this library. I just wanted to know if this feature exists : 
Here is what I require
1. Try loading the image from Source 1
2. If it fails then try loading from Source 2 else show the image
3. If everything fails then show Error image

**Comment by TWiStErRob** [comment]
As far as I know doesn't support as such, but you can emulate:
```
Glide
    .load(source1)
    .listener(
        success -> ignore,
        failure -> Glide
                   .load(source2)
                   .error(R.drawable.error)
                   .into(img)
    )
    .into(img)
```

Make sure to return the appropriate boolean so Glide knows you handled source1's error.

Another option is to use your own model (a data object with source1 and source2 fields) and write the Loader and DataFetcher classes so that it does what you described.

**Comment by AkshayChordiya** [comment]
Thank you.  I'll try that out.

**Comment by sjudd** [comment]
Let us know if you need any more help and we can re-open.
