### ISSUE TITLE
increase Timeout Period ; downloadOnly along with DiskCacheStrtegy.SOURCE and Retry and Timeout

### ISSUE THREAD

**Issue by amansatija** [bumptech/glide#348]
Right not the glide scoket timeout is 2500 ms 
I wish to make it 5000ms
How do I do this  ?

Also I wish to do a retry if timeout happens 

Also I am trying to use download only along with DiskCacheStrategy = DiskCacheStartergy.SOURCE

Please help me out withthese issues

**Comment by sjudd** [comment]
Glide's default networking library is meant to cover basic use cases.

Since you're interested in more control, I'd recommend you try either the Volley or OkHttp integration libraries. Volley in particular will let you set the number of retries and probably the timeout as well. See the [Integration Libraries][1] wiki page for more info.

[1]: https://github.com/bumptech/glide/wiki/Integration-Libraries#using-volley

**Comment by sjudd** [comment]
Let us know if you have more questions.
