### ISSUE TITLE
OutOfMemoryError  in GlideExecutor

### ISSUE THREAD

**Issue by usmanrana07** [bumptech/glide#3481]
Sometimes app crashes with following log details:

If there is OOM issue then it should skip loading or call onError method etc but should not crash.

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 60 byte allocation with 3048 free bytes and 3048B until OOM
       at android.util.Log.printlns(Log.java:567)
       at android.util.Log.e(Log.java:360)
       at com.bumptech.glide.load.engine.executor.GlideExecutor$UncaughtThrowableStrategy$2.handle(GlideExecutor.java:387)
       at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:448)
```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors

**Comment by joimxjtuse** [comment]
3048 > 60 , maybe the root cause is create thread fail.
about OutOfMemoryError question , i think: 
  check memory leak first;
  to some low version android machine, like 4.0.3, 4.1, I think we nearly cannot fix it,    
compare  users average use time to these crash users time, maybe we could accept it.

**Comment by usmanrana07** [comment]
But it should have option to ask for auto downsampling of image by using kind of thumbnail login to download resized photo. It should not crash atleast.
