### ISSUE TITLE
Remote image(google photos) orientation handling.

### ISSUE THREAD

**Issue by rraikarnvi** [bumptech/glide#3484]
glide-version
com.github.bumptech.glide:glide:4.8.0

devices :Motorola g6

os: android8.0

trying to load remote google image (https://tinyurl.com/y8u7b97p)
which if you download and check has exif with 270 CW orientation but this is not reflected when loaded through glide. 

expect：
Glide support for remote image rotation handling.

**Comment by sjudd** [comment]
Let me know if you're able to reproduce this in a test or a sample app.

**Comment by rraikarnvi** [comment]
Here is another url https://tinyurl.com/yb2ezqtt image. This image shows rotated with the exif data having 180 rotation. 
glide doesn't show EXIF segment for the 1st url but it shows EXIF segment in 2nd one(getExifSegment func)

**Comment by sjudd** [comment]
This is caused by: 

1. Incorrectly formatted files that include an orientation in an incorrect exif directory (IFD1)
2. A bug in Android's ExifInterface in Android P that respects the orientation value even though it's in the wrong exif directory.

I've filed a bug for the second issue for Android. You might want to explore why these images contain orientations in IFD1. If you have the images before they're uploaded, you should double check to make sure that the files were not modified after the upload.

We could try to work around this by running Glide's parser (which doesn't have the issue) preferentially over ExifInterface on P for JPEGs, but since these files are incorrectly formatted to begin with, it's probably not worth the trouble unless this is super common.

**Comment by rraikarnvi** [comment]
Thank you for the insight. The image which i had issue with was not taken from android P device but rather a old Samsung device prior to android P.
