### ISSUE TITLE
Default requestOptions of ViewTarget "CenterOutside" cause crash when loading a long and thin image

### ISSUE THREAD

**Issue by dss886** [bumptech/glide#3489]
**Glide Version**: `com.github.bumptech.glide:glide:4.8.0`

**Device/Android Version**: `MI 8, MIUI 10.1 (Android 9.0)`

#### Use case
I am using Glide to show network images. To hide loading on  `onResourceReady()` or show error image on `onLoadFailed()`, I used a custom DrawableImageViewTarget to get these callbacks as the code below:
```java
GlideImageViewTarget target = new GlideImageViewTarget(imageView);
Glide.with(mActivity).load(imageUrl).into(target);
```
#### Issue
In use I found that, displaying a long and thin image (like 1836 × 183px) will cause a crash (as the stack trace below), at the same time displaying a 1920 × 970px image works right.

```ruby
java.lang.RuntimeException: Canvas: trying to draw too large(183440400bytes) bitmap.
    at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
    at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
    at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
    at android.widget.ImageView.onDraw(ImageView.java:1360)
```
#### Reason
Debug on `onResourceReady()`, I found the size of resource/bitmap is 21450× 2138 (screen size of my device is 1080×2138). The direct reason of crash is Glide zooming the image in some way:
![image](https://user-images.githubusercontent.com/5170950/51373023-fa6c5400-1b39-11e9-9f79-e80f00dc1e83.png)

Continue to debug, I finally figure out that it is the default downsampleStategy of "CenterOutside" causing the bitmap be scaled bigger than expected.

![image](https://user-images.githubusercontent.com/5170950/51373498-54214e00-1b3b-11e9-9bef-56bdc6edfaeb.png)
![image](https://user-images.githubusercontent.com/5170950/51373520-5aafc580-1b3b-11e9-8a69-27a88a1695f9.png)

#### Solved
When I apply correct scaleType to the target, it works right:
```java
Glide.with(mActivity).load(imageUrl).apply(RequestOptions.centerInsideTransform()).into(target);
```

#### Questions
So I have three questions:
1. Why the default scaleType of ViewTarget is `CenterOutside`(when the default scaleType of ImageView is FitCenter)?
2. Why Glide choose scaling the bitmap to implement scaleType (instead of Matrix or some way else), which have a fair chance leads to OOM?
3. Why the bitmap will be scaled bigger than the image itself (image is 1836 × 183px and bitmap be scaled to 21450× 2138px)?

Thanks all!

**Comment by sjudd** [comment]
CenterOutside is the default because it preserves image quality. You get the choice in your default between preserving image quality and setting a maximum size. Since most images have a reasonable aspect ratio, we default to trying to preserve quality. 

CenterOutside upscales to try to maximize Bitmap re-use, assuming that most view sizes are uniform and most images are approximately the same size. In practice this isn't as important as it used to be and we could probably switch to defaulting to not upscaling. It would be a potentially unexpected change in behavior for callers, so it's not trivial to just do.

The scale type of the view isn't used because you're working around the logic that inspects the view by creating your own GlideImageViewTarget. If you just use ``Glide.with(mActivity).load(imageUrl).into(imageView)``, Glide will use the scale type of the view.

**Comment by dss886** [comment]
@sjudd I got it, thanks!
