### ISSUE TITLE
Gif memory not clearing

### ISSUE THREAD

**Issue by siddharthbhavsar** [bumptech/glide#3566]
**Glide Version**: 4.8.0, also tried 4.9.0

**Device/Android Version**: Samsung s8+

Im displaying Gifs in a grid view that lies in a view pager which is in a fragment. I am making sure I call Glide with(..).clear(imgView) with the correct 'with' and 'into'. I tried using DiskCacheStrategy.None, skipMemoryCache(true) and also tried useAnimationPool(false),
I also call the decoder (StandardGifDecoder)'s clear method to make sure it is legit clearing.
I need to display atleast 50 gifs and after two or three views of gifs, my memory goes above the roof.
Can you please look into this.

![image](https://user-images.githubusercontent.com/12777735/54485172-1a01cd80-489a-11e9-9ad0-d9fb18beba66.png)

**Comment by siddharthbhavsar** [comment]
I tried to dig into this, seems like GifDrawable's recycle() method is never called when clear() is called, should this be called?
If I manually call the drawable's recycle(), the view calls setVisible in GifDrawable which leads to a crash because of a pre-condition,

So should GifDrawable's recycle be called for clearing out memory?
Also, should GifFrameLoader's clear also be called for cleaning out memory?

**Comment by sjudd** [comment]
The recycle method is called when the corresponding resource is recycled. That happens when the gif is evicted from the memory cache, which will happen at some point after you clear the corresponding View/Target.

**Comment by biggerpan** [comment]
I'm amazed that this issue is not receiving more attention.

Still to this day, with version 4.13.2, every time a GIF gets loaded into an ImageView, the entire bitmap pool gets flooded with the GIF's frames and, as a result, the memory increases by over 200MB in less than 40 seconds on a Pixel 4. And that's for a single GIF. Now imagine rendering 10-20 GIFs at the same time and you get why it soon becomes a garbage collection hell, potentially causing OOMs and ANRs to many users.

Here's the code we are using, as you can see it's pretty basic:

```
glideManager
    .asGif()
    .load(url)
    .apply(RequestOptions.bitmapTransform(
            new RoundedCornersTransformation(radius, actualWidth, cornerType)))
    .transition(new DrawableTransitionOptions().crossFade())
    .addListener(requestListener)
    .into(imageView);
```

The bitmap pool system is great for speed, but don't you think there should be a way to dismiss it, or at least use a separate pool with faster and dedicated GC when it comes to GIFs?

<img width="1022" alt="Screenshot 2022-07-04 at 22 54 49" src="https://user-images.githubusercontent.com/8258992/177215694-86bff110-a546-44ee-89eb-66a41614c4bb.png">

**Comment by siddharthbhavsar** [comment]
I believe I resolved this issue by using with(Fragment) instead of activity.

**Comment by biggerpan** [comment]
Thanks for your reply @siddharthbhavsar. Unfortunately that doesn't solve the memory issue for us, and creates even more allocated objects as we're passing a different context for each image rendering, which must be leaking somewhere.
<img width="1022" alt="Screenshot 2022-07-08 at 11 52 52" src="https://user-images.githubusercontent.com/8258992/177966878-f987252b-01c2-4994-8bf3-4957f1bf9521.png">
