### ISSUE TITLE
not able to load remote svg file using glide

### ISSUE THREAD

**Issue by edcastrahul** [bumptech/glide#3598]
We want to load a remote svg image in our android project but i am not able to do. I followed [https://github.com/bumptech/glide/tree/8f22bd9b82349bf748e335b4a31e70c9383fb15a/samples/svg] the sample code provided by glide but when trying to load svg image i am getting below error.
com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 cause:
java.lang.IllegalStateException(Failed to find any load path from class android.net.Uri$StringUri to class android.graphics.drawable.PictureDrawable)
 call GlideException#logRootCauses(String) for more detail

1) Glide version : com.github.bumptech.glide:glide:4.9.0
2) android svg version : com.caverock:androidsvg:1.2.1

Anyone have any solution for mentioned problem then please let us know.

Thank you In advance

**Comment by axuan2015** [comment]
fix ok?

**Comment by kuldiep** [comment]
> Failed to find any load path from class android.net.Uri$StringUri to class android.graphics.drawable.PictureDrawable
> 
> This means you're trying to load a PictureDrawable from a Uri, but haven't registered the proper components with Glide to do so. See http://bumptech.github.io/glide/doc/configuration.html#registering-components

what to register as register component in glide module class?

**Comment by KunalKathrotia** [comment]
@kuldiep The custom module class is already there created in sample/svg. its SvgModule.java, you just need to add `annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'`
And Rebuild the project, that will generate GlideApp class and use that `GlideApp.with(this)`... to load svg instead of `Glide.with(this).`..

Also note that you might want to use `DiskCacheStrategy.DATA` if things don't work for you as that have fixed my problem.

**Comment by MuradHamidov302** [comment]
Try this verion (fixed for me)=>
implementation 'com.caverock:androidsvg-aar:1.4'
    implementation 'com.github.bumptech.glide:glide:3.8.0'

**Comment by farzadfarazmand** [comment]
@hamidovmurad 's solution works for me too, thanks

**Comment by AbiramiE** [comment]
Hi, I am still getting error. Can anyone please help me

Glide version : implementation "com.github.bumptech.glide:glide:4.15.1"
kapt "com.github.bumptech.glide:compiler:4.15.1"
Android svg version: implementation "com.caverock:androidsvg:1.4"

There was 1 root cause: java.lang.IllegalStateException(Failed to find any load path from class java.lang.String to class android.graphics.drawable.PictureDrawable)
call GlideException#logRootCauses(String) for more detail
Cause (1 of 1): class java.lang.IllegalStateException: Failed to find any load path from class java.lang.String to class android.graphics.drawable.PictureDrawable

**Comment by Kudlayra** [comment]
We can read in SvgDecoder from InputStream what string we get from server. In my case i was captcha

**Comment by pankaj9717** [comment]
> Hi, I am still getting error. Can anyone please help me
> 
> Glide version : implementation "com.github.bumptech.glide:glide:4.15.1" kapt "com.github.bumptech.glide:compiler:4.15.1" Android svg version: implementation "com.caverock:androidsvg:1.4"
> 
> There was 1 root cause: java.lang.IllegalStateException(Failed to find any load path from class java.lang.String to class android.graphics.drawable.PictureDrawable) call GlideException#logRootCauses(String) for more detail Cause (1 of 1): class java.lang.IllegalStateException: Failed to find any load path from class java.lang.String to class android.graphics.drawable.PictureDrawable

did you found any solution
