### ISSUE TITLE
Glide does not find images in drawable-night

### ISSUE THREAD

**Issue by frankyxcs** [bumptech/glide#3778]
Hi 

soon with Android Q the night mode will be very important in my opinion and it would be nice if you can fix this little problem. Glide does not find pictures in the following directories:

drawable-night
drawable-night-hdpi    (also mdpi, xhdpi, xxhdpi and xxxhdpi)

Greets

Frank

**Comment by michaelbukachi** [comment]
@frankyxcs Try using:
```
Glide.with(this)
            .load(ContextCompat.getDrawable(context, R.drawable.some_drawble))
```
instead of 
```
Glide.with(this)
            .load(R.drawable.some_drawable)
```

**Comment by hborders** [comment]
I'm having the same problem. If I use [michaelbukachi's workaround](https://github.com/bumptech/glide/issues/3778#issuecomment-517909978) it works fine for me.

Also, if I explicitly setting a different key for my `Drawable` doesn't work.
```
boolean isNightModeEnabled = ...
String key = (isNightModeEnabled ? "night" +  : "notnight") + drawableResourceId;
Glide.with(context).load(drawableResourceId).signature(new ObjectKey(key)).into(imageView);
```

Neither did explicitly setting the theme:
```
Glide.with(context).load(drawableResourceId).theme(context.getTheme()).into(imageView);
```

**Comment by neworld** [comment]
The main reason why are using Glide is that Glide handles OOM and also reduces fragmentation. Current workaround `.load(ContextCompat.getDrawable(context, R.drawable.some_drawble))` negates Glide benefits. We found an increase of OOM after this workaround. 

The problem why Glide is not working with the dark mode is because Glide loads images from the `application` context. Always.  Maybe we could work around on `Application`, but some activities have different day/night mode settings. 

Sorry for the friendly pinging you @sjudd, but I am really worried, what is the long strategy of this problem is? Is the problem too complex to be fixed, or just no one has a time for it (maybe we could help you).

**Comment by sjudd** [comment]
Duplicate of #3751
