### ISSUE TITLE
Disk cache and gifs

### ISSUE THREAD

**Issue by vovkab** [bumptech/glide#380]
Right now I'm using Disk cache SOURCE, since I want to reuse images, without downloading them multiple times. But then there is an issue with gifs, since now they are not stripped if I use asBitmap, they are now downloaded completely instead of first frame.

Do you know if there is a workaround for it, or maybe there is a way to set different disk cache strategies for gif and regular images?

**Comment by sjudd** [comment]
Unfortunately we don't support a way to change the disk cache strategy based on the content you retrieve (I assume you'd want to check the image header?). 

However, one option would be to write a custom [Encoder][1] that would look at the stream data and only write out the first frame rather than the whole GIF. If you [passed that Encoder in][2] to calls where you use ``asBitmap()`` that might help. Writing the Encoder isn't trivial, but also shouldn't be too bad. 

You can use  our [ImageHeaderParser][3] to check the type and just decode and then re-encode the first frame. You could also parse the GIF file yourself and skip the decoding step by just writing the first frame and dropping the rest of the data, though that would be more complicated.

[1]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/load/Encoder.html
[2]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/BitmapRequestBuilder.html#sourceEncoder(com.bumptech.glide.load.Encoder)
[3]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/load/resource/bitmap/ImageHeaderParser.html

**Comment by vovkab** [comment]
Thanks @sjudd 

But let's start with something simple :)

Let's say something like - per request disk cache strategy:
```
BitmapTypeRequest request = mRequestManager.load(url).asBitmap();
if (url.toLowerCase().endsWith(".gif")) {
    request.diskCacheStrategy(DiskCacheStrategy.RESULT);
}
```

As I understand correctly, now we should get first frame and save it to result, right?

Next we need to make sure we don't load this gif multiple times, according to documentation `override` should work, so I do:
```
BitmapTypeRequest request = mRequestManager.load(url).asBitmap();
if (url.toLowerCase().endsWith(".gif")) {
    request
        .diskCacheStrategy(DiskCacheStrategy.RESULT)
        .override(100, 100)
}
```

But it still load gif twice. @sjudd can you please help, maybe I'm missing something.

**Comment by sjudd** [comment]
Override only helps if you provide the same size consistently across the app. Since non source cache keys include the requested width and height, if they differ in any request, you will get a cache miss.

Try adding .override(100, 100) to your first request and it looks like it should work (again assuming all other options are identical for both requests).

**Comment by vovkab** [comment]
ImageView size is different each time of course, that is the point to use override...
Or maybe override doesn't actually override size?

**Comment by sjudd** [comment]
Override definitely overrides the size everywhere, both for the request and in the cache key.

**Comment by TWiStErRob** [comment]
By default (with ALL) the whole gif is saved in SOURCE and the resized first frame (asBitmap()) in the RESULT cache. You want to change the behavior so that the original sized first frame is in SOURCE and the resized first frame in RESULT. For this you really need your own cacheEncoder which you can conditionally attach if it ends with gif, as you both discussed above.

Note that Glide couldn't default to use such a cacheEncoder for gifs if asBitmap is used, since it would make it impossible to actually display the animated gif later (without asBitmap or with asGif), because only the first frame would be cached in SOURCE.

If you pick your biggest image view size and use that as override throughout the app, then you can save on RESULT cache space, but on the other hand you would load big Bitmaps even if the view is really small.

Just curiosity: why are you using animated gifs if you only ever display the first frame?

**Comment by sjudd** [comment]
Let us know if we can help further, I hope this was resolved!
