### ISSUE TITLE
Image orientation error when load image from network

### ISSUE THREAD

**Issue by TangKe** [bumptech/glide#387]
@sjudd when i load image from remote server, i found the orientation is error, using the version 3.5.2, and test image url: http://img13.360buyimg.com/ee/jfs/t1252/164/367048070/2578186/8ea03123/551cb4bdN0114fb62.jpg

i already check the exif info of this image, Chrome can display correctly

**Comment by TWiStErRob** [comment]
Woah, never seen this before: in android Chrome it was loading the bitmap lines in vertical columns from the right. This must be some exotic image.

**Comment by TangKe** [comment]
@TWiStErRob this image was captured by the camera of Samsung Galaxy 4, no modified.

**Comment by sjudd** [comment]
Thanks I'll take a look.

**Comment by sjudd** [comment]
It's actually due to lower server bandwidth I think. We're asking to read and/or skip small amounts of data in ImageHeaderParser and expecting (without verifying) that we skip/read the entire amount at once. In fact we actually only manage to read or skip some of the expected data. Since we fail to retry (ie continue to call read/skip while the return value is > 0) when we read/skip fewer than the expected bytes, we sometimes fail to correctly parse the image header.

Nice find, thanks for the report!
