### ISSUE TITLE
distorted image with dynamically sized image views

### ISSUE THREAD

**Issue by martinflorek** [bumptech/glide#388]
I have a list view (RecyclerView) with dynamically sized image views (just the height is changing). Every time before loading an image with Glide into an ImageView I set its aspect ratio (custom ImageView, where changing its aspect ratio calls "requestLayout()"). Due to list items recycling I often get a differently sized ImageView then its intended size and here the Glide loads a distorted image.

Problem is that Glide decodes the image for the previous size of an ImageView e.g. 400x300 and then puts it in the final (newly layouted) ImageView with a different size e.g. 400x400. The layout/measuring of the ImageView happens after the Glide takes its size for image decoding even though a requestLayout() was called on the ImageView.

I confirmed this with a RequestListener where in onResourceReady(...) method the GlideDrawable resource has the image view's old size e.g. 400x300 and the target ImageView has a new size here already e.g. 400x400.

How can I use Glide with dynamically sized image views? I tried layout(), invalidate() and other things instead of the requestLayout() but nothing worked. Or is this a bug in Glide?

**Comment by TWiStErRob** [comment]
Glide uses [`SizeDeterminer`](https://github.com/bumptech/glide/blob/v3.5.2/library/src/main/java/com/bumptech/glide/request/target/ViewTarget.java#L116) to capture the ImageView size, and since it first looks for a valid size, which yours have, it uses that rather than waiting for another layout. @sjudd, actually, SizeDeterminer could check if the view is currently waiting to be laid out (`isLayoutRequested`) and if that returns true, the sizes are invalid.

**My first impression for a quick workaround (hack?)**
I guess since you're using an aspect ratio you don't know what's the new size of the ImageView. But you're also saying that the width is fixed, so you can calculate the expected size:
```
width = iv.getWidth();
height = iv.getWidth() * AR; // or /AR
```
then you can use those two values in Glide's [`override()`](http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/GenericRequestBuilder.html#override(int, int))

**Another possible workaround**
Since you're using a custom ImageView, which decides size after first layout, that is not a "regular" `View`, you may need a custom `ViewTarget` implementation and load().into(that). Here you'd probably override [Target.getSize()](http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/request/target/Target.html#getSize(com.bumptech.glide.request.target.SizeReadyCallback)) and return your desired size, or more flexibly: make your own DelayedSizeDeterminer which is like SizeDeterminer, but always delays the size determination with a `.post(Runnable)` or the same way as ViewTarget/SizeDeterminer does.

**[XY problem](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem)?**
Using an ImageView with aspect ratio sound strange to me, but I don't know your whole story.
Check out [my answer on SO](http://stackoverflow.com/a/25069883/253468) regarding a similar problem. I hate hardcoding any value, so I always try to make best use of any layout framework I'm working in. Here of course you can replace "fill_parent" with a fixed width, it should still do the same.
If you use this method with the stock ImageView impl you don't need to worry about sizes, just `Glide...load()` as usual.

*Note: this is a best effort response, I wrote it from past experiences and Googling, didn't run any code today :)*

**Comment by martinflorek** [comment]
Thanks for the reply. I tried both good solutions, the "handler" and the "delayed size determiner". At the end I used the "delayed sized determiner" as it seems more robust to ask for `isLayoutRequested` instead of delaying it just onvce with `post(Runnable)`). Now it works flawlessly.

It would be great if the original `SizeDeterminer` would wait if there is a pending layout request.

Regarding the XY problem, it was a designer's choice to have fixed aspect ratio.

**Comment by sjudd** [comment]
Ideally to avoid your layout changing, you'd actually be able to set a size in dp on each view using the aspect ratio and some scaling factor.

However, it's not unreasonable that if you use a view without fixed sizes or with adjust view bounds set to true that our size determiner would recognize it should wait for a layout pass if one is pending.

**Comment by iqbalmuddassir** [comment]
I was facing the similar issue in list item, I solved it using override(width,height) while loading image into ImageView. You just need to know the width and height of the imageView before the request. I hope this would help others too.

**Comment by sjudd** [comment]
Glide v4.1 attempts to wait for layout. It causes some other issues because there are lots of spurious layout calls. v4.2 will try to work around some of the more common issues. The reality is that this is complicated enough that we're unlikely to be perfect by default no matter what.

The best answers are (if you run into broken behavior):
1. Use ``override()`` to specify common sizes across your app (maximizes cache hits too)
2. Use fixed dp view sizes
3. Subclass ``ViewTarget`` or ``Target`` and implement your own logic for determining size that works for your particular use case.

Since we did technically release the enhancement requested here, closing this for now.
