### ISSUE TITLE
Support contact uris

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#394]
http://stackoverflow.com/questions/29438701/how-to-load-a-uri-with-content-prefix-using-glide-android

**Comment by R4md4c** [comment]
I'm wondering, What do I need to know in order to be able to add this feature to Glide?

**Comment by TWiStErRob** [comment]
PR or for yourself?

**Comment by R4md4c** [comment]
Yes, a PR, I'd like to send a PR.

**Comment by TWiStErRob** [comment]
Cool :) 3.8.0 or v4?
(I'm going out now, I'll give you details later)

**Comment by TWiStErRob** [comment]
Just saw your update, check out https://github.com/TWiStErRob/glide-support/ in the meantime.

**Comment by R4md4c** [comment]
I guess 3.8.0 will be good, as this feature would reach many users who could be afraid of migrating to v4 when it gets released.

**Comment by TWiStErRob** [comment]
Thank you very much for coming with a request like this, it's awesome!

To start dev: first do [Build](https://github.com/bumptech/glide#build) (probably worth doing it on your fork). Then if it works in command line, then [Development](https://github.com/bumptech/glide#development).

This feature needs to be integrated into the leftmost arrow in [this flow](https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit)

Once your env is up take a look at `StringLoader`, `UriLoader` and its descenants. I think you'll need modify `getLocalUriFetcher` or `StreamLocalUriFetcher.loadResource` (latter looks more reusable) to check the authority (`Uri.getHost()`) and then load the best available version with `ContactsContract.Contacts.openContactPhotoInputStream` or similar. Use the latest available API with `SDK_INT` conditions.

A thing to look out for may be that this needs to work after this new feature is introduced (on API 14+):
```java
Glide.with(...)
    .load(Uri.withAppendedPath(contactUri, Contacts.Photo.DISPLAY_PHOTO)
```
because the authority matches, but it doesn't need to be pushed through `openContactPhotoInputStream` for it to work (it should work with current impl).

Useful resource for debugging: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling.

**Comment by R4md4c** [comment]
Thanks for the super helpful introduction! 

I'll try to do what I could, and I think I can do it, but I might ask some questions especially when writing tests. 

The branch that I should work on is 3.0, right?

**Comment by TWiStErRob** [comment]
Yep.

**Comment by R4md4c** [comment]
If I wanted to test loading a contact photo what is the best way to test? Do I create an application for that? or Do I use Robolectric? 

I don't know if Robolectric support testing a contacts Content Uri or not, any test class that might have a similary use case?

**Comment by TWiStErRob** [comment]
I think you should use Roboelectric and mock the ContentResolver to return a MatrixCursor with the right columns; for visual test/debug I guess you can modify one of the sample apps. @sjudd probably can tell you more about this.

**Comment by R4md4c** [comment]
For the time being I hacked an existing project to make that loading contacts works. 
I've had a look on how Picasso handling this feature and took the code from it, (I don't know if it was permitted to take code from Picasso or not).

It now supports these Uri variations.

```
/** A lookup uri (e.g. content://com.android.contacts/contacts/lookup/3570i61d948d30808e537) */
    private static final int ID_LOOKUP = 1;
    /** A contact thumbnail uri (e.g. content://com.android.contacts/contacts/38/photo) */
    private static final int ID_THUMBNAIL = 2;
    /** A contact uri (e.g. content://com.android.contacts/contacts/38) */
    private static final int ID_CONTACT = 3;
    /**
     * A contact display photo (high resolution) uri
     * (e.g. content://com.android.contacts/display_photo/5)
     */
    private static final int ID_DISPLAY_PHOTO = 4;
```

**Comment by sjudd** [comment]
Robolectric requires more or less mocking out the entire contacts provider. You can use it, but probably a better idea is to just create a small sample app. It can be as simple as just loading the contact photo from one particular contact, or just loading all of the contacts into a list.

**Comment by TWiStErRob** [comment]
Closing since #1119 is merged.
