### ISSUE TITLE
Load images through RemoteViews in widget not working in all cases

### ISSUE THREAD

**Issue by TomasValenta** [bumptech/glide#396]
**Glide Version/Integration library**: 3.5.2
**Device/Android Version**: LG G3/5.0.2 - AVD / 4.0.3 / 4.2.2

Hello,
I try to use AppWidgetTarget (#242,#248) to display image from server in widget and it's working, but I have problem with displaying image when widget is created. Not always, but in most cases, is not displayed. Only after refresh...
This is my implementation:
https://github.com/TomasValenta/WebCamViewer/blob/master/app/src/main/java/cz/yetanotherview/webcamviewer/app/widget/WvWidgetProvider.java
inspired by this Gist:
https://gist.github.com/pavlospt/00242d5102ac8f76e169

and working apk, if you want to try:
https://github.com/TomasValenta/WebCamViewer/releases/download/v2.2.0-rc.1/app-release.apk

**Comment by sjudd** [comment]
Hmm I don't actually have any apps that use RemoteViews, you're an early adopter! If you can debug AppWidgetTarget a bit, I'd love to know whether it's an issue with Glide (ie onResourceReady isn't being called), or whether we're doing something odd setting the Bitmap on the widget after onResourceReady is called.

**Comment by TomasValenta** [comment]
Hi Sam,

you are right! I tried simple debugging and when the image didn't show after configuration finished, then onResourceReady wasn't being called. But I do not know why. Sometimes onResourceReady is called, sometimes not.
![debugging](https://cloud.githubusercontent.com/assets/4901251/7064546/d552edde-deaf-11e4-877d-b5eee5254dd3.png)
Can I do something to help with this issue? This is my first debugging ;)

**Comment by TomasValenta** [comment]
Also interesting is this part. In Android developer guide says:
The onUpdate() method **will not be called when the App Widget is created** (the system will not send the ACTION_APPWIDGET_UPDATE broadcast when a configuration Activity is launched).

But when I see my log when creating widget:

04-09 12:14:53.544  onUpdate
04-09 12:14:53.561  onReceive

onUpdate is called immediately when configuration screen is shown. After configuration is finished:

04-09 12:14:53.612  SELECT * FROM webcams ORDER BY position
04-09 12:14:54.807  onUpdate

onUpdate is called again, but this behavior is expected.

Maybe this also related with the problem?

**Comment by TWiStErRob** [comment]
You have a lot of `.into()` calls. Try removing `onEnabled` and `onReceive` Glide calls and first focus on getting `onUpdate` to work. That `for` loop in the beginning is strange, do you display the same thing in all of your app widgets? When I wrote [my app widget](https://play.google.com/store/apps/details?id=net.twisterrob.sun) I had to update each `widgetId` that I got in `onUpdate` separately, because they have different preferences. This also means that using `componentName` could be the problem, I'm not even sure what it does, I was always using singular `appWidgetId`s everywhere.

Another guess... there's a comment on `AppWidgetTarget`:
> For cancellation to work correctly, you must pass in the same instance of this class for every subsequent load.

This probably means you would have to maintain a `Map<int/*appWidgetID*/, AppWidgetTarget>` cache and re-use the targets every time.

Also put `super.onReceive` in the `else` of `if (WIDGET_BUTTON`.

**Comment by TomasValenta** [comment]
Hi Róbert,

thank you for your suggestions. I use now only appWidgetIds and also I separated content things for each widget instance. See in: [WvWidgetProvider.java](https://github.com/TomasValenta/WebCamViewer/blob/master/app/src/main/java/cz/yetanotherview/webcamviewer/app/widget/WvWidgetProvider.java)

But the situation is same. When I create widget, then after configuration sometimes image is loaded, sometimes not. Widget refresh with onReceive method is always working correctly!

**Comment by TWiStErRob** [comment]
I was battling myself about that duplicate updateAppWidget call, but you should try calling it only once via Glide's target. See [your commit](https://github.com/TomasValenta/WebCamViewer/commit/79283bbc26098c29e22d104a6048c1041c8d4db6) for more comments.

**Comment by TomasValenta** [comment]
Sorry, I am not sure if I understand all your comments ;)

```java
Utils.clearImageCache(context);
```
is only for cleaning cache, I have removed it. Now to PendingIntent:

```java
PendingIntent pendingIntent = PendingIntent.getBroadcast(context, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
```

Documentation show me this info about zero position: requestCode - Private request code for the sender. I think, widget id is transfered in this code:

```java
intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, appWidgetId);
```

widget refresh is working fine also with multiple instances, refreshed is only selected widget. 

And when I use only loadImage without updateAppWidget:

```java
int[] ids = {appWidgetId};
AppWidgetTarget mAppWidgetTarget = new AppWidgetTarget(context, mRemoteViews, R.id.wImage,
		400, 400, ids) {};

Glide.with(context)
		.load(url)
		.asBitmap()
		.skipMemoryCache(true)
		.diskCacheStrategy(DiskCacheStrategy.NONE)
		.signature(new StringSignature(UUID.randomUUID().toString()))
		.into(mAppWidgetTarget);
}
```

, then Image and Title text is not shown. And refresh button is not working :)

**Comment by TomasValenta** [comment]
But I think, the important part is in this [comment](https://github.com/bumptech/glide/issues/396#issuecomment-91181609). Why is **onResourceReady** in **AppWidgetTarget** called only sometimes and not allways? Can I help with debuging this part?

**Comment by TWiStErRob** [comment]
@sjudd you can close this one, I solved the issues. It's not a Glide bug, more a lack of general app widget documentation.

I went ahead an installed the app on my phone (from github sources) and debugged what's going wrong. The symptom was that the requests he was expecting to display the images were being cancelled. When I put a breakpoint on `cancel` I saw that `Activity.onStop` was on the stack which is weird considering this is a provider...
It turns out that he was calling [`onUpdate` manually](https://github.com/TomasValenta/WebCamViewer/blob/79283bbc26098c29e22d104a6048c1041c8d4db6/app/src/main/java/cz/yetanotherview/webcamviewer/app/widget/WvWidgetConfigure.java#L75) letting the app widget configuration activity (as context) escape. I replaced it with an `APPWIDGET_UPDATE` broadcast and things started working.

**Comment by sjudd** [comment]
Great glad to hear it, thanks for looking into this @TWiStErRob!

**Comment by TomasValenta** [comment]
Huge thanks to @TWiStErRob! You helped me a lot! Thank you man for your great work!

**Comment by punyakakset** [comment]
Please would you mind provide me the alternative solution? 

this [link](https://github.com/TomasValenta/WebCamViewer/blob/79283bbc26098c29e22d104a6048c1041c8d4db6/app/src/main/java/cz/yetanotherview/webcamviewer/app/widget/WvWidgetConfigure.java#L75) doesn't work

@TomasValenta @TWiStErRob @sjudd

**Comment by TomasValenta** [comment]
I think you are looking for the WidgetProvider class. See this gist:
https://gist.github.com/TomasValenta/4645cb92fdc17ad1bd5e2dd21b145f6b

**Comment by yccheok** [comment]
Hi TomasValenta, I face the same problem as this thread.

https://github.com/bumptech/glide/issues/3340

I look at your gist. I think the only thing I didn't implement is use alarm to keep refreshing app widget. Is that the key action, which makes the images able display in home widet? Thanks
