### ISSUE TITLE
AVG and Avast anti-virus reports Glide library as malware

### ISSUE THREAD

**Issue by mikezliu** [bumptech/glide#4131]
Starting today, AVG and Avast (which have hundreds of millions of downloads) started reporting my apps that use Glide (4.8.0 and 4.11.0) as malware. I reported it to them already, but don't expect a quick fix.

When I replaced Glide with Picasso, the apps are no longer marked as malware. I've already received about 10 bad reviews and dozens of e-mails about this issue and have not updated my app recently, which leads me to think they updated their algo very recently.  I have tried disabling proguard but it makes no difference.

Just FYI in case anyone else hits this issue. I spent about 6 hours paring down the issue to Glide, removing one library at a time.

**Comment by mikezliu** [comment]
Opened ticket with AVG

**Comment by mikezliu** [comment]
Reopening since AVG did not reply

**Comment by joelfernandes19** [comment]
@mikezliu Any updates on this?

One of the apps that I use was flagged as malware. Turns our this app uses Glide for image loading. Not sure if this is because of Glide lib. 

- Device: Asus ROG Phone 2
- OS: Android 9
 
<img src="https://user-images.githubusercontent.com/4933738/76500204-21849400-6466-11ea-90b0-6277a7f7db66.png" width=250 />



P.S. Had to conceal app name

[reddit discussion](https://www.reddit.com/r/androiddev/comments/fe35hv/glide_image_library_being_reported_as_malware_by/)

**Comment by mikezliu** [comment]
AVG is not helpful, I called them, escalated to the supervisor, they said they changed the ticket to the highest priority, and I haven't heard a reply after 1+ week.

**Comment by sjudd** [comment]
I'd expect to see more reports if every app with any version of Glide was reported as malware and it was fixed by removing Glide. I haven't heard anything about any of the Google apps that use Glide.

I wonder if there's some specific combination of libraries? I'm open to ideas on what I can do, but at the moment I'm inclined to close this because I'm not sure there's anything actionable for me.

**Comment by cikaldev** [comment]
Sory for bumped up Closed issue, im facing same problem here. Today i build apps using Glide and Retrofit, but my phone that i used for testing. Reported my app as a malware. (i'm run the app on Android 10 and 9)

My app in general is Consume API from my server (HTTPS) and Showing image using Glide,

This is my app dependencies :
- Glide version 4.14.2 _(latest from repo)_
- Retrofit and Gson Converter 2.9.0 _(latest from repo)_

Android Studio Dolphin | 2021.3.1

![Screenshot 2022-10-16 at 12 27 51](https://user-images.githubusercontent.com/41433325/196019684-9ad16d57-4d70-4444-8779-12b6ac09e146.jpeg)

**Comment by maximeduvey** [comment]
Is this thread resolved?
