### ISSUE TITLE
Glide 4.11.0 ProGuard QMediaStoreUriLoader$QMediaStoreUriFetcher Error

### ISSUE THREAD

**Issue by eawedat** [bumptech/glide#4158]
**When I try to sign the apk, I get these two error messages:**

`com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher: can't find referenced method 'boolean isExternalStorageLegacy()' in library class android.os.Environment`

`com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher: can't find referenced method 'android.net.Uri setRequireOriginal(android.net.Uri)' in library class android.provider.MediaStore`

**I went through these two issues, but they are different error messages**

https://stackoverflow.com/questions/46232898/proguard-error-after-adding-glide-v4

https://github.com/bumptech/glide/issues/2807

**Comment by TWiStErRob** [comment]
I'm guessing you're using an older API level. Change `compileSdkVersion` to the latest available, but at least 29 (Q/10). These classes are meant for interacting with Q only (hint in name). Proguard needs to know what the methods are referenced in that class.

You can safely change compileSdkVersion, it shouldn't affect user behaviour at all. You may see more deprecation warnings.

**Comment by eawedat** [comment]
I learned little about proguard rules,
What about keeping the compileSdkVersion, and adding these two rules?

-keep class com.bumptech.glide.load.model.stream.** { *; }
-dontwarn com.bumptech.glide.load.model.stream.**

What is preferable?

**Comment by TWiStErRob** [comment]
Ignoring problems usually not a good idea, because symptoms can accumulate. You ignore this, and then something else could break because if this, but it could be very hard to find. Fixing the root cause is mostly a better solution, than ignoring/working around. Although in every case you have weigh both.

In this particular case changing the `compileSdkVersion` should be a really easy task, and you will need to do that anyway, eventually. So you can get ahead, and solve two problems. Note that "compile" version is not the "target" version, so it's not going to change compatibility behaviours, and no need to implement anything extra. It literally changes the jar file that is the Android SDK; so IDEA, the compiler, and proguard will see the classes and methods from the latest SDK.

Note: If you go with the workaround, you don't need to `-keep`, just `-dontwarn` to let Proguard know you know this is safe. You tell it that you trust the library author that whatever non-existent (new) method/class they used is correct and will work fine. The difference when changing the `compileSdkVersion` instead of `dontwarn` is that you give proof to Proguard why you trust the author and it'll trust too.
