### ISSUE TITLE
Proper handling of special cases

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#418]
I have some places in my app where I have no way to know the aspect ratio of the image before having the image.

On android side I use a little hack to have all working on all android versions : 

```
                            <FrameLayout
                                android:id="@+id/info_media_thumb_container"
                                android:layout_width="@dimen/info_media_now_playing_thumb_width"
                                android:layout_height="wrap_content"
                                android:layout_marginBottom="-13dp"
                                android:layout_marginLeft="@dimen/info_media_padding_internal_image"
                                android:layout_marginRight="@dimen/info_media_padding_internal_image"
                                android:layout_marginTop="@dimen/info_media_thumb_top_margin"
                                android:background="@drawable/image_background"
                                android:clickable="false"
                                android:clipChildren="false"
                                android:clipToPadding="false"
                                tools:layout_height="@dimen/info_media_now_playing_thumb_width">

                                <ImageView
                                    android:id="@+id/info_media_thumb"
                                    android:layout_width="match_parent"
                                    android:layout_height="match_parent"
                                    android:layout_gravity="top|center_horizontal"
                                    android:adjustViewBounds="true"
                                    android:scaleType="centerCrop"
                                    tools:background="@color/material_blue_grey_800" />

                            </FrameLayout>
```

But I can't find a proper way to have this working correctly with Glide natively.
Each time I end up with a square image.

For now I use 

```
            Glide.with(ctx).load(xxx)
                    .animate(R.anim.abc_fade_in)
                    .error(R.drawable.default_thumb_big)
                    .into(new SimpleTarget<Bitmap>() {
                        @Override
                        public void onResourceReady(Bitmap bitmap, GlideAnimation<? super Bitmap> glideAnimation) {
                            mViewThumb.setImageBitmap(bitmap);
                        }
                    });

```
But this lead to loading image at full size and loosing animations.

**Comment by TWiStErRob** [comment]
When you say square images aren't they expected because of `centerCrop`? I think Glide just cuts the invisible parts of the Bitmap because it will never be shown in that imageView.

If you want to see the whole image use `fitCenter`. I have a grid with square image places, but my images are random aspect ratios (user cropped camera pictures) and they always show up correctly:
![screenshot_2015-04-16-14-16-49](https://cloud.githubusercontent.com/assets/2906988/7180598/6a4892ca-e443-11e4-9bcf-8d803c2e90ed.jpg)
My `grid_item.xml` is (with irrelevant parts like id/margin/... removed):
```xml
<net.twisterrob.android.view.SquareFrameLayout
	android:layout_width="fill_parent"
	android:layout_height="fill_parent"
	>
	<ImageView
		android:layout_width="fill_parent"
		android:layout_height="fill_parent"
		android:adjustViewBounds="true"
		android:scaleType="fitCenter"
		/>
    ...
```
(`SquareFrameLayout` is as simple as `super.onMeasure(widthMeasureSpec, widthMeasureSpec)`)

Can you please post an image if this doesn't help?

**Comment by Tolriq** [comment]
As you can see there's no centerCrop or fit involved as they can't work.

And my problem is because of the wrap_content in the parent ;)

**Comment by TWiStErRob** [comment]
You have `android:scaleType="centerCrop"` on `<ImageView` and Glide [uses](https://github.com/bumptech/glide/blob/v3.5.2/library/src/main/java/com/bumptech/glide/GenericRequestBuilder.java#L638) that information.

Of course it doesn't apply to `.into(SimpleTarget)`, but you said that's a workaround to your problem.

**Comment by Tolriq** [comment]
Well on another issue it's said it's not used.

Anyway fitCenter will always fit the image in the square that comes from nowhere :)

I have a dynamic size because I want it to have a dynamic size on one dimension, I do not want to to have a dynamic size image in a fixed size zone as well I know how to do that.

The problem relies in the fact that Glide does not understand a match parent in a dynamic size container.

But to address many Android bugs I have no choice but using this trick.

**Comment by TWiStErRob** [comment]
> The problem relies in the fact that Glide does not understand a match parent in a dynamic size container.

If the `ImageView` has `match_parent` Glide waits for a layout pass and then reads the laid out size. That size is then used as the final image size as if it was given with `.override()`. There isn't much magic here. If your `ImageView` is laid out as a square before Glide reads the width and height, the image will be a square. `centerCrop` just reinforces that I think.

If we take Glide out of the picture and just look at the layout in itself (e.g. preview) then inner ImageView will have 0 height, because it fills the parent which has wrap as size, except you're observing that **it is a square. That can be for the reason that `View`s will take their background into account when measuring.** Try removing your `tools:` attributes to see what Glide would "see" and then try removing the background (which I assume is a square):
```
android:background="@drawable/image_background"
```

**Comment by Tolriq** [comment]
Well just to be clear I ask for how to handle my special case, not how Android works ;)

This layout does fit perfectly my need and works on more than 1 million device.

Anyway the square was generated by the placeholder that is square, if removing the placeholder or loading from memory image is not displayed as 0dp height.

So my question remains, what is the best way to handle this, as the width of the parent of the image is well known, only unknown in the height.

**Comment by TWiStErRob** [comment]
I hope you still appreciate that I'm trying to help. I'm throwing out ideas. From what I see you had to work around something that triggered another workaround and then you landed on this issue. The reason why I explained how it works is for you to see that even a person can't really figure out how big the view should be, how would then Glide?! :) A simpler layout is always better, and I think changing your layout is your best bet here (I'm curious what @sjudd thinks though). I don't know the context around the FrameLayout but it feels like that wrapper around the ImageView is unnecessary and margins, background and others could be merged to the ImageView leading to a fixed width x wrap_content sizing.

This just gave me an idea, where you don't even have to modify the structure. Since there's no padding involved, you could set the `ImageView`'s size to the same as the layout around it:
```
android:layout_width="@dimen/info_media_now_playing_thumb_width"
android:layout_height="wrap_content"
```
this should change Glide's behaviour (no need to wait for a layout pass) and hopefully help you.

**Comment by Tolriq** [comment]
Yes thanks for helping :)
The width is well known, I know standard Glide can't guess the height.

This is why I ask what is the better way to handle this ;) Simplest way is to get the full image and use the android api to set it but consume more memory.
Better way could be to wait for a layout pass then use glide to override image size, but maybe there's other ways with Glide.

The layout is complex and is here for a reason, this allow to bypass many Android bugs with image backgrounds , 9 patch and covers all my use cases on all android version and manufacturers :) (There's negative margins that triggers problems too).

So no I can not change the layout.

If @sjudd have no idea inside Glide like a special Target or anything I'll keep using the android api way this is not a very big deal as it's only one image.

Or maybe one day I'll build a transformer to add the image background with shadows and everything but lot's of work for little gain.

**Comment by TWiStErRob** [comment]
Fragmentation FTW :) Negative margins always look voodoo to me, never had to use them.
Did you try changing the width/height on the ImageView? I'd be curious how that affects your experience.

**Comment by Tolriq** [comment]
That will break the rendering on some devices ;) I do not have all devices for tests but I know for sure that until I drop 4.0 / 4.1 I'll have to stay like that or completely change the design.

**Comment by sjudd** [comment]
I'm a little less than totally clear on the goal, but I think you if you can roughly estimate the maximum size of your view, you can always use override() and fitCenter() to ensure your image fits within that size.

For example just using override(1024, 1024).fitCenter() will retain the original aspect ratio but make sure the image's largest side is <= 1024. 

How effective setting a maximum bound is will depend on your UI, and how much space you're willing to let each image consume. A screenshot of your layout might help a bit if you want more advice.

**Comment by Tolriq** [comment]
The goal is to have an image with a fixed with (depending on phone / tablet / orientation and much more) and a variable height that keep the ratio.

You add a shadow under the image with borders that works from Android 4.0 and a negative margin and you end up with this ugly hack.

Starting Android 4.2 normal way do work and would simplify my job a lot.

For the size the problem is that I can't really estimate as image ratio goes from 1/2 to 16/9 so taking the worst one is nearly having big images every time.

My hack for the moment will be enough, but since you are doing normal decodebounds maybe there was a way to get the ratio before doing the full decode.

**Comment by TWiStErRob** [comment]
Wouldn't using Sam's `override(x,x).fitCenter()` with
```
int x = getResources().getDimensionPixelSize(R.dimen.info_media_now_playing_thumb_width);
```
load pixel perfect images for wide ratios, and smaller images for tall images which will then be rendered as `info_media_now_playing_thumb_width` wide because of `centerCrop`/`wrap_content`?

**Comment by Tolriq** [comment]
Well yes with a * 2 to it to always have correct quality images. since this is worst ratio I'm aware of.

But having a way to be called between the decodebounds and real decoding could allow better handling for this case and maybe others.

**Comment by TWiStErRob** [comment]
Implementing your own [Downsampler](https://github.com/bumptech/glide/blob/v3.5.2/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java) used with `.asBitmap().downsampler()` should do the trick, but I'm not clear on which method to override and how.
I'm sure it's possible to refactor `Downsampler` a little to be more extensible (extract some protected methods) if required.

**Comment by Tolriq** [comment]
Well love this one, I'll look into it when I'll go on optimization phase.

Seem with just  
```
protected int getSampleSize(int inWidth, int inHeight, int outWidth, int outHeight) {
            return Math.min(inHeight / outHeight, inWidth / outWidth);
        }
```

It's possible to do things, thanks for the head up.

**Comment by sjudd** [comment]
Looks like this is resolved, let me know if there's something actionable I'm missing here.
