### ISSUE TITLE
Glide FutureTarget block a very long time in DataFetcher.

### ISSUE THREAD

**Issue by ParadiseHell** [bumptech/glide#4213]
**Glide Version**:4.9.0

**Device/Android Version**: All Devices

**Issue details / Repro steps / Use case background**: 
I want to combine 4 avatars to an avatar, so I implement a DataFetcher to do this. 
I try to use `BitmapFactory.decodeStream` directly first, but it will reload many same urls so I try to use Glide file cache, but it blocks a very long time I can not tolerate.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
I call the method below in my custom **DataFetcher** which block a very long time, but file is not that big, most less than 200K.
```java
Glide.with(applicationContext).asFile.submit.get();
```

By the way, it will block other images loading, just use the code belowing:
```java
Glide.with(context).asBitmap.into(imageView);
```

**Comment by ParadiseHell** [comment]
Finally, I found a solution to fix the problem.

In `DataFetcher` you cannot use Glide synchronize method straitly, which will block current thread.

Synchronize method as flowing :
```kotlin
Glide.with(applicationContext).asFile.submit.get(); // asBitmap or other
```

All you need to do is to create a new thread to do this ting, for better thread usage, create a thread pool is better.
```kotlin
companion object {
	private val EXECUTOR = ThreadPoolExecutor(
		GlideExecutor.calculateBestThreadCount(),
		GlideExecutor.calculateBestThreadCount(),
		0,
		TimeUnit.MILLISECONDS,
		LinkedBlockingQueue(),
		object : ThreadFactory {
			private var threadNumber = AtomicInteger(1)
			override fun newThread(r: Runnable): Thread {
				return Thread(
					r, "custom-name-thread-${threadNumber.getAndIncrement()}"
				)
			}
		}
	)
}

// And usage

EXECUTOR.execute {
    Glide.with(applicationContext).asFile.submit.get(); // asBitmap or other
}
```

That's all.

**Why need a new thread?**

Because `Glide` really downloads image thread pool is a fixed thread pool(`GlideExecutor#newSourceExecutor`), so if you block all threads, Glide will have no thread to download images, and Glide will not work to download images anymore.

**Comment by sjudd** [comment]
Argh sorry I kept meaning to respond and getting distracted.

There are two other reasonable ways to handle this.

## Use Callbacks
The first is to avoid calling get(). DataFetcher uses callbacks, so you can use [GlideFutures](https://github.com/bumptech/glide/blob/0429ea9bff7eb3aac5469ff9b03c62d4350a3bdd/integration/concurrent/src/main/java/com/bumptech/glide/integration/concurrent/GlideFutures.java#L111) to convert the nested request to a ListenableFuture. Then you can just add a callback for when it finishes:

```java
ListenableFuture<File> listenableFuture =
    GlideFutures.submit(Glide.with(context).asFile());
Futures.addCallback(
    listenableFuture, 
    new FutureCallback<File> {
      @Override onSuccess(File result) {
        callback.onDataReady(result);
      }
      @Override onFailure(Throwable t) {
        callback.onLoadFailed(t);
      }
    },
    executor);
```

The benefit of this approach is that you never block a thread. You both keep Glide's existing threads doing useful work and you don't need any new threads to run your load. 

## Use Glide's Unlimited Source Generators Pool
The second option is to still call `get()`, but add [`useUnlimitedSourceGeneratorsPool`](https://bumptech.github.io/glide/javadocs/4110/com/bumptech/glide/request/BaseRequestOptions.html#useUnlimitedSourceGeneratorsPool-boolean-) to your nested request. It's less efficient than the first option because it still blocks your current thread and creates a new one, but it at least lets Glide control/re-use the new thread and saves you from having to manage your own thread pool.

```java
Glide.with(applicationContext).asFile.useUnlimitedSourceGeneratorsPool.submit.get()
```

**Comment by ParadiseHell** [comment]
@sjudd Thanks a lot, it helps me a lot.

I prefer the second way, it's easy to use and I don't need to dependency concurrent and I don't need to use a lock to handle multi-threads synchronize.
