### ISSUE TITLE
Integration comments 

### ISSUE THREAD

**Issue by danielgomezrico** [bumptech/glide#425]
For Gradle 1.1.0 the proguard line for OkHTTP integration should be:

`-keepnames class * {com.bumptech.glide.integration.okhttp.OkHttpGlideModule;}`

**Comment by TWiStErRob** [comment]
Hi, are you referring to this page: https://github.com/bumptech/glide/wiki/Integration-Libraries ?

Btw, if we're at it, I think the more general:
```
-keepnames public class * implements com.bumptech.glide.module.GlideModule
```
should be applied this way integration libs and any custom modules are also included and users of Glide don't have to worry about it.

Note that I'm not that experience with proguard, what does the `{...;}` do? It looks like a field type (or inner class) to me.

**Comment by danielgomezrico** [comment]
Just with that one I got:

`Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.okhttp.OkHttpGlideModule" on path: DexPathList[[zip file "/data/app/com.thepickupnetwork.customer.app-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]`

I´m not sure about the { ;} but in ButterKnife they suggest to use `-keepnames class * { @butterknife.InjectView *; }`

**Comment by TWiStErRob** [comment]
Ah, then `-keepnames class * { @butterknife.InjectView *; }` means "keep the names of any class that has a field annotated with `@InjectView`". And I think my hunch is correct you're keeping the names of all classes that have a `GlideModule` field. I think with your syntax one you don't get the error, **nor the effect**, i.e. the name of that class is not kept in the final dex. And I'm sure about that statement, since the class file you're erroring on, **`OkHttpGlideModule`, was added in the 1.2.0** version of the integration module released together with Glide 3.5.0 near end of January 2015.

Please update your version numbers to 3.5.2 and 1.2.2. (you can find the integration libs version number for the Glide version number if you select Glide's version as a branch and check [`integration/lib/okhttp`](https://github.com/bumptech/glide/blob/v3.5.2/integration/okhttp/gradle.properties). @sjudd could this go to the wiki in some form?

**Comment by danielgomezrico** [comment]
I´m using those versions 

`compile 'com.github.bumptech.glide:glide:3.5.2'
    compile 'com.github.bumptech.glide:okhttp-integration:1.2.2'`

**Comment by TWiStErRob** [comment]
Then what does "Gradle 1.1.0" mean in your initial comment?

**Comment by danielgomezrico** [comment]
I mean

	buildscript {
	  repositories {
	    jcenter()
	  }
	  dependencies {
	    classpath 'com.android.tools.build:gradle:1.1.0'
	  }
	}

	allprojects {
	  repositories {
	    jcenter()
	  }
	}

**Comment by TWiStErRob** [comment]
Oh, sorry then, wrong assumption there. I was using Android Gradle Plugin 1.1.2 with Glide 3.5.2 and OkHttp-integration 1.2.2 and I found the following:

1. `-keepnames class * com.bumptech.glide.integration.okhttp.OkHttpGlideModule` gives syntax error: _ Expecting opening '{' at ..._, removing `*` fixes the issue

2. `-keepnames class * {com.bumptech.glide.integration.okhttp.OkHttpGlideModule;}` gives syntax error: _Expecting class member name before ';'_

3. From [`-keepnames` doc](http://proguard.sourceforge.net/manual/usage.html#keepnames)

> Specifies classes and class members whose names are to be preserved, **if they aren't removed** in the shrinking phase.

so even if the wiki's or the suggested syntax were to work `-keepnames` is not enough, since nothing keeps the class from being removed at shrinking, I don't think `<meta-data` `name` nor `value` qualifies for auto-keeping (see `build\intermediates\proguard-rules\release\aapt_rules.txt`)

@danielgomezrico, I couldn't reproduce your original problem (ClassNotFoundException), but I agree there are problems with the integration wiki's proguard rules. Please try putting:
```
-keep class com.bumptech.glide.integration.okhttp.OkHttpGlideModule
#or
-keep public class * implements com.bumptech.glide.module.GlideModule
```
to your rules and doublecheck that the rules in that file are being applied, since your original suggestion gave a syntax error for me. Easiest way to do this is to put the rule `-printconfiguration` in the file and run `gradlew cleanProguardRelease proguardRelease --info` which should dump all your proguard configs to the console (run from shell/command prompt, not IDE): look for `GlideModule`

@sjudd What do you think about the broader `* implements` one?

**Comment by sjudd** [comment]
I added a proguard section to the readme and updated the wiki. Thanks!

**Comment by danielgomezrico** [comment]
:+1:

**Comment by danielgomezrico** [comment]
@TWiStErRob thanks too!!

**Comment by TWiStErRob** [comment]
You're welcome! Good luck and keep us posted with issues, should you find anything else!
