### ISSUE TITLE
Thread race - Same image url will get fetched even though there is already an on-going request

### ISSUE THREAD

**Issue by ItamarM** [bumptech/glide#427]
Latest version of Glide/OkHttp integration with DiskCacheStrategy.ALL.

Two different size ImageViews will try to fetch an image from Amazon AWS. For example "https://databricks-training.s3.amazonaws.com/img/spark-logo-77x50px-hd.png". 

Glide library will execute two web requests (for the same web resource). Then it will fail on the DecodeJob as the LRUCache is writing the "first to return" network request to the file system.
I've created a small project that simulates the issue - https://github.com/ItamarM/GlideOkHttpTwoImagesBug.

**Comment by sjudd** [comment]
We ran into a similar issue in the v4 branch as well. We can and will fix the disk cache race.

 Unfortunately it's much more complicated to avoid making two requests because both Glide's default HttpUrlConnection based ModelLoader and the OkHttp based ModelLoader use streaming APIs.

If you need to avoid the multiple network requests, consider an alternate networking library that will do this for you, like [Volley][1].

[1]: https://github.com/bumptech/glide/wiki/Integration-Libraries#using-volley

**Comment by ItamarM** [comment]
Got it! tnx.

**Comment by sjudd** [comment]
Fixed here: 31640f60f6b329c93cb3de4b5e2b4fefdfb653de

**Comment by ItamarM** [comment]
Thanks @sjudd good job!
