### ISSUE TITLE
How to get bitmap when the loading is completed successfully?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [bumptech/glide#428]
Hi! 

I want to get the bitmap if the image from the url loads successfully. 

I am doing it as: 

```java
 Glide.with(mContext)
                            .load(path)
                            .crossFade()
                            .diskCacheStrategy(DiskCacheStrategy.ALL)
                            .listener(new RequestListener<String, GlideDrawable>() {
                                @Override
                                public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                                    return false;
                                }

                                @Override
                                public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                                    return false;
                                }


                            })
                            .into(view.grid_image);
```
Thanks.

**Comment by TWiStErRob** [comment]
Hi, can you please explain what are you planning to do with it? Do you need to show the image, or just want to have a Bitmap variable which then can be used for anything?
Answering the above questions helps us to give a better answer to you.

(_also please try to reformat (edit) your question with ``` before and after the code block_)

**Comment by sjudd** [comment]
Assuming you want to interact with the Bitmap on the main thread and not in a view, take a look at the wiki page on [custom targets][1]. If you're trying to interact with the Bitmap on a background thread, consider [``into(width, height)``][2].

[1]: https://github.com/bumptech/glide/wiki/Custom-targets#simpletarget
[2]: http://bumptech.github.io/glide/javadocs/350/com/bumptech/glide/GenericRequestBuilder.html#into(int,%20int)

**Comment by Shajeel-Afzal** [comment]
Hi @TWiStErRob i want to use Pallet API with the bitmap. (https://developer.android.com/reference/android/support/v7/graphics/Palette.html)

**Comment by TWiStErRob** [comment]
Thanks, then Sam has already pointed you in the right direction because there's an example for that [on the wiki](https://github.com/bumptech/glide/wiki/Custom-targets#overriding-default-behavior).

Also note that we have a currently unsupported Palette related sample and API, see the palette branch and #272.

**Comment by Shajeel-Afzal** [comment]
Thanks @TWiStErRob i think i should wait till the new branch is not merged.

**Comment by sjudd** [comment]
@TWiStErRob it definitely can. I think the last update was that you were going to take a look at the slightly different API? Did you get a chance to do that? Maybe we should follow up on the pull request. 

Since I think we answered the question here, I'm going to close this for now. @Shajeel-Afzal let us know if you have any other questions.

**Comment by shaheer47** [comment]
s
