### ISSUE TITLE
If I provide a mp4 link in url to load a photo then it works perfectly but my question is that how much data it consumes ? Equals to whole length of the video or just a image??

### ISSUE THREAD

**Issue by siddhant792** [bumptech/glide#4321]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by DarkionAvey** [comment]
I was wondering the same, so I tested this video (http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4) which is around 45MB. I loaded it into Glide and recorded the data consumption. It appears that Glide downloads the whole video then processes it, instead of grabbing a single frame. 


<img src="https://user-images.githubusercontent.com/11511782/92982002-ae072200-f49c-11ea-8c0f-5691bf5620be.png" width=30% height=30%>
