### ISSUE TITLE
The images size vary on every refresh of the GirdView and also change while I am scrolling the GridView up and down. and for the ListView the image takes up the full screen.

### ISSUE THREAD

**Issue by adityaiit** [bumptech/glide#439]
I have a fragment which has an option of toggling between Grid View and List View of same set of images being pulled from the server. When I toggle between the Views, the images sizes are being displayed with different sizes, sometimes occupying the entire screen width and screen height. Can you please le me know if I am doing anything incorrectly and also the right way of pulling the images with the correct size in the first request itself.

Here is the Grid Item Layout

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/grid_icon_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
    android:layout_marginBottom="@dimen/grid_view_cloud_content_row_icon_view_marginBottom"
        android:background="@drawable/cloud_file_grid_view_icon_background_selector"
        android:padding="@dimen/grid_view_cloud_content_row_icon_view_padding" />

    <android.support.v7.widget.AppCompatTextView
        android:id="@+id/grid_name_view"
        android:lines="2"
        android:ellipsize="end"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"    android:layout_marginBottom="@dimen/grid_view_cloud_content_row_name_view_marginBottom" />

</LinearLayout>
```
Here is the List Item Layout
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/cloud_file_list_view_icon_background_selector">

    <ImageView
        android:id="@+id/list_icon_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginRight="@dimen/list_view_cloud_content_row_icon_view_marginRight" />

    <android.support.v7.widget.AppCompatTextView
        android:id="@+id/list_name_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:layout_marginRight="@dimen/list_view_cloud_content_row_name_view_marginRight"
        android:layout_toLeftOf="@+id/list_dir_arrow_view"
        android:layout_toRightOf="@id/list_icon_view" />

    <ImageView
        android:id="@id/list_dir_arrow_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"      android:layout_marginRight="@dimen/list_view_cloud_content_row_dir_arrow_view_marginRight"
        android:visibility="gone" />

</RelativeLayout>
```
Below is the code in the adapter I am using to set the icons
```
  if (isGridView) {
                if (gridIconView != null) {
                    Glide.with(mContentFragment)
                    .load(gridIconUrl)
					.error(R.drawable.app_icon)
					.placeholder(R.drawable.app_icon)
					.crossFade()
					.centerCrop()
					.into(gridIconView);                }
                if (gridNameView != null) gridNameView.setText(fileName);
            } 
} else {
                if (listIconView != null) {
                    Glide.with(mContentFragment)
                            .load(listIconUrl)
                            .error(R.drawable.app_icon)
                            .placeholder(R.drawable.app_icon)
                            .crossFade()
                            .centerCrop()
                            .into(listIconView);
                }
                if (listNameView != null) listNameView.setText(fileName);
}
```

**Comment by TWiStErRob** [comment]
Please edit and surround your code blocks with ``` on a separate line before and after the code lines. See [example](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) and also worth including xml or java right after those 3 ticks.

**Comment by adityaiit** [comment]
@TWiStErRob :Thanks for the tip.

**Comment by TWiStErRob** [comment]
Poor Android and Glide can't really figure out how big images you really want. You defined both of your item layouts as `match_parent`. Now if one item matches the parent, then it's kind of like a paging list. It can get even worse if you think about the ListView as a ScrollView because then `match_parent` means make an infinite vertical list. Another issue is that the image loaded to one item requests a new layout and the size changes, then the next image when recycled takes up different dimensions and does another layout. This can make the sizes explode or just "randomly" jump around.

The easiest way to solve this is obviously to give fixed sizes (in `dp`!) to the image views, but the below may worth some tries to have a more flexible layout:
 1. Remove the `centerCrop()` and put `android:scaleType="centerCrop"` on the ImageView in xml, Glide can automatically read that.
 1. I usually put `adjustViewBounds="true"` to my `ImageView`s to keep aspect ratio with `fitCenter`, it may work with `centerCrop` as well.
 1. List item root layout should be always `layout_height="wrap_content"`
 1. List item image could have `layout_height="fill_parent"` which will make Glide wait for the item to be laid out and just then read the size of the view to resize the image. Each item (hence each image) will be as tall as the text + margins.
 1. Grid item root layout should be constrained as well with `layout_height="wrap_content"`, otherwise it just gets too big vertically.

Extras:
 1. The beauty of `findViewById` is that you don't need to know how the layout looks like, just the IDs: this means that if you use "@+id/icon_view" and "@+id/name_view" for example in both grid and list layouts you don't need to have those ifs and multiple variables.
 1. Same stands for the Glide lines: `Glide....load(isGridView? gridIconUrl : listIconUrl)....into(iconView);`
 1. In list item you can replace `RelativeLayout` with the simpler `LinearLayout`, instead of `toLeft/RightOf` put them in order and add `layout_weight="1"` to the view you want to stretch (TextView).
 1. You can also use `tools:src="@drawable/app_icon"` to have a better preview while editing, see [doc](http://tools.android.com/tips/layout-designtime-attributes) for more.

If these don't help please post a screenshot or [video](http://stackoverflow.com/a/19774701/253468) because I'm not sure how the sizes being different. You also didn't mention what the source image sizes are.

**Comment by adityaiit** [comment]
Thank you very much for the detailed comments about the changes. I have put in all the changes you have mentioned. Looks like the issue seems to be the sizes of the images I have. Because they are unknown and I have not fixed their size in the image views, as you mentioned the dimensions of the items are varying on each layout pass. Thanks once again. I will get back to you, if I need more help.

**Comment by TWiStErRob** [comment]
I have random sized images too and there's no jumping around, see [screenshot_2015-04-16-14-16-49](https://cloud.githubusercontent.com/assets/2906988/7180598/6a4892ca-e443-11e4-9bcf-8d803c2e90ed.jpg) and I'm using only `wrap_content` and `match_parent`s. The only exception is that for grid I use a `SquareFrameLayout`:
```
public class SquareFrameLayout extends FrameLayout {
	// constructors matching super class's omitted
	@Override public void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
		//noinspection SuspiciousNameCombination
		super.onMeasure(widthMeasureSpec, widthMeasureSpec);
	}
}
```
