### ISSUE TITLE
Feature request - AnimatedGif progress API

### ISSUE THREAD

**Issue by joshzana** [bumptech/glide#446]
I would like to play a GifDrawable animation, and sync up other UI to progress within the animation (say, setting text on a TextView)  Is there a suggested way to do that today?  

The only way I can see is to extend GifDrawable, override onFrameReady, and store off the frameIndex.  I would then expose a getFrameIndex() that returns the current frame index, and callers can call getFrameCount() and divide to get progress as a fraction.  Would be nice if there was a built in method off of GifDrawable.

**Comment by TWiStErRob** [comment]
@joshzana I think you also need to be notified when a new frame happens so you would need to override `onFrameReady` anyway, what do you think about this?

Also talked to Sam and it turns out that GIF doesn't store the number of frames in the header of the image file, so the only way to know is to count. This means that currently the whole image is read once (skipping the actual frame pixels of course) and the frames are counted and only after that the real decoding will begin. This may change in the future in a way that this pre-read won't happen to avoid an almost unnecessary expensive operation, so after that `getFrameCount()` won't give you a valid value in the first loop or disappear altogether.

@sjudd I guess even if the above is implemented (i.e. pre-parsing removed) and there won't be a count, the current frame index will still be available and can be exposed as joshzana wants it.

**Comment by sjudd** [comment]
The current index will be available, we just won't know the total count, at least not until you get to the last frame the first time.

It's relatively unlikely we will avoid parsing the entire GIF in v3, but I'd like to for v4.

**Comment by joshzana** [comment]
The other options is to have a custom drawing View and just check getFrameIndex() on each onDraw(), which would then not require overriding.

I'd be fine with getFrameCount being indeterminate at some points, as long as there was a booolean get method somewhere that told me it was unreliable.

**Comment by sjudd** [comment]
Ok, that sounds reasonable. If you're interested, please feel free to take a crack at this. I'd be totally ok exposing the current frame and the frame count, with the caveat that the frame count will be unknown (-1?) sometimes at some point in the future.

**Comment by joshzana** [comment]
Implemented in #477

**Comment by sjudd** [comment]
Thanks!
