### ISSUE TITLE
Question regarding Glide recycling resource.

### ISSUE THREAD

**Issue by danysantiago** [bumptech/glide#447]
Hey,

I had a question regarding how Glide determines if a resource is ready to be recycled. I'm making a Glide call to a `PreloadTarget` and in the callback I grab the resource and use it, but during some odd situations the resource gets recycled just before I do more things to it. Is there a way to mark the resource as acquired so Glide does not free the resource? Is it OK the use the callbacks to grab the resource and set it or is it better to have a custom target? Finally I see that `PreloadTarget` has a call to `Glide.clear(this)` in `onResourceReady()` is this eventually causing an immediate recycle?

Here is my current code:

```java
Glide.with(appContext)
        .load(url)
        .asBitmap()
        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
        .listener(new RequestListener<String, Bitmap>() {
            @Override
            public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                remoteControlClient.editMetadata(false)
                        .putBitmap(RemoteControlClientCompat.MetadataEditorCompat.METADATA_KEY_ARTWORK,
                                BitmapFactory.decodeResource(appContext.getResources(), R.drawable.empty_art))
                        .apply();
                return true;
            }

            @Override
            public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target,
                                           boolean isFromMemoryCache, boolean isFirstResource) {
                remoteControlClient.editMetadata(false)
                        .putBitmap(RemoteControlClientCompat.MetadataEditorCompat.METADATA_KEY_ARTWORK, resource)
                        .apply();
                return true;
            }
        })
        .into(target);
```

Glide Version: 3.5.2

**Comment by sjudd** [comment]
Glide uses reference counting to determine when a resource can be released. Each request into a new Target for a given resource increments the count. Each call to ``clear()`` on one of those Targets decrements the count.

When the count reaches 0, the resource is dumped in to the memory cache. If the resource is eventually evicted according to the LRU algorithm, it will be recycled (Bitmaps are returned to the bitmap pool etc).

With that in mind, the call to ``clear()`` in ``PreloadTarget`` is meant to indicate that the ``PreloadTarget`` no longer has any interest in the resource, which it doesn't. If no one else has requested the same resource during the time the resource was loaded, it will be placed immediately into the memory cache and be eligible for eviction.

You cannot safely use a listener to grab the resource, you must have a Target in order to indicate to Glide that you're still interested in the resource. You can then (optionally) clear the same Target to release the resources later to allow them to be pooled/reused. 

Hopefully this helps? Also maybe take a look at [the wiki page][1].

[1]: https://github.com/bumptech/glide/wiki/Resource-re-use-in-Glide

**Comment by danysantiago** [comment]
This is helpful, thanks Sam!

**Comment by sjudd** [comment]
No worries, glad it's helpful. Let us know if you have more questions.
