### ISSUE TITLE
Load same image in two views not working sometimes

### ISSUE THREAD

**Issue by stepango** [bumptech/glide#453]
**Glide Version/Integration library (if any)**: 3.5.2/3.6.0
**Device/Android Version**: 4.4.4, 5.0.x, 5.1
**Issue details/Repro steps**: ~ 40% chance that one of view(blured or original) will be not filled by image. Looks like some kind of race condition.
**Glide load line**:
```
       Glide.with(context)
               .load(url)
               .asBitmap()
               .format(DecodeFormat.PREFER_ARGB_8888)
               .transform(new BlurTransform(context))
               .diskCacheStrategy(DiskCacheStrategy.ALL)
               .into(blured);

       Glide.with(context)
               .load(url)
               .into(original);
```

**Comment by TWiStErRob** [comment]
That's interesting because even though the blurred is cached in SOURCE and RESULT, the original only uses the RESULT cache whose key will never match the blurred one because of the `BlurTranform` (that is if that's implemented correctly with a unique id like "blur") also I think `asBitmap` changes the RESULT cache key significantly (but I would have to check that to be sure). What I'm trying to say that there should be no problem with loading... of course that's not how bugs work :)

Can you please share which `BlurTransform` you're using? We had an issue with a `CircleTransform` using bad pooling in a popular SO answer.

Also please quote some of the layout where `blurred` and `original` comes from, width/height/scaletype of ImageViews and width/height of their parents may have some effects on timings.

Is your url http? Are you using integration libs? The problem may be there because of the same Url, OKHTTP and volley behave differently. (Integration version numbers are 1.x.y and should match the release of Glide)

**Comment by stepango** [comment]
Here is BlurTransform we are using https://gist.github.com/stepango/040bc2a47595c9e7121e

'''
<ImageView
            android:id="@+id/blured"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentTop="true"
            android:scaleType="centerCrop"
            tools:src="@drawable/img_idea_default" />

<ImageView
            android:id="@+id/original"
            android:layout_width="@dimen/song_cover_size"
            android:layout_height="@dimen/song_cover_size"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="@dimen/grid_size_x12"
            tools:src="@drawable/img_idea_default" />
'''
We are not using integration libs.
Looks like you are right abut transform. Without blur transform all works fine, even with transform all works when we get blured image from cache.

**Comment by Tolriq** [comment]
Surely not related at all but 

```
Bitmap bitmap = Bitmap.createScaledBitmap(
                toTransform,
                toTransform.getWidth() / scaleFactor,
                toTransform.getHeight() / scaleFactor,
                false
        );
        toTransform.recycle();
```

You should first do ```if (bitmap != toTransform)``` before recycle as createScaledBitmap can return source image sometimes leading you with a problem.

And more important : https://github.com/bumptech/glide/commit/1fabbe4c5321befdbe708b061797e87c33e88403

You should not recycle toTransform at all as it's Glide that will handle this.

**Comment by sjudd** [comment]
Sounds like you're on the right track, let us know if just fixing the Transformation as mentioned by @Tolriq  and @TWiStErRob didn't solve the issue.
