### ISSUE TITLE
Handle null url in GlideUrl without crashing

### ISSUE THREAD

**Issue by TomasValenta** [bumptech/glide#454]
Hi,
I think it's a bug. When I use this:

``` java

String url = null;

GlideUrl glideUrl = new GlideUrl(url, new LazyHeaders.Builder()
                .addHeader("User-Agent", USER_AGENT)
                .addHeader("App-Agent", APP_AGENT)
                .build());

Glide.with(context)
        .load(glideUrl)
        .fallback(R.drawable.empty)
        .error(R.drawable.error)
        .placeholder(R.drawable.placeholder_small)
        .into(ImageView);
```

Then app crash with:

> String url must not be empty or null

But then fallback for null is unusable in this situation?

**Comment by sjudd** [comment]
Ah interesting. I don't normally pass in GlideUrls directly, I usually parse them from some other type. I agree this is a bug though.

As a work around you can create a custom type wrapping the url and the builder, extend [BaseGlideUrlLoader][1] and [register it using a GlideModule][2], and make your request with the custom type rather than with GlideUrls. For an example, you can take a look at [GiphyModelLoader][3]

BaseGlideUrlLoader will correctly handle null urls and will still allow you to pass in Headers. It's also more efficient because you can create your headers object once and re-use it for every subsequent load rather than passing it in for each new url.

Thanks for the report!

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/load/model/stream/BaseGlideUrlLoader.html
[2]: https://github.com/bumptech/glide/wiki/Configuration#including-a-glidemodule
[3]: https://github.com/bumptech/glide/blob/master/samples/giphy/src/main/java/com/bumptech/glide/samples/giphy/GiphyModelLoader.java

**Comment by TomasValenta** [comment]
Thank you Sam,
but this is so complicated for me ;) I do not use it "directly", I have separated class:

```java
public class HttpHeader {

    public static final String USER_AGENT = "AAA";
    public static final String APP_AGENT = "BBB";

    public static GlideUrl getUrl(String url) {
        return new GlideUrl(url, new LazyHeaders.Builder()
                .addHeader("User-Agent", USER_AGENT)
                .addHeader("App-Agent", APP_AGENT)
                .build());
    }
}
```

and then use it in many instances:

```java
Glide.with(context)
		.load(HttpHeader.getUrl(url))
		.fallback(R.drawable.empty)
		.error(R.drawable.error)
		.placeholder(R.drawable.placeholder_small)
		.into(ImageView);
```

but I think your solution are better ;) Can you show me please easy and complex example for me and this situation?

**Comment by sjudd** [comment]
Eh in that case just do the null check yourself, it's definitely easier:

```java
GlideUrl getUrl(String url) {
    if (TextUtils.isEmpty(url)) {
        return null; 
    } 
    return new GlideUrl(url, new LazyHeaders.Builder() 
        ...
}
```

**Comment by TomasValenta** [comment]
Thank you Sam, it works! ;)

**Comment by sjudd** [comment]
Sure no problem, I'll leave this open as an enhancement to try to make this nicer so you don't have to do the empty check yourself.

**Comment by TomasValenta** [comment]
Nice! ;)
