### ISSUE TITLE
Changing frequently animated gifs in one ImageView result in slow Performance and memory problems

### ISSUE THREAD

**Issue by Chriz91** [bumptech/glide#461]
Hello,

in my app i have 9 animated gifs and i want to display them successive (each about 7 sec) in one ImageView. But after a while the gifs get so slow and the app breaks . Im not so into memory management/garbage collection and i dont know how to fix this.

So this is how i do it:
I have the gifs in my local drawable folder. And i load them in a Background Thread:

FutureTarget<File> future1 = Glide.with(getActivity())
                        .load("android.resource://de.chris.appname/" + R.drawable.car1)
                        .downloadOnly(800, 600);
                try {
                    file1 = future1.get();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                } catch (ExecutionException e) {
                    e.printStackTrace();
                }

and then i get a Signal (modus) and i set the correspondending gif.

 if (modus.equals("1")) {
Glide.with(this).load(file1).asGif().diskCacheStrategy(DiskCacheStrategy.RESULT).into(gifCar);
 }....

Is this the right way to do it?
How can i decrease memory?

Thanks for your help!
Chris

**Comment by TWiStErRob** [comment]
What I see immediately is that you don't need the intermediate downloadOnly File, that is written to the SD card which is pointless since your app is on the SD card, and I dare to say loading something from apk is faster than loading from File (alignment, memory mapping).

You should also try using `.load(@DrawableRes int)` because you know exactly the resource ID from R.drawable. It may or may not benefit you now, but you may get unforeseen optimisations in future releases of Glide if you use that, it's an investment.

You are using result cache explicitly (that's the default), you could try disabling it (NONE), just to see the effect.

Sadly this is all just loading optimization, it probably has nothing with memory.

Check out the [Debugging wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling), and [fuller list of tags](https://github.com/bumptech/glide/issues/457#issuecomment-99505672) and try to figure out the load timings from the log. Also worth checking the memory usage with Android Studio's memory view or the SDK's DDMS tool. These are to confirm if you have a memory or loading/caching problem.

**Comment by Chriz91** [comment]
Thank you, for the fast reply!
I changed all the things you told me and the loading is definitely better and okay for me.
But the memory usage is as you expected too high and this results into slow Performance of the gifs until the whole UI freezes. I will check the debugging wiki and will then report.

**Comment by Chriz91** [comment]
I found the bug. It had nothing to do with glide. It was an other library i use to show diagrams in my app and it caused the high memory usage...

Nevertheless thanks for the fast support!

**Comment by sjudd** [comment]
Sure no problem, thanks for following up. Thanks @TWiStErRob for responding :).
