### ISSUE TITLE
Multiple ImageViews with same image

### ISSUE THREAD

**Issue by IonAalbers** [bumptech/glide#468]
Like #238 and #255 I got an issue with 'using' the already cached version of an image.
I got a RecyclerView with GridLayoutManager, and when selecting an image, it opens an new Activity activity.
This happens with a new Android L animation so I want to re-use the image in the next Activity.

So, I'm using the following code to set the image on both ImageViews:

        DrawableRequestBuilder<String> builder = Glide.with(VLApplication.getInstance())
                .load(url)
                .thumbnail(mThumbRequest)
                .dontTransform()
                .override(mRequestedWidth, mRequestedHeight)
                .diskCacheStrategy(DiskCacheStrategy.ALL);
                .into(imageView);

The **url**, **mRequestedWidth** and  **mRequestedHeight** are in both cases the same value.
But the *onResourceReady* listener reports *isFromMemoryCache = false*. This causes a 'not so smooth' animation.

Opening the same activity the second time results in *isFromMemoryCache = true* and a smooth animation.

Can you explain the construction of the cache-key and when it's not re-using the previous image?

**Comment by TWiStErRob** [comment]
Thanks for the question. Here are some quick tests to try to make it work:
* I suggest you try to make it work without thumbnails first. That may complicate things.
* `dontAnimate()` may also help so it's not trying to `crossFade()` by default while also L-animating to it.
* `asBitmap()` may also change a few things up, that's always worth a try :)

Going deeper: try putting a breakpoint here: https://github.com/bumptech/glide/blob/v3.5.2/library/src/main/java/com/bumptech/glide/load/engine/Engine.java#L152 and compare the key for the first intial load (grid) and the second one (detail). `id` variable should contain the url so you can see which image is being handled when the breakpoint hit.
There's probably no better explanation of construction of cache key than https://github.com/bumptech/glide/blob/v3.6.0/library/src/main/java/com/bumptech/glide/load/engine/EngineKey.java

Btw, at first look I thought of this one, but not sure if it helps here, because you override: https://groups.google.com/forum/m/#!topic/glidelibrary/eBjI1yA0QKw

**Comment by TWiStErRob** [comment]
As an alternative to debugging you can [enable the "Engine" tag logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling).

**Comment by TWiStErRob** [comment]
The whole point of obtain() is that it's a singleton, check EmptySignature.java.

A Java hash code is int which is 32 bit = 8 hex digits. Take a look at the EngineKey class and notice that the order is signature, width, height.

With this info you can see that the target size is 360x537 VS 355x530.

Also you should update to v3.6.0 so you have the latest fixes, which includes for example a better toString for keys among a ton of others depending on how far you're behind. (If you're on latest, then how did you acquire that string?)

**Comment by IonAalbers** [comment]
I was working on v3.5.2 and updated to 3.6.0.
Indeed, the `mRequestedWidth` was incorrect.

It is working great now. Thanks for your help!
