### ISSUE TITLE
onLoadCleared() called prematurely in recyclerview

### ISSUE THREAD

**Issue by mcginty** [bumptech/glide#469]
It looks like the default drawable ViewTarget is having its `onLoadCleared` called when a view is datached vs. when it is actually recycled in a RecyclerView, causing this visual bug.

The screencap below shows the basic issue. The activity contains a RecyclerView that is using a GridLayoutManager, and is loading images into ImageViews via Glide.

I verified that overriding the `onLoadCleared()` to have it be a no-op in `GlideDrawableImageViewTarget` stops this problem from happening. Tested using `com.github.bumptech.glide:glide:3.6.0` and `com.android.support:recyclerview-v7:22.1.1`.

![recyclerimages-optimized](https://cloud.githubusercontent.com/assets/373823/7780838/3baf493c-0099-11e5-8ed0-93e598e0963c.gif)

**Comment by TWiStErRob** [comment]
Hmm, I have several GridLayout RecyclerViews without problems. Can you please share your relevant recyclerview/adapter code? Maybe XML, but that's probably irrelevant here.
My suspicion is that there's something strange in how you use Glide, because as far as I know the view should be rebound on every display. (It's not recycled because the position stays the same.)

**Comment by mcginty** [comment]
I'll just create an example app - will update when finished.

**Comment by TWiStErRob** [comment]
Just thought about one more thing: check if on exception is called for those items via listener(). Maybe it's rebound, but fails to load the image the second time. There's a limitation for ImageView-only lists: setTag cannot be called on the ImageView, Glide reserves that. I'm not sure how RecyclerView handles ViewHolders though.
See ViewTarget.setTagId and issue 370 for more.

**Comment by mcginty** [comment]
@TWiStErRob no exceptions when I added a listener

**Comment by mcginty** [comment]
I made an example app that tried to reproduce the behavior and haven't been able to do it yet, so I'm suspecting it may be something strange with my code as you predicted :). Sorry to have potentially wasted your time - I'll close unless I can get an example app reproducing this.

**Comment by TWiStErRob** [comment]
No worries, we can still try help you resolve the issue. Who knows in the end it may be a rare bug with strange circumstances, yikes. If you check the issue list you'll see a lot of "question"s, similar to yours. Just copy the Glide the related lines here (or the whole onBindViewHolder/Adapter) since most of the time we can guess the issue just by reading the code.
