### ISSUE TITLE
How to add header to all requests?

### ISSUE THREAD

**Issue by mori-honest** [bumptech/glide#471]
I know that HTTP headers can be added like this:

          GlideUrl url = new GlideUrl("http://....", new LazyHeaders.Builder()
                .addHeader("User-Agent", USER_AGENT)
                .addHeader("App-Agent", APP_AGENT)
                .build());
          ....load(url)....;

But how to do that Just one time for all requests?

**Comment by TWiStErRob** [comment]
I would try this way (untested on phone, but compiles):
```java
// make sure it's registered in AndroidManifest.xml as described at https://github.com/bumptech/glide/wiki/Configuration#including-a-glidemodule
public class GlideSetup implements GlideModule {
	@Override public void applyOptions(Context context, GlideBuilder builder) { /* no costumization */ }
	@Override public void registerComponents(Context context, Glide glide) {
		glide.register(String.class, InputStream.class, new HeaderedLoader.Factory());
	}

	private static class HeaderedLoader extends BaseGlideUrlLoader<String> {
		public static final Headers HEADERS = new LazyHeaders.Builder()
				.addHeader("User-Agent", USER_AGENT)
				.addHeader("App-Agent", APP_AGENT)
				.build();

		public HeaderedLoader(Context context) {
			super(context);
		}

		@Override protected String getUrl(String model, int width, int height) {
			return model;
		}

		@Override protected Headers getHeaders(String model, int width, int height) {
			return HEADERS;
		}

		public static class Factory implements ModelLoaderFactory<String, InputStream> {
			@Override public StreamModelLoader<String> build(Context context, GenericLoaderFactory factories) {
				return new HeaderedLoader(context);
			}
			@Override public void teardown() { /* nothing to free */ }
		}
	}
}
```
and then
```java
....load("http://....")....;
```

If you're not using `load(String)`, but `load(Uri)` for example, I think you'll have to register a similar ModelLoader for that too. The idea should be the same for any model.

I guess if you want to combine the two (static and dynamic headers) you would need to change `String`s above to `GlideUrl` and merge headers in getHeaders; or create your own factory for creating `Headers` which prepopulates a `LazyHeaders.Builder` for example.

@sjudd was this what you meant in [3.6.0 release notes](http://github.com/bumptech/glide/releases)?

**Comment by sjudd** [comment]
Yup pretty much.

I'd recommend using a custom data model though, rather than ``String``. If you register a ``BaseGlideUrlLoader<String>`` like the one you've written that only recognizes URLs, you replace Glide's default String loader that recognizes URLs, Uris, and file paths. 

As an alternative you can register a new type (``YourModel``), register a ``BaseGlideUrlLoader<YourModel>``, and then start loads with objects of that class (``Glide.with(fragment).load(yourModel)``). You can see the [``FlickrModelLoader``][1] or [``GiphyModelLoader``][2] for examples of this.

[1]: https://github.com/bumptech/glide/blob/3.0/samples/flickr/src/main/java/com/bumptech/glide/samples/flickr/FlickrModelLoader.java
[2]: https://github.com/bumptech/glide/blob/3.0/samples/giphy/src/main/java/com/bumptech/glide/samples/giphy/GiphyModelLoader.java

**Comment by mori-honest** [comment]
I added @TWiStErRob 's codes but not able to get the image.
how can i log glide headers to see what is wrong?

**Comment by sjudd** [comment]
There isn't a great way to log headers. Can you check using a proxy or just server logs to see what you're sending?

You can put a break point in Glide also, if you're using gradle and the standard HttpUrlConnection library (ie you're not depending on an integration library), you can do so here: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java#L91

**Comment by sjudd** [comment]
Let us know if you need more help.

**Comment by jagrati-turkar** [comment]
Thanks it helped me.

**Comment by AniaSunshine** [comment]
@TWiStErRob Thank you very much! It worked.

**Comment by santhanam1991** [comment]
@TWiStErRob
I have followed the above steps to load image with header data (Note : Image response in content data as encoded), but Glide takes more time for loading. It seems it's loading one by one. then I used Picasso loader(which is suggested [)](https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/android/src/main/java/com/dropbox/core/examples/android/FilesAdapter.java) it's really faster.

But my glide object was loading efficiently for other type of images like device source,url direct image.

Also I have checked image caching logic is working fine.  for loading alone takes around 2.5sec and after that not rendering immediately. 

I don't understand the reason, whether I have done any configuration mistake or due to passing header request for near thousands of images.

**Comment by TWiStErRob** [comment]
@santhanam1991 that sounds like a separate issue (you've successfully added the header, which this issue is about), please open a new one with more details, like headers, encoding, etc.

**Comment by Kolyall** [comment]
@TWiStErRob could you please update your answer to ver 4.6.1? Because methods from current answer don't exist

**Comment by TWiStErRob** [comment]
@Kolyall see above commit

**Comment by 654277633** [comment]
use load(url), not load(uri) or others
