### ISSUE TITLE
Glide and RecyclerView causes view mess

### ISSUE THREAD

**Issue by henriquedesousa** [bumptech/glide#479]
**Glide Version/Integration library (if any)**: Glide 3.6
**Device/Android Version**: Xiaomi Radmi 2 / MIUI with 4.4.4 (kitkat)
**Issue details/Repro steps**: Import RecyclerView sample from Google, add an imageview and load an image into it using Glide. 

**Glide load line**:          
        Glide.with(viewHolder.imageView.getContext())
                .load(ImageFactoryCreator.getImageUrl(position))
                .centerCrop()
                .into(viewHolder.imageView);
```
Glide.with(context)...;    holder.imgView.getContext() [as shown above]
```

```
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="@dimen/list_item_height"
    android:layout_marginLeft="@dimen/margin_medium"
    android:layout_marginRight="@dimen/margin_medium"
    android:gravity="center_vertical">

    <ImageView
        android:id="@+id/icon"
        android:layout_width="wrap_content"
        android:layout_height="fill_parent"
        android:layout_marginRight="6dip"
        android:contentDescription="TODO"
        android:src="@drawable/ic_launcher" />

    <TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/element_text"/>
</FrameLayout>
```

![screenshot from 2015-06-01 12 19 34](https://cloud.githubusercontent.com/assets/12630569/7911706/91aa1602-0858-11e5-9c6d-10c8a877722f.png)

My guess is that Glide tries to get the ImageView's size and fails after some time due to the recycling nature of RecyclerView. I've also tried using holder.setIsRecyclable(false) but this time the extesnding of images will happen on _all_ rows.

Thanks in advance.

**Comment by TWiStErRob** [comment]
Please include the layout xml for each items, and try to give us a "Glide load line" instad of a Picasso one ;) [you can edit your original post]

**Comment by henriquedesousa** [comment]
What a mistake! In my defence, I posted the Picasso line in order to test if it would result in the same issue, but it didn't, Picasso loads the images correctly. Sorry guys, I've  corrected the first post with the Glide line and the row layout. Thanks!

**Comment by TWiStErRob** [comment]
Hehe :) No worries there, it was just funny. (`Glide.with(context)...;` is just there as a placeholder to remind people what a "Glide load line" is.)

So, the problem is `wrap_content`. It means that the view will host whatever is given to it with its intrinsic size. For Glide it means that you want the image to be loaded at full size, and then the imageView will show as big as it wants to be.

You have a few options to try:
 1. Try `android:adjustViewBounds="true"` on the `<ImageView>`, it will make the view keep the drawable aspect, which is constrained by list item height, so the image should be always a squre. This works best if you move `.centerCrop()` onto the imageView: `android:scaleType="centerCrop"`, because Glide reads that automatically (helps with preview too).
 2. Give it a size:

    ```xml
    <ImageView
        android:id="@+id/icon"
        android:layout_width="@dimen/list_item_height"
        android:layout_height="@dimen/list_item_height"
        ...
    ```
 3. Give it a size:

    ```java
    int size = viewHolder.imageView.getContext().getResources().getDimensionPixelSize(R.dimen.list_item_height);
    Glide.....override(size, size)....;
    ```
 4. You can try to constrain the size of the icon with the text, which I don't suggest to use this, but may worth a try if you don't like the above:

    ```xml
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="@dimen/list_item_height"
        android:layout_marginLeft="@dimen/margin_medium"
        android:layout_marginRight="@dimen/margin_medium"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/icon"
            android:layout_width="wrap_content"
            android:layout_height="fill_parent"
            android:layout_marginRight="6dip"
            android:scaleType="centerCrop"
            android:contentDescription="TODO"
            tools:src="@drawable/ic_launcher" />

        <TextView
            android:id="@+id/textView"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            tools:text="@string/element_text" />
    </FrameLayout>
    ```
*Unrelated tip: notice the use of the [tools namespace](http://tools.android.com/tips/layout-designtime-attributes).*

... none of the above is tested ;) Good luck! Please report back if it worked.

**Comment by henriquedesousa** [comment]
The only tip that worked was overriding the image size. Thanks for the help :)

**Comment by sjudd** [comment]
Glad it worked!
