### ISSUE TITLE
too much error for first gradle build because of plugin

### ISSUE THREAD

**Issue by gabrieljuan** [bumptech/glide#489]
Could someone give me a list of plugin I HAVE to download so the library could be compiled with no problem ?

**Comment by TWiStErRob** [comment]
Glide uses Gradle to build, everything is defined in `build.gradle` files in module directories. You can import the project into IntelliJ IDEA 14 Community IDE or compile command line, see `gradle tasks`. Probably worth making command line work (with `--info --stacktrace`) before trying to import in an IDE... IDEA is not the best telling you what the problem is.

Can't you please quote your *first* error? It should compile without errors, since Travis CI is verifying every commit. **Mind you `master` is pre-release and may be unstable, try the `3.0` branch.**

Also if you're planning to build your own by modifying the source consider contributing with a pull request so other get that feature too, or just simply ask a question here in issues to help you find the right combination of Glide feature uses to implement your idea.

**Comment by gabrieljuan** [comment]
No, I'm not build my or modifying the source. I just want to use it. Honestly I don't understand what are you trying to tell me in the first paragraph. Most of the error said, the IDE couldn't found plugin like roboelectric, JACOCO and other plugin in the build.gradle inside the library folder. Sorry if my report misguiding. Thanks for the answer..

**Comment by TWiStErRob** [comment]
Sorry I was guessing a lot. You didn't say what IDE are you using or what build system. And I don't know which ones are you familiar with.
If you really want to build it from sources run `gradlew test assemble --info --stacktraces` and make it work before importing it to an IDE. And the only supported (we know it works there) IDE is IntelliJ IDEA 14.+.

The following works with any IDE and build system: if you just want to use Glide, download `glide-3.6.0.jar` from https://github.com/bumptech/glide/releases and put it in your libs folder. You can also download `-sources.jar` and attach it to the main jar so you can browse, read docs and debug the code..

However it is really worth investing in learning Android Studio and Gradle because it's just one line there and a lot will be taken care of for you. If you're using a build system Glide is also in Maven Central: http://mvnrepository.com/artifact/com.github.bumptech.glide/glide/3.6.0

Hope this clears things up. Feel free to ask more questions.

**Comment by sjudd** [comment]
Let us know if you need more help
