### ISSUE TITLE
Getting Out of Memory Exception?

### ISSUE THREAD

**Issue by appstein** [bumptech/glide#494]
I have using your library to load images in my gallery application. While showing full size images in a ViewPager I'm getting out of memory exception. I'm using following code to load images in onActivityCreated():

Glide.with(getActivity())
                    .loadFromMediaStore(uri)
                    .asBitmap()
                    .signature(new MediaStoreSignature(mimeType, dateModified, orientation))
                    .into(mImageView);

This is usually happening if try to show a photo in landscape mode which was clicked in portrait mode and similarly, showing a photo in portrait mode which was clicked in landscape mode or when i rotate my device.

I also tried to use functions like atMost() - which was lowering image quality further and approximate-which was also giving out of memory exception.

I also tried to use ARGB_8888 format to increase image quality which was only adding to the problem of out of memory.

Is there also any way i can enhance image quality without getting out of memory exception.

I'm using glide 3.6.0 and i'm testing it on Samsung galaxy s3.

**Comment by sjudd** [comment]
How large are your views? How large are your images? Is it possible that you have a memory leak? If so you'd see memory usage go up over time, or after a certain set of actions in your app.

There are basically three possibilities

1. You have a memory leak (typically that's what I see cause OOMs)
2. You're loading many images that are large relative to your heap size at once (many being 3-5)
3. There's a bug where Glide isn't downsampling correctly.

I'd suspect the first, though if you're trying to show high resolution local images, I've seen OOM exceptions where the image size was less than twice the view size, and so couldn't be downsampled without quality loss. If that's the case, you may want to declare your app to be a large heap application. It won't help with memory leaks, but it will give you more room to decode larger and higher quality images.

Keep in mind also that there's typically a texture size limit of between 2048 and 4096 depending on your device. Bitmaps above the limit for the device won't be rendered and will instead log an error.

**Comment by appstein** [comment]
Hi! First of all thumbs up for this amazing library and thanks for replying. As for your questions:
I'm using ImageView with both width and height set to match_parent and upper limit of images size is roughly 3MB and as for the memory leak I will get back to you after making sure if there is 
a memory leak in the app.

However, the only place I'm passing context(which is usually the culprit for memory leak) is in Glide.with(getActivity()) in onActivityCreated(). So, on configuration change does glide hold reference to the previous activity? Maybe?

I'm using viewpager with offScreenLimit as 1. So, yes there are at most 3 images present in memory. But isn't the whole purpose of downsampling is to load a reduced size version of image into memory. Exactly how does Glide downsample image?

Also I am showing thumbnails in a gridview and i have disabled memory cache for them. But when I scroll down, the memory size keep growing as if the previous thumbnails are still kept in memory. And as I keep scrolling up and down repeatedly, the memory size keep on increasing which after reaching a certain size is reduced. Why is memory increasing even if I have disabled memory cache?

**Comment by TWiStErRob** [comment]
>  does glide hold reference to the previous activity?

Glide does hold on to the Activity in a `RequestManager`, but it also follows its lifecycle, so when the Activity is destroyed all the pending requests are cleared and then the `RequestManager` is thrown away.

> Exactly how does Glide downsample image?

The downsampling happens here: https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L329 and it should use the exact view size if it's `match_parent`.

> Why is memory increasing even if I have disabled memory cache?

Shouldn't do that, memory cache means that the list scrolling will reuse bitmaps (stored in memory cache), won't allocate many of them when scrolling fast. You esentially disabled the ability to fling :). Check your list adapter, are you using the ViewHolder pattern correctly? Glide can only clear an ImageView if it's properly recycled by the adapter, otherwise no-one will call `ImageView.setImageDrawable(null)`.

**Comment by sjudd** [comment]
Actually @TWiStErRob, if you disable the memory cache, Bitmaps are still put into the BitmapPool and re-used. They're two separate entities. Probably the reason why you see memory usage increase as you scroll even with the memory cache disabled is from Bitmaps filling the pool. That would also explain the memory increase stopping at some limit as the BitmapPool is also size limited. If you really want to, you can also disable the BitmapPool. 

As for downsampling, we can only really downsample by powers of two because that is all the framework allows for. As a result, we only downsample if you ask for an image with a width and a height that are both less than half of the image size. Otherwise we decode the image at the full size and then typically use the FitCenter transformation to scale it down to exactly the requested size.

**Comment by appstein** [comment]
@sjudd if bitmaps are re-used from the bitmap pool why is memory size increasing? And how can I disable BitmapPool? From what I analyzed from the heap dump, is that the bitmap pool is using most of the memory. I also confirmed that there is no memory leak in my app.

@TWiStErRob I am using recyclerListener on my gridview in which I am doing exactly as you are suggesting.

**Comment by TWiStErRob** [comment]
@appstein here's [how to configure Glide](https://github.com/bumptech/glide/wiki/Configuration#lazily-apply-configuration-changes-using-glidemodules) and here's a [description of BItmapPool](https://github.com/bumptech/glide/wiki/Configuration#bitmap-pool). In short: create a `GlideModule` and write `builder.setBitmapPool(new BitmapPoolAdapter())` into it.

The size is increasing to a certain level probably because even though the bitmaps are reused there are many bitmaps on screen at once. Two images side-by-side in the same row can't have the same backing bitmap (unless they're actually the same image) so the pool is filled with at least as many Bitmaps as thubmnails can be (partially) visible on screen; this should also amount to the same as many times the GridView inflates your item layout.

@sjudd the lower sections on this page suggest to use `new GlideBuilder().`, I think those should be just `builder.` to be consistent with the `GlideModule` on top.

**Comment by sjudd** [comment]
@appstein Robi is correct here, sizing requirements are relatively strict when re-using Bitmaps, so relatively small differences in dimensions require new Bitmaps. You can also mitigate this somewhat by requesting a consistent size and using the fit center transform which will at least make all images with the same aspect ratio the same size.

**Comment by sjudd** [comment]
Let us know if we can help further.
