### ISSUE TITLE
placeholder   when  

### ISSUE THREAD

**Issue by yanglichuan** [bumptech/glide#504]
lide.with(context).load(userInfo.user_icon).placeholder(R.drawable.ic_jia).centerCrop().into(iv_personIcon); 

always show the placeholder,  not show the net image
when first enter the activity

**Comment by yanglichuan** [comment]
i find

when i use circleImageview, it  happened!

but when i  use imageview ,it ok;

**Comment by TWiStErRob** [comment]
It sounds like #302, which seems like it was closed too soon, but in #482, we dug deep and found the core of the problem: https://github.com/bumptech/glide/issues/482#issuecomment-107977982

You have two options:
 * Use [CircleTransform](http://stackoverflow.com/a/25806229/253468) instead of ImageView
 * add `.dontAnimate()`

While disabling the animation seems easier, you may have more luck with the transformation in the long run.

**Comment by sjudd** [comment]
Let us know if you have more questions.
