### ISSUE TITLE
Does this work? new GlideBuilder(context).setDiskCache(new InternalCacheDiskCacheFactory(context, yourSizeInBytes));

### ISSUE THREAD

**Issue by miscellanea** [bumptech/glide#512]
https://github.com/bumptech/glide/wiki/Configuration

I guess not. Since this new GlideBuilder is an orphan, we can not call createGlide(protected) with this GildeBuilder and Glide.get will use another GlideBuilder to createGlide. So the settings on this new GlideBuilder is useless.

BTW: Is it possible to expose createGlide or GlideBuilder singleton so we can use GlideBuilder to initialize Glide without set meta in AndroidManifest.xml?

Thanks

**Comment by TWiStErRob** [comment]
Sorry, the [`GlideBuilder` related doc](https://github.com/bumptech/glide/wiki/Configuration#global-configuration-is-exposed-via-the-glidebuilder-class) is a little misleading since you're now (=3.5+) getting a `GlideBuilder` instance as an parameter in `GlideModule.applyOptions`, call `.setDiskCache` on that. What is the use case that prevents you from putting that single line in the `AndroidManifest.xml`?

*If you really, really want to go the old way*, here's the method in 3.x: [`Glide.setup(GlideBuilder)`](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/Glide.java#L190), but note the deprecation:
> **`@deprecated`** Use `GlideModule` instead. Scheduled to be removed in Glide 4.0.

**Source**: there's a little "revisions" link below the "Configuration" header
> Sam edited this page on Apr 14 · [8 revisions](https://github.com/bumptech/glide/wiki/Configuration/_history)

with that you can go back older documentation to see how it was done before, say ["Nov 7, 2014"](https://github.com/bumptech/glide/wiki/Configuration/fc2cabfed674a2a800c5265a238faa5e81fc3cbc), before the `GlideModule` doc was added.

**Comment by miscellanea** [comment]
Thanks.
Actually, my problem is that I want to use two different formats (RGB565 and ARGB8888) for different images.
So I'm wandering if some day we can use two glides with difference GlideModule, in that case I think it's better to use code to set instead of AndroidManifest.xml. 
Maybe there is other way to support different formats, I'm not sure.
BTW: UIL supports two ImageLoader with difference configurations.
Thanks

**Comment by TWiStErRob** [comment]
What a nice manifestation of an [X/Y problem](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem) :)

There many ways around this. See #261: it will be available to use more broadly in 4.0, but you can as easily apply different format per request: `.asBitmap().format(DecodeFormat.*)`. The key here is `.asBitmap()`. You can do a little more with Bitmaps than Drawables in 3.x. When using `asBitmap()` the only thing I'm aware that you lose is GIF animation support and `crossFade()`.

So you can apply the default for Drawables globally via `GlideBuilder` (i.e. where you want GIFs and/or cross-fade) and do one of the following elsewhere:
 1. add `.format()` to each call
 2. create a factory and use `Images.image565(context).load("...").into();`:

    ```java
    static BitmapRequestBuilder<String, Bitmap> image8888(Context context) {
        return Glide.with(context).fromString().asBitmap().format(PREFER_ARGB_8888);
    }
    static BitmapRequestBuilder<String, Bitmap> image565(Context context) {
        return Glide.with(context).fromString().asBitmap().format(PREFER_RGB_565);
    }
    ```
 3. You can even store them as fields:

    ```java
    private BitmapRequestBuilder<String, Bitmap> im32;
    private BitmapRequestBuilder<String, Bitmap> im16;
    public void onCreate(...) {
        im32 = Glide.with(this).fromString().asBitmap().format(PREFER_ARGB_8888);
        im16 = Glide.with(this).fromString().asBitmap().format(PREFER_ARGB_565);
    }
    void use() {
        // cloning is advised when shared, because not doing so can lead to weird/hard-to-trace bugs
        if (...) {
            im32.clone().load("...").into(...);
        } else {
            im16.clone().load("...").into(...);
        }
    }
    ```

If you want to separate cache directories based on format, you're out of luck I think, but I can't really think of any reason why you would really want that.

**Comment by miscellanea** [comment]
sorry about X/Y:) But it's indeed an issue in document:)
Thanks for solutions.
Unfortunately, I need to support gif as well as other formats. That's why I switched from UIL to glide:)
Fortunately, I'm using 4.0, #261 works, thanks a lot.

**Comment by ShreyashPromact** [comment]
What is the Alternate of **.setDiskCache()** method?
I am using Glide 3.8.0
