### ISSUE TITLE
Can useUnlimitedSourceGeneratorsPool be utilized in DATA|RESOURCE_CACHE stages?

### ISSUE THREAD

**Issue by ttseattle** [bumptech/glide#5177]
**Glide Version**: 4.15.1

**Issue details / Repro steps / Use case background**: 

I have a content provider that makes a GlideRequest like this: 
```
FutureTarget<File> futureFile = glideRequests.get().download(mediaModel).useUnlimitedSourceGeneratorsPool(true).submit();
File file = futureFile.get(/* timeout= */ 30, TimeUnit.SECONDS);
```

My screenshot test loads a photos grid which invokes the content provider. It uses a GlideRule which is configured to have 4 threads. The grid has 3 items which each fire off 2 GlideRequests, 1 for high-res and 1 for thumbnail. A Glide thread deadlock keeps happening because the `get()` call above is blocking but all the threads are taken. I am worried this will happen not just in testing, as long as the thread pool is small enough.

I initially added `useUnlimitedSourceGeneratorsPool` because I was seeing Glide requests failing in manual testing. I worked around this using this as a guide: https://github.com/bumptech/glide/issues/4213 In the test though, deadlock is happening at a different stage than where `useUnlimitedSourceGeneratorsPool` is utilized. 

```
public synchronized void start(DecodeJob<R> decodeJob) {
    this.decodeJob = decodeJob;
    GlideExecutor executor =
        decodeJob.willDecodeFromCache() ? diskCacheExecutor : getActiveSourceExecutor();
    executor.execute(decodeJob);
}
```

`useUnlimitedSourceGeneratorsPool` takes effect only if `getActiveSourceExecutor()` is invoked. However, we end up using `diskCacheExecutor` because `DecodeJob` is still at `DATA|RESOURCE_CACHE` stage.

Can `useUnlimitedSourceGeneratorsPool` be utilized in these stages as well?

**Comment by sjudd** [comment]
I'm guessing your ContentProvider can be called by other GlideRequests? So that you have a request in Glide that makes another request in Glide?

If so you, you will need useUnlimitedSourceGeneratorsPool in any request that your content provider makes because those requests might call back into Glide. Without the unlimited pool, Glide thread 1 can call call your content provider and block. Then your content provider can call back into Glide thread 1 and block, creating deadlock (you actually need several requests because Glide has 4 threads, not 1, but that's the general idea). 

You should not need to change the disk cache executor though because you do not control any logic that runs on the disk cache executor. The disk cache executor only ever reads data from the disk cache and decodes it. Assuming your ContentProvider is only called in a ModelLoader, it will never be called from the DiskCache thread. I suppose there are some exceptions for weirder cases like if you have a custom ResourceDecoder that calls Glide recursively, but I'm guessing you don't?

**Comment by ttseattle** [comment]
Thanks for the response! Correct, other GlideRequests are calling into the content provider which makes its own GlideRequest. `useUnlimitedSourceGeneratorsPool` is already set on the request within the content provider -- does it need to be set on the callers of the content provider as well? 

To clarify, above I was referring to my understanding of why Glide was not able to utilize the unlimited pool. I did not set the `diskCacheExecutor` flag on the GlideRequest, though I do think it was automatically set as being a request to `download()`. Are you saying though that the callers should never be in the `DATA|RESOURCE_CACHE` stage? I have only been able to produce this issue within the screenshot test, not when manually testing.

**Comment by sjudd** [comment]
You do not need to set `useUnlimitedSourceGeneratorsPool` on callers of the content provider, unless they're also called from some similar recursive blocking context (like another ContentProvider). 

In the data / resource cache stage, Glide should never call your code. So as long as your code isn't being called recursively, there's no chance for deadlock. 

The safe flow is: Application -> FixedThreadExecutor -> ContentProvider -> DiskCacheExecutor -> Glide code or
Application -> FixedThreadExecutor -> ContentProvider -> UnlimitedThreadExecutor 

The unsafe flow is:
Application -> FixedThreadExecutor -> ContentProvider -> FixedThreadExecutor because the FixedThreadExecutor is called recursively. 

Does that help? If you have a stack trace you can redact and put here, I'm happy to look. I don't recall exactly what the test setup is for screenshot tests. There are some weirder edge cases that could lead to a recursive cal in a decoder, but it would be hard to pin down without looking at what each thread is doing and where it's stuck. Often tests that time out print a complete set of stack traces somewhere.

**Comment by PureSin** [comment]
Hi Sam!

Thanks for the break down. We are doing the safe flow so there is not any deadlock in the app. However our test infra configured glide with the same executor for source/disk cache -> this was causing the test to deadlock. 

That's been resolved (Test Glide is updated to match the actual default Glide config). Appreciate the help!
