### ISSUE TITLE
Image takes to much time at first time loading after seconde time they appear quickly 

### ISSUE THREAD

**Issue by pawarlalit29** [bumptech/glide#522]
Image takes to much time at first time loading after seconde time they appear quickly

**Comment by sjudd** [comment]
Assuming these are images retrieved over the network, there isn't much we can do to increase network speed, so there may not be much we can do here.

For large images requested in large sizes, some not insignificant part of the request time can be spent re-encoding transformed thumbnails. You could try [``DiskCacheStrategy.SOURCE``][1], which will only write the raw received bytes to disk and see if that helps. 

If not, there isn't a whole lot we can do. You could try OkHttp or a different networking library, but I'd guess you won't see much difference.

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/load/engine/DiskCacheStrategy.html#SOURCE

**Comment by pawarlalit29** [comment]
i was change DiskCacheStrategy.SOURCE, but its not create big difference and i am also using OkHttp integration for increase timeout

**Comment by TWiStErRob** [comment]
Setting cache to `SOURCE` makes no difference because the problem is probably not CPU bound, it's network bound. Sam wanted you to confirm that and you just did. However keep it that way or set it to `ALL` so that any load that is not the first will be using the cache and reducing the bad experience the network causes.

If you need increased timeout that means that your ISP is giving you slow internet, Glide downloads the images via internet so the only option is to use a faster connection or accept the slowness. Note that you won't get any faster speeds with other libraries nor if you just open the same URL in a browser.

A possible workaround is to lower the resolution of the images on the server if you have control over the files. That way fewer bytes need to be transmitted (sometimes just reencoding a camera's jpeg with quality set to 80% without changing resolution makes a huge difference and not much visible quality loss). Sometimes there are options to add query string params or change the folder structure to achieve this. Also I'm sure you're not the first so there may be third party services that offer this feature in a format like this: http://example.com/resize?w=500&scale=fit&url=http://original/url.jpg

**Comment by pawarlalit29** [comment]
thanks for the reply,
but what was the solution in these case.
