### ISSUE TITLE
glide 3.6.0 bug in listview

### ISSUE THREAD

**Issue by a1018875550** [bumptech/glide#524]
if the item imageview android:layout_height="match_parent"  ;all of view will not display

**Comment by TWiStErRob** [comment]
Please include the whole list item layout xml and the Glide-related parts of the adapter.

**Comment by a1018875550** [comment]
e sorry,can you detail for it; 
if put the code it's very good

**Comment by TWiStErRob** [comment]
I don't understand. You can't share it? Is it too long? We just need the relevant parts.

**Comment by a1018875550** [comment]
this is my item layout
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

   <ImageView
       android:layout_width="match_parent"
       android:layout_height="match_parent"
       android:id="@+id/image"
       android:src="@drawable/pics_4"/>

    <ProgressBar
        android:id="@+id/progress"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:layout_centerHorizontal="true" />
</RelativeLayout>



and this is my getview code
  public View getView(int position, View convertView, ViewGroup parent) {
            convertView = getLayoutInflater().inflate(R.layout.item, null);
            ImageView imageView = (ImageView) convertView.findViewById(R.id.image);
            final ProgressBar progress = (ProgressBar) convertView.findViewById(R.id.progress);
            Glide.with(getApplicationContext())
                    .load("http://www.huabian.com/uploadfile/2015/0410/20150410040727869.jpg")
                    .crossFade()
                    .fitCenter()
                    .into(new GlideDrawableImageViewTarget(imageView){


                        @Override
                        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> animation) {
                            super.onResourceReady(resource, animation);
                            progress.setVisibility(View.GONE);
                        }

                    });

            return convertView;
        }

**Comment by TWiStErRob** [comment]
Hmm, that really looks OK other than a few probably unrelated issues. Can you please try to fix these and see if it works?
 * Learn about ViewHolder, for example [here](http://www.javacodegeeks.com/2013/09/android-viewholder-pattern-example.html)
 * `crossFade()` is the default animation, no need to be explicit
 * You can move `fitCenter()` to the XML with `android:scaleType="fitCenter"` on the ImageView.
 * you should attach a `listener()` to hide the progress instead of a custom target.

While writing those I noticed one important thing: **the item layout will be as tall as the progress view, that's how you defined it. Now, if you hide it (GONE) the list item will be 0 height, so you won't see an image (which matches height 0).**

Try adding `android:minHeight="?android:attr/listPreferredItemHeight"` to the root (RelativeLayout) or set a static `layout_height` like 150dp for the root.

**Comment by a1018875550** [comment]
thank you very much,

**Comment by a1018875550** [comment]
i solve that's bug;;
 i change "match_parent" to "fill_parent" it's solved;
but I have a new bug now
![image](https://cloud.githubusercontent.com/assets/8246218/8564387/f0a8825a-257d-11e5-92d3-c8d0ddc35c37.png)
 why i add the ".asGif()" the  method "GlideDrawableImageViewTarget" can't use it; 
i don't why

**Comment by TWiStErRob** [comment]
GIF requires a special drawable that can be animated. Remove the explicit target creation: `.into(ImageView)`.

**Comment by a1018875550** [comment]
i want to show the progress in gif;how shoud i do?It's there have any demo?thak you very much
--I'm sorry to my poor English

**Comment by TWiStErRob** [comment]
That question was discussed in detail in #446. Try [searching](https://www.google.hu/search?q=glide+gif+progress) before you ask ;)
