### ISSUE TITLE
Paused activities

### ISSUE THREAD

**Issue by TepesLucian** [bumptech/glide#526]
I've been testing my app on some emulated low memory devices (heap size 64MB) and if i navigate through a series of activities with images at some point the images aren't loaded anymore due to OOM exceptions. Please note that i managed to clear all memory leaks of the app activities with square's LeakCanary lib. My guess is that bitmap's aren't freed from the paused activities in the stack. 
Do you have any suggestions about this?

**Comment by TWiStErRob** [comment]
Read this article: [Activities not destroyed to free heap space](http://commonsware.com/blog/2011/10/03/activities-not-destroyed-to-free-heap-space.html) and the linked SO answer from Dianne.

You could probably work around it by `Glide.clear`ing the images in `onStop`. Treat the images like an expensive external resource, similar to Gyroscope for example.

**Comment by TepesLucian** [comment]
@TWiStErRob thank you for the advice. I was a bit surprised to find Dianne's answer because I recalled the docs stated that "If an activity is paused or stopped, the system can drop it from memory" like CommonsWare pointed out in the comments. You can go ahead and close this issue.

**Comment by eicm** [comment]
@Rob does clearing the view on pause cause flickers in views when app
resumes back?

**Comment by TWiStErRob** [comment]
@TepesLucian I've had that belief too, but then I ran into the same situation as you and found this article. Sadly "can drop it" doesn't mean "will drop it", but that's why this article is so revealing. My solution was to just restructure the app so that it's less likely to go too deep.

@eicm it should only happen if the user went so far that the Bitmap was evicted from the memory cache. In which case I think a little flicker is better than a crash :) But it's worth testing it since I've never done what I suggested...

**Comment by eicm** [comment]
@Rob is there a chance of another image (from the second activity) being
decoded into the bitmap while the bitmap is still hold by a view (from the
paused activity) when the app navigates through an activity life cycle?

**Comment by TWiStErRob** [comment]
@eicm It cannot be held by the view since you called `Glide.clear`. If you don't call that the ImageView (=its target) still owns the Bitmap so Glide is not handing it to anyone else.

**Comment by TepesLucian** [comment]
@TWiStErRob I've taken the safest route and always clear the bitmaps on activity onStop to see how the memory usage will fluctuate. @eicm The images don't flicker if the system doesn't call gc.

**Comment by TepesLucian** [comment]
@TWiStErRob since integrating the clear `onStop()` and loading `onStart()` there has been far less OOM crashes for users. At the moment I'm using ARGB_8888 bitmap configuration. There are still few crashes that remain and I think that if I change the config to RGB_565 if the heap size <= 64 MB it would solve them. Any suggestions/thoughts/recommandations about this?

**Comment by TWiStErRob** [comment]
I'd suggest to first try to reproduce those OOMs, it's possbile you have a rare memory leak.
You can even consider using RGB_565 for all users (depending on the images you show), if some people can handle 565 maybe all can :)

**Comment by TepesLucian** [comment]
@TWiStErRob I didn't want to open another issue but wanted to ask 2 things : 

1) Will there be an option like this in the future so Glide would automatically unload bitmaps on `fragment.onStop()` or `activity.onStop()`?

2) I have a screen where I load manually larger drawables from resources and see few OOM crashes. Should I consider `Glide.clearMemory` before that screen or should I consider loading the drawable using Glide to reused the its memory? I previously had a similiar issue on a different screen and since I've used Glide to load the drawables there were no more OOM issues on that screen.

**Comment by TWiStErRob** [comment]
1) exactly the type that needs a separate issue, so we can either track an enhancement or close as wontfix and reference from future issues. Possibly a good idea for future, it helps a lot with deep activity stack. I think my application could use it too. Feel free to open a new issue with a nice description and reason why it is a good idea (detailed use case).

2) `clearMemory` shouldn't help because Glide will automatically clear the memory cache and bitmap pool if app is low on free memory. Also Glide doesn't reuse bitmaps when loading a `resId` as far as I know. It just delays the load to the furthest possible point (e.g. if image is in memory cache, there's no need to load the placeholder, this saves time and memory; same with error and fallback)
The key to OOM as in this issue is that Glide needs to know that the images are not shown in any views (not active) so it's possible to get rid of the them prevent OOM. For this you need to call `Glide.clear` manually or destroy the fragment/activity that was used in `with`. Note: fragment hide doesn't qualify as destroy as far as I remember. I would say tap around for a while in that activity and then take a heap dump to see if any Bitmap is unnecessarily kept in memory. (Call `clearMemory` before dump as it doesn't affect active resources)
In case by drawables you meant assets disregard what I said and use Glide!

**Comment by TepesLucian** [comment]
1) Opened #942 

2) The app has big drawables bundled to be shown in that screen (stored in the drawable-nodpi so they won't get scaled). I'm wondering if `Glide.with(this).load(resId)` has any advantage over `BitmapFactory.decodeResource` (aside from decoding logic already built in Glide) ?

**Comment by TWiStErRob** [comment]
Hmm, I'm not sure if glide uses `decodeResource` (not found in v4 sources) and whether it can downsample when decoding an `int`. I would suggest to put those in `src/main/assets` and use `file:///android_asset/` so the normal InputStream flow can be used. I'll need to double check this.

**Comment by TepesLucian** [comment]
@TWiStErRob Thanks for the suggestions. Let me know if it's better to include the images in the assets folder.

**Comment by TWiStErRob** [comment]
So, it looks like Glide constructs an `android.resource://package/type/name` Uri (see `ResourceLoader`) which is then opened with `ContentResolver.openInputStream` (see `StreamLocalUriFetcher` built from `UriLoader`), so all decoding/downsampling will work the same as with assets. This means that loading both assets and Drawable integers through Glide should be on the same efficiency level, and are both better than hand-decoding with `BitmapFactory`. I personally would still put those in the assets if they're not used or planned to be used from anywhere else in the app via their `R.drawable.name`.

**Comment by TepesLucian** [comment]
@TWiStErRob thanks again for all your help. :+1:

**Comment by zpfkufei** [comment]
@TWiStErRob My problem is Out Of Memory.It points to ActiveResources class . Please help me ,thank you~

![_152489028741](https://user-images.githubusercontent.com/4396725/39392058-08edc22c-4ae1-11e8-8a41-480ccf1a3767.png)
202 instances of "android.graphics.Bitmap", loaded by "<system class loader>" occupy 321,328,448 (59.18%) bytes. 

Biggest instances:

•android.graphics.Bitmap @ 0x3370ce80 - 8,916,264 (1.64%) bytes. 
•android.graphics.Bitmap @ 0x33172880 - 8,640,072 (1.59%) bytes. 
•android.graphics.Bitmap @ 0x34691e80 - 7,203,928 (1.33%) bytes. 
•android.graphics.Bitmap @ 0x34695100 - 7,203,928 (1.33%) bytes. 
•android.graphics.Bitmap @ 0x333eb800 - 6,140,552 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x33ace5c0 - 6,140,552 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x34848100 - 6,140,552 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x33125640 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x33409a80 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x3348e5c0 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x3348e6c0 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x3359aa40 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x335a0b00 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x335bcd80 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x33647dc0 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x33750c40 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x33757780 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x33777e80 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x338eb480 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x33a96d00 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x34695580 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x346955c0 - 6,120,744 (1.13%) bytes. 
•android.graphics.Bitmap @ 0x34695600 - 6,120,744 (1.13%) bytes. 
These instances are referenced from one instance of "java.util.HashMap$HashMapEntry[]", loaded by "<system class loader>"

Keywords
java.util.HashMap$HashMapEntry[]
android.graphics.Bitmap

![1](https://user-images.githubusercontent.com/4396725/39392065-31332038-4ae1-11e8-8a7f-192b36a7e24c.png)

**Comment by TWiStErRob** [comment]
@zpfkufei please open a new issue with all info provided.
