### ISSUE TITLE
Animations on widget stutters when I load image into imageview

### ISSUE THREAD

**Issue by gauravlnx** [bumptech/glide#530]
In my app, I have a continuous animation of a widget going on. There are 4 to 5 image views on which I load images using Glide as:

Glide.with(getActivity()).load(imageFile).centerCrop().into(imageView1);

When the image is not available in cache and I load the image, the animation stutters a bit. Next time as the image is cached, animation is not affected. User can pick many images and they are changed after a fixed interval using a timer.

Is there anything I can do to solve this issue?

**Comment by TWiStErRob** [comment]
Does your animation animates those ImageViews? It's possible that the animation is happening on the GPU, but when Glide sets the new drawable it needs a little time to re-create the GPU textures.

Or maybe a relayout happens which takes away precious frame time from the animation. See more on this on [SO](http://stackoverflow.com/a/31246096/253468), however you don't use placeholders nor image size changes because of centerCrop, so it's just a guess.

You can also try do to a [trace](http://developer.android.com/tools/performance/index.html) (just press Start Method Tracing in Android view in Android Studio) and see how the regular pattern changes when Glide is loaded.

Also think about this: continous animation is not a good idea in a resource-constrained environment, like Android. How many times did your phone die before the end of the day? (If your answer if none, what kind of futuristic phone do you have? ;) Do you wish that for others?

**Comment by gauravlnx** [comment]
Thanks for the reply.

I am not animating the imageviews. Its a custom marquee animation of TextView. I can't show placeholders in my imageviews because of client's requirement.

Does Glide loads images on main thread?

**Comment by TWiStErRob** [comment]
It doesn't load them on main thread, that would defeat the whole purpose of it. The files are decoded in background and the the final Bitmap/Drawable is handed to the ImageViewTarget on the main thread to set via setImageBitmap/setImageDrawable.

I would play around with setDrawingCacheEnabled and setLayerType to see if that helps (in case it's the GPU texture that causing the problem).

**Comment by sjudd** [comment]
You might also try [`dontAnimation()`][1], but beyond that all Glide does is call setImageDrawable/setImageBitmap on the ImageView. No loading is done on the main thread. 

If you're loading sufficiently large images it's possible the texture upload time is the culprit. You could test by seeing whether loading smaller images incurs the same jank.

Let us know if you have any other questions.

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/DrawableRequestBuilder.html#dontAnimate()

**Comment by gauravlnx** [comment]
In my project, in a screen I import some images from gallery to app's private directory and show the images(thumbnails) in a RecyclerView Grid. While importing images I display a progress dialog. I have noticed that when the thumbnail is loaded into the grid item's ImageView, progress bar animation also gets a hiccup.

Sorry for posting this in the closed thread.

**Comment by TWiStErRob** [comment]
Try to profile your code:
 * http://developer.android.com/tools/debugging/debugging-tracing.html
 * http://developer.android.com/tools/debugging/systrace.html
 * http://developer.android.com/training/improving-layouts/optimizing-layout.html

Obviously anything you do will take time using Glide or not, setting a Bitmap in an ImageView is a really expensive operation compared to spinning a progress bar, and both are competing for the UI thread. 

If you're adding items to a RecyclerView a layout happens every time a new item is added. You can try to prefill the grid with empty items (if you know at the beginning of import how many will be imported). You can also try using smaller thumbnails maybe.
