### ISSUE TITLE
invalidate cache key

### ISSUE THREAD

**Issue by andaag** [bumptech/glide#538]
Hi

I'd like an option to invalidate a cache key where the url/signature is known.

 I've read through https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation, and that makes sense. However, if I set my own signature (for example "personalavatar"), and I know that key has changed during a background service upload. It should be easy enough to invalidate that one key.

There are other cases as well. For example in some situations when uploading new images we are very aware of where those images are being used and exactly which url is loaded. It would make sense in those scenarios to invalidate those cache keys, and wait for the next load to reload the image.

**Comment by TWiStErRob** [comment]
The problem is that a lot of info is needed to find (and invalidate) a cache item: model (url), target size, decoder, transformation and others. You can see that all these are only available at the exact load site (especially the size). So it's not possible to say "delete all whose signature is X", more so because cache keys are hashed values of all those above, so you can't even hack it...

In case of a personal avatar you must have some model for the user(s) stored on the phone (DB, properties), or even a web service that returns it every time. I suggest to add a `lastAvatarUpdate` field next to the `avatarUrl` and set it to currentTimeMillies on upload completion (this is the invalidation). You can then use that number as `signature()` (this is the waiting for next load) resulting in the required behaviour.

**Comment by andaag** [comment]
Right, I didn't think about the different cache for differen transform operations. Sorry about the noise and thanks for the explanation!

**Comment by TWiStErRob** [comment]
No worries!

> When in doubt, file an issue. We'd rather close a few duplicate issues than let a problem go unnoticed. --- [`CONTRIBUTING.md`](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md)
