### ISSUE TITLE
Using DrawableRequestBuilder without ever creating a SquaringDrawable

### ISSUE THREAD

**Issue by nathanielwolf** [bumptech/glide#545]
I spent some time trying to figure out why my near square images where being skewed into squares, and then I discovered how `GlideDrawableImageViewTarget` worked to return SquaringDrawable for images with aspect ratios < 0.05f.

How can I override this behavior so `SqauringDrawables` are never created?

I know I can use a `BitmapRequestBuilder` with `.asBitmap()`, but I'd prefer not to incur the cost of a bitmap instead of a `GlideDrawable`.

**Comment by nathanielwolf** [comment]
I may have found my own question here:
https://groups.google.com/forum/#!searchin/glidelibrary/squaringdrawable/glidelibrary/UPq4H4009OY/WoIXxZhURxUJ

```
@SuppressWarnings("unchecked")
        ImageViewTarget<GlideDrawable> target =
                (ImageViewTarget<GlideDrawable>) (ImageViewTarget) new DrawableImageViewTarget(mAlbumArt);
        drawableRequestBuilder.into(target);
```

**Comment by TWiStErRob** [comment]
Yep, that's pretty much it, here's the [exact source of that code](https://groups.google.com/d/msg/glidelibrary/UPq4H4009OY/WoIXxZhURxUJ).

There's one thing to note: actually the default load has (an ignorable, see later) extra cost of creating the GlideDrawable over just a Bitmap, which is the opposite of what you think. `ImageViewTarget`'s children use `setImageDrawable` by default versus `setImageBitmap` for `asBitmap()`, which secretly creates a `BitmapDrawable` anyway.
A Bitmap has to be created, there's no other way to store pixels (unless you cleverly load a vector-like drawable into Picture). The default `.transform()` wouldn't work otherwise.

Check out [Glide flow](https://docs.google.com/drawings/d/1KyOJkNd5Dlm8_awZpftzW7KtqgNR6GURvuF6RfB210g/edit?usp=docslist_api) for more details (for asBitmap `transcode` is just a `return bitmap`).

Check `GlideDrawable`'s two children: one holds a Bitmap and the other one is for GIF, we can ignore Squaring here, since that's your issue. So if you don't use GIFs and willing to give up crossFade, `.asBitmap()` looks better in code that that generics hack. (See Alternative solution in the linked email.)

**Comment by sjudd** [comment]
In 4.0 the squaring drawable will become optional so this will be less of a pain to work around. Let us know if you still have questions.
