### ISSUE TITLE
Change the Glide singleton visibility to protected

### ISSUE THREAD

**Issue by pdegand** [bumptech/glide#548]
Hello,
If the singleton static variable of Glide in Glide.java would be protected, this would allow the possibility to override its value when subclassing Glide.

For example, this would be very useful to replace the default Glide implementation by a mocked one to assert the last url loaded by Glide.

Today, it's still possible to do this with reflection, but it would be cleaner with a protected field and I don't think this will break Glide internally, only if developers decides to subclasse Glide and do stupid things with the singleton.

I would like to see what you think about this.

Thank you and keep the good work on this great library :)

**Comment by TWiStErRob** [comment]
I don't think it's a good idea to allow subclassing Glide, let alone allow to replace the singleton. Though currently you can easily replace it without reflection, just call the deprecated `setup(GlideBuilder)` with a mock.

I think for testing you just need to replace the [default loader](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/Glide.java#L235) and capture/return mocks there, like this:

```java
// setup
ModelLoaderFactory<GlideUrl, InputStream> factory = mock();
ModelLoader<GlideUrl, InputStream> loader = mock();
mock(factory.build()).return(loader);
Glide.get(context).register(GlideUrl.class, InputStream.class, factory);

//test
Glide.with(context).load("http://..").into(imageView);
GlideUrl actualUrl = mock(loader.getResourceFetcher()).getCapturedArgs()[0]; // model, width, height

//teardown
Glide.get(context).register(GlideUrl.class, InputStream.class, new HttpUrlGlideUrlLoader.Factory());
```

This is just a rough idea, also check out how [Sam did the testing](https://github.com/bumptech/glide/tree/3.0/library/src/androidTest/java/com/bumptech/glide), maybe there's something useful there.

I'm curios what @sjudd says to this too.

**Comment by sjudd** [comment]
I'm also not inclined to allow subclassing, but you can definitely take a look at our unit tests for how we handled setting up and mocking the various parts of the singleton.

Keep in mind that almost all primary actions are actually started with the [`RequestManager`][1] class, which is not final and can therefore be mocked.

Instead of:

```java
Glide.with(fragment)
    .load(url)
    .into(view);
```

You can just retrieve the `RequestManager` once and use it for each load, which would allow you to inject a mocked version in your tests:

```java
RequestManager requestManager = Glide.with(fragment)
...
requestManager.load(url).into(imageView);
```

Let us know if these suggestions don't cover your use case.

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/RequestManager.html
