### ISSUE TITLE
Use RecyclerView Problem - memory leak 

### ISSUE THREAD

**Issue by Changsik00** [bumptech/glide#551]
i use glide library in my project ( release 3.6.1 )

i found error memory leak in RecyclerView on RecyclerView.Adapter of onBindViewHolder

so make test project (https://github.com/Changsik00/GlideTest.git)

recyclerMode = true is found only when the use.

**Comment by Changsik00** [comment]
solved problem 

RecyclerView.Adapter ->  override onViewRecycled

```java
@Override
public void onViewRecycled(RecyclerView.ViewHolder holder) {
    super.onViewRecycled(holder);
    ViewHolder viewHolder = (ViewHolder) holder;
    Glide.clear(viewHolder.foodImage);
}
```

**Comment by TWiStErRob** [comment]
Glide is designed for lists. You do no need to manually clear items unless you do advanced things. Loading a list of URLs into a list with ImageViews is not advanced.

The problem is [here](https://github.com/Changsik00/GlideTest/blob/master/app/src/main/java/lowmans/test/glidetest/RecyclerViewAdapter.java#L25), you should return 0 or not even override that method. By returning `position` you essentially tell RecyclerView not to recycle anything. Different viewType means different **incompatible** layouts, but you only have one type of layout!

## Additional tips
You don't need `ImageViewWithTarget` for Glide, Glide handles Targets and Requests very gracefully out of the box (see `ViewTarget` for implementation details).

You should also implemented the list view adapter contract correctly:
```java
    // notice it returns String instead of Object
    // java 5 introduced covariant return types
    // which means you can declare to return subclasses when overriding
    // String is a subclass of Object
    @Override public String getItem(int position) {
        return Data.URLS(position);
    }
    @Override public long getItemId(int position) {
        return position;
    }
```
Then you can use:
```java
viewHolder.setView(position, getItem(position));
```
The benefits are not immediately visible, but using `getItem` makes your code DRY.

You can do the same for `RecyclerViewAdapter`.

**Comment by sjudd** [comment]
Also worth noting that in some cases with RecyclerView you may want to keep the clear call in onViewRecycled. RecyclerView is a little more aggressive about keeping views around in the pool than ListView and particularly if you have a couple of view sizes, they can build up pretty quickly. Clearing the view at least ensures the view doesn't contain a large Bitmap while it's sitting in the pool.

**Comment by amankumarjain** [comment]
how to clear memory if i have multiple viewType recycler view with some of holders have image and others don't have.

**Comment by TWiStErRob** [comment]
@amankumarjain yep, that's it.
