### ISSUE TITLE
Remove images from cache

### ISSUE THREAD

**Issue by binaryfork** [bumptech/glide#552]
I'm downloading lots of images in cache for offline usage. It would be nice if I could somehow tag a group of images and then delete them by using the tag. Is it possible to implement?

**Comment by TWiStErRob** [comment]
Sorry, but it's not directly possible by design.

### Clear all
You can delete all via
```java
    Glide.get(context).clearDiskCache()
```
on a background thread.

### asBytes
You can also disable caching (`.diskCacheStrategy(NONE)`) and save the file for yourself (`.asBytes()`), then load those files offline and delete the folder when you want to remove the group.

### downloadOnly
You can also be hacky and use `downloadOnly()` with the same arguments as the load used to display those images to get a File handle into the cache and store the File names for later when you want to delete the files. You'll need to know the view size or use `SOURCE` cache. See [wiki](https://github.com/bumptech/glide/wiki/Loading-and-Caching-on-Background-Threads) for more.

**Comment by binaryfork** [comment]
I see, thank you for the clear answer.
