### ISSUE TITLE
Glide can encoding image url automatically?

### ISSUE THREAD

**Issue by Folyd** [bumptech/glide#555]
It seem like Gilde never deal with url encoding,cause it cannot load such a url to a image. http://7qnc4r.com1.z0.glb.clouddn.com/a_zmqbbazclz_907宁夏 梁静茹.jpg

Notice:the url contain white space,but the browser can encoding the url to http://7qnc4r.com1.z0.glb.clouddn.com/a_zmqbbazclz_907宁夏%20梁静茹.jpg 

Does Glide support  encoding the image url automatically?

Any comment is welcome.Thanks!:)

**Comment by TWiStErRob** [comment]
There's isn't much magic going on with URL encoding, see [Glide's StringLoader](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/model/StringLoader.java#L31).

Glide essentially wraps [`Uri.parse`](http://developer.android.com/reference/android/net/Uri.html#parse(java.lang.String)) so `Glide.with.load(String)` accepts whatever that can accept; and it says it's expecting "an RFC 2396-compliant, encoded URI", so there you have it.

In general you can't compare user interface behavior to a low-level programming API. The browser's addressbar does magic most of the time, they're using the low-level API to recognize and convert user input. For example it can somehow handle partially encoded uris as well. I think an Uri without properly encdoed parts is not a Uri (i.e. it is not according to RFC standard), see for example above in your comment, the first one is not recongized because the space cannot be part of an Uri.

Glide is a programming API, and is mostly used with Strings coming from other programming APIs, for example web services, and those should be spitting out RFC Uris. If you think about it it's a hard problem too, if Glide were to encode the received String you couldn't hand it encoded Uris because they would be double-encoded, see for example `%20 -> %2520` in [this comment](http://stackoverflow.com/questions/3286067/url-encoding-in-android#comment32532417_3286128).

Also take a look at
 * http://developer.android.com/reference/android/net/Uri.html#encode(java.lang.String)
 * http://developer.android.com/reference/java/net/URLEncoder.html
 * http://developer.android.com/reference/java/net/URLDecoder.html

**Comment by sjudd** [comment]
We do a bit of encoding here as well: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/GlideUrl.java#L91.

That said I agree with Rob, if you might be passing strings that need to be encoded to Glide, you're probably better off doing the encoding in your app rather than trying to get Glide to do it. We're likely to either not cover your use case or by covering your use case, break someone else's use case.
