### ISSUE TITLE
load image to slowly

### ISSUE THREAD

**Issue by xyzmst** [bumptech/glide#573]
load gif image too slowly and fail some times ,
load jpg image fail first time

**Comment by TWiStErRob** [comment]
Please provide more information, it's hard to figure out anything from "it doesn't work". See [the issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues). In your case the most important part is the reason of the failure (exception) which can be obtained via [logging](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling). Also if you can provide how you load it (Glide load line) it may help too, the URL you request (actual values passed to load) also can be helpful since we can check the original image, and observe the server speed.

Without the above my guess is that you most likely have a timeout for JPEG, so you need to change network library and set up a bigger timeout; and you have a long/large GIF, so you should set `.diskCacheStrategy(SOURCE)` on the GIF load.

**Comment by xyzmst** [comment]
Load image disappear the first time when never load the image , wharever  from the network or local，
no fail logging for more infomation. 
but it appear when load the image again .
the version is 3.6.0 and 3.6.1
the code:

final String path = paths.get(position);
Uri uri;
 if (path.startsWith("http")) {
      uri = Uri.parse(path);
   }else{
      uri = Uri.fromFile(new File(path));     
  }
Glide.with(mContext)
                    .load(uri)
//                  .dontAnimate()
                    .override(1800,1800)
                    .listener(new RequestListener<Uri, GlideDrawable>() {
                        @Override
                     public boolean onException(Exception e, Uri uri,  Target<GlideDrawable> target, boolean b)     
                        {
                            progressBar.setVisibility(View.GONE);
                            return false;
                        }
                        @Override
                        public boolean onResourceReady(GlideDrawable glideDrawable, Uri uri,    Target<GlideDrawable> target, boolean b, boolean b1) {
                            progressBar.setVisibility(View.GONE);
                            imageView.requestLayout();
                            imageView.invalidate();
                            return false;
                        }
                    })
                    .dontTransform()
                    .into(imageView);

**Comment by TWiStErRob** [comment]
Is it an extended ImageView?
Try to remove invalid and requestLayout.

Also that Uri.parse part is automatic you can just hand the string to Glide, it'll know what to do.

**Comment by xyzmst** [comment]
thanks!
but it no used to remove invalid and requestLayout.
the image disappear
my test url is
http://7jptcr.com5.z0.glb.clouddn.com/48/45/20150810160812439168000482.jpg
and 
http://7jptcr.com5.z0.glb.clouddn.com/173/32/20150808230202739974000381.jpg

**Comment by sjudd** [comment]
My guess is this is actually a layout issue. Is imageView actually an ImageView, or is it a subclass? If you try giving the view itself a fixed width and height in dp, does the problem go away?
