### ISSUE TITLE
Can glide not load when listview scrolling?

### ISSUE THREAD

**Issue by start141** [bumptech/glide#582]
Hi everybody!
  I want to load image when listview not scrolling, because it can let listview scrolling smooth?
I know picasso has methods about this. Can glide do this?

Thanks!

**Comment by TWiStErRob** [comment]
Check out `Glide.with.pauseRequests`:
> if you call Glide.with(fragment/activity).pauseRequests(), new requests will not run until you make a corresponding resumeRequests() call. Those changes let you add an OnScrollListener and pause/resume requests depending on the scroll state. --- https://github.com/bumptech/glide/issues/90#issuecomment-53967672

**Comment by start141** [comment]
Yeah, thank you!

I have try pauseRequests and resumeRequests, it's work.
But another problem found, if the image already in the memory, it also cannot load when listview scrolling.
I think it is not a good experience.

So, can not load images when listview scrolling only images which not in the memory？

**Comment by TWiStErRob** [comment]
I'm not aware of that, but, the default behaviour is that you just start all loads while scrolling or anything happens, in the list Adapter's bind phase, and that will result in smooth scrolling and images showing up from memory cache. Because of the recycling all requests will be started, but some will be immediately cancelled by the next one on the same item view. Resulting in the behaviour you ask for. Picasso may not work this way, that's why you manually need to pause/resume, but in Glide you generally don't have to. Those methods are more for lifecycle, that is to pause when fragment/activity is hidden (whcih is, again, automatic).

If the scrolling is not smooth by default usage, I have these to double check:
 * list recycling is correctly implemented using ViewHolder pattern: no extra views are inflated, just enough to fill the screen
 * run your app without attached debugger or if you must attach it, reduce the number of breakpoints to the minimum; this doesn't mean to do a release build, just press the other button on the toolbar next to Debug.
 * Sometimes it gets laggy because there's too much layout going on: http://stackoverflow.com/a/31246096/253468

**Comment by start141** [comment]
Thank you!

**Comment by bwelco** [comment]
Using pauseRequests() / resumeRequests() let listview scroll not smooth...
i catch it in dispatchEvent
i do it wrong?
