### ISSUE TITLE
I want to reload picture from sdcard.

### ISSUE THREAD

**Issue by wangkunlin** [bumptech/glide#583]
As the title,I do not know how to do with Glide.Please help me.

**Comment by TWiStErRob** [comment]
Assuming you mean you changed the original file contents and the changes are not reflected on the UI, that's because Glide caches a resized version of the image by default for memory and CPU efficiency.

Read the [Cache invalidation wiki](https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#cache-invalidation) from header to end of document.

If that's not what you meant, please explain you problem in more detail.

**Comment by wangkunlin** [comment]
thanks a lot,it solved my problem
