### ISSUE TITLE
Why the toTransform width/height which of the custom transform callback is not equal the outWidth/outHeight, when glide load with transform!

### ISSUE THREAD

**Issue by start141** [bumptech/glide#597]

**Comment by start141** [comment]
Sorry for my poor English!

Glide load image with custom transform, like this:
```
Glide.with(this)
    .load(new File(filePath))
    .override(300, 300)
    .centerCrop
    .transform(new MyTransformation(this))
    .into(imageView);
```
```
private static class MyTransformation extends BitmapTransformation {

    public MyTransformation(Context context) {
       super(context);
    }

    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap toTransform, 
            int outWidth, int outHeight) {
       Log.e("MyTransformation", "toTransform width=" + toTransform.getWidth() + ", height=" + toTransform.getHeight()
+ "; outWidth=" + outWidth + ", outHeight=" + outHeight);
       // do nothing
       return toTransform;
    }

    @Override
    public String getId() {
        return "MyTransformation";
    }
}
```

The log shows, toTransform width/height not equal outWidth/outHeidht. it is larger than 300.


But Glide load without custom transform, the values is equal. toTransform width and height is 300.
Glide line is:
```
Glide.with(this)
    .load(new File(filePath))
    .override(300, 300)
    .centerCrop
    .into(imageView);
```

It may be a bug?

**Comment by start141** [comment]
How can I get the value of the accurate with custom transform? Thanks!

**Comment by start141** [comment]
I want to do something in my custom transform, it is important for the toTransform width and height.

**Comment by floating-cat** [comment]
Looks it works as intended.
```
@param toTransform The {@link android.graphics.Bitmap} to transform.
@param outWidth The ideal width of the transformed bitmap (the transformed width does not need to match exactly).
```
> toTransform width/height not equal outWidth/outHeidht

`toTransform`'s width and heigh are the actual values of the bitmap. And the `outWidth` and `outHeight` are ideal width of the transformed bitmap calculated by Glide. They are not equal most of the time.

Looks you misunderstand `@param toTransform`.

**Comment by start141** [comment]
But I set `override` already. I don't understand why not equal, I think to transform the value of the accurate should be glide's job. 

Sorry for my poor English!

**Comment by start141** [comment]
And why the values equal when glide load without custom transform?

**Comment by floating-cat** [comment]
This is `toTransform`, not the `transformed`.
```
@param toTransform The {@link android.graphics.Bitmap} to transform.
```
Not
```
@param transformed The transformed {@link android.graphics.Bitmap}.
```

So `toTransform`'s width and heigh are the actual values of the original bitmap. `toTransform`'s width and heigh are always same whether you set a `Transformation`.
But the transformed bitmap' size is not equal whether you set a `Transformation`.

```
@Override
protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
    // do nothing
    return toTransform;
}
```
You just return the original bitmap, some `override` makes no senese.

**Comment by start141** [comment]
In my test `toTransform`'s width and heigh is not actual values of the original bitmap!

So I don't understand what the `toTransform` mean actually.

How can I get the actual target width/height in the transform call back?

**Comment by start141** [comment]
For example:

I hava a image, first step I must to transform it to 100 x 100, two step I will transform it in my `custom transform`, the step one's transformed size is very important, it must be accurate！

In Glide, I don't know how to do this! Somebody know how can do this? Thanks a lot!

In Glide's custom transform, the call back `toTransform` is not equal your `override` size!
I think it may be a bug of the Glide.

**Comment by floating-cat** [comment]
On, I guess I misunderstood `override` (Actually I forget this).
You can see this issuse:
https://github.com/bumptech/glide/issues/441

`toTransform`'s size is not equal `override`. If you want get actually size, you should write you own `Transformation`.

**Comment by start141** [comment]
Yeah, thank you. I see you issue #441 before. With @sjudd said, mean `fitCenter()` and `centerCrop()` doesn't work when use `custom transform`?

In my Glide line, I also use `centerCrop()`, `toTransform`'s size is still not equal `override`.

**Comment by TWiStErRob** [comment]
`toTransform` is the image *to transform* to have `outWidth` by `outHeight` size. When you use Glide normally, without any transformations, it automagically uses the `android:scaleType` set on the ImageView, see `GenericRequestBuilder#into`.

In general a transformation's job is to change the size to the requested one, and since there are too many possibilities of fitting a small/large image into a large/small area, it can't be automatic. The default Glide behavior ends up with the size you give in the `.override()` because of the automagic transformation (see above). By using `.transform()` you set the `isTransformationSet` internal flag and take the responsibility of resizing the image to `outWidth` by `outHeight` size, which you can do by applying a resizer transformation chained before your custom one (see below).

```java
...
    .override(300, 300)
    .centerCrop()
    .transform(new MyTransformation(this))
```
doesn't work as you expect because `.transform()` calls are not additive, so your custom transformation overrides `centerCrop()`. If you check the source code of `centerCrop()` you'll find it's calling `.transform()` as well.

Take a look at this question: https://groups.google.com/forum/#!topic/glidelibrary/VuoCeU30G88
which is the same as what you want: a custom transform after Glide has done it's job, you can try the following syntax:
```java
BitmapPool pool = Glide.get(context).getBitmapPool();
...
    .override(300, 300)
    .transform(new CenterCrop(pool), new MyTransformation(this))
```

**Comment by start141** [comment]
@TWiStErRob Yes, I can use multiple `transform` to solve it. Thank you very much!

**Comment by sjudd** [comment]
Thanks all!
