### ISSUE TITLE
Memory leak related to Glide

### ISSUE THREAD

**Issue by RomainPiel** [bumptech/glide#616]
```
In com.example:2.0:45.
* com.example.ArtistActivity has leaked:
* GC ROOT thread com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.<Java Local> (named 'fifo-pool-thread-0')
* references com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$LoadTask.sync
* references java.util.concurrent.FutureTask$Sync.callable
* references java.util.concurrent.Executors$RunnableAdapter.task
* references com.bumptech.glide.load.engine.EngineRunnable.manager
* references com.bumptech.glide.load.engine.EngineJob.cbs
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* references com.bumptech.glide.request.GenericRequest.target
* references com.bumptech.glide.request.target.GlideDrawableImageViewTarget.view
* references android.widget.ImageView.mContext
* references android.support.v7.internal.view.ContextThemeWrapper.mBase
* leaks com.example.ArtistActivity instance
```

Leak Canary just found that memory leak in my app and it looks like it's related to Glide.
This call is not doing anything fancy:
```Java
Glide.with(heroImage.getContext())
                .load("http://....")
                .into(heroImage);
```

I only reproduced the issue on API 16.

Any ideas?

**Comment by TWiStErRob** [comment]
Glide should be hooking into the activity life cycle, if Leak Canary does the same, there may be an ordering issue: that is Leak Canary checks too soon, before Glide has the chance to clean up in response to a stopped activity.

If you can reproduce consistently, you could check a heap dump few seconds after you get this message to prove that the leak is real and not a false positive.

**Comment by LiHanGuang** [comment]
@TWiStErRob 
@RomainPiel
I also have this problem,  but i solve it.

Solution:
MyActivity.java
onDestory(){
        Glide.get(this).clearMemory(); //  call this method manual 
}

Question:
"Glide should be hooking into the activity life cycle",
Is Glide auto call "clearMemory()" when the callback method "onDestory" be called?

**Comment by TWiStErRob** [comment]
No-one should call clearMemory, it's too harsh, it works against the whole existence of Glide: have the images ready as fast as possible. Imagine someone leaves the activity and then immediately comes back, all the images have to be reloaded, but if they are in memory cache, it's as simple as a `Map<>` lookup, otherwise it involves disk I/O. Also "unused memory is wasted memory" ;), which in this case means that it's better to have some Bitmaps occupy RAM and only remove them once some more space is needed for new ones, until then they're just ready to be reused.

> Is Glide auto call "clearMemory()" when the callback method "onDestory" be called?

See [RequestManager](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/RequestManager.java#L221), it essentially stops any pending loads, because "why load an image that will never be displayed?".

**Comment by TWiStErRob** [comment]
@RomainPiel do you have any news on this one? Are you still seeing it?

I looked at the code of Android/Glide/LeakCanary more deeply and found this:

 * `LeakCanary.install` will add a new `ActivityLifeCycleListener` inside `ActivityRefWatcher`.
 * Glide will add a `[Support]RequestManagerFragment` into each Activity it lays its hand on via `with(Activity|Fragment|Context)`.
 * Android support's `FragmentActivity.onDestroy` calls super first which notifies the lifecycle listeners via `Application.dispatchActivityDestroyed` (last line in `Activity.onDestroy`) while `mFragments.dispatchDestroy()` is called after that.

This means that Glide doesn't stand a chance cleaning up before LeakCanary checks for leaks.
Luckily without the support lib the stock Android order is the opposite, see `Activity.performDestroy`.

The above sounds like a reasonable explanation but I may be wrong, because it doesn't answer the only API 16 thing. What others did you try on?

**Comment by sjudd** [comment]
For what it's worth, that reference chain is entirely expected behavior. We don't use weak references, but rather rely on callers to tell Glide that they're no longer interested in a load. Typically that happens automatically in onDestroy as @TWiStErRob mentioned.

As long as you don't see memory usage increasing over time, it's probably a race of some kind and is safe to ignore. Typically loads will be short lived even if they're not cancelled, and if @TWiStErRob is correct, then these actually are cancelled and should be even more short lived.

**Comment by TWiStErRob** [comment]
@RomainPiel please reopen if you think there's anything more we can do and you have a chance to answer the above questions.

**Comment by jemshit** [comment]
I was getting this too, so it is safe to ignore

**Comment by ctarabusi** [comment]
I am also experiencing the same leak only on api level 16

I added logging breakpoints and seems that the GenericRequest#cancel and Engine#onEngineJobComplete and Engine#onEngineJobCancelled are called when the screen is rotated.

We are choosing to ignore this issue being a small amount of our customers still on that api level

![glide-leak api16](https://cloud.githubusercontent.com/assets/3064062/26238201/542063ee-3c78-11e7-82fa-c02b5c32f654.png)
