### ISSUE TITLE
How to get gif from third-party applications asset using glide?

### ISSUE THREAD

**Issue by shewenbiao** [bumptech/glide#622]
I used glide to load gif from asset , like this Glide.with(getContext()).load("file:///android_asset/01.gif").into(mImageView),
it could load the gif,but when I used Glide to load gif from othird-party applications asset, like this : 
Context context = getContext().createPackageContext(packageName, Context.CONTEXT_IGNORE_SECURITY);
Glide.with(context).load("file:///android_asset/01.gif").into(mImageView), it couldn't load the gif .This problem confused me ,could you talk me a way to solve this problem? Thanks!

**Comment by TWiStErRob** [comment]
@shewenbiao how did you solve it?

**Comment by shewenbiao** [comment]
@TWiStErRob I'm so sorry for just saw your reply today.I find the solution in Google‘s forum(https://groups.google.com/forum/#!topic/glidelibrary/6X_Q0Z9ERB4), that is your answer for Asker. My code like this:
Context context = null;
            try {
                context = getContext().createPackageContext(pkg, Context.CONTEXT_IGNORE_SECURITY);
            } catch (PackageManager.NameNotFoundException e) {
                e.printStackTrace();
            }
            if (context != null) {
                AssetManager assetManager = context.getAssets();
                InputStream inputStream = null;
                try {
                    inputStream = assetManager.open(filePath + File.separator + fileName);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                if (inputStream != null) {
                    Glide.with(getContext()).load(inputStream).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(holder.stickerImg);
                }
            }
Thanks your answer help me solve my problem!

**Comment by TWiStErRob** [comment]
Aaah, that's a workaround :) Actually, you shouldn't call `assetManager.open` on the UI thread. My rule of thumb is: if I need to catch `IOException` then it's potentially blocking, which cannot run on UI. I suggest that instead of the passthrough loader you create a model containing `pkg` and `filePath` and `fileName`, create and register a `ModelLoader` for it, and a `DataFetcher` that contains the above code and returns the stream. It'll be more reusable, faster and safer. Take a look at https://github.com/bumptech/glide/issues/634#issuecomment-141344318 or [this thread](https://groups.google.com/d/msg/glidelibrary/wneghdP2v2o/rHsVen8G8fEJ) for an example.

**Comment by shewenbiao** [comment]
Thanks for your fast reply, I will try it and let you know if I get some issues.

**Comment by shewenbiao** [comment]
Thank you very much for your suggestion.It works pretty well than before.

2015-09-19 18:48 GMT+08:00 Róbert Papp <notifications@github.com>:
