### ISSUE TITLE
Can I use BitmapPool like this?

### ISSUE THREAD

**Issue by start141** [bumptech/glide#633]
```java
boolean maskFromBitmapPool = true;
Bitmap mask = mBitmapPool.get(source.getWidth(), source.getHeight(), Bitmap.Config.ARGB_8888);
if (mask == null) {
    maskFromBitmapPool = false;
    mask = Bitmap.createBitmap(source.getWidth(), source.getHeight(), Bitmap.Config.ARGB_8888);
}

if (maskFromBitmapPool) {
    mBitmapPool.put(mask);
}
```

Hi!
Can I use BitmapPool like this?

**Comment by start141** [comment]
The full code in:
https://github.com/start141/glide-transformations/blob/831f038d29190c2d29243522058bf6951b7e2202/transformations/src/main/java/jp/wasabeef/glide/transformations/MaskTransformation.java

**Comment by TWiStErRob** [comment]
Yes, you can, but since that's a temporary Bitmap you don't need the `maskFromBitmapPool` bool. Just offer (`put`) the Bitmap you don't need any more to the pool, if it accepts: anyone can use it later, if it doesn't: it'll take care of recycling.

Also see my other comments on: https://github.com/start141/glide-transformations/commit/46d5d4d72f0cde405ca6c368387bd3148ee1db63#diff-5842c8b348c7425e2c44a24a1b6909de

**Comment by start141** [comment]
If not have the `maskFromBitmapPool` bool, it will make Glide takes more memory?

**Comment by TWiStErRob** [comment]
No, for two reasons:
 * pool is size bounded
 * if you put a new Bitmap into the pool, because the pool didn't give you a matching Bitmap, that newly allocated one will be a matching one for the next `get`. So overall the pool may be bigger, but it should speed up scrolling significantly, because your transformation won't go into `if mask == null` and allocate.

**Comment by start141** [comment]
Good answer!

**Comment by start141** [comment]
https://github.com/wasabeef/glide-transformations/pull/20

@TWiStErRob something shoule to change?
