### ISSUE TITLE
How can I judge the image is already cached in disk?

### ISSUE THREAD

**Issue by ShenghuGong** [bumptech/glide#639]
Hi,now I want to migrate my app from universalimageloader to glide. But I have a question is that I can‘t judge a image is already cached in disk。

There is my case:
There are many different resources and different URL for one image. Different network environments load different resources。For example，When I was in the 3G network，load the low quality image resource and the URL is "http://www.xxxxx_3g.png"。When I was in the WIFI network，load the high quality image resource and the URL is "http://www.yyyyyy_wifi.png"，There are two different URLs。

BUT! When I was in the 3G network，check the  high quality image resource first。If the high quality image resource is already cached, load the  high quality image resource URL from disk cache. Otherwise  load "http://www.xxxxx_3g.png"。

```
if (isCache("http://www.yyyyyy_wifi.png") {
    Glide.with(...)
        .load("http://www.yyyyyy_wifi.png")
        .into(...);
} else {
    Glide.with(...)
        .load("http://www.xxxxx_3g.png")
        .into(...);
}

public boolean isCache(String url) {
    // what should I do ???
}
```

So,How can I judge the high quality image resource(URL is "http://www.yyyyyy_wifi.png") is already cached in disk synchronously?

 Thank you very much。

**Comment by TWiStErRob** [comment]
Sorry, there's no sync version to check it, I tried many workarounds, but blocking the main thread causes a deadlock, because Glide does some scheduling on the main thread. Also I/O is not advised on the main thread, which is required to check if the file is there.

But, you actually don't need sync checking (this idea is based on [our Google Groups discussion](https://groups.google.com/d/topic/glidelibrary/TcFOy0tcxXA/discussion)):
```java
String url3G = "http://placehold.it/640x480?text=3g";
String urlWifi = "http://placehold.it/1920x1080?text=wifi";

DrawableRequestBuilder<String> load3G;
DrawableRequestBuilder<String> loadWifi;

// disable unneded parts, to just hit the cache if available
if (NetworkUtils.isOnSlowNetwork()) {
	load3G = Glide.with(this).load(url3G);
	loadWifi = Glide.with(this).using(new NetworkDisablingFetcher()).load(urlWifi);
} else {
	load3G = Glide.with(this).using(new NetworkDisablingFetcher()).load(url3G);
	loadWifi = Glide.with(this).load(urlWifi);
}

// set up loads
load3G
	.diskCacheStrategy(DiskCacheStrategy.ALL) // SOURCE is enough too
	.centerCrop() // just to show that you can add different parameters to loads
;
loadWifi
	.diskCacheStrategy(DiskCacheStrategy.ALL) // SOURCE is enough too
	.transform(new CircleTransform(context)) // just to show that you can add different parameters to loads
;

// do the actual load
loadWifi.thumbnail(load3G).into(imageView);
```

You can play around and customize it for yourself, for example you may don't even want to try the cached 3G image when you're on WiFi, in which case `load3G` doesn't need to be initialized and `loadWifi.thumbnail(load3G).into(imageView);` can be simply `loadWifi.into(imageView);`. Depending on your use case the above code can shorten a lot if you inline some variables. I kept it spacey for hopefully easier understanding.

The key is that WiFi wins over 3G, which, if WiFi version is cached will be almost immediately loaded and the 3G load canceled (thumbnail is not needed if we have the full image) probably even before network is established. Depending on WiFi availability the networking part of Glide is disabled for that particular load resulting in not just kind of checking the cache, and if WiFi version is not found the thumbnail wins, because an image is better than a failure.

```java
class NetworkDisablingFetcher implements StreamModelLoader<String> {
	@Override public DataFetcher<InputStream> getResourceFetcher(final String model, int width, int height) {
		return new DataFetcher<InputStream>() {
			@Override public InputStream loadData(Priority priority) throws Exception {
				throw new IOException("Forced Glide network failure");
			}
			@Override public void cleanup() { }
			@Override public String getId() { return model; }
			@Override public void cancel() { }
		};
	}
}
```

**Comment by TWiStErRob** [comment]
Just to crosslink, this is also higly related, if not duplicate of #509.

**Comment by BrightYu** [comment]
mark
