### ISSUE TITLE
Integrate Proguard rules

### ISSUE THREAD

**Issue by DreaminginCodeZH** [bumptech/glide#646]
From http://stackoverflow.com/a/30801516:

```gradle
buildTypes {
    release {
        consumerProguardFiles 'proguard.txt'
    }
}
```

As in afollestad/material-dialogs#708.

This simple change can make integration much easier and less error-prone.

**Comment by ashughes** [comment]
You should specify the `consumerProguardFiles` in `defaultConfig` rather than `buildTypes/release` so that it works if the consuming application proguards in both debug and release mode (e.g. to avoid the 65k dex method limit).

```
defaultConfig {
    consumerProguardFiles 'proguard-rules.txt'
}
```

I agree this would be a great addition to this library!

**Comment by TWiStErRob** [comment]
Glide is not an AAR distributed lib, only the integration libraries are. See http://search.maven.org/#search%7Cga%7C1%7CGlide

I agree though it would be nice to include ProGuard rules in the dist instead of on the wiki, I haven't seen this consumer config before. I guess an AAR distribution could be made to include this, since it will help some people (using `@aar`), but it won't make AAR the required form of consuming Glide.

**Comment by vanniktech** [comment]
Any update / plans on this one?

**Comment by TWiStErRob** [comment]
Nope, there are other bigger issues.
Pull requests are always welcome though ;)
