### ISSUE TITLE
Images don't read from the cache

### ISSUE THREAD

**Issue by vkuba** [bumptech/glide#667]
Hi I have a problem with reading images from cache. 

At 1st I'm trying to download Images only to cache

 GlideUrl glideUrl = new GlideUrl(url + i, new LazyHeaders.Builder()
                                .addHeader("email", MyApplication.getEmail())
                                .addHeader("password", MyApplication.getPassword())
                                .build());
                        Glide
                                .with(context)
                                .load(glideUrl)
                                .downloadOnly(new SimpleTarget<File>() { ...});

Secondly, in other activity, I try o download the same images (the same URL)

 GlideUrl glideUrl = new GlideUrl(urlofPage, new LazyHeaders.Builder()
                        .addHeader("email", MyApplication.getEmail())
                        .addHeader("password", MyApplication.getPassword())
                        .build());

                Glide
                        .with(getContext())
                        .load(glideUrl)
                        .asBitmap()
                        .diskCacheStrategy(DiskCacheStrategy.ALL)
                                .into(new SimpleTarget<Bitmap>(displayWidth, displayHeight) {
                                    @Override
                                    public void onResourceReady(Bitmap resource, GlideAnimation glideAnimation) {
                                        ...
                                    }
                                });

But the whole time gets images from internet insted from cache.

What I am doing wrong?

**Comment by TWiStErRob** [comment]
I don't see anything really wrong neither, the types match, and it looks like the contents (url/email/password) too. `EngineKey` returns an `OriginalKey` instance which is [used to key the source cache](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/DecodeJob.java#L109). In any case, since `SOURCE` cache is used in both cases, double check your `url + i` and `urlofPage` are matching and also `getEmail()` and `getPassword()` too; just log them.

In general you should use `.downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)` to ensure correct `Target` lifecycle as the built-in `RequestFutureTarget` does a few things over `SimpleTarget`. Alternatively you can also try `.preload()`.

**Comment by eicm** [comment]
Maybe images getting removed from cache before next reuse.

**Comment by TWiStErRob** [comment]
@eicm that's possible, but only if the [default 250MB](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/cache/DiskCache.java#L18) has been tampered with or using extremely large/lot of images.

**Comment by vkuba** [comment]
Ok, as You said guys I had a extra "/" on the end of urls. Thanks You for help and sorry for trouble

**Comment by TWiStErRob** [comment]
No problem, glad you found it.
