### ISSUE TITLE
How to set SD Image URI to GLIDE thumbnail  ? Can we do it in GLIDE ?

### ISSUE THREAD

**Issue by SaravanarajaGITHUB** [bumptech/glide#668]
At first thanks for the GLIDE Library .!!.My requirement ->  In my list view i don't want my user to see empty view at all, so after downloading the low resolution ( which is saved in SD card ) of the HD image  then i'm creating the View item. so that user cant see an empty white item in List View. I'm trying to set SD card image URI path to glide thumbnail, but it didn't pop up the image before downloading the HD Image. Can we achieve this in GLIDE.?

**Comment by eicm** [comment]
You should post your load line.
This should work for your purpose:
Glide.with(context).load(hdImageUrl).thumbnail(Glide.with(context).load(pathToThumbnail)).into(imageView);

**Comment by SaravanarajaGITHUB** [comment]
Ok i'll.  Thanks @eicm it working.! my another question ? the params we giving inside Thumbnail is called generic request builder or drawable request builder.? what the difference ?

**Comment by TWiStErRob** [comment]
The generic one has 4 open Java Generics arguments: `GenericRequestBuilder<ModelType, DataType, ResourceType, TranscodeType>` and the drawable one has some locked in: `DrawableRequestBuilder<ModelType> extends GenericRequestBuilder<ModelType, ImageVideoWrapper, GifBitmapWrapper, GlideDrawable>`; similarly `.asBitmap()` will give you: `BitmapRequestBuilder<ModelType, TranscodeType> extends GenericRequestBuilder<ModelType, ImageVideoWrapper, Bitmap, TranscodeType>`.

`thumbnail()` needs to be polymorph otherwise you can't have different images loaded: for example display a custom loaded icon from another application's resources as a thumbnail for a simple HTTP URL load.

**Comment by SaravanarajaGITHUB** [comment]
Thanks @twisterrob

**Comment by TWiStErRob** [comment]
I think you double-clicked on *Close*...
