### ISSUE TITLE
Make BitmapPool native

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#671]
@sjudd just an idea from stumbling upon [How to cache bitmaps into native memory?](http://stackoverflow.com/q/17900732/253468): What if the Bitmaps loaded by Glide are stored in native memory? That way a lot of OOMs would disappear and allow the users of Glide use the memory for something else. Obviously this wouldn't be the default, but maybe an alternative implementation of `BitmapPool` which can be set by `GlideModule`?!

**Comment by sjudd** [comment]
I'm not totally on board with using native memory to get around java memory limits. The java memory limits are there in no small part to make sure apps are good citizens on the device. Working around that seems wrong to me. On a more practical level, natively storing Bitmaps is likely to make it harder to discover and track down memory leaks because the largest leaked objects will be held natively.

**Comment by TWiStErRob** [comment]
Makes sense, thanks. I'm not feeling strongly about this myself.

**Comment by christopherperry** [comment]
I believe there is a case to be made for this feature when it comes to placeholder images. There's no reason my app should have to re-upload a placeholder image to the GPU over and over if my intention is to reuse it (imagine a RecyclerView with tons of images). Does the GPU already have the image in memory in some sort of LRU cache? I can't seem to find how this works at a lower level. If you could point me to some documentation that would be awesome.
