### ISSUE TITLE
Images Don't Seem to be Caching Using .preload() & DiskCacheStrategy.ALL

### ISSUE THREAD

**Issue by sumbulAlvi** [bumptech/glide#674]
Hi, I've been trying to get preloading of images working in the `Tumblr` android application with Glide. It doesn't look like the images I cache using `.preload()` are being cached. I've looked through the Flickr sample project provided and it looks like there is no use of the `.preload()` interface there; just a fancy `ListPreloader` that is being used with the regular `.load().into()` callback. Could you please provide some insight into what I could be doing wrong here? It would be much appreciated.

In the recycler view's adapter:
```
public void loadImageAhead(PhotoPost dataObject) {
    Glide.with(context)
          .diskCacheStrategy(DiskCacheStrategy.ALL)
          .load(dataObject.getPhotoUrl())
          .preload();
}

public void bindView(final int position, final ImageView view, final PhotoPost dataObject) {
    Glidr.with(context)
           .load(dataObject.getPhotoUrl())
           .placeholder(R.color.placeholder)
           .into(view);
}
```
Where `loadImageAhead()` is called when the user starts dragging their finger slowly on the recyclerview.

I have verified that the URLs in `bindView()` and `loadImageAhead()` are the same. I've also verified that the images have completed downloading by sticking a `RequestListener` in the preload call in `loadImageAhead()`. The reason I think the images are not being cached is because I drag my finger to let some images loadAhead, but not bind yet. Then I turn off internet connection and scroll down to the images that should've been saved to cache. But the images don't load into place, I just see the placeholder image in the posts.

**Comment by TWiStErRob** [comment]
I think you might be hitting this line: [`DecodeJob` 105](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/DecodeJob.java#L105) or having a dimension mismatch and therefore a cache miss.

When it comes to `diskCacheStrategy` the default is `RESULT`. When you change it, you change both reads and writes. You can't expect your `bindView` load to read data from the `SOURCE` cache if you don't allow writing there. Also if you're expecting to hit the `RESULT` cache in `bindView` you're out of luck, because `loadImageAhead` caches the image full size (`SIZE_ORIGINAL`). So you have two options:
 * add `.diskCacheStrategy(ALL)` to `bindView` and change `loadImageAhead` to `SOURCE`  
*this will save the url stream into the `SOURCE` cache and allow reading from there later and also save the resized and displayed image to `RESULT` for scrolling back and forth.*
 * know the size of `bindView.view` and call `.preload(w,h)`  
(optionally remove `diskCacheStrategy` from `loadImageAhead` to default to `RESULT`)  
*this will save only one image to the cache: the resized displayed one. The only problem you'll face is determining the actual size of an `ImageView` in the list item.*

**Comment by sumbulAlvi** [comment]
Your solution of adding `SOURCE` to `loadImageAhead` and `ALL` to `bindView` worked perfectly (as well as using `SOURCE` in both). 

Just to clarify the original error, it wasn't working because using `.preload()` only saved the image to `SOURCE` cache (full sized image) and not to `RESULT` cache. In `bindView`, it was trying to be accessed from the `RESULT` cache which didn't have the resource.

Using `.preload(w,h)` can save it to two caches, `RESULT` (the resized image) and `SOURCE` using 'DiskStrategy.ALL`. So later on in `bindView`, I can use `DiskStrategy.RESULT` to access it with the same w&h. 

Makes sense! Thanks for the help!

**Comment by sumbulAlvi** [comment]
As a follow up, if you specify using a `DiskCacheStrategy.ALL` in your load, will it first search the `RESULT`, and then the `SOURCE` cache after?

**Comment by TWiStErRob** [comment]
> Just to clarify the original error ...

Yep, in `bindView` it didn't have the correct sized (see next paragraph) `RESULT` cached image, and `SOURCE` cache access was not allowed.

I think using `.diskCacheStrategy(ALL).....preload()` is pointless, because as far as I can tell it will save the original into `SOURCE`, then decode the image and resize it to `SIZE_ORIGINAL` and then save it to `RESULT` cache, so you have an original and a re-encoded version of the same image. I may be wrong about this, I'm not sure if Sam made any preventive steps about this. This may also apply to `.override()`s. @sjudd is there any point caching `RESULT` in this case?

> If you specify using a `DiskCacheStrategy.ALL`

Hehe, I was just typing this sentence: [First `RESULT` is tried and then `SOURCE` is queried](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/EngineRunnable.java#L105), there's no point decoding and resampling from SOURCE if there's already a probably smaller resized image saved in RESULT which can be just decoded.

> Using `.preload(w,h)`...

Correct.

Actually, @sjudd, is there any reason not to have `preload()` be like `downloadOnly()`:
```java
public Target<TranscodeType> preload() {
        return diskCacheStrategy(SOURCE).preload(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);
}
```
or at least document that the no-arg version should be used with `SOURCE` 99% of cases.

**Comment by sumbulAlvi** [comment]
> I think using .diskCacheStrategy(ALL).....preload() is pointless

Ah yes, that makes sense. Both caches have the same sized image. 

> at least document that the no-arg version should be used with SOURCE 99% of cases.

I agree with this. Unless it's faster to access the `RESULT` cache or something, which I think is not the case.

Thanks a ton for the clarifications!
