### ISSUE TITLE
Image space occupied but not Image is shown.

### ISSUE THREAD

**Issue by Tirthtrivedi** [bumptech/glide#677]
com.github.bumptech.glide:glide:3.6.1
Android version 4.2.2

In my samsung 4.4.2 with lowe memory configuration i am also facing the same issue as #130 my image view height width is match parent and i am using ` menuImage.setBackgroundDrawable(resource);` for setting glide resources....it loads the image but not showing in imageview.

why it happens in specific old devices.?

Any other workaround?

```java
Glide.with(MenuImageFragment.this).load(imageUrl).listener(LocalDataProvider.getListener()).
placeholder(R.drawable.ic_transparent_logo).
error(R.mipmap.ic_launcher).signature(new StringSignature(imageUrl)).dontAnimate().
diskCacheStrategy(DiskCacheStrategy.ALL)
into(new SimpleTarget() {
@Override
public void onResourceReady(GlideDrawable resource,
                            GlideAnimation<? super GlideDrawable> glideAnimation) {
                  //  menuImage.setImageDrawable(resource);
                  menuImage.setScaleType(ImageView.ScaleType.FIT_XY);
                  menuImage.setBackgroundDrawable(resource);

                  dragParent.setViewToCapture(menuImage);
                }
...
});
```

```xml
<ImageView
android:id="@+id/menuImage"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:adjustViewBounds="true"
app:layout_direction="vertical"
app:layout_draggable="true"
tools:background="?colorPrimaryDark"
tools:src="@mipmap/ic_launcher" />
```

ABOVE CODE IS WORKING FINE IN VERSION >5.0 AND HIGHER MEMORY RAM DEVICES.

Using view pager in my app to load dynamic image via glide.

**Comment by TWiStErRob** [comment]
Try to add a listener that logs when `onResourceReady` is called, but I guess you would have seen if there was an actual loading problem because you have an `.error`.

Few potential issues:
 * You're using `SimpleTarget` which means that Glide doesn't know how big an image it should load.
  * Try using `ViewTarget` instead  
    Glide uses the `getWidth()` and `getHeight()` of the `ImageView` which is only available after layout
  * Try `.override(w,h)` or `new SimpleTarget(w,h)`  
    You'll definitely need to override the size if you have a dragging parent, most likely you have an OOM because it's loading too big images.(check LogCat carefully for OOM)
 * You're likely using a custom ImageView or layout (based on `app:` arguments) which may cause problems
  * Try to load it into a stock `ImageView` first
  * or without dragging layout around the view
 * `scaleType` doesn't affect backgroundDrawable
 * `scaleType` should be set before you start a Glide load because Glide uses that to figure out which transformation to use
 * `.signature(new StringSignature(imageUrl))` is not necessary the model (passed to `load()` is part of the cache key

Please correct me if I implied anything wrong from your code posted above.

**Comment by Tirthtrivedi** [comment]
hey thanks for your quick reply.....but I dont get any kind of error in logcat also image is loaded but not showing in image view...And also in lowe memory device and in android version 4.2.2 it happens.

my imageview have dragg layout wrapping around.
//////////////////////////////

<com.utils.DragLayout
    android:id="@+id/dragParent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/menuImage"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true"
        app:layout_direction="vertical"
        app:layout_draggable="true"
        tools:background="?colorPrimaryDark"
        tools:src="@mipmap/ic_launcher" />

</com.utils.DragLayout>

**Comment by Tirthtrivedi** [comment]
i am getting images same as the offset i have set for viewpager...after that image not shown.

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by TWiStErRob** [comment]
In addition to my above "Try ..." suggestions also look at #679 for tips about `ViewPager`.

**Comment by TWiStErRob** [comment]
@Tirthtrivedi Did you have a chance to check what's happening with a `.listener` or `setprop` or try my suggestions?

**Comment by Tirthtrivedi** [comment]
thanks for your suggestions.!Glide.clear working for me.
