### ISSUE TITLE
Caching not fully loaded image

### ISSUE THREAD

**Issue by vavan4567** [bumptech/glide#691]
I have 2 activities. 1st - list where I am loading image and 2nd - fullscreen image (same images).
Where image is not fully loaded in 1st activity and I am opening 2nd activity the image starts loading from start. Progress from first activity is not saved. B t w using DiskCacheStrategy.ALL

**Comment by TWiStErRob** [comment]
Glide's `Engine` has the concept of adding a new load to an existing one. For that to happen the two loads must match iv every regard, i.e. the load has to happen with the same size even. This will happen only if you're using ApplicationContext for the 1st Activity's `Glide.with`, because otherwise Glide will be notified of `Activity.onStop/onDestroy` and cancel the request which is bad for you in this case. Also note that caching partial results is not possible, Glide's disk cache either has the full file or nothing.

Based on the above I'm inclined to say it's not possible to what you want. Even if you manage to match the size of the targets, which means either the fullscreen will be blurry or the list will consume too much memory, the other constraints and tricks are too fragile. I'm curious what @sjudd says about this.

**Comment by vavan4567** [comment]
Thank you for answer,
You have the coolest lib

**Comment by TWiStErRob** [comment]
I'm curious what @sjudd says about this.

**Comment by sjudd** [comment]
I'm a little unclear on the question here. If you want to continue to show the image from the list while loading the full size image, you can use the [``thumbnail()``][1] API in the fullscreen view. Pass a request identical to that used in the list to ``thumbnail()`` and then load the larger image in the main request.

If you want to re-use the data you downloaded for your list in your fullscreen activity, then DiskCacheStrategy.ALL should work, as long as the URL/Uri you use to request the image in both places is the same. The request in the fullscreen activity won't complete instantly because it takes time to decode the image (particularly large ones), but it shouldn't require downloading the data again.

[1]: http://bumptech.github.io/glide/javadocs/360/com/bumptech/glide/DrawableRequestBuilder.html#thumbnail(com.bumptech.glide.DrawableRequestBuilder)

**Comment by TWiStErRob** [comment]
@sjudd the trick here is that the small image in the list has the same URL as the full image. Using ALL/SOURCE will help re-using the downloaded network file. The question is: is there a way to re-use a partial HTTP stream?
Imagine that the network is slow and images are huge. User opens a list, first two images are loading one by one in 15 seconds each, third image already went through DataFetcher and the stream is being read. User reads the title of the third item and taps. At this time the pending request is paused/cancelled and SOURCE cache is not filled, all the downloaded data is lost and the full screen activity has to restart that stream again, or will it match up somehow?

**Comment by sjudd** [comment]
Ah yes, that's not supported. If you knew it was going to happen ahead of time you could use preload(), which would create a request that would survive during the activity transition. But if you do cancel the request, we will throw out any data we've received so far.
