### ISSUE TITLE
Question - possibility to define a few target image sizes for cache different from view size

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#704]
I allow the user to setup grid sizes and images sizes (all are square), I have different sizes in portrait and landscape, I have different grid layouts between views and therefore I would need following feature, as I use (even if the user does not change any settings) one image in 3 to 4 different but very near sizes...

I think following would solve the problem, rounding target widths and heights to some snapped values, for example:
widht x height <= 100x100 => cache image for an 100x100 target
widht x height <= 200x200 => cache image for an 200x200 target
widht x height <= 300x300 => cache image for an 300x300 target

I want that if I view an image in an 48x48 `Imageview` and turn the screen and suddenly the image is displayed in an 64x64 `ImageView` that glide uses the next higher image size, loads the cached image in this size and uses this image (in my example both views would be filled with the 100x100 image)...

I know I can define a DiscCacheStrategy, but this does not allow above...

Any idea how I can achieve that? Is that currently achievable? Any better suggestions?

**Comment by TWiStErRob** [comment]
You can implement whatever bucketing logic you want and use `.override()`. The problematic part is if you don't know the exact ImageView size, because it's not laid out yet, but based on your description you set fixed sized layout params so you know the sizing even before layout.

`.diskCacheStrategy(ALL)` will prevent downloading the same image multiple times (even if the user changes the sizing) and will also make sure that a small change like 48->64 will still hit the same RESULT-cached image (100). Beware that `.override()` receives pixels and not dp, so be sure to scale according to device DPI.

**Comment by MFlisar** [comment]
This will be quite a work, but I should achieve that (I use a few grids/lists and one screensize view of the images)

* I will calculate the thumbnail size that best fits the current user setup and use a custom request for the thumbnail with a fix target for all list/grid request
* I will use the screensize for the big image, so that on rotation the same cached image is used

I think that will work quite good. Thanks.

PS: Offering a `thumbnail(int x, int y);` would be a nice addition to current multiplier option...

**Comment by TWiStErRob** [comment]
`.thumbnail(w,h)` would be just convenience, you can easily achieve that via `.thumbnail(Glide.....override(w,h))`.

Note: currently `wrap_content` falls back to the appropriate screen dimension.
