### ISSUE TITLE
centercrop is not always working for RecyclerView with none uniform imageview

### ISSUE THREAD

**Issue by zhihuawensc** [bumptech/glide#705]
We have a recyclerview with imageViews similar to the gallery sample and we load image in onBindViewHolder callback. The difference is that we have both landscape and portrait imageviews.
When the imageView was originally portrait but used as landscape or vice versus, we found the centerCrop is done correctly.

We also found the following hack solved the problem for unknown reason, i.e., instead of loading it directly into the view, we override the onResourceReady callback to set it ourselves.

We also noticed that sometimes the size of the imageView changed between before loading the images and inside the callback.

```
    mRequestManager.load(uri).into(new ViewTarget<ImageView, GlideDrawable>(ImageView.this) {
        @Override
        public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
            ImageView.this.setImageDrawable(resource);
            // The size and the orientation of the image view sometimes changed.
        }
    });
```

This issue seems similar to https://github.com/bumptech/glide/issues/613, but we already set the layout width and height to be "match_parent" and scaleType to be centerCrop.

Do you know if this an known issue, is our work around OK? For some reason we don't see this problem while using Picasso.

```
<com.snapchat.android.ui.ImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerCrop"
    />
```

**Comment by TWiStErRob** [comment]
What kind of customizations are there in your custom ImageView? What do you mean by an ImageView's orientation and that it changed? (width/height got swapped?!)

Also notice that your custom target is a `ViewTarget` and the default is one of the subclasses of `ImageViewTarget`, which means that just by creating that custom target you're skipping a lot of code; so don't just attribute your hack's success to overriding `onResourceReady`.

**Comment by sjudd** [comment]
Does it work if you remove the hack and add dontAnimate()?

**Comment by zhihuawensc** [comment]
@sjudd 
It doesn't work with dontAnimate(), I am trying to use ImageViewTarget by overriding setResource now.

**Comment by zhihuawensc** [comment]
Using ImageViewTarget also seems working.

        mRequestManager.load(uri).into(new ImageViewTarget<GlideDrawable>(ImageView.this) {
            @Override
            protected void setResource(GlideDrawable resource) {
                setDrawable(resource);
            }
         }

**Comment by TWiStErRob** [comment]
Then this issue is about `SquaringDrawable`, that's the only difference between your implementation now and `GlideDrawableImageViewTarget` and you dropped GIF support with the custom target.

**Comment by TWiStErRob** [comment]
@zhihuawensc Can you please confirm that by removing the custom target and checking in debug if `GlideDrawableImageViewTarget#63` is hit and `SquaringDrawable` is created at any time? If that's the issue you should also be able to work around it by `.asBitmap()` which, again, drops GIF support.

@sjudd what do you think?

**Comment by zhihuawensc** [comment]
@TWiStErRob 

Actually .asBitmap didn't fix the problem. We tracked GlideDrawableImageViewTarget#onResourceReady and found SquaringDrawable was never created since our imageViews were either portrait or landscape.

The problem happened when the viewRatio and drawableRatio is of different orientation, i.e., drawableRatio = 0.618 while viewRatio = 1.618 or vice versus.

**Comment by TWiStErRob** [comment]
> When the imageView was originally portrait but used as landscape or vice versus, we found the centerCrop is done correctly.
> The problem happened when the viewRatio and drawableRatio is of different orientation

These two are opposites, did you miss a "not" from the first one?

What happens if you do `.dontTransform()`, that is disable the automatic `.centerCrop()` and let the ImageView do it later?

Is there any customizations in your custom ImageView that may relate to layout or the drawable set?What determines if an ImageView will be portrait or landscape? What's around the ImageView in layout, that is: what gives it constrained size? Would it be possible for you to create a small runnable repro app?

**Comment by zhihuawensc** [comment]
Sorry, I mean when the imageView was originally portrait but used as landscape or vice versus, we found the centerCrop is done incorrectly.

We found dontTransform is working, and even if we use GlideDrawableImageViewTarget directly, it's still working, i.e.,
mRequestManager.load(uri).into(new GlideDrawableImageViewTarget(this));

For your second question, we have a custom GridLayoutManager that sets the width of the view, then in our RecyclerView adapter we calculate the height for each item in the onBindViewHolder method.

Performance wise, is there any difference between
mRequestManager.load(uri).into(new GlideDrawableImageViewTarget(this));
and
mRequestManager.load(uri).dontTransform().into(this);
?

**Comment by TWiStErRob** [comment]
The difference between the two lines is calling `into(Target)` and `into(ImageView)`. The latter has a little bit of code to automagically discover the scale type and apply a transformation. If you create a Target manually you skip this method entirely, and if you call `.dontTransform()` you skip the `switch` inside the method. So I would say there's ignorable difference here. I suggest `.dontTransform()` because it better shows your intent.

The bigger difference is between the buggy and the non-buggy version. The buggy version at least tries to resize the loaded image to fit the ImageView perfectly reducing memory footprint. The non-buggy version (either way) doesn't transform the loaded image, so it may be a big one, hopefully the Downsampler reduces the size enough so it's not a problem. Try to add a `.listener()` in both cases and check the resulting Bitmap sizes. (`.asBitmap()` makes it easier to access the Bitmap to read the sizes).

If you know the image sizes (i.e. landscape and portrait has kind-of fixed sizes) you could also try `.override()` which will allow you to properly load and transform the image. **I think the issue here is that when you change your image from one to the other you only set the layoutParams, but Glide reads the getWidth/getHeight from the ImageView, and therefore it reads the the value from the previous layout.** I just ran into the same thing. If the size of portrait and landscape is fixed I would suggest using two separate viewTypes to prevent changing from one to the other. It'll also speed up laying out the item views (i.e. scrolling) because there won't be a layout pass after every bind.

**Comment by sjudd** [comment]
Yes this is an issue. There are a couple of methods we can try to use in ViewTarget to detect if this is occurring and delay the load accordingly:

http://developer.android.com/reference/android/view/View.html#isLayoutRequested() http://developer.android.com/reference/android/view/View.html#isLaidOut() 

This was discussed internally in b/25810638

**Comment by sjudd** [comment]
I believe this is fixed in Glide v4.
