### ISSUE TITLE
Loading DSLR raw images

### ISSUE THREAD

**Issue by eicm** [bumptech/glide#718]
I'm curious about loading raw formats images, what is the best approach?

**Comment by TWiStErRob** [comment]
#### Base case
```java
Glide
	.with(context)
	.load(localFilePath)
	.asBitmap()
	.imageDecoder(new RawStreamDecoder(context))
	.diskCacheStrategy(RESULT) // default
	.into(imageView)
;
```

`RawStreamDecoder` should read `source` stream into a Bitmap object (here you can do whatever you want with the stream, so any format can be decoded. Make sure it's not using too much memory, the best is obviously if the loaded image matches the given width/height so any downstream transformation will just pass it on. Note that this includes downsampling, that is the equivalent of `inSampleSize` handling. See the built-in `StreamBitmapDecoder` for more details and inspiration.

#### Advanced caching
If you want to SOURCE-cache images you'll need a cache-decoder, which is really easy because you already have an InputStream->Bitmap RAW decoder:
```diff
Glide
	.with(context)
	.load(model)
	.asBitmap()
	.imageDecoder(new RawStreamDecoder(context))
-	.diskCacheStrategy(RESULT) // default
+	.diskCacheStrategy(SOURCE)
+	.cacheDecoder(new FileToStreamDecoder<>(new RawStreamDecoder(context)))
	.into(imageView)
;
```

Sadly #707 prevents you from simply using ALL, but there's a way for that to work too in your case:
```diff
Glide
	.with(context)
	.load(model)
	.asBitmap()
	.imageDecoder(new RawStreamDecoder(context))
-	.diskCacheStrategy(SOURCE)
+	.diskCacheStrategy(ALL)
	.cacheDecoder(new FileToStreamDecoder<>(new RawStreamDecoder(context)))
+	.encoder(new RawStreamEncoder())
	.into(imageView)
;
```

SOURCE cache is always the RAW stream saved to disk unless you define a `sourceEncoder` (unnecessary in this case). In #707 it's clear that if you change `cacheDecoder` to decode from SOURCE cache, you need to change RESULT cache format as well with an `encoder` so both SOURCE and RESULT will have the same format and can be decoded with the same decoder.
(see #707 for more on workarounds).

#### Remarks
Notice that none of the above cares where the data is coming from, that's handled by Glide: `model` -> `InputStream`; then it let's you decoder the image, manage the cache formats; and the rest (transformation, delivering to target) is again handled by Glide.

**Comment by eicm** [comment]
@TWiStErRob thanks

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/issues/832#issuecomment-166697493 for a v4 compatible implementation.
