### ISSUE TITLE
RequestManagerRetriever: You cannot start a load on a fragment before it is attached, but it is.

### ISSUE THREAD

**Issue by ZkHaider** [bumptech/glide#723]
The app crashes when I try to load an image with `Glide`. 

Just as some background, I am setting up `Glide` after `onAttach` in my `Fragment` inside the `onCreateView` call. I have a Presenter class that I pass the context to, and it goes and talks to an API to grab an image via `Retrofit`.

So my code looks like this:

**Base Fragment**:

```java
public abstract class BaseFragment extends Fragment {
    
    Context context;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        context = getActivity();
    }

}
```

**TestFragment**:

```java
public class TestFragment extends Fragment {

    IPresenter mPresenter;

    @Bind(R.id.testImage) ImageView mTestImage;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        // Do setup stuff here...
        // Setup presenter here and pass in the context
        mPresenter = new Presenter(context);

    }

    // This is called from the presenter to set an image

    public void setTestImage(String url) {
         Glide.with(context)
                  .load(url)
                  .listener(new RequestListener<String, GlideDrawable>() {
                            @Override
                            public void onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                                 return false;
                            }

                            @Override
                            public void onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemory, boolean isFirstResource) {
                                 // Do stuff
                                 return false;
                             }
                    .into(mTestImage);

      }
}
```

The issue is that the following error gets thrown:

>Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load on a fragment before it is attached
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java)
       at com.bumptech.glide.Glide.with(Glide.java)

Specifically this gets called:

```java
@TargetApi(Build.VERSION_CODES.HONEYCOMB)
public static RequestManager with(android.app.Fragment fragment) {
    RequestManagerRetriever retriever = RequestManagerRetriever.get();
    return retriever.get(fragment);
}
```

And then in the `RequestManagerRetriever` class this gets thrown:

```java
@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
public RequestManager get(android.app.Fragment fragment) {
    if (fragment.getActivity() == null) {
        throw new IllegalArgumentException("You cannot start a load on a fragment before it is attached");
    }
    if (Util.isOnBackgroundThread() || Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR1) {
        return get(fragment.getActivity().getApplicationContext());
    } else {
        android.app.FragmentManager fm = fragment.getChildFragmentManager();
        return fragmentGet(fragment.getActivity(), fm);
    }
}
```

I don't understand why the `Activity` from `fragment.getActivity()` is null? What seems to be the issue here? I am passing in the context in `onCreateView()` after the context is initialized.

**Comment by TWiStErRob** [comment]
Thanks for the details, here's my take:
* Assuming you meant `TestFragment extends BaseFragment` ()
* Assuming "Do setup stuff here..." includes `super.onCreate`
* Assuming `context` is visible in `TestFragment` (the same package with `BaseFragment`)
* Assuming `context` is not shadowed by any other `context`-named field/variable, especially one whose type is `Fragment`

What you say happening is plain impossible... if `with(context)` is `BaseFragment.context` which is typed `Context` it is not possible for Java to call `with(Fragment)`.

* Double-check the stacktrace below `Glide.with`.
* Double-check if there are any other Fragments attached to the same activity, especially ones that call `Glide.with(this)`. (easiest is to execute "find usages" on the `Glide.with(Fragment)` method)
* Try to hardcode a `setTestImage(...)` call in `onCreate` instead of creating the presenter, just to see if the same exception is thrown.
* Could whatever framework contains `@Bind` interfere with Glide and/or your `context` field?  Decompile the generated class file to see what's going on  
(easiest is to drag-drop the class file onto any IDEA/AS window)
* Do you have anything else called on the `load` in `setTestImage` because `.listener()` is not terminated properly? (most likely not the cause, just asking)

**Comment by ZkHaider** [comment]
Thanks for the thorough response, all those assumptions are correct in the first bullet point. There is another `Fragment` that is also hosted by the `FragmentManager` that uses `Glide` but it is only called when the user taps a button so on application startup there is only 1 `Fragment` present.

I'll investigate `Glide.with(Fragment)` like you mentioned and report back!

**Comment by ZkHaider** [comment]
Also to answer your question no nothing else is called on `Glide.with(context).load(url).listener(...).into(...);`

**Comment by TWiStErRob** [comment]
How silly... I forgot the easiest investigation option: put a breakpoint on the throw statement in Glide and walk the stack to see variables. :)

**Comment by TWiStErRob** [comment]
@ZkHaider any news?

**Comment by ZkHaider** [comment]
@TWiStErRob coming back to this today! I noticed another thing, this happens when I start a `Fragment` then suddenly hit the home button and click on the app again. In the app there is a network request called to load an image with `Glide` and then it throws the:

>Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load on a fragment before it is attached
at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java)
at com.bumptech.glide.Glide.with(Glide.java)

**Comment by TWiStErRob** [comment]
Can you do the stack-walk-debug I mentioned above and a fuller stack trace?

**Comment by ZkHaider** [comment]
I ended up figuring this out. User enters app, then app immediately goes to background. A call is sent to `Glide` from a background thread and that's where it crashes before the `Fragment` is attached.
