### ISSUE TITLE
Skip all caches unless the remote resource request fails

### ISSUE THREAD

**Issue by mdivkovic** [bumptech/glide#724]
Hey guys, first off, I love your work here, the library is really fast, flexible and robust.

One use case that I encountered recently would require me to always try for an up-to-date version of a profile picture, and only go for the cache if the request fails.

I actually don't even know how to approach this. I know about skipMemoryCache, but it looks like there is no equivalent for the disk cache. I can't just use DiskCacheStrategy.NONE because that's not what I need - I DO want the image to be cached if it's retrieved, I just want to try for the fresh remote resource first. The cached version will then be used if there is a network failure, or server timeout, or just general lack of connectivity.

Looking forward to your reply and thanks in advance!

**Comment by TWiStErRob** [comment]
`diskCacheStrategy` controls both read and write from/to SOURCE/RESULT cache. There's no way to tell Glide to read, but don't write; or write, but don't read the cache. Also Glide assumes that a model always points to the same resource at any point in time.

I think you can kind of make what you want happen with a solution similar to #639:
```java
String profileUrl = "...";
long lastProfileCache = context.getSharedPreferences("profile", 0)
                               .getLong("lastCacheTime", System.currentTimeMillis());
Glide // display a fresh version
	.with(context)
	.load(profileUrl)
	.thumbnail(Glide // display a cached version
		.with(context)
		.using(new NetworkDisablingFetcher()) // only if exists in disk cache
		.load(profileUrl)
		.signature(new StringSignature(String.valueOf(lastProfileCache)))
		.diskCacheStrategy(SOURCE)
		.centerCrop() // must be explicit even if ImageView.scaleType is set
	)
	.diskCacheStrategy(NONE) // downloaded right now
	.centerCrop() // may be implicity from ImageView.scaleType
	.into(imageView)
;

// update the profile cache (for example on app startup)
private void updateProfileCache(Context context, String profileUrl) {
	long lastProfileCache = System.currentTimeMillis();
	Glide
		.with(context)
		.load(profileUrl)
		.signature(new StringSignature(String.valueOf(lastProfileCache)))
		.diskCacheStrategy(SOURCE)
		.listener(new SaveLastProfileCacheTime(context, lastProfileCache))
		.preload()
	;
}

private static class SaveLastProfileCacheTime implements RequestListener<String, GlideDrawable> {
	private final Context context;
	private final long lastProfileCache;
	public SaveLastProfileCacheTime(Context context, long lastProfileCache) {
		this.context = context;
		this.lastProfileCache = lastProfileCache;
	}
	@Override public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
		return false;
	}
	@Override public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
		context.getSharedPreferences("profile", 0).edit().putLong("lastCacheTime", lastProfileCache).apply();
		return false;
	}
}
```
however this may be too complex, fragile and hacky; or simply doesn't even work, I didn't try it...
If it works it works because thumbnail is kept in the view even when the outer load has failed.

I would suggest you re-think the logic, the best solution is that you know when the image behind profileUrl has changed. If you know that, you can simply request the latest version:
```java
.load(user.profileUrl)
.signature(new StringSignature(user.profileUrlLastUpdate))
```
With this solution you can also store the last known `profileUrlLastUpdate` and do the `thumbnail`/`NetworkDisablingFetcher` trick to try to load a cached (but old) version.

If you don't have control over the server (to store/update/return `profileUrlLastUpdate`), then you can try storing it yourself in a pref or simply falling back to regular update intervals:
```java
.signature(new StringSignature(System.currentTimeMillis() / (24 * 60 * 60 * 1000))) // re-requests profile image every day
```

**Comment by mdivkovic** [comment]
Thanks for the super quick reply! 

The first solution, that you provided code samples for, looks like it might work but it really does seem like overkill for what I'm trying to accomplish and a little hacky .

Unfortunately, the thing is that the profile picture can come from some external provider (e.g. Facebook, Google, Gravatar etc.), and we don't store it on our server side, but just transparently fetch it from the URL returned by our API, wherever it may lead. For those we simply don't know when they are updated, and the URL doesn't reliably change to reflect the update. This is why we can't rely on knowledge about the update time.

Your last suggestion, just updating it periodically, is probably what I'll have to do. It's straightforward, concise, and, with a reasonably short update interval (a couple of hours), I think it should be **good enough™** :)

Again, thank you very much for the help!
