### ISSUE TITLE
Is it possible to use Glide with a programmatically created View (ImageView)?

### ISSUE THREAD

**Issue by dolphinziyo** [bumptech/glide#734]
I'm trying to draw one image in a programmatically created ImageView using Glide, I tried with locally stored images and internet images but none works, the image doesn't show. 
Is this possible?

**Comment by TWiStErRob** [comment]
Of course it is possible, the XML does the same automagically. Here are a few things to check:
 * Is it added to the view hierarchy  
preferable before `.into()` call
 * Is it visible?  
Hidden views won't be laid out, and because of that, Glide won't receive a size to load, use `override` to load into hidden ImageView.
 * Is it a custom `? extends ImageView`?  
We have had some problems with those (if they're not carefully implemented), try it with a stock class.
 * Does it have `match_parent` or fixed sizing?  
(wrap_content should work too, but it's better with the former two)

If none of these help, please try https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener

**Comment by dolphinziyo** [comment]
I had no time to try it, when I can I will make you know.
Thank you very much. Glide is awesome!

**Comment by dolphinziyo** [comment]
Thank you very much TWiStErRob the problem was trying to add the image to a hidden ImageView, it's now solved with the "override" call.
