### ISSUE TITLE
Wouldn't it be safer to assume an image has alpha when we don't know?

### ISSUE THREAD

**Issue by airk000** [bumptech/glide#736]
**Glide Version/Integration library (3.6.1)**

as I said in the title, I saw code in **DownSampler.java**

method **getConfig()**

```
...

boolean hasAlpha = false;
try {
            hasAlpha = new ImageHeaderParser(is).hasAlpha();
        } catch (IOException e) {
            if (Log.isLoggable(TAG, Log.WARN)) {
                Log.w(TAG, "Cannot determine whether the image has alpha or not from header for format " + format, e);
            }
        } finally {
            try {
                is.reset();
            } catch (IOException e) {
                if (Log.isLoggable(TAG, Log.WARN)) {
                    Log.w(TAG, "Cannot reset the input stream", e);
                }
            }
        }
...
```

while **IOException** occurred, it means we can't determine if a image has alpha.

For more effective, I prefer to use RGB_565 to decode image, but if the image has alpha indeed, it will display in the wrong way as we know. Now I wonder will we met the **IOException** often, if the answer is **NOT**, can we just pretend the image HAS alpha for safe? So I can rest assured use PREFER_RGB_565 later.

**Comment by TWiStErRob** [comment]
I think the default `false` is there because there are more images (and image formats) that don't have alpha. So loading an image with alpha is rare in general. If we were to encounter an error while trying to figure out the format from header while assuming a default of `true` we would simply waste memory space.

Do you have a specific case when `ImageHeaderParser` fails with an exception? If so, we're better off fixing that bug, than hiding it. That `IOException` case should be really exceptional (i.e. extremely rare).

**Comment by airk000** [comment]
Thank you, I got it, I'm so crude XD. I'll pay more attention on the exception.
