### ISSUE TITLE
Error:CreateProcess error=2, System cannot find the specified file.

### ISSUE THREAD

**Issue by lixuecheng** [bumptech/glide#756]
when I run the glide demo by Android Studio,  I received this error message:

> Error:CreateProcess error=2, System cannot find the specified file.

I want to know how to solve

**Comment by TWiStErRob** [comment]
Try to build it from command line first with `gradlew :samples:gallery:assembleDebug` if that works flawlessly then go on and import it to AS. Also make sure you're using the latest AS version for the master (4.0) branch.

Building the 3.0 branch is harder because it needs an older version of AS or IDEA, but gradlew should work for that too.

Make sure you followed all steps here:
https://github.com/bumptech/glide/blob/master/README.md#build

**Comment by Wood-Water-Peng** [comment]
I have followed the step according to 
https://github.com/bumptech/glide/blob/master/README.md#build
but，when i import the glide to AS，the error "Error:CreateProcess error=2" still occurred.
My AS version is 1.5,but will that affect to result?
