### ISSUE TITLE
The RecyclerView's item sometimes display the placeholder image res first time , but when i refresh again , it can display the right image from url . 

### ISSUE THREAD

**Issue by qinjuning** [bumptech/glide#757]
I  use the RecyclerView and Glide(thanks u very much :) ) in my app , but i find a problem that RecyclerView's item sometimes display the placeholder image res first time , but when i refresh again , it can display the right image from url . The code like this : 
  `
 Glide.with(BaseApplication.getInstance()).load(imageUrl)
				.centerCrop()
                                .placeholder(R.drawable.XXX)
				.crossFade()
				.into(imageView);
 `

 when i remove the  placeholder method, it can display the image well .

 Bye the way,  i use the https://github.com/StanKocken/EfficientAdapter to use the ViewHolder of  RecyclerView

   i cannot find any way to resolve this problem, can you help me ?

**Comment by TWiStErRob** [comment]
I don't see what the problem is, please try to rephrase it. (Did you miss a "not" somewhere?)

What you describe seems like the default behaviour: at first the image loading takes time (downloading and/or decoding from disk cache), next time it may be in memory cache which means there'll be now I/O in this case it's pointless to delay showing what we already have by displaying a placeholder again.

**Comment by qinjuning** [comment]
Thanks for you answer . I am sorry because of  my English is poor.

  I mean the ImageView always display the placeholder until i manually scroll or refresh the  RecyclerView again. I seems it cannot load the real image when its done . It spent enough time to observer this phenomenon.

Maybe the follows  image can tell me what i said: 

1. The i mageView always show the placeholder at first time      
  
 <img src="http://i1287.photobucket.com/albums/a627/qinjuning1/999_zps9pflautq.png" />

2 .After 10 minutes, i refresh the RecyclerView again, it can display the real image well

 <img src="http://i1287.photobucket.com/albums/a627/qinjuning1/000.png_zps1cklnc4p.jpeg" />

**Comment by TWiStErRob** [comment]
Showing the `placeholder` usually means there was an error during loading. Take a look at [`RequestListener`](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) and check what Exception is thrown. I would imagine a timeout maybe.

**Comment by qinjuning** [comment]
I don't think the cause is that  there was an error during loading.   Like I said before, "It seems it cannot load the real image when its done at first time". 

Then I use the Picasso to do the same thing , it works well . 

 `
 Picasso.with(BaseApplication.getInstance())
				.load(imageUrl)
				.placeholder(defaultPlaceHolder)
				.into(imageView);

`

**Comment by qinjuning** [comment]
I add the RequestListener to observer the callback, it invoke the onResourceReady method. Log is 
  ```
  zzzzz onResourceReady  model http://img.kaka.in/UploadImages/2015/10/12/2015101212383478099.png
 ```
Code is 
```
  Glide.with(BaseApplication.getInstance()).load(imageUrl)
				.placeholder(defaultPlaceHolder)
				.listener(new RequestListener<String, GlideDrawable>() {
					@Override
					public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {

						Logger.d("onException %s  model %s" , e, model );

						return false;
					}

					@Override
					public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
						Logger.d("onResourceReady  model %s", model );
						return false;
					}
				})
				.into(imageView);
```

So I don't think the cause is that  there was an error during loading.   Like I said before, "It seems it cannot load the real image when its done at first time". 
Then I use the Picasso to do the same thing , it works well . 

 ```
 Picasso.with(BaseApplication.getInstance())
				.load(imageUrl)
				.placeholder(defaultPlaceHolder)
				.into(imageView);

```

**Comment by qinjuning** [comment]
Finally , I find out that the problem is occurred when  I used <a href="https://github.com/hdodenhof/CircleImageView"> CircleImageView </ImageView> .

**Comment by TWiStErRob** [comment]
Ah, the magic "Circle view" :) Sorry for not noticing earlier. Here's a ]nice list](https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=is%3Aissue+CircleImageView+OR+CircularImageView). We dug deep and found the core of the problem: https://github.com/bumptech/glide/issues/482#issuecomment-107977982
(_scroll down a little, the images may make the URL anchor displaced, it's the last long comment by me_)

You have two options:
 * use [CircleTransform](http://stackoverflow.com/a/25806229/253468) instead of custom ImageView
 * add `.dontAnimate()`

While disabling the animation seems easier, you may have more luck with the transformation in the long run.

**Comment by Bertkiing** [comment]
THX U very much!

**Comment by AmrAbuelhamd** [comment]
Thank you guys very much
