### ISSUE TITLE
Bad Image Quality

### ISSUE THREAD

**Issue by aiwiguna** [bumptech/glide#759]
i load this image from SDCard using glide ![img_20150918_150520](https://cloud.githubusercontent.com/assets/6139404/11293484/1f100694-8f8d-11e5-9fa0-2dc8463fac5a.jpg), and crop it using Bitmap.CreateBitmap , save it to file (already test JPG and PNG wiith 100 Quality), and load it again using glide, the result is like this 
![pasted image at 2015_11_18 13_45](https://cloud.githubusercontent.com/assets/6139404/11293543/7bcc1760-8f8d-11e5-8504-3b42460b6fcc.png)

i forced to change all my code to use other image loader library because of this :(

note: crop is in code because it have square,portrait and landscape type, so i need to crop it by code

**Comment by TWiStErRob** [comment]
There's nothing wrong here I think, it's just that Glide defaults are meant for displaying most images, but there are quite a lot of configuration options. Other libraries work because they consume more memory than necessary by default. Your image is quite exceptional, in that it's CGI, try to set the bitmap format to 8888 [application-wide](https://github.com/bumptech/glide/wiki/Configuration#bitmap-format) or use `.asBitmap().format()` to set it on a single load.

**Comment by aiwiguna** [comment]
Thank you for your answer, that fix it :+1:
