### ISSUE TITLE
No crossFade animation for fallback nor error

### ISSUE THREAD

**Issue by malloth** [bumptech/glide#764]
Why there's no default crossFade animation for fallback and error drawables? I want to toggle image (null <-> not null) and animate between image and fallback (or error if it occurs). Animation only shows in fallback -> image direction but not the other way around.

I'm loading my images like this:
```java
private ImageView vPhoto;

private void setPhoto(File photoFile)
{
	Glide.with(this)
		 .load(photoFile)
		 .signature(new MediaStoreSignature("", photoFile != null ? photoFile.lastModified() : 0L, getResources().getConfiguration().orientation))
		 .centerCrop()
		 .error(R.drawable.ic_broken_image)
		 .fallback(R.drawable.ic_photo)
		 .into(vPhoto);
}
```

It doesn't event work if I explicitly add crossFade() method.

**Comment by TWiStErRob** [comment]
Each load is separate so Glide doesn't see what's in the ImageView before the load (it calls `onLoadStarted(Drawable placeholder)` on `Target` which clears previous contents). To cross-fade from an already loaded image you have to tell Glide what is it you want to fade from.

Consider the following (untested) solution (see https://github.com/bumptech/glide/issues/527#issuecomment-148840717 for more on this hacknique):
```java
private void setPhoto(File photoFile) {
	DrawableRequestBuilder<Integer> fallback = Glide.with(this).load(R.drawable.ic_empty_merchandise);
	if (photoFile != null) {
		vPhoto.setTag(R.id.previous, photoFile);
		loadPhoto(photoFile).thumbnail(fallback).into(vPhoto);
	} else {
		File prevFile = (File)vPhoto.getTag(R.id.previous); vPhoto.setTag(R.id.previous, null);
		fallback.thumbnail(loadPhoto(prevFile)).into(vPhoto);
	}
}
private DrawableRequestBuilder<File> loadPhoto(File photoFile) {
	return Glide
			.with(this)
			.load(photoFile)
			.signature(new MediaStoreSignature("", photoFile.lastModified(), getResources().getConfiguration().orientation))
			.centerCrop();
}
```

To make sure you have the ID defined, create `src/main/res/values/ids.xml`:
```xml
<resources>
    <id name="previous" />
</resources>
```

**Comment by malloth** [comment]
Glide somehow knows what is in ImageView because:

Image <-> Image : animates
Fallback -> Image: animates
Image -> Fallback: does not animate

Glide should treat fallback and error drawables just like any other Image.
The behavior is inconsistent and should be a subject to fix.

**Comment by TWiStErRob** [comment]
It's worth noting that `fallback` was just a quickly added shorthand to prevent complex `if`s around the Glide load line, see #268.

> Fallback -> Image: animates

That's obvious because it's on the same load, same as "Placeholder -> Image".

> Image -> Fallback: does not animate

This is also the same as "Image -> Placeholder" which doesn't animate either.
For a simple: `Glide.with(this).load(stuff).placeholder(pl).fallback(fb).error(err).into(imageView)` here are the possible `ImageView.setImage*` calls:
 * `stuff` loaded OK: `setImageDrawable(pl); setImageDrawable(resource);`
 * `stuff` is `null`: `setImageDrawable(pl); setImageDrawable(fb);`
 * `stuff` failed to load: `setImageDrawable(pl); setImageDrawable(err);`

Notice that even if there was ever a (previous) image set, it's immediately cleared by the placeholder. If placeholder is `null` `setImageDrawable` is still called, so "previous image -> fallback" is not possible.

> Image <-> Image : animates

I'm not sure how you achieved that, as far as I remember we had many issues opened because users wanted to cross-fade from a previously loaded image, see #527 and all its duplicates. Can you please explain what you meant by "Image <-> Image"? (If it's `thumbnail`: again, it's on the same load so fading is possible.)

**Comment by malloth** [comment]
As for Image <-> Image : animates - I checked that again and it looks that I mistooked very quick blink on setImageDrawable(pl) (with pl = null) as a crossFade animation. Sorry for that.

But why do you actually do setImageDrawable(pl) if there's no placeholder? It would be really nice if crossFade could be used just like ImageSwitcher.

**Comment by malloth** [comment]
I think that in situations: pl->fb and pl->err crossFade animation should work, because now I set a placeholder as a previously loaded GlideDrawable. Yet it doesn't - why?

**Comment by TWiStErRob** [comment]
> `.placeholder(vPhoto.getDrawable())  // here's the change :)`

Yes, that `vPhoto.getDrawable()` trick would be really nice, but it's unsafe. If it's a drawable loaded from an APK resource it may be ok, but if it's a `BitmapDrawable` loaded by Glide it can be recycled after acquiring a reference to it. Glide gives ownership over the `Bitmap` to the `Target` via `onResourceReady` and takes it away via `onLoadCleared`.
`.placeholder(vPhoto.getDrawable())` is called just before `onLoadCleared` is called by `.into()`. So the `Bitmap` in `BitmapDrawable` is not valid any more. Glide may choose to recycle it or reuse for the current load (if size and bit-depth match) in which case even a draw may happen while the `Bitmap` is being filled with pixel inside a `BitmapFactory`.
The hacknique I showed you above works around this by requesting the same `Bitmap` from Glide (from memory cache) quickly enough (thumbnail requests have higher priority) that it won't be reused.

> Why do you actually do setImageDrawable(pl) if there's no placeholder?

See above. If the `ImageView` wasn't cleared before starting a load an invalid image may stay there or it would show the placeholder from  the previous load. Take a look at the `Target` interface and it's documentation and the implementation in `ImageViewTarget` You can try creating a custom target that doesn't set null placeholders, but remember that you "have to" free resources, which includes `null`-ing the image drawable when `onLoadCleared` is called. It's worth noting explicitly that both `onLoadCleared` and `onLoadStarted` will result in `setImageDrawable(pl)`.

> I think that in situations: pl->fb and pl->err crossFade animation should work

 * placeholder->fallback doesn't really make sense, because it should be an immediate replacement (it's "just" a null check). In this case you may even not see the placeholder so animating would be weird, as in it would show the placeholder unnecesarily.
 * placeholder->error crossfade actually makes sense, because placeholder may be displayed for a long time (for example when error happens because of a timeout) and then error drawable is shown quickly. I would say that displaying the error drawable shouldn't be in the happy-path workflow of the app, and hence it should be really exceptional and rare so not animating is not a big deal. @sjudd what do you think on this point?

You can try to extend one of the `ImageViewTarget` subclasses and do a custom animation when `onLoadFailed` is called.

**Comment by malloth** [comment]
```onLoadCleared``` should take into consideration that cleared drawable (especially ```BitmapDrawable```) is still in use in current request (is either: error, fallback, placeholder or thumbnail) and select other drawable from cache. You have access to those drawables and to bitmap pool and quick check wouldn't hurt here.

crossFade animation is to notify user that an image has change - no matter to what.

**Comment by TWiStErRob** [comment]
But it is not in use any more, that's the point. After Glide calls `onLoadCleared` the resource becomes invalid. That's one of the fundamentals of Glide, and resource-sensitive stuff in general. If you clear something you don't expect to use it any more. As an analogy: in C++ once you call `delete[] arr` you know you can't `arr[0]`, because that memory may be re-used by the OS.

A better example may be a scrolling list which shows 3 items: 1,2,3, once item 1 is scrolled out (not smooth scrolling) and item 4 would come on screen, you know you can re-use item 1 to display item 4. The same happens if you use Glide in a RecyclerView, item 1 went out of screen, recycled and bound to item 4, then the `into()` call must clear item 1's image and may even re-use the same Bitmap. If you're displaying 3 images at a time, you shouldn't need more than 3 images in memory at a time (not taking smooth scrool and preloading into account).

**Comment by sjudd** [comment]
@TWiStErRob I agree, I don't think the complexity is worth the benefit of animating animating placeholder -> error

**Comment by TWiStErRob** [comment]
I think this is decided then. All the questions have been debunked or explained above in detail, or there are no plans to implement them yet.
