### ISSUE TITLE
how can I get image path in DiskCache with url

### ISSUE THREAD

**Issue by zhuangyf** [bumptech/glide#765]
Who can help me,Thank you!

**Comment by TWiStErRob** [comment]
There's no sync method for that, because it requires I/O and it's should be avoided on the UI thread.

See [`get "cache path"` issue search](https://github.com/bumptech/glide/issues?utf8=✓&q=is%3Aissue+get+"cache+path") for numerous discussions.

Closing this as a duplicate of #509, please press subscribe on the right column on that issue if you want to get updates.
