### ISSUE TITLE
override

### ISSUE THREAD

**Issue by fly1314** [bumptech/glide#788]
What is the role override realization

**Comment by TWiStErRob** [comment]
`.override()` JavaDoc:

> Overrides the Target's width and height with the given values.

By default the target is asked "how big are you?" via `Target.getSize(OnSizeReadyCallback)`, the most used logic is in `ViewTarget`:

> Determines the size of the view by first checking View.getWidth() and View.getHeight(). If one or both are zero, it then checks the view's ViewGroup.LayoutParams. If one or both of the params width and height are less than or equal to zero, it then adds an ViewTreeObserver.OnPreDrawListener which waits until the view has been measured before calling the callback with the view's drawn width and height.

If you call `override` before `into` to prevent waiting for the layout or if you know better what size you want to load. For example you want the original image size because you have a custom zooming view, or just want a smaller image because you'll blur it anyway so pixelation doesn't hurt.
