### ISSUE TITLE
Custom cache directory per request

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#792]
I would like to use different cache folders on a per request base. I use different data sources in my app like dropbox, drive, box and so on so I want to clear a data source specific cache and therefore I would like to set the cache a request should use on every request manually.

Is that somehow possible?

PS: 

For me it's only important to clear the disc cache...

The perfect solution would be to be able to setup different caches for my data sources so that the different sources do not share the cache size and I can define different cache sizes. But as long as I can somehow control where the different data sources but their cache files, it would be fine, even if the cache size is shared...

Is anything like that possible?

**Comment by MFlisar** [comment]
For me it's only important to clear the disc cache...

The perfect solution would be to be able to setup different caches for my data sources so that the different sources do not share the cache size and I can define different cache sizes. But as long as I can somehow control where the different data sources but their cache files, it would be fine, even if the cache size is shared...

Is anything like that possible?

**Comment by TWiStErRob** [comment]
Sorry for the late response, I was waiting for some revelation... which didn't really happen.

An idea may be to create different models for different caches, which you must already have because you're using `DataFetcher`s. You could build on the idea of #746 and manage caches yourself (each model-fetcher having a different fallback which represents a different cache), while still keeping Glide's behavior for most of the loading. @Teovald, you seem to be experienced in this, do you have any better idea?

**Comment by TWiStErRob** [comment]
Here's a more centralized, but one hacky idea: create a `DiskCache` super-wrapper which delegates to multiple `DiskLruCacheWrapper` instances which work in different folders. You can then call `DiskCache.clear` on that particular folder's cache through some custom API you design on your super-wrapper to clear a single part of your overall cache. I highly suggest sticking to this method instead of wiping the folder because the runtime (`DIskLruCache`) may get confused.

You'll need to create a subclass to be able to create wrappers for different dirs because sadly the constructor is protected:
```java
class FolderCache extends DiskLruCacheWrapper {
    public FolderCache(File directory, int maxSize) { super(...); }
}
```
The super-wrapper can create multiple instances pointing to different folders, the problematic part is figuring out which instance to call for a particular Key. I think you'll either receive an `OriginalKey` or an `EngineKey`, both of them have a `signature` field which you can hijack to designate the cache it supposed to go to.

The next issue is getting that information out of the keys. Sadly both fields are private, so, I guess... the only way is reflection. If you can accept that you should have a straightforward route from here. `setAccessible` is king :) If you can't access the field for some reason or it is `null` you can have a fallback cache where you put "everything else". Make sure you proguard keep these two specific fields.

Once you have the `signature` value you can cast it to your own `Key` implementation which has getters to help decide. If you want to be lazy or nasty you could even behave like `EmptySignature` and not modify the hash key so you can change stuff freely behind the scenes.

**Comment by TWiStErRob** [comment]
@Tolriq from #383, do you have any insights on @MFlisar's original question?

**Comment by Teovald** [comment]
One way to do that would be to declare a no-op Glide disk cache for your data. I don't think you can coerce Glide to follow the behavior you want (unless you use reflection), so let's ignore its disk cache.

Second step : link up your ModelLoader/DataFetcher to separate caches, like in #746
The `loadFromSynchro(@NonNull Model model, int width, int height);` method of https://gist.github.com/Teovald/bfddf6cbddc8e61ade80  would call the cache corresponding to that type of data.  

Since you are handling these caches yourselves, nothing prevents you from flushing one when you feel like it.  

It is a bit hacky, but it would work and would not need any reflection.

I am not sure it is worth the effort though. One LRU for all your data seems more than enough to me but if you really want to, it is doable.

**Comment by MFlisar** [comment]
Thanks for all the tips. I was thinking about the problem today and actually I think there is a really simple solution that's good enough for my use case and is really simple:

I can save signature "salts" for every data source and save them in my preferences. If I want to "clear" the cache of a specific data source I just create a new salt for it. This will invalidate all cached data of this specific data source at once...

So I'm sharing one cache size for all data sources but that's anyway ok for me.

But as Teovald suggested using a no op cache and do caching myself I would have full control over the storage as well and so I could delete the cached files from disc but that's actually not even necessary

That ks for all the input

**Comment by TWiStErRob** [comment]
Yet again, signature to the rescue :)
Thanks for the feedback!
