### ISSUE TITLE
Problems with EXIF orientation

### ISSUE THREAD

**Issue by px-amaac** [bumptech/glide#829]
I am not the best and Linear Algebra but I was debugging an issue in our app. We are using glide to display images taken from both android and iOS phones. Android photos are being displayed correctly but iOS images are not. The Android photos do not have an orientation in the EXIF headers but the iOS images do. As a solution we have removed the orientation tag and rotated the image on iOS but not sure if this is a bug or not.

Here is the EXIF header from one of the images. 
Exif Image Size	1,920 × 1,080
Orientation	Rotate 90 CW
Resolution	72 pixels/None
File Type	JPEG
File Type Extension	jpg
MIME Type	image/jpeg
File Size	439 kB
Image Size	1,920 × 1,080

[Photo metadata](http://regex.info/exif.cgi?imgurl=https%3A%2F%2Fs3.amazonaws.com%2Ftimeset-photos%2FRackMultipart20151217-4907-vnn7er.jpeg)

The iOS image is stored rotated 90deg CCW so to restore it to its captured orientation it needs to be rotated 90deg CW like the EXIF orientation specifies.

in the method [rotateImageExif()](https://github.com/bumptech/glide/blob/28859ec29420788d35da69606db96f3a94c9e4e8/library/src/main/java/com/bumptech/glide/load/resource/bitmap/TransformationUtils.java#L267) is where I lost track of what was happening.

By this point there is already a Bitmap. The bitmap returns the correct width and height as if the image was already rotated.

The current width is 812 and the current height is 1443 (This is the correct width and height that was requested from the server but does not describe the image that is stored.)
RectF(0.0,0.0,812.0,1443.0) <-- starting RectF

The matrix that is returned from examining the orientation is 
[0,-1, 0],
[1, 0, 0],
[0, 0, 1]
I believe this is the translation matrix to rotate 90deg CCW around Cartesian origin.

Rect(-1443,0,0,812) is the resulting rectangle which means the height and width are reversed and the image displays with a stretched width and compressed height.
these numbers are correct given the starting rectangle on a Cartesian coordinate system.
Again i do not know if this is a bug or if the orientation tag was incorrect but we fixed it by avoiding using exif headers at all and uploading the image already rotated.

![squishedios](https://cloud.githubusercontent.com/assets/2364583/11904635/335d3226-a576-11e5-8b5f-b2b172fd0382.png)

**Comment by sjudd** [comment]
Fascinating, can you attach an original sample image?

**Comment by TWiStErRob** [comment]
The "Photo metadata" link above has the original:
https://s3.amazonaws.com/timeset-photos/RackMultipart20151217-4907-vnn7er.jpeg

**Comment by TWiStErRob** [comment]
I tried to reproduce this (Galaxy S4, 4.4.2) and the closest I got was with `scaleType=fitXY`, it was distorted, but the full image. Notice that you're also missing part of the image. For some reason all combinations of width/height resulted in correct bitmaps and correct transforms for me. As described below I think the math is sound, the questions are:
 * Why do you get an already standing Bitmap?
 * When I tried the size of the target didn't change anything  
here's the debug state in the Downsampler: [812x1443](https://cloud.githubusercontent.com/assets/2906988/11914372/b2078ebe-a67f-11e5-8299-45e442a6629d.png) VS [1443x812](https://cloud.githubusercontent.com/assets/2906988/11914373/b2081244-a67f-11e5-9c0d-5109bfee9408.png)  
(the memory addresses of Bitmaps are the same, because they're pooled)  
Can you please compare this to what happens at yours?
 * Also check whether the `downsampled` Bitmap is corrupt or not?  
(there's a "View Bitmap" action in debugger on Bitmap objects)
 * What is your Glide load line and layout XML?
 * Is it possible that Android 5 BitmapFactory rotates by EXIF already?

---

This is a 2D rotation, so 3x3 matrix is needed. Essentially we are rotating around the z axis, so it should be unit there (1). Additionally there is a translation baked in ([see Wolfram](https://www.wolframalpha.com/input/?i=Composition%5BTranslationTransform%5B%7Bx%2Cy%7D%5D%2C+RotationTransform%5Btheta%5D%5D)):
```java
[r, r, tx]
[r, r, ty]
[0, 0,  1]
```

`exifOrientation` passed to the method is `6 == ExifInterface.ORIENTATION_ROTATE_90`), so `Matrix.setRotate(90)` is called, which results in:
```java
[ cos 90° = 0, -sin 90° = -1, -newRect.left = toOrient.getHeight() ],
[ sin 90° = 1,  cos 90° =  0,                                    0 ],
[           0,             0,                                    1 ]
```
which looks right to me. The whole code simplifies to this if called with exif=6:

```java
Matrix matrix = new Matrix();
matrix.setRotation(90);
int newWidth = toOrient.getHeight();
int newHeight = toOrient.getWidth();
matrix.postTranslate(newWidth, 0);
```

**Comment by px-amaac** [comment]
Ill try to answer those in order here.

Why do you get an already standing Bitmap? Not sure what you mean here or even if I can answer this.
What is your Glide load line and layout XML?

Here is my xml entry. The image is being loaded in a recycler view adapter.

    <timeset.com.customViews.ResizingImageView
                android:id="@+id/img_thumbnail"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:src="@drawable/white"
                android:visibility="visible"/>

The Resizing image view simply sets the view height and width prior to the image being loaded with glide which is why the test image has so much white space. The image view is the size that the image is supposed to be.

Here is where I am loading the image with Glide

        Glide.with(context)
                .load(widthHeightUrl)
                .placeholder(R.drawable.timeset_white)
                .crossFade()
                .into(img_thumbnail);

Please check whether the downsampled Bitmap is corrupt or not before calling exif rotate? 
Here is the original image for this second test.
![img_0691](https://cloud.githubusercontent.com/assets/2364583/11941136/528db8a0-a7e2-11e5-9327-d6cc11548c91.JPG)

Here is the downsampled image
![downsampled](https://cloud.githubusercontent.com/assets/2364583/11941139/5b793160-a7e2-11e5-899e-c22c9ead6c9e.png)

Here is the rotated Image
![rotated](https://cloud.githubusercontent.com/assets/2364583/11941153/6ad05620-a7e2-11e5-864e-142d588a17e5.png)

Is it possible that Android 5 BitmapFactory rotates by EXIF already?  Not sure on this one. I can confirm that I am using Lollipop.
(Assuming Android 5 based on your button shadow :))

When I tried the size of the target didn't change anything
here's the debug state in the Downsampler: 812x1443 VS 1443x812
(the memory addresses of Bitmaps are the same, because they're pooled)
Can you please compare this to what happens at yours?

Here is the same breakpoint in my code on a failing image
![screenshot_1](https://cloud.githubusercontent.com/assets/2364583/11941203/b6d178ba-a7e2-11e5-9025-7fd6593fdf1f.png)


Here is that same breakpoint on an image that displays correctly.
![secondbreakpoint](https://cloud.githubusercontent.com/assets/2364583/11941293/490c3968-a7e3-11e5-8bcf-ea956c6734c0.png)


I hope this helps. Please let me know if there is anything else you need from me.

**Comment by TWiStErRob** [comment]
Thanks for this awesome amount of information, it's nice to work with you!

Below are my findings and thoughts. **bolded** some parts where there are new quesitons.

>> Why do you get an already standing Bitmap?

> Not sure what you mean here or even if I can answer this.

In your original post the metadata says "Image Size 1,920 × 1,080" and the image in the Exif Viewer is landscape, which is correct if we ignore the Exif rotation. We can see the natural orientation would be portrait. You said upon entering the `rotateImageExif` method "*as if the image was already rotated*" and "*The current width is 812 and the current height is 1443*", so the image it receives (`downsampled` outside) is standing (=portrait, sorry if I chose the wrong word). This led me to this question and the question "*Is it possible that Android 5 BitmapFactory rotates by EXIF already?*".

>> Please check whether the downsampled Bitmap is corrupt or not before calling exif rotate?

So from your new debug image dumps we can see that the `TransformUtils` rotation has nothing to do with the corruption, the `downsampled` `Bitmap` is already bad for you.

> The Resizing image view *simply* sets the view height and width prior to the image being loaded with glide 

**Can you reproduce** the same issue **without that magic `ImageView`**? I noticed when we (devs) phrase something as "simply" it's a clue to be investigated ;) ...
Tip: if you use match/match on a stock `ImageView` Glide will automatically retrieve the size the view takes, this means the least amount of pixels (pixel perfect Bitmap) will be loaded; there's also an `override(w,h)` to force the resulting Bitmap/Drawable to match what you want. Is there any other reason **why you would set the `ImageView` size** dynamically?

> Here is the same breakpoint

 * What I see from there is that the `outWidth/outHeight` is the same in both cases: `1440x2560`, as a full-screen `ImageView` on a portrait phone would suggest, so this is fine.
 * In the correct case it's not rotated (i.e. same object returned), while in the failing case the `rotated` is a new bitmap with `1443x812` size, but since I stated above you have a `Bitmap` in `downsampled` already.
 * The `downsampled` Bitmap in both cases is the same: `812x1443`, this causes some concern for me. The `sampleSize` uses `degreesToRotate` to figure out which side to divide with which side, but `downsampleWithSize` ignores that. `inWidth/inHeight` are the raw values from the image in the stream. This means that a big enough bitmap will be used, but the orientation may be wrong, hence the distortion... `BitmapFactory` seems serious about filling the given `inBitmap` fully, but I couldn't reproduce it at all; the following all work in all cases I tried:
  * real Galaxy S4 4.4.2 (19)
  * Genymotion Nexus 5 5.0 (21)
  * Genymotion Nexus 6 5.1 (22)
    I was using the sample images you provided [here](https://s3.amazonaws.com/timeset-photos/RackMultipart20151217-4907-vnn7er.jpeg) and [here](https://cloud.githubusercontent.com/assets/2364583/11941136/528db8a0-a7e2-11e5-9327-d6cc11548c91.JPG), can you please **try these exact Uris** if they work or not?

Let's get down some numbers too:
 * What is your **Glide version**?
 * What is your exact **Android verison**?
 * What **device** can you repro this on?

**Comment by px-amaac** [comment]
Because we have moved on i keep making the iOS developer break the image stuff to test this issue. This is a very interesting issue to me so I am happy to help solve it if I can.

__Can you reproduce the same issue without that magic ImageView?__
If I remember correctly we were still getting bad images when using a stock ImageView.

__why you would set the ImageView size dynamically?__
Without setting the size of the images before the images are loaded the recycler view would load without the image and while scrolling the recycler view would jump around as the images get loaded in and the imageView resizes to fit the images. We have an image resizing server and our api calls accept width and height for images. So we combine metadata(width/height) of the image with width of the screen to load the exact size that the image view is expecting based off the screen width and keeping aspect ratio for the height. I was not aware of any feature in Glide to get around this.

__What is your Glide version?__ 3.6.1
__What is your exact Android verison?__ 5.1.1
__What device can you repro this on?__ I am using a Galaxy Note 5 for all testing but I can confirm this was also happening on Moto X 2nd gen, and Nexus 5.

I will try to reproduce with the exact URIs and a stock image view. Because testing this is becoming cumbersome to our current project I am going to see if I can reproduce in a separate project first. Ill try to get that up tonight or tomorrow. I will have another shot to reproduce with URIs and Stock ImageView on our project tomorrow morning.

**Comment by TWiStErRob** [comment]
Yep, a simple repro app would be awesome! Thanks for looking.

**Comment by px-amaac** [comment]
Sorry it has taken me a min to get this up. I have a repo app that I made but I just got done moving and my computer was packed up. Ill post it asap. It did not solve anything but was interesting. I used both stock image view and my magic image view. Both image views worked as expected with no image skewing.

**Comment by TWiStErRob** [comment]
No probs for the time. That "worked as expected" doesn't sound good. So you weren't able to reproduce the same issue outside of the real app? When can't go far if it's not reproducible.

**Comment by TWiStErRob** [comment]
Do you have any news on this? I acknowledge you might be busy, just curious if you found something related to this.

**Comment by px-amaac** [comment]
I was never able to reproduce again. Its a funky error. I think maybe there was something happening on the server to the images. Maybe the EXIF headers did not reflect the state of the image when retrieved from the server. Either way ill close this ticket as there has been no progress. Sorry for letting this slip.

**Comment by draxdave** [comment]
Anyone with a similar issue refer to [this](https://stackoverflow.com/a/8914291/4799599) stackOverFlow post
