### ISSUE TITLE
how to get Request Detail

### ISSUE THREAD

**Issue by d3graph** [bumptech/glide#837]
i working on a project with glide to load images form net and save to disk but i am unable to get the request object please see the code below 

```java
Glide.with(getApplicationContext())
    .load(Uri.parse(list[i]))
    .asBitmap()
    .diskCacheStrategy(DiskCacheStrategy.ALL)
    .into(new BitmapImageViewTarget(ImageViews[i]) {
        @Override
        protected void setResource(Bitmap resource) {
            GenericRequest req = (GenericRequest) this.getRequest();
        }
    })
;
```

when i put Req object in watch window during i can see model property but i am unable to access them in code. My question is that how to get uristring from request object so that i can get file name to save the bitmap

Any help will be really appreciated

**Comment by TWiStErRob** [comment]
`GenericRequest` is an internal part of Glide and usually you don't need to worry about the contents. There are several ways to achieve what you want, I'll list all I know here. I'll assume that you only want to save the image and not actually display it. Based on this assumption it's worth to free up resources explicitly, otherwise you may get an `OutOfMemoryError` eventually. The usual problem is that you can't do your `I/O` in a sync way, because it has to be on a background thread, and `Glide.clear` has to be on the UI thread, so there's a lot more to take care of. For this reason I assume you have a method to save your data in the background and call `Glide.clear(target)` after the save on the UI thread, something like:
```java
void save(final Target target, final Uri url, final Bitmap image) {
    new AsyncTask<Void, Void, Void>() {
        @Override protected Void doInBackground(Void... ignore) {
            OutputStream out = null;
            try {
                File file = new File(dir, url.getLastPathSegment()); // or however you do it
                out = new BufferedOutputStream(new FileOutputStream(file));
                image.compress(CompressFormat.JPEG, 85, out);
                out.flush();
            } catch (Exception ex) {
                Log.w("SAVE", "Failed", ex);
            } finally {
                try { if (out != null) out.close(); } catch (IOException ignored) {}
            }
            return null;
        }
        @Override protected void onPostExecute(Void ignore) {
            Glide.clear(target);
        }
    }.execute();
}
```

# Saving the `Bitmap` with `ImageView`

## Anonymous inner class `Target` with `url` in closure
`getRequest().model` is private, but the url inside the generated `$1` inner class closure is not.
```java
final Uri url = Uri.parse(list[i]);
Glide
    .with(context)
    .load(url)
    .asBitmap()
    .diskCacheStrategy(DiskCacheStrategy.NONE)
    .skipMemoryCache(true)
    .into(new BitmapImageViewTarget(imageViews[i]) {
        @Override protected void setResource(Bitmap resource) {
            save(this, url, resource);
        }
    })
;
```
Characteristics:
 * Pro: closest to what you have
 * Con: it needs an inflated and visible `ImageView`

# Use `.listener()` to access model
A `RequestListener` can peek at the data in a more generic way, having access to model for example. A single listener can be used on multiple requests even if their data is different.

```java
Glide
    .with(context)
   .load(Uri.parse(list[i]))
   .asBitmap()
   .diskCacheStrategy(DiskCacheStrategy.NONE)
   .skipMemoryCache(true)
   .listener(new RequestListener<Uri, Bitmap>() {
       @Override public boolean onException(Exception e, Uri model, Target<Bitmap> target, boolean isFirstResource) {
           return false;
       }
       @Override public boolean onResourceReady(Bitmap resource, Uri model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
           save(target, model, resource);
           return false;
       }
   })
   .into(imageViews[i])
;
```
Characteristics:
 * Pro: no closure, everything is available as typed local variable
 * Con: it needs an inflated and visible `ImageView`

---

# Saving the `Bitmap` without `ImageView`
So far there was an `ImageView` needed to acquire the `Bitmap`, there are more direct ways.

## `downloadOnly`
`downloadOnly` is usually used to pre-fill the `SOURCE` cache. The arguments `width`/`height` are used for bucketing to create an url where server-side has multiple versions of the same image, not to get a sized image.

```java
// on a background thread
Uri url = Uri.parse(list[i]);
FutureTarget<File> target = Glide
    .with(context)
    .load(url)
    .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
;
File fileInCache = target.get();
FileUtils.copy(fileInCache, figureOutTarget(url));
Glide.clear(target); // FutureTarget is safe to clear in background
```
Characteristics:
 * Pro: no `ImageView` needed
 * Pro: everything must be on background thread
 * Con: no sizing and transformations at all
 * Pro: low memory usage (`Bitmap` is not created at all)
 * Con: Glide is an image loader, not a networking library

## Loading `Bitmap` into a `Target` with explicit transformations
Without the `ImageView` you have to specify the size of the bitmap and the way you want the image to be resized and transformed.

```java
final Uri url = Uri.parse(list[i]);
Glide
    .with(context)
    .load(url)
    .asBitmap()
    .fitCenter().override(1000, 1000)
    .diskCacheStrategy(DiskCacheStrategy.NONE)
    .skipMemoryCache(true)
    .into(new SimpleTarget<Bitmap>() {
        @Override public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
            save(this, url, resource);
        }
    })
;
```
Characteristics:
 * Pro: no `ImageView` needed
 * Pro: explicit control over sizing and transformation  
   *"code is read more than is written"*

## Use Glide to encode `Bitmap`
The magic method `toBytes` can encode the `Bitmap` and return the JPG/PNG bytes, so the only thing left is to write it to an `OutputStream`.

```java
final Uri url = Uri.parse(list[i]);
Glide
    .with(context)
    .load(url)
    .asBitmap()
    .toBytes(CompressFormat.JPEG, 85)
    .fitCenter().atMost().override(1000, 1000)
    .diskCacheStrategy(DiskCacheStrategy.NONE)
    .skipMemoryCache(true)
    .into(new SimpleTarget<byte[]>() {
        @Override public void onResourceReady(byte[] resource, GlideAnimation<? super byte[]> glideAnimation) {
            save(this, url, resource); // almost the same as the Bitmap version, just: out.write(image);
        }
    })
;
```
Characteristics:
 * Pro: no `ImageView` needed
 * Pro: explicit control over sizing and transformation  
   *"code is read more than is written"*
 * Pro: no worries about the `Bitmap`

---

# Displaying and saving

Notice that above almost everywhere it's `.diskCacheStrategy(NONE).skipMemoryCache(true)`, that's becuase it's worth to not cache anything if this is a one-off save. By which I mean the `Url` will never be queried again (I guess that's why it's copied to another location). In case you want to display it later it's worth using `.diskCacheStrategy(SOURCE)`. In any case it's better to do the display and save separately, you can save the original with `downloadOnly` and use `.diskCacheStrategy(ALL)` on a load into an `ImageView`. It's worth noting that designating the `diskCacheStrategy` means that Glide is allowed to read AND write to the given cache(s).

**Comment by d3graph** [comment]
thanks that solved my prob.Thanks

**Comment by TWiStErRob** [comment]
Just curious: which one?

**Comment by d3graph** [comment]
using .listener() to access model. this one fit in to my setup
