### ISSUE TITLE
Glide don't cache on disk or memory when url is too long

### ISSUE THREAD

**Issue by sleepingAnt** [bumptech/glide#841]
Hi,this is my url:

http://image.gongren8.com/img/21c07dee68/d5aec0d58c/c28523b5d098e947f50c258868709dac.jpg%401e_0o_0l_400h_300w_90q.jpg?OSSAccessKeyId=STS.Ltps8pBk2fsDlZbQukVf&Expires=1451075351&Signature=2odF35Toq%2BxeLoWrmYEbCGVnpmk%3D&security-token=CAES/gIIARKAAZYC9GL9lXDF3cVUXhVVM9nYNRMzc2CWYRDFARQ3c%2BmzbC1/lWt/6bxKy3nzW/iFv3Pk3WD6vQaOgGCjYKZXArnTZRoPyqpawUnPBAimJajWSItPQ%2BvwQT7LAUzxj5hYthaCDfZxI3jfQ6ePqpqaARz%2Bsym4lPUQbZxrYAF0vunLGhhTVFMuTHRwczhwQmsyZnNEbFpiUXVrVmYiEjM2MjUxNjM0NzE0MDk1OTIyOCoDenhnMKPGwNWdKjoGUnNhTUQ1QmwKATEaZwoFQWxsb3cSJwoMQWN0aW9uRXF1YWxzEgZBY3Rpb24aDwoNb3NzOkdldE9iamVjdBI1Cg5SZXNvdXJjZUVxdWFscxIIUmVzb3VyY2UaGQoXYWNzOm9zczoqOio6Z29uZ3JlbjhkLypKEDEyNzE5NTQwODE2NDMzMzhSBTI2ODQyWg9Bc3N1bWVkUm9sZVVzZXJgAGoSMzYyNTE2MzQ3MTQwOTU5MjI4cgd6eGctcmF5

```java
Glide
	.with(context)
	.load(url)
    .centerCrop()
    .crossFade()
    .into(imageView)
;
```

**Comment by TWiStErRob** [comment]
Did the image show up at all for you? That's an important info you didn't tell us. If there's no image it means there was an error. It's easy to see loading errors, read [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener).

Chrome on my laptop can always load it just fine, but with Glide I got varying results of:
 * .onException(java.net.UnknownHostException: Unable to resolve host "image.gongren8.com": No address associated with hostname  
 * .onException(java.io.IOException: Request failed 403: Forbidden
 * successfuly load.

I changed the networking layer from default to [OkHttp](https://github.com/bumptech/glide/wiki/Integration-Libraries#okhttp) and it worked fine immediately.

So there's no caching issue, the image just doesn't load because the server is misbehaving or maybe because of something like [this](https://code.google.com/p/android/issues/detail?id=67324). It's also possible that long urls break the DNS resolution: I was only able to load after trying to load the url a few times without the query string part.

**Comment by sleepingAnt** [comment]
Yes, the image show up at all for me every time, but it neither cache on disk nor memory.The image server is at china ,so the exception you got may be the network is unstable or something else.

**Comment by TWiStErRob** [comment]
Sorry, does it show up or not? ("at all" is usually used with negative statements, so it's ambiguous above).

**Comment by sleepingAnt** [comment]
Sorry. I mean, the picture can display normally on my phone, if you don't load succeed, may be because the network is not stable, because the picture server in China.

**Comment by TWiStErRob** [comment]
What happened, did you find the problem?

**Comment by sleepingAnt** [comment]
Yes, it's my problem,my url changes every time, when url is fixed, pictures can be properly cached.Thank you for your help.

**Comment by TWiStErRob** [comment]
Ah, I see, check out #607 for that.

**Comment by sleepingAnt** [comment]
Oh! This solved my problem，Thank you!
