### ISSUE TITLE
How to add cross fade when loaded from SimpleTarget<Bitmap>

### ISSUE THREAD

**Issue by manjunathc23** [bumptech/glide#847]
Hey Glide Member, 

Please let us know how to have the cross fade when loaded from `SimpleTarget()`. Also let us know the difference between setting listener `RequestListener` and loading into `SimpleTarget()`

Thanks!
Manjunath

**Comment by TWiStErRob** [comment]
In general I don't recommend using SimpleTarget, because you lose the View support (see ViewTarget and ImageViewTarget, they have fair amount of code). I'm saying this because when you say cross fade it immediately implies that you want to display the resulting resource, and in Android you kind-of need a View - or more likely an ImageView - to do that.

The difference between a target and and a listener is that the listener runs before the target and the target is mandatory compared to listener being optional, but listener can override/prevent target delivery. They have separate functions, Target encapsulates where the decoded/transcoded resource is headed (the reason of your load), while the listener is just peeking at it right before it's delivered to the target.

If you really want to go for it I just demonstrated how to cross-fade Bitmaps in #840, that solution could be used with any custom transcoded type that has (or convertible to / likely in constant time) a Bitmap/Drawable.

Feel free to elaborate your use case so we can suggest the best solution, a general question like the above won't get you too far and it's also possible we have an [X/Y problem](http://xyproblem.info/) on our hand.

**Comment by manjunathc23** [comment]
Thanks a lot for the reply. @TWiStErRob 

Well, I'll explore on `ImageViewTarget` which looks like fit my requirement.  

I see the calling to preLoad() and immediate next call to Glide with same URL doesn't return me resource from cache memory.  I am missing something?

**Comment by TWiStErRob** [comment]
`preload` is async I think, to be honest, I didn't use that yet :) Make sure you match the exact arguments: most importantly size and transformation because they're automagic from the given View.

See [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) for how to see what cache hits and misses you have.

**Comment by manjunathc23** [comment]
I forgot to mention this, Yes, We wait for the callback before we make another request. To my surprise we don't see the image comes from cache. Due to this I see tiny flicker in my image views.

**Comment by TWiStErRob** [comment]
I don't really see why you need to preload if you immediately display it, please describe your usage in detail.

**Comment by manjunathc23** [comment]
I am glad you asked. Well, Here is my use case. 

1. We pass the image bitmap(Thumbnail) from the Fragment A to Fragment B for the shared element transition. 
(Note : Image from fragment A has different url(Thumbnail) then Fragment B url(Big Image). As the sizes are different so as our image url's. we are required to resize from our server end. )

2. While we wait for the transition to complete from Fragment A to Fragment  B we pass on the image url to Glide to cache and keep it ready  we do `PreLoad()` here.

3. Once we have shared element transition complete + image is pre loaded(asych). We request for  our custom view pager to load the image that we requested previously. Hoping that it will come back soon from the cache. So that we can fade in from temp image bitmap holder in Fragment B to actual image view pager in fragment B. 

We have set up this framework based on the `Picasso's` Target callback. I am looking for replacing Picasso without much refactor in our code. 

Hope now you have some idea. It will be great if you can help us here.

**Comment by TWiStErRob** [comment]
Thanks for the use case. (*See I told you it's X/Y ;) you want Lollipop transitions, not Bitmap crossfade.*)

It's possible to do the transition without having a single Bitmap or fake view, you just have to hit the caches. That flicker may also come because of a rouge `.crossFade()` do you use `.thumbnail()`? If logging the cache key above and the email I sent you doesn't help please share your Glide loads/preloads here. See #502 and related issues for more details.

**Comment by manjunathc23** [comment]
Hey @TWiStErRob, 

Thanks for the note. No we don't use `thumbnail()` just yet.

I see setting the `placeholder` for next consecutive request with the bitmap we get from `preLoad()`
helps avoiding flicker to some extent. However I am sure consecutive request is not giving me image from cache. I'll keep looking into it. Will keep you posted.

Thanks a lot for all your help and sample code. 
Manju

**Comment by TWiStErRob** [comment]
`iv.getDrawable()` or stealing a Bitmap from a listener/target is usually considered unsafe, especially if you're using it in the same view and then start a new load with it. The resource delivered to the target (via `onResourceReady`) is valid only to the point where `Target.onLoadCleared` is called, after that it may be reused or recycled, both may result in undefined behaviour.

To prevent flicker you can try `.dontAnimate()`, though that usually just hides the issue doesn't fix it. It's also possible that a relayout is causing it, maybe when hiding the "temp image bitmap holder"? Just throwing ideas here.

**Comment by manjunathc23** [comment]
Aha~ I see. 

Well, we copy the entire bitmap in the target callback from `onResourceReady()`like  `new BitmapDrawable(getResources(), placeHolder)` this should save us from the problem you mentioned right? 

Good idea, I'll try with `.dontAnimate()` once. 

Thanks!
Manju

**Comment by TWiStErRob** [comment]
Sadly, no, the problematic part is the `Bitmap`, not the `Drawable` around it, so unless you make a pixel-by-pixel copy, you may be in trouble. Your case might be the exception to the rule though, because you seem to steal a Bitmap from the "temp image bitmap holder" and use it as a placeholder for another `ImageView` inside the pager. It's still unadvised though because you can just hit the Glide memory cache with a thumbnail to have the same effect, which is not as hacky.

**Comment by manjunathc23** [comment]
I see... Make sense! I'll revisit my implementation with this.

**Comment by manjunathc23** [comment]
Hey @TWiStErRob ,

Now there is no flicker `dontAnimate()` did the magic here! As you said we shall deep copy the bitmap. 

![gif](https://cloud.githubusercontent.com/assets/1502341/12054224/18b551fe-aee7-11e5-938f-3d72aca3cc14.gif)

Thanks!
Manju

**Comment by TWiStErRob** [comment]
Awesome, though I would still suggest to look for a better solution as deep copying is intense, not everyone has a fast phone like your dev phone.

**Comment by manjunathc23** [comment]
Yeah totally agreed!

**Comment by TWiStErRob** [comment]
I guess this is resolved with a workaround, feel free to follow up if you find a better solution in case someone reads this through :)
