### ISSUE TITLE
why recyclerview use Glide,the image didnt display.Piccaso working good.

### ISSUE THREAD

**Issue by wozuihighwa** [bumptech/glide#851]
I try to set the width,height and scaleType properties of ImageView(fitcenter,centercrop),but also didnt work. Piccaso working good. 

here's some code:
```java
Glide.with(context).load(photoUrls.get(position)).into(holder.imageView);
Picasso.with(context).load(photoUrls.get(position)).into(holder.imageView);
```

xml:
```xml
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:scaleType="fitCenter"
```

**Comment by TWiStErRob** [comment]
Wrap causes the `ImageView` to have size 1080x0 size on first layout (because there's no src/drawable yet) which is then used by Glide to load a Bitmap of that size, which obviously is a pointless load. See #135 for more: try not to use wrap_content or use .`override()`. Note that `.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)` will be no different than what Picasso does (as far as I remember), wasting memory. Try to give a number for at least one dimension to save resources (e.g. screenwidth/2 for a 2-column grid).

**Comment by wozuihighwa** [comment]
Thx.

**Comment by wozuihighwa** [comment]
It's helpful,thx. :)
