### ISSUE TITLE
Glide doesn't load URIs with special characters? (%)

### ISSUE THREAD

**Issue by sumbulAlvi** [bumptech/glide#867]
Noticed that some of the URIs we are trying to load that contain a `%` sign in the filename end up not getting loaded, the exception being:
```
java.io.FileNotFoundException: No such file or directory
```
Example URI name: 
```
file:///storage/emulated/0/Tumblr/https%3A%2F%2F40.media.tumblr.com%2Fe14acf4122fcff3ccd312b606e4edd6d%2Ftumblr_o08kd903HD1tt3zoto1_500_1.jpg
```
However, if the same uri was renamed to be 
```
file:///storage/emulated/0/Tumblr/https3A2F2F40.media.tumblr.com2Fe14acf4122fcff3ccd312b606e4edd6d2Ftumblr_o08kd903HD1tt3zoto1_500_1.jpg
```
Glide has no problem loading the image.
Is this expected or no? Any other symbols to watch out for in the filepath? Thanks!

**Comment by TWiStErRob** [comment]
How are you loading these? Please share the code and types of arguments to Glide methods.
I tried with a file named `/sdcard/file%3A%2F.jpg` and possible combinations I can think of to load it:
```java
String path = "/sdcard/file%3A%2F.jpg";
Glide.with(context).load(path).into(imageView);
Glide.with(context).load(new File(path)).into(imageView);
Glide.with(context).load(Uri.fromFile(new File(path))).into(imageView);
```
all worked fine, so you must be doing:
```java
Glide.with(context).load(Uri.parse("file://" + path)).into(imageView);
```
or similar, which is not a valid way of creating an Uri from a file path.

If you take a closer look on your first example: it is an `Uri.toString` most likely, which means that Uri encoding rules apply, therefore any %-escapes must be decoded when reading it, resulting in what you would get with `URLDecoder.decode(uri.toString())`, so `file:///storage/emulated/0/Tumblr/http://40.media...` which cannot be a valid Unix path. When you log or debug an Uri that has special chars in it, it must look like this: `file:///sdcard/file%253A%252F.jpg`, notice that it's a proper Url (has schema and the initial `://` is not %-escaped, but the second one looks double-encoded. That's because `Uri.toString()` gives a safe representation that is interchangable and valid in all cases. If you interpret this Uri you get back the original file name (in variable `path`) which still contains %-escapes.

**Comment by sumbulAlvi** [comment]
How the uri is loaded:
```
final Uri imageUri = Uri.parse(url);
Glide.with(context).load(imageUri).into(imageView);
```
Different file path urls tried and result:
```
1. String url = "/storage/emulated/0/Tumblr/http%3A%2Fgif-images.png";
java.lang.Exception: Failed to load model: '/storage/emulated/0/Tumblr/http%3A%2Fgif-images.png'
(verified this filename and type exists at this location)

2. String url = "/storage/emulated/0/Tumblr/http3A2Fgif-images.png"
java.lang.Exception: Failed to load model: '/storage/emulated/0/Tumblr/http3A2Fgif-images.png'
(verified this filename and type exists at this location)

3. String url = "file:///storage/emulated/0/Tumblr/http%3A%2Fgif-images.png";
java.io.FileNotFoundException: No such file or directory
(verified this filename and type exists at this location)

4. String url = "file:///storage/emulated/0/Tumblr/http3A2Fgif-images.png";
**Success, image loads**
```

As you can see, there was no exception that occurred when the filename did not contain the "%" symbol and when the "file://" prefix was left in the url.

**Comment by TWiStErRob** [comment]
It won't work because `parse` will resolve %-escapes. By using `new File(path)` you lock down the escapes and `fromFile` will escape anything that needs to be escaped however weird the name is.

1 & 2. `/storage/...` is not a valid `Uri` for `parse` (lacks protocol),  
but `Glide....load(url)` will resolve it correctly, because it notices that it's a File path.
3. will try to load `/storage/emulated/0/Tumblr/http:/gif-images.png` which cannot exists  
(remember `toString` is escaped)
4. no weird characters and file protocol, that of course works :)

**Comment by sumbulAlvi** [comment]
Ahh yes, looking into parse, looks like it is expecting the encoded url string! And so will give the incorrect, decoded filepath in toString(). Thanks. Using `Uri.fromFile()` with the absolute filepath was the solution.

**Comment by TWiStErRob** [comment]
Note that you don't have to worry about all this if you pass the original absolute path String directly to `load`, Glide will load it correctly. The first three loads I quoted above are equivalent.
