### ISSUE TITLE
Issues with Glide making layout jump/create jarring effect 

### ISSUE THREAD

**Issue by GaryDoo** [bumptech/glide#871]
Hi,

I have a n application with a timeline, much the same as facebook.  My problem is in the timeline there are many images displayed in posts and these images are of all different sizes.  As they are different sizes it's very hard to have and adequate placeholder image created.  I have added a default one regardless but when the image loads, if it's height or width is less or more than that of the place holder I get the jarring/jumping effect on the timeline which looks terrible.

Is there anything I can do to combat this?

Regards, 
Gary

**Comment by TWiStErRob** [comment]
See #363, `.dontAnimate()` may help, or you can try using a 9-patch placeholder.

**Comment by GaryDoo** [comment]
Hi,  thanks for that.   I already have `.dontAnimate()` included

  //Display Images using Glide
    void displayGlideImage(IUserFeedContent feedContent, Uri imageUri,  ImageView imageView, TextView gifTag, int placeholder){

        DrawableRequestBuilder<Uri> request = Glide
                .with(view.getContext())
                .load(imageUri)
                        //.placeholder(placeholder)
                .dontAnimate()

                .diskCacheStrategy(DiskCacheStrategy.ALL);


        if(gifTag!= null) {
            if (ModelUtils.getMedia(feedContent).getMimeType().equals("image/gif")) {
                gifTag.setVisibility(View.VISIBLE);
                request.diskCacheStrategy(DiskCacheStrategy.SOURCE);
            } else {
                gifTag.setVisibility(View.GONE);
                request.diskCacheStrategy(DiskCacheStrategy.ALL);
            }
        }
        if(placeholder!=-1){
            request.placeholder(placeholder);
        }
        request.into(imageView);
    }

Can you explain what difference the 9-patch place holder would make to the issue? 

Thank you.

Regards, 
Gary

**Comment by TWiStErRob** [comment]
Hmm, if it is like #363 then the crossfade animation is making the images deformed. Theoretically (never tried it, sadly) a 9-patch would adapt to the size of the resulting image while crossFading, because it can be laid out in many sizes.

I checked the mobile Facebook webpage and they preset the sizes of `<IMG>` so they fit. Does getMedia has width/height so you can set the size of `ImageView` before loading into it?

Another option is to preload the images, so by the time the item becomes visible on screen the Bitmap is in memory -> no need for placeholder, except on really slow connections.

Yet another is to use a fixed size slot with centerCrop, that's the simplest.

I'm just throwing ideas. Can you describe the jumpiness in more detail (or GIf/video)?

**Comment by GaryDoo** [comment]
Hi...
That worked a treat.  I got the server lads to send down the height and width of the image and I've sized the image view accordingly...got a nine patch also and it's solved the issue.  Thanks
