### ISSUE TITLE
Use Glide cache for non-image files?

### ISSUE THREAD

**Issue by minimalviking** [bumptech/glide#872]
In my app I have a listview with thumbnails of images and videos. Upon row click, the image or video are opened in another fragment. I want to preload the full size images and videos so that opening would be faster. It works perfectly for images, in case of videos I tried to use: 
```java
Glide.with(getContext()).load(videoUrl).downloadOnly(new SimpleTarget<File>() {

	@Override
	public void onLoadFailed(Exception e, Drawable errorDrawable) {
		super.onLoadFailed(e, errorDrawable);
	}

	@Override
	public void onResourceReady(File resource, GlideAnimation<? super File> glideAnimation) {
			Glide.with(getContext()).load(resource).asBitmap().diskCacheStrategy(DiskCacheStrategy.SOURCE)
			.into(imageview);
	}
});
```
But it doesn't work - the second Glide call
```java
Glide.with(getContext()).load(resource).asBitmap().diskCacheStrategy(DiskCacheStrategy.SOURCE)
			.into(imageview);
```
fails and `onException` is called with null Exception.

The strange thing is that when I download the video file manually and pass it to glide, the thumbnail is loaded correctly.

Is there any I could download it with Glide and then use it?

**Comment by TWiStErRob** [comment]
You cannot load remote videos (#862), nor you can play any videos with Glide (#831), it needs to be a local File to load thumb successfully. Also look at the argument on #862 why it's a bad idea to use Glide's cache for videos.

---

You get `null` instead of an exception, because `BitmapFactory` returns a `null`, Bitmap, so there's actually no exception, but `onResourceReady` will never be called with a `null` resource so it's a failure, notice the log:
> D/skia: --- SkImageDecoder::Factory returned null

---

Regarding `SOURCE`: The cache key is different for the loaded videos, so it cannot hit the cache. Notice that you use `videoUrl` first and then `resource`, a `http://` VS `file://` there's no way for Glide to make the connection that they're the same. Notice that `load(videoUrl)` will cache the video file, and then when you load the File object it'll cache it again, so you'll end up with two copies of the video file in the cache. Since Glide doesn't even support remote videos, it doesn' try to decode anything as video if it is `SOURCE` cached (there's no point in copying a video to cache just to get the thumb from it). So your hack to work around the "no remote video supported" problem of Glide will work if you use the default `.diskCacheStrategy(RESULT)` (that is: remove the method call). I found this out by debugging `DecodeJob.cacheAndDecodeSourceData` which calls `loadFromCache` to decode using `cacheDecoder` which did not handle videos.

---

Glide is also not a networking library, I suggest you roll your own video-downloading based on OkHttp or Volley and then load those Files with Glide to get the thumbnail.

**Comment by arvi** [comment]
@TWiStErRob Hello, I've been stuck with this for hours already. I'm trying to create a thumbnail coming from our remote url e.g `https://myapp.com/uploads/testing.mp4`

When it's local file, this code has no issue:
```
Glide.with(mContext)
                .load(message)
                .into(mVideoThumbnailView);
```

Any suggestions? Thanks a lot.

I've read about the CustomModel / DataFetcher... and found this but can't understand Kotlin syntax... not really sure if it supports remote video preview. https://gist.github.com/stepango/5edcbdb408b0ba87f8383f868961c257

**Comment by TWiStErRob** [comment]
@arvi Try that Gist again, Kotlin is not that complicated to read: `fun` denotes a method, `methodName(args): RetType`, `?` means either a nullable type or a null-checked method invocation; `Unit` is `void` and `val`/`var` are fields/local variables with automatic types; `ClassName(args)` is `new ClassName(args)`.
