### ISSUE TITLE
images in ListView have different size(s), they would load in memory at the same time,so OOM!

### ISSUE THREAD

**Issue by Ddiaodehuali** [bumptech/glide#875]
images in ListView have different size(s), and ImageView is `android:layout_width="match_parent"` and `android:layout_height="wrap_content"` . As a result , when setAdapter for ListView, all images would load in memory at the same time, and OOM now!

Sorry for my poor English, thanks!

```xml
<ImageView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:scaleType="fitCenter" />
```

**Comment by TWiStErRob** [comment]
Please provide more info, see: https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues

In general phones have about twice as much memory size as screen size, so 2 screens worth of bitmaps can be loaded at once. There could be a memory leak, or the loading goes too big, this is why I'm asking for more info.

About that match-wrap, when you say all images, you literally mean all of them? It happened to me once that similar combo led to 0-height items, so all 20 items I had were inflated and loaded, and then after some jumping (layout changes after load due to wrap) it settled down. If this is what you see, try to put minHeight on the list items so only a few will be shown on setAdapter.

**Comment by Ddiaodehuali** [comment]
Thank you very much!
This is really the cause of OOM.Just because wrap_content, all items are 0-height,and all would be loaded into memory once when getView().
But, if I put a minHeight on the item and resize when image load ready,it would be jerk or flicker.
What should I do about it? Looking forward to your reply.Thanks again!

**Comment by TWiStErRob** [comment]
I would say: have fixed height items, sadly I've never come across a way of properly handling this. I think it's impossible to reach a pleasant user experience without knowing the image sizes beforehand. You can try querying/modifying the API you use to return the width/height along with URL.
