### ISSUE TITLE
It does not work when preload meets downloadOnly.

### ISSUE THREAD

**Issue by luxiaoyu** [bumptech/glide#880]
I found downloadOnly will flush activeResource of Engine and make items which have been preloaded out of activeResource.
Is there any way that make preload work with downloadOnly?
I want to do this, e.g.
1.preload [11, 20]
2.predownload [21, 30]

**Comment by TWiStErRob** [comment]
Active resources are ones which are shown in some view (more specifically delivered to some target, but not cleared yet). Both downloadOnly and preload should clear themselves after completion resulting in removing from actvive and adding to memory cache.

Can you please describe more, with code? I don't get those numbers.

**Comment by luxiaoyu** [comment]
There is a list of 50 items. And items [1, 10] (from 1 to 10) are visible.
I want to preload items [11, 20] (from 11 to 20), and predownload items [21, 30] (from 21 to 30)

my code :
https://gist.github.com/luxiaoyu/456c45a668b5223ffef0

**Comment by TWiStErRob** [comment]
Ah, you're using v4, right? Is this preloader forked from https://github.com/bumptech/glide/tree/master/integration/recyclerview ? Can you please also share the implemented `PreloadModelProvider` as it shows how the requests are crewted.?

**Comment by luxiaoyu** [comment]
The preloader I used is forked from https://github.com/bumptech/glide/blob/c2fc19316d8680322cabeed31234d19e942866e8/library/src/main/java/com/bumptech/glide/ListPreloader.java .I modify some function making it can work with RecyclerView.
I add the implemention of PreloadModelProvider to gist. https://gist.github.com/luxiaoyu/456c45a668b5223ffef0

**Comment by TWiStErRob** [comment]
So there's no `downloadOnly` involved in this one. If you want real predownload you should return something like: `requestManager.downloadOnly().load(item)` in `getPredownloadRequestBuilder`, no need for any `apply` calls there. You'll also need to change `into` to `submit` in `predownloadItem()`. If you want to reuse Targets, you can try manually creating `RequestFutureTarget` objects, but you'll need to review the code thoroughly to see if they're reusable.

Your version of downloadOnly is no different than the normal preload other than the priority. You explicitly requested `RESOURCE` caching which means that only the resized image will be saved, not the original. The `size` given to `override` is different in the two methods, so the predownload request is wasting resources in 3 places:
 * it downloads the full file to decode a Bitmap with a size that won't be used
 * it saves this file into disk cache
 * it doesn't save the origial file into cache

This means that when the user scrolls down the predownloaded items will be preloaded again by downloading the full file and saved into disk cache, now with the correct size, so when it comes to view it'll be shown.

Compare the above to the real `downloadOnly` solution which downloads the original file and saves it into disk. Then the user scrolls down and the preloader loads the properly sized image from disk cache and saves it with the right size. When it comes into view it either hits memory cache or loads the sized image. You'll need to add `ALL` instead of `RESOUCE` to preload so that it can read the `DATA` cache that was populated by `downloadOnly`.

I hope the above makes sense. Feel free to argue with anything as I didn't try this, just read your code.

**Comment by eicm** [comment]
I have a semi similar question:

load line:
     requestManager
.load(mediaPath)
.placeholder(R.drawable.bg_dark_grey)
.centerCrop()
.thumbnail(requestManager.load(thumbPath).centerCrop().Override(T_WIDTH, T_HEIGHT).into(imageView))
.animate(R.anim.fade_in_300)
.override(R_WIDTH, R_HEIGHT)
.into(imageView);

    @Override
    public GenericRequestBuilder getPreloadRequestBuilder(MediaData item) {
        return requestManager
.load(thumbPath)
.centerCrop()
.diskCacheStrategy(DiskCacheStrategyNONE);
    }

    @Override
    public int[] getPreloadSize(MediaData item, int adapterPosition, int perItemPosition) {
        return getMediaLoadSize(new int[] {T_WIDTH, T_HEIGHT);
    }

Does prelaod here for thumbnails hits the memory cache?

**Comment by TWiStErRob** [comment]
@eicm I reformatted your code, notice that it wouldn't compile at multiple points; most eye-catching thing is: `thumbnail(...into)` that shouldn't work. Ignoring these I think it should work. The `diskCacheStrategy` is NONE for preload request, but is RESULT for the real request... so it will be saved into cache if the memory cache is not hit, you may be better off always saving it; this shouldn't affect memory caching though as far as I know.

Refer to the [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) to find out if you hit memory cache or not.

**Comment by eicm** [comment]
@TWiStErRob I was writing the snippet of memory out of curiosity. Another question regarding the size multiplier:
Consider the above example but this time we load thumbnail using the size multiplier " .thumbnail(0.4) "
now my preload size would be:
@Override
public int[] getPreloadSize(MediaData item, int adapterPosition, int perItemPosition) {
    return getMediaLoadSize(new int[] {(int) (0.4 * R_WIDTH), (int) (0.4 * R_HEIGHT));
}

is this correct?

**Comment by TWiStErRob** [comment]
See `GenericRequest.onSizeReady` why it would work only sometimes.

**Comment by eicm** [comment]
@TWiStErRob thanks

**Comment by TWiStErRob** [comment]
@luxiaoyu you went real silent so I assume you solved the issue, feel free to ask more if you need to.
