### ISSUE TITLE
Loading an image from Disk Cache takes too long

### ISSUE THREAD

**Issue by JulienChene** [bumptech/glide#893]
Hello,

I'm currently using Glide to retrieve images from network. Obviously, the first time I retrieve one, it takes some time to download the picture.
However, I'm encountering problems when I want to reload them a second time as it takes around 100ms to load the image any other time (except when the image is loaded from memory).

Hereunder some logs I took:
```java
GLIDE DEBUG﹕ Loading contact picture: 99ms
GLIDE DEBUG﹕ Is image from memory?    false
GLIDE DEBUG﹕ Byte count for bitmap:   2981888
GLIDE DEBUG﹕ Bitmap size: 728x1024
```

And here when it comes from memory
```java
GLIDE DEBUG﹕ Loading contact picture: 17ms
GLIDE DEBUG﹕ Is image from memory?    true
GLIDE DEBUG﹕ Byte count for bitmap:   2981888
GLIDE DEBUG﹕ Bitmap size: 728x1024
```

This comes from here:
```java
final long startTime = System.nanoTime();
Glide.with(context)
    .load(this.imageUrl)
    .bitmapTransform(new BlurTransformation(context))
    .diskCacheStrategy(DiskCacheStrategy.ALL)
    .listener(new RequestListener<String, GlideDrawable>()
    {
        @Override
        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource)
        {
            return false;
        }

        @Override
        public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource)
        {
            long endTime = System.nanoTime();
            long duration = (endTime - startTime);
            Bitmap bitmap = ((GlideBitmapDrawable) resource).getBitmap();
            Log.d("GLIDE DEBUG", "----");
            Log.d("GLIDE DEBUG", "Loading contact picture: " + (duration / 1000000) + "ms");
            Log.d("GLIDE DEBUG", "Is image from memory?    " + isFromMemoryCache);
            Log.d("GLIDE DEBUG", "Byte count for bitmap:   " + bitmap.getByteCount());
            Log.d("GLIDE DEBUG", "Bitmap size: " + bitmap.getWidth() + "x" + bitmap.getHeight());

            return false;
        }
    })
.into(this);
```

I am aware that retrieving from disk has to be slower than retrieving from disk. However, I was wondering if that was normal, or if there was something I could do to make this load faster, as we first wanted to avoid this loading time by caching the image.

As you could guess, this code is within a class that extends `ImageView`, and its 728x1024 size is the one it should take in order to cover the whole screen.
One other thing is that I load another image about the same size with a `File`, and it is instantaneous.

I'm not sure this is an issue, but I wanted to make sure that was a regular loading time for an image this size. And if not, know what step I could take to make it work faster.

Thank you.

**Comment by TWiStErRob** [comment]
* Are your running your app with debugger attached?
(that can slow things down a lot, esp with lot of breakpoints (even if not hit))
* Are you loading only a single image when you're testing?
* The time may also include all the class loading and Glide setup (#299) if this the only thing that happens in the app. Try starting the counter after `Glide.with(context)` (extract variable) or simply make it repeatable and measure multiple times.
* Double-check if Blur is being called or not (override the transformation method in an anon inner class and log); if yes it means you're not hitting the RESULT cache, but only SOURCE cache.
* You can also enable Glide's internal logging to see the timings and cache hits/misses, see the [wiki](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling)

You may be also interested in #731.

**Comment by SnakerXV** [comment]
• What's the device and OS?
Running on a Nexus 9 and 5.0.2

• Are your running your app with debugger attached? (that can slow things down a lot, esp with lot of breakpoints (even if not hit))
No, every log was made with no debugger attached

• Are you loading only a single image when you're testing?
I'm also loading another image with smaller dimensions. This one is loading immediately when the view is loaded (~10-20ms).

• The time may also include all the class loading and Glide setup (#299) if this the only thing that happens in the app. Try starting the counter after Glide.with(context) (extract variable) or simply make it repeatable and measure multiple times.
Apparently, Glide is already setup as I logged several times, and I always had the same timing:

```
        Log.d("GLIDE DEBUG", "----");
        this.imageUrl = imageUrl;
        final long startTime = System.nanoTime();
        RequestManager requestManager = Glide.with(context);

        final long glideLoadedStartTime = System.nanoTime();
        requestManager.load(this.imageUrl)
                .dontAnimate()
                .bitmapTransform(new BlurTransformationTest(context))
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .listener(new RequestListener<String, GlideDrawable>()
                {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource)
                    {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource)
                    {
                        long endTime = System.nanoTime();
                        long duration = (endTime - startTime);
                        long retrievingImageDuration = endTime - glideLoadedStartTime;
                        Bitmap bitmap = ((GlideBitmapDrawable) resource).getBitmap();
                        Log.d("GLIDE DEBUG", "Init & loading picture : " + (duration / 1000000) + "ms");
                        Log.d("GLIDE DEBUG", "Loading picture:         " + (retrievingImageDuration / 1000000) + "ms");
                        Log.d("GLIDE DEBUG", "Is image from memory?    " + isFromMemoryCache);
                        Log.d("GLIDE DEBUG", "Byte count for bitmap:   " + bitmap.getByteCount());
                        Log.d("GLIDE DEBUG", "Bitmap size:             " + bitmap.getWidth() + "x" + bitmap.getHeight());

                        return false;
                    }
                })
            .into(this);
```

And what I'd usually get:

```
GLIDE DEBUG﹕ Init & loading picture : 131ms
GLIDE DEBUG﹕ Loading picture:         131ms
```

• Double-check if Blur is being called or not (override the transformation method in an anon inner class and log); if yes it means you're not hitting the RESULT cache, but only SOURCE cache.
This point is getting interesting because whenever the image is not loaded from Memory Cache, I get a log from the transformation method.
So if I get it right, the RESULT is being cached in Memory, but not in Disk ?

Makes me think it could come from the place I try to store the information ?
```
@Override
    public void applyOptions(Context context, GlideBuilder builder)
    {
        String cacheDirectory = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/" + CACHE_DIRECTORY + "/").getAbsolutePath();

        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
        builder.setDiskCache(new ExternalCacheDiskCacheFactory(context, cacheDirectory, DISK_CACHE_SIZE));
    }
```

I did check if the [External Directory was writable](http://stackoverflow.com/questions/7616974/how-to-check-internal-and-external-storage-if-exist)

```
External storage available: true
External storage writable : true
```

• You can also enable Glide's internal logging to see the timings and cache hits/misses, see the wiki
So I did enable Glide's internal logging and here's what I get:

```
D/GLIDE DEBUG﹕ ----
/**************************************
// Loading of medium sized avatar
**************************************/
V/Engine﹕ Started new load in 0.126583ms, key: EngineKey{avatar_url/medium.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[-2147483648x-2147483648]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}

V/DecodeJob﹕ Decoded transformed from cache in 8.577167, key: EngineKey{avatar_url/medium.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[-2147483648x-2147483648]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}

V/DecodeJob﹕ Transcoded transformed from cache in 0.01075, key: EngineKey{avatar_url/medium.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[-2147483648x-2147483648]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}

/**************************************
// Loading of large sized avatar: This is the one that's being blurred.
**************************************/
V/Engine﹕ Started new load in 0.0815ms, key: EngineKey{avatar_url/large.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[2048x1440]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

V/DecodeJob﹕ Decoded source from cache in 22.925417, key: EngineKey{avatar_url/large.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[2048x1440]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

D/GLIDE DEBUG﹕ ~~~Blur transformation being called~~~
V/RenderScript_jni﹕ RS native mode
V/RenderScript﹕ 0xab8abeb8 Launching thread(s), CPUs 2

V/DecodeJob﹕ Transformed resource from source in 265.133333, key: EngineKey{avatar_url/large.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[2048x1440]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

V/DecodeJob﹕ Transcoded transformed from source in 0.01975, key: EngineKey{avatar_url/large.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[2048x1440]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

D/GLIDE DEBUG﹕ Init & loading picture : 309ms
D/GLIDE DEBUG﹕ Loading picture:         309ms
D/GLIDE DEBUG﹕ Is image from memory?    false
D/GLIDE DEBUG﹕ Byte count for bitmap:   4194304
D/GLIDE DEBUG﹕ Bitmap size:             1024x1024
```

**Comment by SnakerXV** [comment]
Sorry, I just realized I had set the Disk Caching Strategy to SOURCE for a few tests, including the ones I showed you.
Please do not refer to those.

I reran those the tests setting `DiskCacheStrategy.ALL`

Here it goes:

```
D/GLIDE DEBUG﹕ ----

V/Engine﹕ Started new load in 0.091166ms, key: EngineKey{https://s3.amazonaws.com/api-dev-insensi-fr/avatars/users/7e32413b-cc6f-4c2d-8d21-6cc5b661694a/medium.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[-2147483648x-2147483648]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}

V/DecodeJob﹕ Decoded transformed from cache in 7.0625, key: EngineKey{https://s3.amazonaws.com/api-dev-insensi-fr/avatars/users/7e32413b-cc6f-4c2d-8d21-6cc5b661694a/medium.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[-2147483648x-2147483648]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}

V/DecodeJob﹕ Transcoded transformed from cache in 0.014332999999999999, key: EngineKey{https://s3.amazonaws.com/api-dev-insensi-fr/avatars/users/7e32413b-cc6f-4c2d-8d21-6cc5b661694a/medium.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[-2147483648x-2147483648]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+''+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+''+''}


V/Engine﹕ Started new load in 0.086167ms, key: EngineKey{https://s3.amazonaws.com/api-dev-insensi-fr/avatars/users/7e32413b-cc6f-4c2d-8d21-6cc5b661694a/large.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[2048x1440]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

V/DecodeJob﹕ Decoded transformed from cache in 62.258832999999996, key: EngineKey{https://s3.amazonaws.com/api-dev-insensi-fr/avatars/users/7e32413b-cc6f-4c2d-8d21-6cc5b661694a/large.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[2048x1440]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

V/DecodeJob﹕ Transcoded transformed from cache in 0.023166, key: EngineKey{https://s3.amazonaws.com/api-dev-insensi-fr/avatars/users/7e32413b-cc6f-4c2d-8d21-6cc5b661694a/large.jpeg+com.bumptech.glide.signature.EmptySignature@1c3be1ec+[2048x1440]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

D/GLIDE DEBUG﹕ Init & loading picture : 83ms
D/GLIDE DEBUG﹕ Loading picture:         83ms
D/GLIDE DEBUG﹕ Is image from memory?    false
D/GLIDE DEBUG﹕ Byte count for bitmap:   4194304
D/GLIDE DEBUG﹕ Bitmap size:             1024x1024

```

**Comment by TWiStErRob** [comment]
> D/GLIDE DEBUG﹕ Loading picture:         309ms

So the blur is taking it's toll when not cached, as expected. This is where adding RESULT caching gives you a big win.

> Makes me think it could come from the place I try to store the information?

Do you mean that the external disk may be slower than the internal? It's possible. I don't know the build of N9, but my S4 has only one internal storage which is partitioned and mounted as a fake external one as well. And it counts towards the same quota, so on S4 it doesn't matter where you put the caches (except the external one is visible to the user).

> "from cache in 7", "from cache in 62", "Loading picture: 83ms"

So we have the following:

||Medium|Large|
|---------|----------|-------|
|source size|512px|1024px|
|decode RESULT cache|7ms|62ms|
|others|<1 ms|<1 ms|
|unaccounted for|not timed|10ms|

The `62ms` is the time spent in `BitmapFactory`, see `Downsampler.decode`.

You can check what the "unaccounted for" is, if you diff the time of the last Glide internal log VS your first `GLIDE DEBUG`, it's likely posting the result from the background thread to the UI thread.

---

There's the difference beteween medium and large size, which is huge, considering that the image area is only 4x bigger. Sadly I can't explain that, but I don't think that number comparable anyway, because the medium is not blurred.

---

Assume that your timings are representing the median well, in which case decoding `1024px`:
 * from `SOURCE` takes `22ms` (from your measurement mistake)
 * from `RESULT` takes `62ms` (from the correct measure)

This is really strange, because it's the same size and even if wrapping the InputStream in many layers degrades performance, the same wrapping (`Downsampling` is done in both cases, but for RESULT cache it should be `inSampleSize = 1`) is applied to both SOURCE and RESULT cache. So... why else could it be slow? the file must be bigger. Why would the file be bigger? Too high quality, or different format. Luckily you included your `GlideModule` above which sets `PREFER_ARGB_8888` meaning decoded images (JPG or PNG source) may be cached as PNG in `RESULT`! I'm not sure if they do, it depends on whether `BitmapFactory` returns an image that `hasAlpha` (see `BitmapEncoder`). Please try to remove that `setDecodeFormat` line to see if it makes a difference; but before that maybe check the cache contents if the files there are in JPG or PNG format.

If this is the culprit using `SOURCE` cache only should speed things up, the problem is your blur which cannot be cached in that case.

---

(*You didn't clean the second batch of logs, I cleaned it for you.*)

**Comment by SnakerXV** [comment]
Thank you so much for your exhaustive answer ! I'll try this all out and let you know how I'm doing.

**Comment by SnakerXV** [comment]
Hey, I ran the same tests on another device with a lower configuration and here are the times I come up with:

Loading argument | URL | File
------------ | ------------- | ------------- 
DiskCacheStrategy | ALL | ALL
Blur | YES | YES
Decode result cache | 292 ms | 2 ms
Others | <1 ms | <1 ms
Unaccounted for | 28 ms | 52 ms
Total time | 320 ms | 54 ms

And here are the logs for it:

### URL
```
D/GLIDE DEBUG﹕ ----

V/Engine﹕ Started new load in 0.23066699999999998ms, key: EngineKey{avatar_url/large.jpeg+com.bumptech.glide.signature.EmptySignature@2c98e7d0+[1024x768]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

D/dalvikvm﹕ GC_FOR_ALLOC freed 3178K, 42% free 9553K/16280K, paused 18ms, total 18ms
I/dalvikvm-heap﹕ Grow heap (frag case) to 12.702MB for 3473424-byte allocation
D/dalvikvm﹕ GC_FOR_ALLOC freed 3K, 21% free 12941K/16280K, paused 16ms, total 16ms

V/DecodeJob﹕ Decoded transformed from cache in 292.544667, key: EngineKey{avatar_url/large.jpeg+com.bumptech.glide.signature.EmptySignature@2c98e7d0+[1024x768]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

V/DecodeJob﹕ Transcoded transformed from cache in 0.10099999999999999, key: EngineKey{avatar_url/large.jpeg+com.bumptech.glide.signature.EmptySignature@2c98e7d0+[1024x768]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'BlurTransformation(radius=25, sampling=1)'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}

D/GLIDE DEBUG﹕ Init & loading picture : 320ms
D/GLIDE DEBUG﹕ Loading picture:         319ms
D/GLIDE DEBUG﹕ Is image from memory?    false
D/GLIDE DEBUG﹕ Byte count for bitmap:   3473408
D/GLIDE DEBUG﹕ Bitmap size:             848x1024
D/GLIDE DEBUG﹕ Bitmap has alpha?        true
```

I retrieved this data using RGB_555

### File
```
D/GLIDE DEBUG﹕ ----

D/GLIDE DEBUG﹕ Init & loading picture : 54ms
D/GLIDE DEBUG﹕ Loading picture:         54ms
D/GLIDE DEBUG﹕ Is image from memory?    true
D/GLIDE DEBUG﹕ Byte count for bitmap:   1572864
D/GLIDE DEBUG﹕ Bitmap size:             1024x768
D/GLIDE DEBUG﹕ Bitmap has alpha?        false

V/Engine﹕ Loaded resource from active resources in 1.8619999999999999ms, key: EngineKey{file:///path_to_file+com.bumptech.glide.signature.EmptySignature@2c957a18+[1024x768]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'CenterCrop.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
```

One additional question I have is: Why does it take so much less time to load an image from a `File` ?

**Comment by TWiStErRob** [comment]
Loading from active resources means it was a sync load. No network, nor disk, likely not even a UI dispatch; "is image from memory" also confirms this.

That "bitmap has alpha" is weird though if you have 565 enabled, it means it was loaded as 8888 still. Note that if you didn't clear the cache you're likely loading the previously saved PNG file, because 565 VS 8888 is not part of the cache key as you can see in the logs. You need to reinstall or `Glide.get(context).clearDiskCache()` on a background thread.
