### ISSUE TITLE
Gif animation in recyclerview stop playing after scrolling

### ISSUE THREAD

**Issue by zahid-ali-shah** [bumptech/glide#899]
Gif animation in **recyclerview** stop playing after scrolling and if i scroll again two or three times animation automatically starts again. This problem doesn't occur always. I am using glide 3.7.0-SNAPSHOT. I am using glide in code like this:

``` java
Glide.with(context)
                .load(MyApp.INSTANCE.getUser().getUserAvatar())
                .fitCenter()
                .centerCrop()
                .thumbnail(0.1f)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .placeholder(R.drawable.ic_profile_picture)
                .into(holder.imageView); 
```

Am I doing something wrong ?

**Comment by TWiStErRob** [comment]
The only thing that pops out is fitCenter/centerCrop, you can't apply both, because it overwrites, but it doesn't make any difference if you remove fitCenter.

How fast do you scroll back and forth? How far do you scroll from the GIF? Can you post a video? Can you please try to make a repro app where it happens most of the time? You could try without placeholder or thumbnail, maybe add dontAnimate. These sometimes offer a not so nice workaround.

You should remember that recycler view recycles the items so when you scroll a gift out, it'll be actually cleared and overwritten with another image. So your description sounds like: "memory cached GIFs are not started again sometimes".

Actually, since you're using thumbnail, is it possible you're seeing the thumbnail for a long time when "gif stops playing"? You could try to add listeners to both the main load and thumbnail and [log](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener) what's happening. Alternatively you could add some effect to the thumbail, like color filter or flip it upside down transformation to distinguish it.

**Comment by LNeway** [comment]
@TWiStErRob 

Hello , I have the same when I  use recyclerview and glide.

that is my code in onBindView 

`   Glide.with(fragment).load(gifImage).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(imageView);`

I will try to load the gifs ( 100+ ) from the internet , after the first part load successfully , I  scroll the 
recyclerview , then all the gifs which plays normal will stop. after the the second part load successfully , all the gifs will play normal again.

Do you have any suggestion about this issue ?  thank you very much!!!

**Comment by mlostekk** [comment]
Same issue here. Any suggestions?

**Comment by sjudd** [comment]
What networking library are you using?

**Comment by mlostekk** [comment]
I am using retrofit2. What is glide using internally?

**Comment by feng88724** [comment]
Same issue here. Any suggestions?

**Comment by GokhanArik** [comment]
I had the same problem today and mine was caused by a 3rd party LayoutManager we were using. After switching to the LinearLayoutManager it started working properly.
