### ISSUE TITLE
Modify cache and allow changing the value 

### ISSUE THREAD

**Issue by preetb123** [bumptech/glide#906]
I need a functionality where i need to check if the image exists in the cache, then replace that image with a new image.

I.e.

1. Take image from the device and apply it on the imageview. This image will be added to the cache with key as local uri(`file://etc....` OR `content://.....`)

    ```java
    cache.put(absolute path of the file, decoded image);
    ```
2. This image is then uploaded to the server and server gives me a new url where the image is stored.(eg. https://aws.amazon.com/........png).  After this i need to update the cache for this image and change the key with the url received.

    ```java
    cache.put(image url, decoded image);
    ```
3. I also should be able to remove an item from the cache.

This features are present in Universal image loader and Fresco library, but for many other reasons i like Glide and keep using it. It would be really nice to have this api.

**Comment by TWiStErRob** [comment]
1. There's no problem here as I see, just load the image, you can turn off caching the result (`diskCacheStrategy(NONE)`) because as I see it'll only be used once while the image uploads, so no point in caching
 2. After the upload use the given url to replace the image in the imageview (this time using the cache). This is equivalant to `cache.put(image url, decoded image)`, however it will re-download the image.
 3. The disk cache in Glide is an LRU cache, it manages itself, just leave the image there and it'll be evicted eventually. If you want you can lower the cache size to make it happen faster, but then you may risk re-downloading images that are really used; all this depends on your app's usage of images.

If you want to overwrite a cached image from the same url, use the `.signature()` API.

See also the [numerous issues](https://github.com/bumptech/glide/issues?utf8=%E2%9C%93&q=is%3Aissue+remove+cache+) related to this.

There's also #509 as tracking issue for `cache.contains()`.

**Comment by preetb123** [comment]
if i already have an image, why should i re-download it? Image should be downloaded only if it is not already in cache. I just want to use the previously decoded image with the new image_url that i received. 
This is very efficient, as it'll prevent the unnecessary network and memory usage, as downloaded image again needs to be decoded to show in the imageview.

**Comment by TWiStErRob** [comment]
As for the redownload, it is assumed that the server is the authority on what the URL contains. And after upload it may even change the image (resize, color correct, ...). Does this use case happen a lot for you? It sounds like a profile picture update flow, so a quarterly or once per life redownload shouldn't be a biggie.

That's just how the cache works, everything is hashed so it's almost impossible to find the key to replace. You're free to implement your own disk cache and set it up with GlideModule (see GlideBuilder for defaults). You can try to create a Key to match the SOURCE cache key and manually write the image via `StreamBitmapEncoder` (not sure on the exact name) so that next time Glide tries to load that remote URL it hits the cache. For this to happen you need to mimic how the Glide `Engine` writes to the cache. To hit this written image your load must have SOURCE or ALL `.diskCacheStrategy()`.

**Comment by preetb123** [comment]
The usecase is just like posting a new photo for a post as it is done in G+, instagram, tumblr etc. It's a must. Is there any other hacky way instead of writing my own cache and have it pluggedin via GlideBuilder?

**Comment by TWiStErRob** [comment]
Ah, that's more frequent then... you don't necessarily need to write your own cache, just configure it so you have a reference to it when you want to `cache.put` because there's no `Glide.get().getDiskCache()` as far as I remember. I was curious so I did it quickly:

```java
builder.setDiskCache(new StealingDiskCacheFactory(new InternalCacheDiskCacheFactory(context)));

Glide
	.with(this)
	.load(userSelectedImage)
	.asBitmap()
	.diskCacheStrategy(DiskCacheStrategy.NONE)
	.override(2000, 2000) // size of the image to upload
	.dontTransform()
	.listener(new RequestListener<Uri, Bitmap>() {
		@Override public boolean onResourceReady(Bitmap resource, Uri model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
			upload(resource); // start uploading after we've shown the image to the user
			return false;
		}
	})
	.into(imageView)
;

private void upload(Bitmap resource) {
	new AsyncTask<Bitmap, Void, String>() {
		@Override protected String doInBackground(Bitmap... params) {
			Bitmap bitmap = params[0];
			String url = "https://aws.amazon.com/........png";
			// TODO upload bitmap to cloud and get a resulting url
			// placeholder is there to show that it works even with a malformed non-existent url
			cache(url, bitmap);
			return url;
		}
		@Override protected void onPostExecute(String url) {
			// this is optional really, because the imageView is already showing the same bitmap
			// it may be a good thing though to load the image in a smaller size so less memory is consumed
			Glide
				.with(TestFragment.this)
				.load(url)
				.diskCacheStrategy(DiskCacheStrategy.ALL) // must allow SOURCE to hit the just-cached image
				.into(imageView)
			;
		}
	}.execute(resource);
}

private void cache(String url, final Bitmap bitmap) {
	Key key = new StringSignature(url);
	// the key here is that Engine uses fetcher.getId() for constructing OriginalKey from EngineKey
	// see Engine.load and also signature can be ignored because it is an EmptySignature instance for most
	App.getInstance().getDiskCache().put(key, new Writer() {
		@TargetApi(VERSION_CODES.KITKAT) // for try-with-resources
		@Override public boolean write(File file) {
			try (OutputStream out = new FileOutputStream(file)) {
				// mimic default behavior you can also use Bitmap.compress
				BitmapResource resource = BitmapResource.obtain(bitmap, null);
				new BitmapEncoder().encode(resource, out);
				return true;
			} catch (IOException e) {
				e.printStackTrace();
				return false;
			}
		}
	});
}

public class StealingDiskCacheFactory implements DiskCache.Factory {
	private final DiskCache.Factory factory;
	public StealingDiskCacheFactory(Factory factory) {
		this.factory = factory;
	}
	@Override public DiskCache build() {
		DiskCache cache = factory.build();
		App.getInstance().setDiskCache(cache);
		return cache;
	}
}
```

**Comment by preetb123** [comment]
Thanks a lot @TWiStErRob 

Below code was giving `Bitmap pool cannot be null` error

`BitmapResource resource = BitmapResource.obtain(bitmap, null);
                            new BitmapEncoder().encode(resource, out);
                            return true;`

Got it working with 

App.getInstance(ServiceInfoActivity.this).getDiskCache().put(key, new DiskCache.Writer() {
                    @Override
                    public boolean write(File file) {
                        FileOutputStream out = null;
                        try {
                            out = new FileOutputStream(file);
                            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out);
                        } catch (FileNotFoundException e) {
                            e.printStackTrace();
                            return false;
                        } finally {
                            if(out != null){
                                try {
                                    out.close();
                                } catch (IOException e) {
                                    e.printStackTrace();
                                    return false;
                                }
                            }
                        }
                        return true;
                    }
                });

public class App extends GlideBuilder{
    private static App sBuilder;
    private DiskCache mDiskCache;

    public App(Context context) {
        super(context);
    }

    public static App getInstance(Context context) {
        if(sBuilder == null){
            sBuilder = new App(context);
        }
        return sBuilder;
    }

    @Override
    public GlideBuilder setDiskCache(DiskCache diskCache) {
        this.mDiskCache = diskCache;
        return super.setDiskCache(diskCache);
    }

    public DiskCache getDiskCache(){
        return mDiskCache;
    }
}

**Comment by preetb123** [comment]
@TWiStErRob  I am doubtful about whether this bitmap will be added to the `BitmapPool` and whether Glide will be able to reuse this bitmap?

**Comment by TWiStErRob** [comment]
The Bitmap will be reused because it's life cycle is handled by the load in the original targe, remember that we just stole it for a moment to save it. If you decide not to reload in `onPostExecute` you may want to call `Glide.clear(imageView)` to force an early reuse. It really depends on how your application works. Even if you don't call, upon destroy of the context/fragment passed to `Glide.with` it'll be ready to be reused automatically.

You can always get a pool from: `Glide.get(context).getBitmapPool()`. I didn't supply it because that resource is temporary and shouldn't mess with the Bitmap's life cycle. But if it's mandatory to create a resource then you obviously need it, it'll be probably fine.  I don't know how I missed it, I tried the code. Using the encoder is better because it handles transparency effectively. Saving any random image as PNG is really wasteful, just try taking a photo outside with a camera and save it as PNG to see the difference.

App should `extend android.app.Application` or nothing. The rest you got right. You can init the instance field in the constructor or onCreate via `this`. Only one will be created if you set the `<application android:name=".App"` in the manifest. It really doesn't matter where you store the disk cache, but it needs to be static so the cache factory can access it. The app context singleton is a good candidate.

**Comment by TWiStErRob** [comment]
Let me know if you need further clarifications.

**Comment by preetb123** [comment]
Getting the below error when i use this in android library.
 `java.lang.NullPointerException: Attempt to invoke interface method 'void com.bumptech.glide.load.engine.cache.DiskCache.put(com.bumptech.glide.load.Key, com.bumptech.glide.load.engine.cache.DiskCache$Writer)' on a null object reference`

**Comment by TWiStErRob** [comment]
Who is calling the method? (first few lines of stack trace). If it's the `cache` method I quoted above you likely didn't execute any loads before so the Glide singleton is not initialized yet. You may need to call `Glide.get(this)` in `App.onCreate` so the `GlideModule`s are executed.

**Comment by xizzhu** [comment]
@TWiStErRob in comment https://github.com/bumptech/glide/issues/906#issuecomment-173221063, in the `cache` method:
> Key key = new StringSignature(url);
>     // the key here is that Engine uses fetcher.getId() for constructing OriginalKey from EngineKey
>     // see Engine.load and also signature can be ignored because it is an EmptySignature instance for most

But as far as I can see, when `DiskLruCacheWrapper.get()` is using `SafeKeyGenerator.getSafeKey()` to generate the key for `DiskLruCache`, the generated `safeKey` is different. The reason is that the `updateDiskCacheKey()` methods in `StringSignature` is quite different from the one in `EngineKey`. Can you shed some light on if I'm doing something wrong, and how to work around this?

Thanks.

**Comment by TWiStErRob** [comment]
The above hack only works for SOURCE cache, because OriginalKey is so simple, EngineKey is not involved. I guess if you write your own EngineKey mirror it may be possible to do it for RESULT as well, but it's always worth considering the non-hacky signature API.

Above I wrote that you can use ALL, but now I think that would lead to inconsistent results. So use `.diskCacheStrategy(SOURCE)` with this hack.

**Comment by xizzhu** [comment]
`.diskCacheStrategy(SOURCE)` does the trick, thanks a lot!

**Comment by ShreyashPromact** [comment]
@preetb123 
Can you please Explain the flow of saving the image to cache before/after uploading it. I am not very clear with the code you have mentioned above in your reply. Also, DiskCache is deprecated. So is there any alternative to it?
Please reply.

Thanks.
