### ISSUE TITLE
How can i load the GIF without animation

### ISSUE THREAD

**Issue by billy2271** [bumptech/glide#908]
how can i stop the animation? If the file type must be GIF.

**Comment by TWiStErRob** [comment]
`.load().asBitmap()` will load the first frame. This is the most effective.

Otherwise check how `GlideDrawableImageViewTarget` starts the drawable: you can extend that class and stop it immediately after super starts it and use `into(new MyStoppedGDIVT(imageView))` instead of `into(imageView)`. You'll also need to explicitly apply a transformation (centre crop or fit center). Note that this version still loads all the GIF bytes into memory, even though only the first frame will be displayed. You may be able to display any frame by programmatically advancing the drawable.

**Comment by billy2271** [comment]
@TWiStErRob I'll try it. Thanks!!!

**Comment by TWiStErRob** [comment]
If you want to start/stop on user request: load as normal (or force with `asGif()`) and in a click listener:
```java
Animatable gif = (Animatable)imageView.getDrawable();
if(! gif.isRunning()) gif.start(); else gif.stop();
```

**Comment by iielse** [comment]
@TWiStErRob i want to play gif animation just one time. How should I do

**Comment by TWiStErRob** [comment]
@iielse As far as I know there's a way to tell repetition count inside the GIF format, so if you have control over the files, export it with repeat=0 instead of infinite.
Otherwise Glide doesn't give you listeners for GIF events so you may have to look around for a specialised GIF library or you can try to make something work based on #446 (It looks like it's only in 4.0 snapshot, see wiki).
