### ISSUE TITLE
Padded dynamic sized ImageViews load low-quality blured images

### ISSUE THREAD

**Issue by sant527** [bumptech/glide#939]
I am using glide for my android project.

I am using `compile 'com.github.bumptech.glide:glide:3.6.1'` in build.gradle

I have the following imageview.xml used for displaying images in recyclerview

``` xml
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:padding="2dp"
```

Now all my images in my recyclerview show blurry.

I am using the following glide code:

``` java
Glide.with(personViewHolder.itemView.getContext()).load(images.get(i)).into(personViewHolder.place_image);
```

**Comment by TWiStErRob** [comment]
Does it show better images with other layouts?

**Comment by sant527** [comment]
yes. even in the gridlayout also
GridLayoutManager glm = new GridLayoutManager(rvgallery.getContext(),2,GridLayoutManager.VERTICAL,false);

**Comment by TWiStErRob** [comment]
Can you share one of those images?
Can you please post a screenshot (feel free to black out stuff)?

**Comment by sant527** [comment]
![glide1](https://cloud.githubusercontent.com/assets/6462531/12677113/94531a58-c68e-11e5-8a25-77baa93cf144.jpg)

**Comment by TWiStErRob** [comment]
Wow, that's really bad... it looks like Glide is reading the incorrect size from the ImageView and loads a roughly 8x8 image. Try to remove the padding to see if that helps. If it works without padding you can achieve the same effect with `layout_margin` without messing with Glide.

Giving fixed height might also help, but it wouldn't play nice with staggered layout.

Yet another option is to use something like `.override(half screen, half screen)` which will help with `wrap_content` and staggered view.

**Comment by sant527** [comment]
remove padding means
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"

**Comment by TWiStErRob** [comment]
Yes, or `0dp`.

**Comment by sant527** [comment]
yes, it shows the images properly. But i want some gap all around the image. what will be the suitable way to do

**Comment by sant527** [comment]
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:adjustViewBounds="true"
android:layout_margin="2dp"

then it works. margin works than padding

**Comment by TWiStErRob** [comment]
Thanks for confirming the workaround. Let's leave this open in case we can add support for padding.

**Comment by sjudd** [comment]
Just to double check my understanding - this happens because Glide checks the view width and height on an empty and sees they are set to whatever the padding is? 2dp in this case?

So the request would be that we ignore the view width and height entirely I think and rely instead on the layout_width and layout_height attributes in the view's layout params. We probably should be doing that for every case except match_parent?

**Comment by TWiStErRob** [comment]
Yes, Glide reads 2dp (or 2x2dp) height and loads a very small image. Your suggestion sounds reasonable, but it could be problematic because it's not a law that `layout_<size> == get<Size>()`, any parent can constrain the size. I'm pretty sure putting a 5000dp sized view in a FrameLayout would lay it out just like `match_parent`, in which case Glide would lose it's ability to load a "pixel-perfect" Bitmap. I think it may be a better approach to conditionally ignore the `get<Size>()` when there's padding on that axis, or just simply always take padding into account with the same math that is used in ImageView.

**Comment by devlee-team** [comment]
When do you plan to fix it?

**Comment by TWiStErRob** [comment]
You can try this in [`4.0.0-SNAPSHOT`](https://github.com/bumptech/glide/wiki/Snapshots) before v4 is released.
