### ISSUE TITLE
Unable to load entire Image in image view.

### ISSUE THREAD

**Issue by MAnfal** [bumptech/glide#953]
I am trying to load image from a URL in Image view but because Glide maintains the aspect ratio by default I can't seem to display my entire Image in the view.

Following is my Image View

```xml
<ImageView
    android:layout_width="match_parent"
    android:layout_height="262dp"
    android:layout_alignParentTop="true"
    android:adjustViewBounds="true"
    android:scaleType="fitCenter"
    android:layout_centerHorizontal="true"/>
```

I have tried following methods.

```java
Glide.with(context)
     .load(URL)
     .centerCrop()
     .crossFade()
     .into(ImageView);
```

It fits the image and crops what is cannot be displayed.

```java
Glide.with(context)
     .load(URL)
     .fitCenter()
     .crossFade()
     .into(ImageView);
```

Loads entire image but does not fill the Image View.

```java
Glide.with(context)
     .load(URL)
     .override(//Width of Image View from dp to px conversion, //Height of Image View from dp to px conversion)
     .centerCrop()
     .crossFade()
     .into(ImageView);
```

the last method does seem to work but even in this case Glide tries to maintain aspect ratio and is cropping my image. Is there a workaround to this problem?

**Comment by TWiStErRob** [comment]
Please read the docs on `ImageView.scaleType`: http://developer.android.com/reference/android/widget/ImageView.ScaleType.html

Glide uses the above to transform images. It's unusual to want to display an image that fills the view and distorts the image, that's why the aspect is kept: think faces or textual logos.

I think from the avaiable scaleTypes you're looking for `android:scaleType="fitXY"`. Put that in XML and remove all the `override`/`centerCrop`/`fitCenter` calls from Java code.

**Comment by MAnfal** [comment]
Looks like I was looking in the wrong direction, thanks for pointing to the right one.
