### ISSUE TITLE
center image into container using Transformation

### ISSUE THREAD

**Issue by AngleV** [bumptech/glide#969]
i am using the following code to transform downloading image 

```java
public class myBitmapTransformation extends BitmapTransformation {
    private Context aContext;

    public myBitmapTransformation(Context context) {
        super(context);
    }

    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
        return bitmapChanger(toTransform, outWidth, outHeight);
    }

    @Override public String getId() { return "some_id"; }

    private static Bitmap bitmapChanger(Bitmap bitmap, int desiredWidth, int desiredHeight) {
        float originalWidth = bitmap.getWidth();
        float originalHeight = bitmap.getHeight();

        float scaleX = desiredWidth / originalWidth;
        float scaleY = desiredHeight / originalHeight;

        //Use the larger of the two scales to maintain aspect ratio
        float scale = Math.max(scaleX, scaleY);

        Matrix matrix = new Matrix();
        matrix.postScale(scale, scale);
        return Bitmap.createBitmap(bitmap, 0, 0, (int) originalWidth, (int) originalHeight, matrix, true);
    }
}
```
How can i center vertically and horizontally the image inside my container ?

**Comment by TWiStErRob** [comment]
What are you trying to achive exactly? What is your source and destination?
Adding padding inside the Bitmap is really wasteful of memory, the transparent pixels still require the same amount of memory as non-transparent ones. Imagine a 64x64px bitmap that you would want to display in a 1024x1024px view. You would add `(1024-64)/2` padding on each side: the size of the original bitmap is so insignifant (less than 16kB) that you would be wasting about 4MB of memory just to store the transparent pixels. It's much better to load the image into a Bitmap with a certain size and then let the ImageView center the Bitmap inside itself.

**Comment by AngleV** [comment]
@TWiStErRob 

My xml layout is 

```
           <FrameLayout
                android:id="@+id/arrow_layout"
                android:layout_width="320dp"
                android:layout_height="320dp"
                tools:visibility="visible"
                android:layout_gravity="center">

                    <ImageView
                        android:id="@+id/pager"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:contentDescription="@string/descr"
                        android:scaleType="matrix"
                        android:src="@drawable/beache"
                        android:layout_gravity="center" />
</FrameLayout>
```

i want to fetch the photo in full resolution keeping the aspect ratio and centered vertically and horizontally inside ImageView. 
My goal is to allow the user to be able to touch and move the image which leaves inside the 320dp square Framelayout container.

**Comment by TWiStErRob** [comment]
In that case the transformation solution you tried wouldn't help because you would have to reload the image on every touch to relocate and that would cause a huge performance issue right away.

`.override(Target.SIZE_ORIGINAL)` will give you the full resolution image. Then you would have to find the way to manipulate the display matrix on touch to move it around.

Another possibility if you have a small image is to have an ImageView with `wrap_content` on both sides. In this case Glide will default to loading an image matching the screen dimensions, but you can use `.override()` with any value. Wrapping will also allow the `layout_gravity` to take effect as well, currently it doesn't do anything. You can move the ImageView around via `layout_marginTop` and `layout_marginLeft` on the ImageView from code.

Zoom and Pan is out of scope for Glide it can only give you an image that has the size you request. There are many pan/zoom/pinch/etc. libraries and codes out there, consider using one.

**Comment by AngleV** [comment]
ok thank you. I came up with a different solution
