### ISSUE TITLE
Rename cached file and cache persistence

### ISSUE THREAD

**Issue by Magnarus** [bumptech/glide#976]
**Glide Version : 3.6.1 **:
**Samsung Galaxy S4/Android 5.0.1**:
**Monitor call with Charles**:

Hello, 
For specific reasons, I have to change the cache folder, I did it with a glideModule extension : 
```Java
public class GlideConfiguration implements GlideModule {
    @Override
    public void applyOptions(final Context context, GlideBuilder builder) {
        builder.setDiskCache(new DiskCache.Factory() {

            @Override
            public DiskCache build() {
                String dataDirPath = context.getApplicationInfo().dataDir;
                File cacheLocation = new File(dataDirPath + "/media");
                if(!cacheLocation.exists()) {
                    boolean success = cacheLocation.mkdirs();
                    if(success) System.out.println("build succeed");
                }
                return DiskLruCacheWrapper.get(cacheLocation, 20000000);
            }
        });
    }

    @Override
    public void registerComponents(Context context, Glide glide) {

    }
}
```

And I also need to rename my cached files, I did it with dowloadOnly(..) : 
```Java
Glide.with(this)
            .load("http://www.wired.com/wp-content/uploads/2015/09/google-logo.jpg")
            .downloadOnly(new SimpleTarget<File>() {
                @Override
                public void onResourceReady(File resource, GlideAnimation<? super File> glideAnimation) {
                    File folder = resource.getParentFile();
                    if (folder.exists() && folder.isDirectory()) {
                        File newPath = new File(folder, "google-logo");
                        /*
                            NOTICE : renameTo change the filesystem path BUT NOT the File object
                            so resource.getPath() will return the OLD path
                            but resource.exists() return false while newPath.exists() return TRUE
                            so the file is changed as we want to.
                         */
                        resource.renameTo(newPath);
                    }
                }

            });
```
while I'm in-app it works fine and will not call the web to find the image for each simple call with load(..).into(imageView);
But if I close or kill the app and relaunch it, the first call with code above is performed again.
Is there a way to make my changes persistent? Is there a cleaner way to do what I want? I need to be able to change both the location and the name of cached files.
Thanks !

**Comment by TWiStErRob** [comment]
Tip: the following should be equivalent to your custom factory:
```java
new DiskLruCacheFactory(context.getApplicationInfo().dataDir, "media", 20*1024*1024)
```

Glide manages the disk cache via seemingly random named keys. These keys come by digesting (hashing) all the data that uniquely identifies the load. By renaming the File you're esentially making it invisible to Glide. It works while you don't exit the app, because the load hits the memory cache, but as soon as it's closed it'll miss the disk cache and re-download the file.

**What is the reason behind renaming?** You should be able to access the image any time by requesting the same Url (if `SOURCE` cache is enabled, which it is because of `downloadOnly`). If you want to have a named file I suggest that you copy the file and not rename it, which can be probably achieved easier if you just download the network stream (without Glide) to a File of your choice. If you do this you can even leave the cache at the default location.

If you really want you try to write a custom `DiskCache` that saves named files, but you'll have to hack the Key object with reflection because the fields are not accessible. See also #906 for some tricks.

**Comment by Magnarus** [comment]
I need to rename cached files because we're doing a progressive migration from our cross-platform (Titanium) project -with our old custom cache management- to our native project and we need to link both cache to enable interactions and avoid duplicate or zombie files.
Anyway, we just found a smoother way to link them without doing tricky things with Glide :)
Thanks for your explanation and quick response ! :+1:

**Comment by TWiStErRob** [comment]
Hmm, that's a hard one. #746 might help.
Can you share your solution for future readers?

**Comment by Magnarus** [comment]
Of course.
We decided to handle only image loading inside native code for images used in native part, and then trigger Titanium image loading process. (since cross-platform remaining code is now a .jar file included into native project, we can interact pretty easily)
If an image is both used inside native and Titanium part, then we load it normally inside native part with Glide and duplicate the file inside Titanium cache folder with the right name. This way, when the Titanium loading process will check this image url, it will retrieve it in the cache and won't do any extra web call.
So yeah, we will have a few duplicated file, but we'll only have one web call for those images and this is only a temp fix, it will disappear once migration is over.
We think it's the easiest and costless way to achieve this.
