### ISSUE TITLE
OnItemEvicted in Glide does not expose the EngineKey to retrieve the url it loaded for the bitmap

### ISSUE THREAD

**Issue by khandelwaludit** [bumptech/glide#977]
Hello there,
I am trying to use glide as our image rendering engine. We have width and height specified in our urls. I   know that glide caches multiple images for the same url if the dimensions of the image view are different. Using this quality, what I am trying to do, is create a Custom ModelLoader which has its own HashMap with one to many mapping. The HashMap has a baseUrl and maps it to models with different sizes but same baseUrl. Now, when one loads an image, if my map already has an entry for the right/bigger image, I would update the currently queried url with already existing url, so that I can get the cached image. I have also overriden the LruResourceCache to get access to onItemEvicted method. The problem is that onItemEvicted has the generic Key in arguments and although it maps to EngineKey, I cannot typecast it since EngineKey is not in scope. Basically, I want the url so that I can remove the entry from my model Hashmap as well. I tried to mail, but I do not seem to have the rights. Please suggest a workaround for this and I do not want to use glide as a local module. I hope I am clear.

**Comment by TWiStErRob** [comment]
> I cannot typecast it since EngineKey is not in scope

Yep, `EngineKey` is really secretive, it has default visibility and everything is private in it.
You can always use reflection:
```java
static Field idField = Class.forName("com.bumptech.glide.load.engine.EngineKey").getDeclaredField("id");
static {
	idField.setAccessible(true);
}
onItemEvicted(Key key) {
	String url = (String)idField.get(key);
}
```
but the above is the quick and dirty way if it works at all...

> create a Custom ModelLoader

From what I understand above your custom loader works like this:
```
baseUrl, 640x480 -> Loader -> new Fetcher(baseUrl_800_600) if it exists
baseUrl, 640x480 -> Loader -> new Fetcher(baseUrl_640_480) if it doesn't
```
The problem I don't get is how do you know what's in the cache after restarting the app? You're overriding the memory cache which is cleared on restart. Even if you save your mapping the disk cache may also evict some files, so Glide would have to download a bigger image for a smaller one to display. Another concern is that you can't really hit the memory or `RESULT` cache just by changing the Url, if the requested size is different it'll still miss. All of the fields in `EngineKey` contribute to these cache keys.

Are the images really that big that it's worth this effort? You could just load `baseUrl` with `.diskCacheStrategy(SOURCE)`, that way only one image is downloaded and the user's device is not cluterred with multiple resolutions. `BaseGlideUrlLoader` is designed for bucketing, but I can't think of a way to fall back to larger sizes, because it's almost impossible to know what's in the cache. Using SOURCE will store your `baseUrl` as a file and any future loads will load a Bitmap from that file regardless of size. If you add RESULT to the mix (via `.diskCacheStrategy(ALL)`) the different resolutions that were loaded by Glide will be stored, but still only one goes through the network.

> I tried to mail, but I do not seem to have the rights.

I assume you mean the glidelibrary Google Group. You need to be a member to post (should be a simple click on UI to join), but it's publicly readable.

**Comment by khandelwaludit** [comment]
Oh. Here's the thing. I am not providing the modelCache to ModelLoader during initialization. So in all cases, when the BaseGlideUrlLoader tries to access the ModelCache, it will be null. Then, it goes to the getUrl part. Here, my code kicks in. The String Url will be decided from the ModelLoader with my custom (disk cache/ memory cache) implementation. This after a small hashing and computation , provide me the string url which was already requested for the base Url. My only assumption is that for the same given string and the headers, although a new GlideUrl object is created, the resource fetcher should map the given url to the same image. Now, overriding the LruResourceCache part. I am overriding it just so that I get notified when an item is evicted. The dirty way of reflection is what I wanted to avoid. Had this given me the url, I can easily reverse engineer my BaseUrl and evict the entry from my custom cache. Is my understanding wrong. Thanks for the detailed reply. :+1:  Let me know if what I say is making sense.

**Comment by TWiStErRob** [comment]
> My only assumption is that [...] the resource fetcher should map the given url to the same image.

I think that is only partially correct, it depends on the `diskCacheStrategy`. Following is an over-simplified view of Glide's Engine (see classes `Engine`, `EngineRunnable`, `DecodeJob` for more).

Let's assume that you can track the mappings as you want so that you have a consistent view of the cache state. Also assume that you have the most used standard resolutions available on the server, consider that these things happen in your app:
 * baseUrl requested for a 512x512 view  
   custom loader doesn't find any matches so it loads the next bigger bucket: 800x600  
   Glide would store`baseUrl_800x600` into SOURCE, `baseUrl_800x600_into512x512` into RESULT and memory
 * baseUrl requested for an 1024x1024 view  
   custom loader doesn't find any matches so it loads the next bigger bucket: 1280x1024  
   Glide would store `baseUrl_1280x1024` into SOURCE, `baseUrl_1280x1024_into1024x1024` into RESULT and memory
 * baseUrl requested for an 128x128 view  
   custom loader finds two matches, picks either one of them, say 800x600  
   The current key is `baseUrl_800x600_into128x128`.

Now if that last loader returns a fetcher with `getId()` for `baseUrl_800x600` the following will happen (that ID doesn't contain the `into` part because that's stored separately in `EngineKey` and is irrelevant for `SOURCE` cache which uses `EngineKey.originalKey`):
 * any memory cache query will miss
 * any `RESULT` cache query will miss
 * `SOURCE` cache will hit -> no network

So if you're going for minimal network, use `.diskCacheStrategy(SOURCE)`; and if you're going for faster repeted load times use `.diskCacheStrategy(ALL)`; in any case you need `SOURCE` cache.

Sorry if you knew all this, hope this helps in some way. Sadly for the "consistent view of the cache state" I can't think of anything right now and that is why I suggested to skip the bucketing and just load a reasonably large `baseUrl` (into SOURCE) and that will always hit regardless of view size.

**Comment by khandelwaludit** [comment]
I did not understand why SOURCE would give no network. I mean the original key would remain the same i.e. baseUrl_800X600. Why will it not serve this image ? Had that been the case, how would source serve the image in case I use source as disk strategy. Anyways, I would need to dig deeper to understand more and see if my use case can be served.

**Comment by TWiStErRob** [comment]
I just wanted to point out the distinction between caches. Yes that key will be found in the source cache and because of that no network request will fire.

The problem is the big assumption in the beginning, if the disk cache evicted that 800x600 image, but you don't know about it, then the source cache would not hit and you would download that big image again, to display in a 128x128 view, which could have been served from the 320x240 version on the server had there been no matching going on in the loader.

**Comment by khandelwaludit** [comment]
Thanks :+1: There is one more thing that I am trying to figure out. You have the signature attribute which helps to invalidate an entry. In our case, for all urls that we have, we use one more attribute called quality to optimally use network bandwidth. When the bandwidth is good, we use best quality and keep degrading based on the network strength. I wanted to leverage the signature attribute here. I was trying to use quality as a signature so that it invalidates an entry if it is below quality. But it should not invalidate entries with higher quality. To accomplish this, I was overriding the equals method with the appropriate condition and keeping the messageDigest same. I see that you use message digest to generate a safe key and use that in the engine key to get to the image from disk. But you do not use equals to make a final conclusion. The example on IntegerVersionSignature also uses the equals method to achieve this. Am I missing something ?

**Comment by khandelwaludit** [comment]
Hi,
I think I have figured it out. I missed to override the hashCode. Now, that I have made hashCode of all the signature same. It all boils down to the equals method to match the object. To check if it is loading correctly, I am putting the request listener and printing from where it is coming.
