### ISSUE TITLE
Glide class not found

### ISSUE THREAD

**Issue by sanketcouragedigital** [bumptech/glide#998]
Glide class gives error on this line.
Glide.with(image).load(url).centerCrop().crossFade().into(image);

I import the library into module settings and set it as compile in Intellij IDEA.
And also added met-data into manifest too.

**Comment by TWiStErRob** [comment]
Do you have an import for it at the top of the file?
If you use IDEA, why not use Gradle Android project? (File > New > Project > Android)

**Comment by sanketcouragedigital** [comment]
I am not using android gradle project. I add glide library in my project using an option 'Add as Library'. And in module settings I set the scope as 'Compile'.

**Comment by TWiStErRob** [comment]
Try adding it under the libs folder and refresh the dependencies.

I'm suggesting Gradle because it makes things extremely simple and what you experience now never comes up with it. I was hesitant to move to it, but once I did I never looked back. Android Studio evolved so much in the past two years that it's a joy to develop Android apps compared to the old Ant-based Eclipse experience. Google is also pushing the Gradle/IDEA combination, it's worth following them: http://developer.android.com/tools/studio/index.html

**Comment by sanketcouragedigital** [comment]
I added it under libs folder and also refresh dependency.. but still getting error.

**Comment by TWiStErRob** [comment]
Hmm, let's back up a little, where did your jar file come from? And is it a jar file?

**Comment by sanketcouragedigital** [comment]
Yes it is a jar. I get that from [glide](https://github.com/bumptech/glide/releases/download/v3.7.0/glide-volley-integration-1.4.0.jar).

**Comment by TWiStErRob** [comment]
Ah, that explains a lot :)

Take a look into the jar file (`jar tf file.jar` or rename to .zip and open the file) you'll see it as only has a few classes. These classes are needed to connect the API of Glide to the API of volley. But you still need [glide.jar](https://github.com/bumptech/glide/releases/download/v3.7.0/glide-3.7.0.jar) and volley.jar separately in your libs as well. (Assuming you have this problem with your petapp, you already have volley)

So again, if you used Gradle/Maven referencing the integration library would have also pulled in the glide and volley dependencies automatically.

**Comment by sanketcouragedigital** [comment]
It works. Thank you so much.
